src/main.cpp

As the title says, the wallet shouldn't resend transactions if the node is importing or in IBD state. The node doesn't know the real status until it's synced.

[Wallet] Do not try to resend transactions if the node is importing or in IBD

---

qa/rpc-tests/test_framework/siphash.py
src/coins.cpp
src/coins.h
src/hash.cpp
src/hash.h
src/main.cpp
src/net.cpp
src/net.h
src/test/hash_tests.cpp

Builds on top of 
Use SipHash for node eviction and add more test vectors for siphash
(backports bitcoin/bitcoin#8173)

[Core] Use SipHash for node eviction

---

src/kernel.cpp
src/main.cpp
src/main.h
src/miner.cpp
src/pivx-tx.cpp
src/policy/policy.cpp
src/rpc/rawtransaction.cpp
src/script/interpreter.cpp
src/script/interpreter.h
src/script/sigcache.h
src/script/sign.cpp
src/script/sign.h
src/test/DoS_tests.cpp
src/test/main_tests.cpp
src/test/multisig_tests.cpp
src/test/script_P2SH_tests.cpp
src/test/script_tests.cpp
src/test/sighash_tests.cpp
src/test/transaction_tests.cpp
src/txmempool.cpp
src/wallet/wallet.cpp
src/wallet/wallet_ismine.cpp
src/wallet/wallet_zerocoin.cpp
test/functional/wallet_txn_clone.py

Base work for the new transaction digest algorithm for signature verification on PIVX Sapling transactions.
Essentially, an implementation of BIP143 + few more good commits that found down the rabbit hole.
Back ports:
* bitcoin#7276 
* bitcoin#7976
* bitcoin#8118
* bitcoin#8149 (only amount validation and SignatureHash commits).
* bitcoin#6088 (only the dummy signature one - will be removed once #1663 get merged -).
* bitcoin#6379
* bitcoin#8524
Next step over this area (need 1553 merged to be able to push it) is the further specialization of BIP143 into our custom implementation of ZIP143 (with a different digest algorithm definition using our tx data and hash personalization).

Base work for the Sapling signatureHash

---

src/main.cpp
src/test/accounting_tests.cpp
src/validationinterface.cpp
src/validationinterface.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/wallet_zerocoin.cpp
src/zmq/zmqnotificationinterface.cpp
src/zmq/zmqnotificationinterface.h
src/zpiv/zpivwallet.cpp
src/zpivchain.cpp

Work done on top of #1717 .
Essentially an improvement over `SyncWithWallets` & `SyncTransaction` flow to run without locking `cs_main`.
(made as less modifications as possible over the zpiv wallet/chain files, no real need to improve that code.. most of it will disappear soon)
It's an adapted version of bitcoin#7946.

[Validation] Reduce cs_main locks during ConnectTip/SyncWithWallets

---

configure.ac
contrib/devtools/symbol-check.py
src/compat/glibc_compat.cpp

Bump up the minimum supported libc version to 2.17, which is necessary moving forward with sapling work.
2.17 was chosen as that is what CentOS 7 includes, which won't reach EOL until 2024.
Also included here are a couple cleanups for checks or backwards compatibility code that are rendered moot with the libc version bump.

[Build] Bump minimum libc to 2.17 for release binaries

---

src/coins.cpp
src/test/coins_tests.cpp

backports bitcoin/bitcoin#5967
> Previously it would break if you flushed a parent cache while there was a child cache referring to it. This change will allow the flushing of parent caches.
> 
> It also modifies the unit test to include flushing of intermediate caches.

[Core] Alter assumptions in CCoinsViewCache::BatchWrite

---

src/coins.cpp
src/coins.h
src/main.cpp
src/test/coins_tests.cpp

Adapted version of bitcoin/bitcoin#6932
> When processing a new transaction, in addition to spending the Coins of its txin's, it creates a new Coins for its outputs. The existing ModifyCoins function will first make sure this Coins does not already exist. It can not exist due to BIP 30, but because of that, the lookup can't be cached and always has to go to the database. Since we are creating the Coins to match the new tx anyway, there is no point in checking if it exists first anyway. However this should not be used for coinbase tx's in order to preserve the historical behavior of overwriting the two existing duplicate tx pairs.
>
> In conjunction with bitcoin/bitcoin#6931 this will help ConnectBlock be much more efficient with caching access to the database.
We remove the restriction on …

[Core] ModifyNewCoins saves database lookups

---

CMakeLists.txt
src/Makefile.am
src/qt/walletmodel.cpp
src/rpc/rawtransaction.cpp
src/script/ismine.cpp
src/script/ismine.h
src/test/multisig_tests.cpp
src/test/script_P2SH_tests.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Mixing few back ports with code readability improvements.
By commits position:
1) Moves `wallet_ismineh` to is `mine.h` and makes multisig and P2SH tests compile without wallet built-in.
2) COutput class refactor.
3) Adds an `solvable` member in COutput to describe whether an output is solvable by the wallet or not (btc#7688).
4) Code refactor to make the spendable and solvable definition simpler and not duplicate code.
This is an initial step, will continue moving forward until can split the ismine code from the solvability aspect.

[wallet] List COutput solvability + wallet_ismine refactoring.

---

src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/wallet_basic.py

Cleaning a duplicate watch only filtering configuration from `CWallet::AvailableCoins`. The same configuration can be found in `CCoinControl` object, `fAllowWatchOnly` member.
It has mostly non-functional changes and only duplicated code cleanup. The only functional change exception is in `listunspent` rpc command.
`listunspent` command will not be able anymore to retrieve only the watch only utxo. watch only utxo can be added or not to the utxo set with a custom configuration (same as before).

[Wallet] AvailableCoins remove duplicated watchonly config argument.

---

src/main.cpp
src/main.h
src/masternode-budget.cpp
src/masternode-payments.cpp
src/masternodeman.cpp
src/test/DoS_tests.cpp

In several places we had synchronized data structures accessed without cs_main being held.

lock cs_main for Misbehaving

---

src/main.cpp
src/undo.h

The `fCoinStake` variable of the undo metadata, which  is constructed in `UpdateCoins`, is never set.
Similarly, the coins cache entry is not restoring the `fCoinStake` flag from the undo data  in `ApplyTxInUndo`.
Now, since `coins->IsCoinStake()` is checked within places like `CheckTxInputs`/`AcceptableInputs`/etc..., this could potentially lead to consensus issues in case of reorganizations.

[BUG] Properly copy fCoinStake memeber between CTxInUndo and CCoins

---

src/coins.cpp
src/coins.h
src/main.cpp
src/txmempool.cpp
src/txmempool.h

backporting bitcoin/bitcoin#6872

[Core] Remove UTXO cache entries when the tx they were added for is removed

---

src/coins.cpp
src/coins.h
src/legacy/validation_zerocoin_legacy.h
src/main.cpp
src/rpc/blockchain.cpp
src/test/coins_tests.cpp
src/test/netbase_tests.cpp
src/txdb.cpp
src/txdb.h

Other two quick backports needed for the upcoming per-txout model.
- bitcoin/bitcoin#7756 - Add cursor to iterate over utxo set, use this in `gettxoutsetinfo`
> - Add a method `Cursor()` to `CCoinsView` that returns a cursor which can be used to iterate over the whole UTXO set.
> - Implement `GetUTXOStats` in terms of this, remove `GetStats()` method on `CCoinsView`.
> - Change `gettxoutsetinfo` RPC to use new `GetUTXOStats` function.
- bitcoin/bitcoin#7815 - Break circular dependency main ↔ txdb (part of this was done already in #1302 and #1319)
> - Moving `CBlockFileInfo` from main.h to chain.h. I think this makes sense, as the other block-file stuff is there too.
> - Moving `CDiskTxPos` from main.h to txdb.h. This type, used for `-txindex` seems specific to txdb.
> - Pass a functor …

[Refactoring] Break circular dependency main ↔ txdb

---

src/coins.h
src/memusage.h
src/streams.h

Couple of quick backports (needed for the upcoming per-txout model for cache and chainstate db):
- bitcoin/bitcoin#10249 - Switch CCoinsMap from boost to std unordered_map
- bitcoin/bitcoin#10250 - Fix some empty vector references

[Core] Use unordered_map for CCoinsMap and fix empty vectors in streams

---

src/qt/transactionrecord.cpp
src/qt/transactionrecord.h

Initial step towards a cleaner and more understandable `TransactionRecord::decomposeTransaction` function.
No functional change. Have done mostly code refactoring with some cleanups and improvements.

[Model] TransactionRecord decomposeTransaction refactoring

---

src/main.cpp

Only last commit is new.
Now that we have implemented `HaveCoinsInCache`, we can use it to speed up `AlreadyHave`, by avoiding unnecessary database access for unknown transactions.
(backported from bitcoin/bitcoin#7874)

[P2P] Improve AlreadyHave

---

src/masternode.cpp
src/masternode.h

In `CalculateScore`, `GetMasternodeInputAge` and `GetBlockHash` we had `chainActive` accessed without cs_main being held. This PR fixes it.
No functional changes. Can be added to 4.2.1 back ports list as well.

[Masternodes] Missing cs main locks in CalculateScore and GetMasternodeInputAge

---

configure.ac
src/Makefile.am

The RUST_TARGET variable only applies when cross-compiling. Build
systems like launchpad and copr don't cross compile, but also need
pre-vendored rust sources as they don't allow network access during the
build stage. In this situation, the RUST_TARGET variable is empty.
This will fix our nightly PPA builds on Launchpad, and is supported by
additional changes in my `pivx-packaging` repo, as well as a new
`rust-vendored-sources` repo, both hosted on launchpad.
A separate PR will
be made to fix our nightly Snap builds, which will either entail re-working
how those builds are done, or rewrite the `rust.mk` descriptor.

[Build] allow for empty RUST_TARGET in offline builds

---

src/qt/transactionrecord.cpp

The `TransactionRecord sub` is already appended to the `QList<TransactionRecord> parts` at the end of `decomposeCoinStake` (line 78)

[BUG][GUI] Don't append cold-stake records twice

---

build-aux/snap/snapcraft.yaml

Depends currently doesn't support non-x86_64 linux builds for the rust
dependency, so switch our nightly snap builds to use syslibs instead of
depends.
This also maintains the running of unit tests by fetching the zk params
during the build process.

[Build] Use syslibs for nightly snap builds

---

src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Built on top of #1759 .
Improved code readability of the `CWallet::AvailableCoins` method decoupling nested statements and adding comments in between the checks.
Plus, removed an unused "add zero value utxo" flag.
An ugly area of the code could get pretty readable with some love.
#1757 is going further on this area with some more improvements.

[wallet] AvailableCoins code readability improved

---

src/main.h
src/policy/fees.cpp
src/policy/fees.h
src/policy/policy.h
src/qt/coincontroldialog.cpp
src/rpc/blockchain.cpp
src/rpc/client.cpp
src/rpc/mining.cpp
src/rpc/server.cpp
src/rpc/server.h
src/test/policyestimator_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/wallet/wallet.cpp
test/functional/feature_fee_estimation.py

Another back port, coming from #6134 .
> When automatically adding a fee estimate to a transaction and in the event no estimate is available for the desired confirmation target, it makes more sense to default to a fee estimate for a worse confirmation target rather than the hard coded minimum.
> 
TODO: Left to back port smartfees.py. 
We need it to be able to move forward in #1726

Improve usage of fee estimation code

---

src/main.cpp
src/rpc/blockchain.cpp
src/test/mempool_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
src/txmempool.cpp
src/txmempool.h

On top of #1707 and #1717 .
Back ports bitcoin#6898 (without back porting the last commit as we need some cleanup on the miner area first).

[Backport] mempool score index.

---

src/coins.cpp
src/main.cpp
src/test/coins_tests.cpp

Going on with the coins view cache update work (started with #1774 and #1777).
This backports the following upstream PRs (adapting them with the assumption that duplicate coinbase transactions are not possible):
- bitcoin/bitcoin#9308 - [test] Add CCoinsViewCache Access/Modify/Write tests
- bitcoin/bitcoin#9107 - Safer modify new coins
- bitcoin/bitcoin#9310 - Assert FRESH validity in CCoinsViewCache::BatchWrite
- bitcoin/bitcoin#9435 - Removed unused variable in test, fixing warning.
Note: Will rebase #1773 on top of this one (to change `ApplyTxInUndo` return value in the unit test too).

[Core] Safer modify new coins

---

doc/release-notes.md
src/coins.cpp
src/coins.h
src/dbwrapper.h
src/hash.cpp
src/hash.h
src/main.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/test/coins_tests.cpp
src/test/hash_tests.cpp
src/test/transaction_tests.cpp
src/txdb.cpp
src/txdb.h
src/undo.h
test/functional/rpc_blockchain.py

This backports the commits listed as "Preparation" in bitcoin/bitcoin#10195.
The rest will be included in a followup PR.
Here we:
- add in-memory size estimation of a LevelDB batch
- remove the usage of `error()` in ApplyTxInUndo/DisconnectBlock
- Introduce the new CHashVerifier class to hash read data
- Add a specialized version of SipHash for tuples of 256 bits and 32 bits data
- Remove the transaction version from utxo and undo data structures
- Add on-disk size of the utxo set to gettxoutsetinfo
- store tx metadata in all undo records, instead of records corresponding only to the last output of a tx being spent.

[Core] per-txout model preparation

---

src/main.h
src/memusage.h

[Core] Use std::unordered_{map,set} (C++11) instead of boost::unordered_*

---

test/functional/rpc_deprecated.py
test/functional/test_runner.py

No need to generate blocks for this test. We can speed it up a bit.

[Tests][Trivial] Remove mining in rpc_deprecated test

---

src/miner.cpp

No functional changes, purely a code decoupling over the zPIV duplicated serials validations at the miner code (which we will remove in the next months).
Doing this to make the old #1727 a little bit easier to rebase + adapt to current master.

[Miner] decouple zPIV duplicated serials checks from CreateNewBlock

---

src/activemasternode.cpp
src/interface/wallet.cpp
src/qt/walletmodel.cpp
src/rpc/misc.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/wallet_zerocoin.cpp

Added test coverage for the `CWalletTx` balances cache structure to verify the correctness of `CREDIT/ISMINE_SPENDABLE`, `DEBIT/ISMINE_SPENDABLE`, `AVAILABLE_CREDIT/ISMINE_SPENDABLE`, and a 'fake' block creation flow to verify `CWallet::GetUnconfirmedBalance`. (Leaving for a future PR, the cold staking balance types coverage)
Plus, popped up an issue in `CWalletTx::GetAvailableCredit` that is solved too.
Issue description:
As is now, `CWalletTx::GetAvailableCredit` is caching the amount using the AmountType::CREDIT when need to be using AmountType::AVAILABLE_CREDIT.
As them are different type of balances and are using the same cache position, only one of those is stored and the other one returns, invalidly, the value of the first one cached.
I intentionally have committed the unit test …

Wallet: wtx cached balances test coverage + getAvailableCredit problem fix.

---

.travis.yml

in order to increase the time reserved for executing the tests.
Currently the 8th travis job fails, and saves a cache of the binaries, at the end of the build phase, if it took more than 14 minutes.
This leaves at least 36 minutes to run the functional test suite, which is not enough anymore.
Lower the build timeout to 9 minutes, so we have at least 41 minutes for the tests. We'll need to restart that job more often, but we'll see less timeouts.

[Travis] Lower the build timeout for the functional tests job

---

src/spork.cpp

Removed a not needed `ChainActive` access in `ProcessSpork`. One `cs_main` lock less.

sporks: remove unneeded chainActive access.

---

src/logging.h
src/masternode.cpp
src/masternodeman.cpp

mnping logs are very spammy. Introduce a dedicated BCLog category for them (`MNPING`), so they can be optionally turned off (whilst still keeping the `MASTERNODE` category logged).

[Refactor] Dedicated logging category for masternode pings

---

src/masternodeman.cpp
src/masternodeman.h

Cleaning unused methods, GetMasternodeByRank, GetEstimatedMasternodes and CMasternodeMan not implemented constructor.

[Cleanup] removing unused GetMasternodeByRank method

---

src/wallet/wallet.cpp
src/wallet/wallet.h

auto-descriptive title, removed the following methods:
`CWalletTx::GetUnlockedCredit` and `CWallet::GetUnlockedCoins` `CWallet::GetLockedWatchOnlyBalance` and `CWalletTx::GetLockedWatchOnlyCredit`

[Wallet] Cleanup getbalance methods that are not fulfilling any purpose.

---

src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-payments.cpp
src/masternode-payments.h
src/miner.cpp
src/primitives/block.h
src/rpc/mining.cpp
src/wallet/wallet.cpp

Another step forward improving the miner `CreateNewBlock` function.
This time, have unified the coinbase tx creation flow that was previously dispersed over the function and having some redundant initializations/sets.
Plus, cleaned up some unused and/or unneeded fields and function arguments.
This is a preparation for #1815 work.  It will not be possible to modify any of the elements of a transaction once them are appended to a block, thus why the transaction needs (more than ever) to be crafted in one single place and not all over the sources.

[Miner] Unifying the disperse coinbase tx flow + further clean up.

---

src/masternode.cpp
src/masternode.h
src/rpc/masternode.cpp

`CMasternodePing` null check using new method `IsNull` instead of checking equality against a new created object every time.

[Cleanup] CMasternodePing: removed null check comparison against a new object.

---

src/rpc/blockchain.cpp

The third argument of ABC should be `fAlreadyChecked` (defaulted to `false`).
In reconsiderblock and invalidateblock RPC, the pointer returned by `g_connman.get()` (which can be automatically cast to bool) is improperly added as third (instead of fourth) argument.

[RPC][BUG] Fix ActivateBestChain calls in reconsider(invalidate)block

---

src/main.cpp
src/masternode-payments.cpp
src/masternode-payments.h

Cleaned `IsBlockValueValid` method to be much more readable, plus removed a not needed chainActive access.

cleanup: IsBlockValueValid refactored properly. 

---

src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Have re introduced the filtering arguments that were removed when the accounts system got deprecated in `getbalance`. With this, `getbalance` RPC command will be able, again, to filter by watch-only, minimum depth and include/exclude delegated balance.

[RPC] re introducing filtering args in getbalance

---

src/coins.cpp
src/coins.h
src/main.cpp
src/main.h
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/swifttx.cpp

Introduce a `GetCoinDepth()` utility function in CCoinsViewCache and use that instead (with `pcoinsTip`... no need to lock/load the mempool too in the  backend). 
This should fix the invalid lock order:
```
2020-09-02 10:23:17 POTENTIAL DEADLOCK DETECTED
2020-09-02 10:23:17 Previous lock order was:
2020-09-02 10:23:17  cs_process_message /src/masternodeman.cpp:690 (in thread pivx-msghand)
2020-09-02 10:23:17  (1) mempool.cs /src/main.cpp:777 (in thread pivx-msghand)
2020-09-02 10:23:17  (2) cs_main /src/main.cpp:785 (in thread pivx-msghand)
2020-09-02 10:23:17 Current lock order is:
2020-09-02 10:23:17  (2) cs_main /src/main.cpp:4571 (in thread )
2020-09-02 10:23:17  (1) cs /src/txmempool.cpp:590 (in thread )
```
To be able to use the new per-txout interface, this is based on top of:
The …

[Refactor] Remove GetInputAge and GetMasternodeInputAge

---

src/miner.cpp
src/miner.h
src/rpc/mining.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Work on top of #1816 and part of #1817 coinstake transaction creation speedup goal. Starting on 01814d5
Improving the following situation: we are calculating the stakeable utxo twice for the same PoS block creation process (looping over the entire wallet's transactions map twice), one before calling `CreateNewBlock` in `CheckForCoins` and the second one inside the `CreateNewBlock` method when we call `CWallet::CreateCoinStake`. 
This PR fixes it adding an unique available coins vector calculated before the block creation, only once per try, in the `CheckForCoins` function and feeding `CreateNewBlock` with it.

[Miner] PoS process, calculate stakeable utxo only once.

---

src/init.cpp
src/main.cpp
src/main.h
src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-payments.cpp
src/masternode-sync.cpp
src/masternode-sync.h
src/masternodeman.cpp
src/masternodeman.h
src/primitives/transaction.cpp
src/primitives/transaction.h
src/rpc/blockchain.cpp
src/rpc/budget.cpp

Refactoring of the masternode budget classes (`CBudgetManager`, `CBudgetProposal`, `CBudgetVote`, `CFinalizedBudget`, `CFinalizedBudgetVote`), providing better encapsulation of the data, removing unused functions, and giving a first round of styling cleanup.

[Refactor] Masternode Budget first refactoring and cleanup

---

src/main.cpp

Update the cached chain height in budget manager as soon as possible  (no need to complete the mn sync first).

[Bug] Update budget manager best height even if mnSync is incomplete

---

src/masternode-payments.cpp
src/masternode-payments.h
src/masternode-sync.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp

This time removing:
1) `GetOldestBlock` & `GetNewestBlock` unused methods from CMasternodePayments. 
2) `pubKeyCollateralAddress1` & `pubKeyMasternode1` unused members from CMasternode.
3) Direct `chainActive` access in `GetLastPaid` from CMasternode.
Plus:
1) Added a missing cs lock in `CMasternode::Check`

[MN] more cleanup over the tier two area.

---

src/Makefile.test.include
src/init.cpp
src/qt/walletmodel.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_test_fixture.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

auto-descriptive title. Locking the wallet's Sapling functionality to only be run in regtest.

[Wallet] Lock Sapling wallet functionality to regtest only for now.

---

src/guiinterface.h

The rest of the codebase has switched to using a template of boost::optional instead, this is the only part which still uses boost::optional instead of the template added for it

Use Optional template in guiinterface.h

---

src/masternode-budget.cpp
src/rpc/budget.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

The `CReserveKey` passed to `GetBudgetFinalizationCollateralTX`/`GetBudgetSystemCollateralTX` (for the change address) is not the same that is later passed to `CommitTransaction`.
So, if commit fails, for whatever reason, the original key is not returned to the keypool.
Also, the implementations of `GetBudgetFinalizationCollateralTX` and `GetBudgetSystemCollateralTX` are absolutely identical. The only difference is a single constant variable (the fee amount used).
Unify them in `CreateBudgetFeeTX` (passing a bool `fFinalization` to select the correct proposal/finalized-budget fee amount).

[Bug] wrong reserveKey when committing budget/proposal collaterals

---

src/init.cpp
src/qt/addresstablemodel.cpp
src/qt/walletmodel.cpp
src/rpc/misc.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp

Essentially, have restricted `mapAddressbook` access to the wallet class only. Migrating every direct access to the correspondent getter, setter and iterator wrapper. Plus, solved a todo in `AddressTableModel::getAddressToShow` (df262e4).
It's a preparation for the shielded addresses addressbook support.

[Wallet] Address book encapsulation.

---

src/Makefile.am
src/main.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
src/sapling/proof.cpp
src/sapling/proof.hpp
src/sapling/sapling_transaction.h
src/script/interpreter.cpp
src/script/interpreter.h
src/serialize.h

Work coming from #1798. Decoupled commits related to the Sapling transaction primitive data and the new signature hash to make the review a little bit easier there. Plus, squashed some of them.
List of commits taken from #1798:
Primitive data:
* Add serialization for primitive boost::optional<T>. —> 659cc558
* Transaction: Implement BaseOutPoint class.  —> f17b23c7
* Backport zkSNARK compression. —> 5dbc3c9
* Basic Sapling transaction primitive data --> c49594f
* Add serialization for std:list objects. —> 7cc57f7
* sapling_transaction.h migrated to the new serialization —> dbb618f6
* Fix sighash_tests —> e1e33163 
* Transaction GetShieldedValueIn & GetValueOut back port —> 0fbe0236
* BugFix in GetShieldedValueIn —> 57ee1bc6
* Missing SaplingOutPoint::ToString() method implemented —> …

Sapling transaction primitive data.

---

src/logging.cpp

For some reason mnping log category wasn't added to the logcategories vector. Discovered it trying to exclude it with `debugexclude=mnping` which notifies the error.

Missing mnping category added to logcategories

---

src/init.cpp

After #1801 the coins database is updated to the new format.
During this time (which could take a minute or so), QT wallet reports "Loading block index..."
which is wrong: even without the coins DB upgrade, it loads first the sporks DB, before the block index.
So:
- remove the misplaced init message for BlockIndex load (there's another one in the right place).
- add a new init message for the coins DB upgrade (if the DB is already upgraded, the function returns immediately so this is shown only for a fraction of a second before "Loading sporks...").
Note: As 4.3 is the first release including the new DB, we should probably backport this trivial PR.

[Trivial][GUI] Fix init messages

---

src/qt/pivx/addresseswidget.cpp
src/qt/pivx/send.cpp

Improved two similar methods that are calling `WalletModel::validateAddress` and `DecodeDestination` right after it.
As `WalletModel::validateAddress` is calling internally to `DecodeDestination`, the address is being decoded twice.
This PR improves it to only decode the address once.

[GUI] do not decode the address twice in save contact.

---

src/blocksignature.cpp
src/chainparams.cpp
src/consensus/merkle.cpp
src/consensus/zerocoin_verify.cpp
src/kernel.cpp
src/main.cpp
src/masternode-payments.cpp
src/merkleblock.cpp
src/miner.cpp
src/primitives/block.cpp
src/primitives/block.h
src/primitives/transaction.cpp
src/primitives/transaction.h
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/serialize.h
src/test/main_tests.cpp
src/test/mempool_tests.cpp
src/test/merkle_tests.cpp
src/test/pmt_tests.cpp
src/test/policyestimator_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet_zerocoin.cpp
src/zpivchain.cpp

Inspired on #9125 (with many more adaptations), preparation for #8580. Ant work 🐜 
Establishing the bases for the work, we will need to continue migrating `CTransaction` to `std::shared_ptr<const CTransaction>` where is possible. Example bitcoin#8126 (can find more in #1726 list).
TODO: 
* back port final `CTransactionRef` implementation commit.
EDIT:
This is now depending on #1816 .

Make CBlock a vector of shared_ptr of CTransactions

---

CMakeLists.txt
contrib/devtools/gen-json-headers.sh
src/test/CMakeLists.txt

This adds support for compiling the unit test binary `test_pivx`
directly with CMake. This also allows for CLion to perform code analysis
and completion on the test source files.
Requires the hexdump utility to be installed.
Note: actually running the unit tests from within CLion (Boost.Test targets) is not optimized, and the tests take a considerable amount of time compared to running the `test_pivx` binary.

[CMake] Add test_pivx unit test target

---

src/init.cpp
src/main.cpp
src/main.h
src/miner.cpp
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/test/miner_tests.cpp
src/validationinterface.cpp
src/validationinterface.h
src/zmq/zmqnotificationinterface.cpp
src/zmq/zmqnotificationinterface.h

Backports bitcoin/bitcoin#8865 and bitcoin/bitcoin#8969, in preparation for the long-awaited net_processing/validation split.

[Refactor] Decouple peer-processing from block-connection logic

---

src/main.h
src/primitives/block.h
src/primitives/transaction.h
src/streams.h
src/test/mempool_tests.cpp
src/test/merkle_tests.cpp
src/test/policyestimator_tests.cpp
src/txmempool.cpp
src/txmempool.h

PR solving the current master's syncing issue (syncing process not passing through block 5840), solved in 9d8b8a2. 
Essentially, when we merged #1815, we moved from using the default transaction constructor and the ser/unser template methods (`SerializationOp`) to be using, inside the templated serialization puzzle, the deserializing constructor (`CTransaction(deserialize_type, Stream& s)`) which internally creates a `CMutableTransaction` which wasn't having the same sapling tx version guard as `CTransaction` ser/unser method. So, in other words, it was trying to parse the shielded transaction data from an old version two transaction (yes, we already have version two transaction in our network.. first one is in block 5840).
Plus, i took the mischief of not only including the bugfix, have …

BugFix: tx sync parsing problem fixed + extra refactoring.

---

src/masternode-budget.cpp
src/masternode-budget.h
src/rpc/budget.cpp

Keep going with the `masternode-budget` classes refactoring, mainly addressing the thread synchronization aspect.
There is currently a potential deadlock due to wrong lock order between `cs_main` and `cs_budgets`, which will be solved in a follow-up PR as it needs a more invasive refactoring (decoupling the checks in `UpdateValid`/`IsCollateralTransactionValid`, doing those that don't depend on the chainstate just once, and not requiring `cs_main` held for the others).

[Refactoring] Budget, round 2: review locks

---

src/validation.cpp

Small bug introduced in #1814, the flag is set on every new tip but not initialized at startup.
Discovered rebasing #1798 on top of master and running any sapling functional test. As `g_IsSaplingActive` is false at startup, the transaction hash is different, making the merkle tree hash different, failing in `VerifyDB`.

BugFix: g_IsSaplingActive flag is not initialized at startup.

---

src/serialize.h

Straightforward and easy to check PR.
The list serialization wasn't updated to the latest serialization format (`nType` and `nVersion` removal).
Decoupled from #1798 --> 4053e97b .

[BugFix] Migrate list serialization to the current flow.

---

src/script/standard.cpp

Bug introduced in #1830 (hunted down with @furszy ).
Emplacing `uint160(key1)` into a vector of `CTxDestination` makes it construct the destination as a `CScriptID` instead of `CKeyID`. Therefore `ExtractDestinations` returns wrong addresses for cold staking scripts.

[BUG] Fix regression with emplace_back on cold-staking scripts

---

src/rpc/budget.cpp

Fixes a bug in the RPC `mnfinalbudget show`.
All finalized budgets have the same name (`"main"`).
This is used as key for the object returned by the RPC, therefore only **one single** finalized budget is returned (despite there being many more in the map).
Fix it by adding the hash to the object key (removing it from the object value).
Side note: why finalized budgets  do even need a `strBudgetName` (which is the same for every one) is a mystery to me... but, since it's part of the broadcast, we can't just outright remove it, it needs to be guarded with a network upgrade (future work).

[RPC][BUG] Fix 'mnfinalbudget show' returning a single budget

---

src/sapling/note.cpp
src/sapling/note.hpp
src/test/librust/noteencryption_tests.cpp
src/test/librust/sapling_note_tests.cpp

Another decoupling from #1798. Similar to #1870, these changes are part of the primitives unit test coverage back port work.
Commits included: 
* change cm() to cmu() in SaplingNote class —> d437276a4b922c6c70d810cff0719a2e76f1a4bc
* Note Encryption unit tests back ported. —> e4c1bbf1618fd797599b6bf3511cea79e6d9d4d7

[Sapling] Note Encryption unit tests back ported.

---

src/script/sign.cpp
src/script/sign.h
src/wallet/wallet.cpp

Fixing a minor bug introduced in #1757.
`IsSolvable` always tries to produce a signature with the owner key, so it logs an error (and reports the coin as not solvable) for cold stakers.
Fix it introducing a boolean argument in `IsSolvable`, to check the appropriate public key in the keystore.

[BUG][Script] Add fColdStaking boolean argument to IsSolvable

---

src/qt/pivx/dashboardwidget.cpp
src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/pivxgui.cpp
src/qt/pivx/pivxgui.h
src/qt/pivx/settings/settingsfaqwidget.cpp
src/qt/pivx/settings/settingsfaqwidget.h
src/qt/pivx/settings/settingswidget.cpp

Bug reported today on discord.
Wallet (GUI 4.3.0) crashes when the FAQ buttons from the masternode widget are pressed.
**Cause:**
The FAQs sections have been recently reduced to only 6 (old zerocoin sections have been removed).
But the buttons in the masternode widget still reference the old indexes (9 and 10),  which are now out of bounds.
Further, the safety check inside `setSection`, still has the old (10) max value hardcoded, so does not prevent this.
**Fix:**
This clearly shows the difficulty in maintaining code with fixed magic numbers (which depend on a list of objects that may be modified in future releases).
So, let's introduce a proper enumeration inside `SettingsFaqWidget`, and use that to manage the sections, instead of just integers.

[BUG][GUI] Fix wallet crashing on faq-buttons press

---

src/masternode-budget.cpp
src/masternode-payments.cpp
src/miner.cpp
src/test/main_tests.cpp
src/validation.cpp

This is a known old bug, which was never truly fixed, due to it being harmless (and discovered after the last block-value reduction).
The function `GetBlockValue(int nHeight)` returns the block-reward value for a block at a given height (based on a "halving" schedule hardcoded within the function).
The issue is that it was being called passing the height of the *previous* block.
At some point, one particular call (in `CreateCoinStake`) was changed to use the (correct) current block height, while leaving the wrong one in all other places (including masternode payments/budgets  and validation code).
This made no real difference with PIVX, as the change was introduced before the last milestone (which increased the block value from 4.5 to 5, rather than reducing it), and, after that, the …

[Bug] Fix misaligned height in calls to GetBlockValue

---

src/init.cpp

Fix a bug Introduced in #1826, which makes the node erase all proposals and finalized budgets, after reading them from the DB during startup (and thus having to ask everything again from the peers).
**Cause:**
The budget manager best height is set after reading the budgetdb.
As non-dry runs of `CBudgetDB::Read` include a call to `CheckAndRemove()` at the end (to delete expired objects), the manager's best-height needs to be already set.

[BUG] Set budget best height before reading budget DB during init

---

src/kernel.cpp
src/legacy/stakemodifier.cpp
src/miner.cpp
src/miner.h
src/rpc/mining.cpp
src/rpc/misc.cpp
src/stakeinput.cpp
src/stakeinput.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/zpiv/zpos.cpp
src/zpiv/zpos.h

Essentially, this work is removing an unneeded `GetTransaction` call from `CPivStake::GetIndexFrom` for every stakeable output during each cycle of the staking process.
As `GetTransaction` is a direct access to disk (txindex), this means faster staking.
Future work, the methods `StakeableCoins` and `AvailableCoins` can be abstracted even more. They are sharing almost the same code with an specific distinction that makes this change possible without introducing an extra blockIndex set into `AvailableCoins`.

[wallet] Extra GetTransaction call in stakeable coins selection flow removed.

---

src/test/sighash_tests.cpp

Decoupled from #1798 d0099f50 . 
Initial sighash unit test coverage for shielded transactions.

[Test] Update sighash tests for shielded transactions.

---

src/masternode.cpp
src/masternode.h

Solving a dead end inconsistency over the masternode activation process.
Context:
A valid masternode is created, mn start message is broadcasted and the entire network receives it. Peers moves the masternode status to pre_enable (active) and are waiting for a mn ping update to fulfill the min ping time requirement to move the status to enable.
Issue:
As the mnping update message work flow is not performing any action until the masternode is in an enable status (masternode.cpp, line 707), the masternode ping is never updated, there by the masternode will never be moved to enable status.
Why this is working now:
It's working because (1) the masternodes list is being requested, cleaned and re requested an insane amount of times, (2) some peers are broadcasting the start message twice and (3) …

[Masternodes] dead end over the activation process.

---

src/compat/glibc_sanity.cpp

Directly coming from upstream df6bde031b24112abf3a94337a2c096698acde6e (full explanation there).

[Backport] test: remove glibc fdelt sanity check

---

src/net.cpp
src/net.h
src/net_processing.cpp

Cleaning the currently not unused `mapRelay` and `cs_mapRelay`. Making #1786 obsolete.

[Cleanup] removing unused mapRelay and cs_mapRelay.

---

src/rpc/misc.cpp
src/rpc/server.cpp

**Problem**:
Most RPC commands crash the wallet during the initialization phase.
**Solution**:
An attempt to fix this specifically for `getinfo` was made in #543, checking the existence of `chainActive.Tip()`.
A better solution, instead of checking all places that try to access the block index, (or  the chainstate, or the second layer maps, etc...), is to throw a JSON-RPC exception with any call, if the server is still in warm-up phase (returning the exact init message), directly from `CRPCTable::execute`.
Closes #1908

[Bug][RPC] Guard RPC server during warm-up

---

src/qt/pivx.cpp
src/qt/pivx/splash.cpp
src/qt/pivx/splash.h

Removing an obsolete `QFlags` member. Not compiling in qt 5.15.
Issue reported by @Rhubarbarian in discord 👌   .

[QT] fixing qt flag deprecation

---

src/validation.cpp
src/validation.h

Simple one.
Remove code duplication and inefficiency, passing the previous block index from `AcceptBlock` to `AcceptBlockHeader`.

[Refactor] Pass previous index from AcceptBlock to AcceptBlockHeader

---

src/Makefile.am
src/init.cpp
src/moneysupply.h
src/rpc/blockchain.cpp
src/rpc/client.cpp
src/rpc/misc.cpp
src/rpc/server.cpp
src/rpc/server.h
src/validation.cpp
src/validation.h
test/functional/mining_pos_reorg.py

With #1878 the RPC call `getinfo` becomes awfully slow (it triggers a flush of the chainstate to disk and recalculates the amount).
In this PR we introduce a in-memory global object (instance of a dumb storage class) to cache the money supply, as well as the height of the chain when it was last updated.
The cache is updated in 3 cases:
- at startup
- after periodic full flushes to disk (blocks and chainstate), except during shutdown or IBD
- on-demand via RPC (see below)
A new RPC `getsupplyinfo` is introduced. It returns the contents of the cached object, after an optional flush/recalculation (if the `forceupdate` argument is set to true).
The money supply is still part of `getinfo` output, for backward compatibility, but the fetching is redirected to the new `getsupplyinfo` (with …

[RPC] Cache money supply on memory. Introduce getsupplyinfo

---

CMakeLists.txt
src/Makefile.am
src/coins.cpp
src/coins.h
src/policy/fees.cpp
src/sapling/sapling_txdb.cpp
src/test/coins_tests.cpp
src/txdb.cpp
src/txdb.h
src/txmempool.cpp
src/txmempool.h

One more PR decoupled from #1798 to make the review process faster.
Essentially, the chain view state will be storing and caching the best anchor hash and 2 new entry types: (1) Anchors, (2) Nullifiers (Each of them with their entry class and map).
Note: This PR is introducing the new capabilities and validating the functionality correct behavior with a good amount of unit tests (test coverage inside `coins_tests.cpp`), it's not connected to the network flow.
Note2: There is a functional tests in 1798 (`sapling_wallet_anchorfork.py`) that wasn't able to decouple here due larger features requirements (new RPC calls introduced down 1798 commits line) but can be easily run there.
* CoinsView, Anchor and nullifier view integration. —> 5a8f5ebd3b2d111572aa48ad34717fdb3e84bcbf
* CCoinsViewCache …

[Sapling] Anchors and nullifiers integrated into the chain state view layered cache.

---

src/swifttx.cpp

Was walking around the sources and discovered this strange way of blocking functionality, cuak :p .
As swiftx is disabled, this doesn't represent any problem, just showing us the need of using brackets always.

[bug] Swiftx DoConsensusVote missing brackets always returning without doing anything.

---

CMakeLists.txt
src/Makefile.am
src/Makefile.test.include
src/primitives/transaction.cpp
src/sapling/sapling_validation.cpp
src/sapling/sapling_validation.h
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/test/CMakeLists.txt
src/test/librust/sapling_keystore_tests.cpp
src/test/librust/sapling_test_fixture.cpp
src/test/librust/sapling_test_fixture.h
src/test/librust/transaction_builder_tests.cpp
src/test/librust/utiltest.cpp
src/test/librust/utiltest.h
src/wallet/test/wallet_test_fixture.cpp
src/wallet/test/wallet_test_fixture.h

Another decoupling from #1798 . Focused on three points:
1) Standalone builder class encapsulating the shielded transaction building process.
2) Basic network validations for the shielded transaction primitive data. -- NOT connected to the network in any way, only used in the unit tests (point 3) --
3) Transaction builder unit tests coverage verifying the correct behavior of the included functionality.
* Sapling transaction builder back port. --> 3fbf19855889881c5888b6cc80b4d2871932bfaa
* [NET] Sapling validation files created. --> 267b088d6270e752e3550e70c0f30f8a3770762d
* sapling test fixture implemented. --> eb12b515dcea420e0bd7d848d2e79a5f6f2d1764
* Backport utiltest files. --> 27168c6a54d7e54c7787d3cfcdc8856e15fb27a7
* Sapling transaction builder tests back ported. --> …

[Sapling] Sapling transaction: builder, sapData net validation and builder unit tests coverage

---

src/net.cpp

Fixes another inconsistency found with #1920 :
```
2020-10-15 23:43:11 POTENTIAL DEADLOCK DETECTED
2020-10-15 23:43:11 Previous lock order was:
2020-10-15 23:43:11  (1) pnode->cs_vSend net.cpp:1152 (TRY) (in thread pivx-net)
2020-10-15 23:43:11  (2) pnode->cs_inventory net.cpp:1154 (TRY) (in thread pivx-net)
2020-10-15 23:43:11 Current lock order is:
2020-10-15 23:43:11  pnode->cs_sendProcessing net.cpp:1898 (in thread pivx-msghand)
2020-10-15 23:43:11  cs_main net_processing.cpp:1992 (TRY) (in thread pivx-msghand)
2020-10-15 23:43:11  (2) pto->cs_inventory net_processing.cpp:2081 (in thread pivx-msghand)
2020-10-15 23:43:11  (1) pnode->cs_vSend net.cpp:2568 (in thread pivx-msghand)
```
backporting the only missing commit from upstream bitcoin/bitcoin#9674

[Core] Lock cs_vSend and cs_inventory in a consistent order even in TRY

---

src/memusage.h
src/miner.cpp
src/miner.h
src/net_processing.cpp
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/rpc/rawtransaction.cpp
src/swifttx.cpp
src/swifttx.h
src/test/DoS_tests.cpp
src/test/mempool_tests.cpp
src/test/policyestimator_tests.cpp
src/test/test_pivx.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/validation.h
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp

Made my own way up to be able to back port bitcoin#9014. This will mean a performance regression fix over the block-connection process + less memory usage storing `CTransactionRef` instead of a plain `CTransaction` copy in the mempool.
The first three commits are essentially covering:
1) mempool: using `CTransationRef` instead of coping each transaction.
2) validation: ATMP and ATMPW migrated to receive `CTransationRef`.
3) net_processing: ProcessMessage migrated TX message processing to use `CTransactionRef`.
4) swiftx: ProcessMessage migrated IX message processing to use `CTransactionRef`.
5) migrated mapOrphanTransactions to use `CTransactionRef`.
And from [085dc57](https://github.com/PIVX-Project/PIVX/commit/085dc576d1b4c8bd4ba715ef22f3948b4d618e56) starts btc/9014 back porting work.

Fix block-connection performance regression and mempool not copying tx performance improvement

---

src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-payments.cpp
src/rpc/budget.cpp

Current PR starts with `[Refactor] Decouple CBudgetProposal::UpdateValid checks` (6c6a97e3b27ffc3fe953d88e0f008c3fa9cdee4c).
This focuses on extracting context-independent checks and doing them only once in `AddProposal`/`AddFinalizedBudget`.
As for the confirmation/expiration check (which is the only thing left for `UpdateValid`) , it is done without locking `cs_main` (while holding `cs_budgets`/`cs_proposals`) by caching the height of the block with the collateral transaction and relying on it (todo: it needs to be addressed the case of it being reorganized from the chain). 
This new field, called `nBlockFeeTx` is added directly to the serialization of CBudgetProposal and CFinalizedBudget, so the old budget.dat will be invalidated and recreated new at startup.

[Refactoring] Budget, round 3: split UpdateValid checks for proposals / finalized budgets

---

src/Makefile.am
src/activemasternode.cpp
src/cyclingvector.h
src/init.cpp
src/masternode-payments.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/masternodeman.h
src/rpc/blockchain.cpp
src/rpc/masternode.cpp
src/rpc/server.cpp
src/rpc/server.h
src/validation.cpp
test/functional/feature_blockhashcache.py
test/functional/test_runner.py

**Problem**:
Validation of many objects on the second layer (masternode pings, winners/scores, etc...) requires access to chainActive to get the hashes of blocks at a certain height. This is done very often (especially for masternode pings) and means holding `cs_main` lock every time, making the process slow and possibly leading to locking order inconsistencies.
**Solution**:
Cache the last N block hashes in the masternode manager.
In order to implement this efficiently, we introduce a new data structure called `CyclingVector`, which is a fixed-size vector, exposing only a setter `Set(i,  value)` which modifies the index `i % N`.
The cache is initialized at startup and updated when blocks get connected to /  disconnected from the tip.
The size (`CACHED_BLOCK_HASHES`) is currently set a …

[Validation] Introduce rolling cache for block hashes in masternode manager

---

src/qt/walletmodel.cpp

Simply checking if the data being pointed exists in the first place before accessing them in `WalletModel::isStakingStatusActive()`.

[GUI] isStakingStatusActive pointers guarded.

---

src/qt/pivx/topbar.cpp
src/qt/walletmodel.cpp
src/qt/walletmodel.h

Solving a crash due an `exc_bad_access`. Happened to me running the wallet with the debugger attached. 
At shutdown, the wallet ptr was already released and the GUI tried to access it from the `updateStakingStatus` function triggered by the timer.

[BUG][GUI] guarding wallet ptr access in WalletModel:getEncryptionStatus .

---

src/sapling/saplingscriptpubkeyman.cpp

Extremely trivial thing. Just to remove an annoying compiler warning.

[Trivial] Remove unused var in SaplingSPKM::AddSaplingSpendingKey

---

src/chain.cpp
src/chain.h
src/miner.cpp
src/primitives/block.cpp
src/primitives/block.h
src/rpc/blockchain.cpp
src/swifttx.cpp
src/txdb.cpp
src/validation.cpp
src/validation.h
src/validationinterface.cpp
src/validationinterface.h

Another decoupling from #1798, built on top of #1903 and #1915.
Containing three topics:
1) Sapling merkle tree root hash inclusion in the block header.
* Block version bumped to v8.
* Miner crafting the new merkle tree root hash and setting it into the block.
2) Track network total value entering and exiting the shielded pool. (*)
* Similar to the previous, initial, zc failsafe flow. (this can be done much better, like we did with zerocoin supply)
* Block negative shielded value pool balances. -- Network validation consensus rule --
3) ChainTip signal implemented.
* Signal to notify the listeners (wallet) about new blocks (or chain reorgs), broadcasting the new block and the current merkle tree so the listener can build upon it. -- Not connected to anything yet --
* Track net value …

[Validation] v8 blocks, Sapling merkle tree inclusion.

---

.travis.yml
src/Makefile.test.include
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/saplingscriptpubkeyman.h
src/test/CMakeLists.txt
src/test/librust/sapling_rpc_wallet_tests.cpp
src/test/librust/sapling_wallet_tests.cpp
src/test/librust/utiltest.cpp
src/test/librust/utiltest.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

Another PR decoupled from #1798. Built on top of #1912. PR starting on 69c58a2.
Focused on introducing sapling notes, nullifiers and witnesses management capabilities to the wallet and the sspkm (essentially wallet support for Sapling primitives). Tested by a wide range of unit tests that can be found in `sapling_wallet_tests.cpp`.
Further functional tests verifying the correct behavior of the implementation are included down the commits line in 1798: `sapling_wallet.py`, `sapling_wallet_nullifiers.py` (Haven't been able to include them here because those are depending on the shielded spend functionality that is introduced after this work and will have its own separate PR).
* Add Sapling notes map to CWalletTx —> 8ae2ea25fb2592378cae939ebba59bb38991b208
* [Sapling] SaplingNoteData class …

[Wallet] Sapling notes, nullifiers and witnesses management.

---

src/masternodeman.cpp
src/masternodeman.h
src/rpc/masternode.cpp

Built on top of #1904 . PR starting on 9123d22.
`listmasternodes` RPC command was taking a considerable amount of time, checked the flow and discovered a lot of redundancies in the process. This PR aims to correct them.
1) `CMasternodeMan::GetMasternodeRanks` is only used for an RPC call and it was checking and validating each Masternode instead of just retrieve them as it suppose to be doing (the tier two thread is the only one responsible of check and update the masternodes list).
2) `CMasternodeMan::GetMasternodeRanks` had a totally unneeded second vector load. Looping over the entire masternodes list one more time after getting it.
3) `listmasternodes` after calling `GetMasternodeRanks` was looking for each of the retrieved masternodes one more time using the retrieved masternode vin …

[RPC] Speeding up listmasternodes command

---

src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-sync.cpp
src/net_processing.cpp
src/rpc/budget.cpp

Continues the budget-refactoring thread.
Remove the following classes entirely
- `CBudgetProposalBroadcast`
- `CFinalizedBudgetBroadcast`
Replace them with a new dastream-based constructor and a `GetBroadcast` function (returning the serialized stream) inside `CBudgetProposal` / `CFinalizedBudget` classes.
This allows us to get rid also of `mapSeenProposals` and `mapSeenFinalizedBudgets` and all the relative ugly code duplication (just rely on `mapProposals` and `mapFinalizedBudgets` to check for existence, and to get the broadcast messages to send).
Starts with `[Refactoring] Introduce CFinalizedBudget/CBudgetProposal::GetBroadcast` (37c629881372e492a65ea17a4b18ad02cd53ed58)

[Refactoring] Budget, round 4: remove Broadcast classes

---

.travis.yml
src/Makefile.test.include

Travis environments don't have `/dev/tty`

[Travis] Increase Travis ccache size and reduce spam

---

src/qt/pivx/furabstractlistitemdelegate.h
src/qt/pivx/settings/settingsbackupwallet.cpp
src/qt/pivx/settings/settingsconsolewidget.cpp
src/qt/utilitydialog.cpp
src/test/transaction_tests.cpp

Also removes a few unused includes and cleans up the include ordering in
affected files.
This is part of a larger header include cleanup, but i'm keeping PRs narrowly
focused so as to avoid conflicts with existing PRs

[Cleanup] Remove duplicate header includes

---

src/bloom.cpp
src/bloom.h

Since the `--peerbloomfilterszc` is no longer available, we can remove the dependency on libzerocoin/bignum from `bloom.h` (which is implicitly carried over to a huge number of files, via `net.h` inclusion).

[Cleanup] Remove ZLNP remnants in bloom.h/bloom.cpp

---

src/Makefile.test.include

with this, there are now 3 distinct targets for unit tests:
- `check-standard`: Standard unit tests and util script tests
- `check-zerocoin`: Legacy unit tests for zerocoin related functions
- `check-sapling` : New sapling unit tests
Running `make check` from the repository root will run the 3 targets in
reverse order from the above to prioritize the longer tests being run
first.

[Tests] Split out zerocoin and sapling unit tests to their own targets

---

.travis.yml
src/Makefile.test.include

The unit tests for this job take upwards of 35 minutes due to 32-bit
performance restrictions, so set a stricter build timeout.
A build timeout of 600 seconds (10 minutes) was chosen as it is roughly double what a (currently) fully ccache'd build requires, so some leeway is left over to avoid unnecessary job restarts when a PR's changeset has a minimal impact on the build time.
Additionally, revert the workaround "hack" to continuously output `.`'s to the console when running the unit tests as #1944's reordering to run longer tests towards the beginning of the process has made it unnecessary. This also restores the easier to read output formatting.

[Travis] Set stricter timeout for Dash 32bit job

---

src/init.cpp

Startup option to initialize the node with mocktime set (regression testing only).
Hidden issue: the functional testing framework is already trying to use it without any luck as the startup option doesn't exist. (`TestNode` class, line 70).
Extra notes, this fixes #1916 tier two functional testing sync issues.

Testing framework, adding mocktime startup arg.

---

src/consensus/consensus.h
src/consensus/tx_verify.cpp
src/consensus/tx_verify.h
src/policy/policy.cpp
src/primitives/transaction.h
src/qt/walletmodel.cpp
src/sapling/sapling_transaction.h
src/sapling/sapling_validation.cpp
src/sapling/sapling_validation.h
src/sapling/transaction_builder.cpp
src/script/standard.cpp
src/validation.cpp
src/validation.h

Hopefully the last decouple from #1798.
Focused on introducing network flow connection and validations for shielded transactions (primitives and contextual checks), coins cache nullifier and anchor and a test case covering the invalid paths.
This work can be verified running 1798 functional tests suite. `sapling_wallet_nullifiers.py`, `sapling_wallet.py`, `sapling_wallet_anchorfork.py` , `sapling_key_import_export.py` are all running on top of this work, creating shielded txs, checking balances and generating blocks.
-- A future to do in the area is the mempool validations (nullifiers) connection (stated in 1798 but a little bit of redundancy here doesn't hurt) and continue adding more test coverage for the validation area. Plus, discuss the fee topic further on its own PR, can be dynamic …

[Validation] Introducing Sapling transaction network connection and validations.

---

src/txmempool.cpp
src/wallet/wallet.cpp

Bug introduced in #1698 .
The LockHeld assertion in `CheckFinalTx` fails when it is called from `GetMasternodeVinAndKeys` (via `CheckTXAvailability`).
This  PR adds an assertion to the functions calling `CheckFinalTx`
- `removeForReorg`
- `CheckTXAvailability`
And acquires `cs_main` mutex in `GetMasternodeVinAndKeys`.

[BUG][Wallet] Lock cs_main before accessing CheckFinalTx

---

src/masternode-budget.cpp
src/masternode-budget.h
src/rpc/blockchain.cpp
src/validation.cpp

Starting with `[Budget] Introduce mapFeeTxToProposal and mapFeeTxToBudget` (0eb9e45)
Since #1845 we no longer check repeatedly the active chain, when updating a budget object, we just save the height of the block including the collateral tx (ref #1845), when we first add the proposal/budget to the map.
Therefore we need to handle the case where said block is disconnected from the chain.
In order to do so efficiently, this PR adds two indexes (`mapFeeTxToBudget`/`mapFeeTxToProposal`), mapping collateral txids to the relative budget objects (while such objects are stored in the map).
A simple function `CBudgetManager::RemoveByFeeTxId()` can then be called from `DisconnectBlock` when undoing transactions, in order to remove the now-conflicted budget objects (without …

[Refactoring] Budget, round 5: proposals/budgets FeeTX indexes

---

src/policy/policy.cpp
src/policy/policy.h
src/primitives/transaction.h
src/qt/coincontroldialog.cpp
src/qt/guiutil.cpp
src/qt/paymentserver.cpp
src/wallet/wallet.cpp

Move only, moving `GetDustThreshold` and `isDust` from the transaction primitive class to policy.cpp.
Coming from 330bb5a456a5f9c26703fa742e4c80691e1455ab

[Backport] Moving GetDustThreshold out of transaction primitive

---

src/wallet/wallet.cpp

Missing initialization for `fStakeDelegationVoided` flag in `CWalletTx`.

[wallet] CWalletTx: missing fStakeDelegationVoided initialization

---

src/masternodeman.cpp
src/masternodeman.h
src/primitives/transaction.h
src/tiertwo_networksync.cpp

Built on top of #1845.
Refactored `Masternodeman:ProcessMessage` decoupling in different methods and stripped out every `cs_main` lock for a `Misbehaving` function call.

[Refactor] Strip out cs_main lock for misbehaving from Masternodeman:ProcessMessage

---

src/rpc/misc.cpp
src/wallet/rpczpiv.cpp
src/wallet/wallet.h
src/wallet/wallet_zerocoin.cpp
src/zpiv/zpivtracker.cpp
src/zpiv/zpivtracker.h

Trivial cleanup.
Remove unused map in `CzPIVTracker::GetBalance` and not-needed balance functions in `CWallet`.

[Cleanup] Remove unconfirmed/immature zerocoin balance calculations

---

CMakeLists.txt
src/Makefile.am
src/amount.h
src/coincontrol.h
src/init.cpp
src/memusage.h
src/miner.cpp
src/policy/feerate.cpp
src/policy/feerate.h
src/policy/fees.h
src/policy/policy.h
src/qt/bitcoinunits.cpp
src/qt/pivx/sendcustomfeedialog.h
src/rpc/blockchain.cpp
src/test/mempool_tests.cpp
src/test/policyestimator_tests.cpp
src/txmempool.h
src/validation.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.h

After #1950, this PR completes the backport of bitcoin/bitcoin#9279 to move CFeeRate out of libconsensus.
> CTxOut and CTransaction shouldn't depend on CFeeRate, which is something for policy checks and not consensus checks.

[Refactor] Move CFeeRate out of the consensus module

---

src/init.cpp
src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-payments.cpp
src/masternode-sync.cpp
src/net_processing.cpp
src/rpc/blockchain.cpp
src/rpc/budget.cpp
src/test/budget_tests.cpp
src/validation.cpp

Based on top of 
-  [x] #1858 
Starting with `[Trivial] Rename global budget object to g_budgetman` (64f0840)
This refactors `CFinalizedBudget::SubmitVote`, moving it to the budget manager (`VoteOnFinalizedBudgets`), and removing the nested locking issues.
It also does some trivial cleanup:
- rename the global budget manager `g_budgetman`
- pass const references to  `CBudgetVote`/`CFinalizedBudget` constructors
- pass the manager externally to `DumpBudgets` (instead of using the global one)

[Refactoring] Budget, round 6: masternode vote for finalized budgets

---

src/coins.cpp
src/consensus/tx_verify.cpp
src/miner.cpp
src/net_processing.cpp
src/pivx-tx.cpp
src/policy/policy.cpp
src/policy/policy.h
src/primitives/transaction.cpp
src/primitives/transaction.h
src/qt/transactionrecord.cpp
src/rpc/rawtransaction.cpp
src/sapling/sapling_core_write.cpp
src/sapling/sapling_validation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/transaction_builder.cpp
src/test/script_P2SH_tests.cpp
src/test/sighash_tests.cpp
src/test/transaction_tests.cpp
src/txmempool.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/rpczpiv.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Uniform the definition of `isSapling` transaction, which originally was meant only for txes with version equal to 2, and it was later changed to include also txes with version greater than 2 (but not updated everywhere).
Add a `IsShieldedTx` utility function defining "shielded tx" any transaction with isSapling version and with non-empty sapData.
Use `GetTotalSize` to get the serialized size of a transaction (instead of calling GetSerializeSize with `CTransaction::CURRENT_VERSION`).
Remove the possibility of having non-standard txes due to their version, after v5 enforcement.
Transactions with invalid version are now directly rejected in CheckTransaction.
Re-enables the IsStandardTx check on regtest.

[Core] Sapling transaction version

---

src/sapling/saplingscriptpubkeyman.cpp

Small and quick fix, master is currently not compiling due #1955 and #1952 getting merged without being based one on the other. the first PR renamed the tx `isSapling` method to `isSaplingVersion` and in the second PR, a new function was implemented `GetShieldedChange` that was using using `isSapling`.

[Wallet] fix GetShieldedChange, tx isSapling renamed to isSaplingVersion

---

src/consensus/tx_verify.cpp
src/sapling/sapling_validation.cpp
test/functional/feature_fee_estimation.py

The size limits for a sapling transaction are currently checked in 3 places:
1- `CheckTransaction` (validation.cpp)
2- `CheckTransactionWithoutProofVerification` (called by `SaplingValidation::CheckTransaction`)
3- `SaplingValidation::ContextualCheckTransaction`
While in (2) and (3) the size is correctly checked against `MAX_TX_SIZE_AFTER_SAPLING`, in (1) it is checked against the old `MAX_ZEROCOIN_TX_SIZE`. 
So a shielded transaction with size greater than `MAX_ZEROCOIN_TX_SIZE` would be wrongly rejected in `CheckTransaction`.
Fix the check in (1), selecting the correct max size for shielded/non-shielded transactions.
Move the size-check before calling SaplingValidation::CheckTransaction (as it's faster).
Remove the checks in (2) and (3) that are just redundant.

[BUG] Fix transaction size limits for sapling version

---

src/miner.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Currently, during the staking thread, the list of available coins is updated every 5 minutes.
This can lead to two problems:
- If a coin is not included due to low confirmations number, when it matures, it cannot be staked immediately: it gets included only after the full 5 minutes.
- If a coin is spent, it is not removed immediately from the list. So, if a valid kernel is found with said coin, the following two things happen.
First, the newly created block fails `TestBlockValidity` (as it contains essentially a double spend) and gets discarded by the staker, who also clears his mempool (thus removing the transaction that was spending the coin). 
Then, after few seconds, the staker tries again with the same coin, finding again a valid kernel with it, but this time creating a (valid) empty …

[Bug] Updated stakeable coins in staker thread

---

src/sapling/address.hpp
src/sapling/key_io_sapling.cpp
src/sapling/key_io_sapling.h
src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/saplingscriptpubkeyman.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_shielded_balances_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Up until now, the sapling operation flow (shielded transaction building) only was allowing to create a transaction from a single address source (transparent or shielded). This means that the user needed to select from which address the wallet should take funds from to spend.
This PR introduces two main new features and several improvements over the sapling operation class.
Main features:
(1) spending from several transparent sources and (2) spending from several shielded sources. Both selected by the operation process automatically, no user input needed.
Secondary improvements:
(1) making the change address key optional, (2) decoupling sapling operation build and send process (this is needed in order to be able to create the tx on the GUI and raw shielded txs using the command line). …

Sapling operation new spend from several different sources feature + send/build decoupling.

---

src/txmempool.cpp
src/txmempool.h
src/validation.cpp

Keep track of nullifiers of notes spent by mempool transactions (preventing in-mempool double spends).
Add consistency checks with coins view nullifiers.
Also, if the sapling anchor changes after a disconnection, we must evict from mempool any transaction that spends from the now-invalid root.

[Validation] Sapling nullifiers mempool connection

---

src/masternode-budget.cpp
src/masternode-budget.h
src/masternode-payments.cpp
src/masternode-payments.h
src/miner.cpp
src/wallet/wallet.cpp

Made the following changes:
1) Refactored `FillBlockPayee` flow to not have to input the previous index pointer, only the chain height.
2) Added chain height argument to `BudgetManager::FillBlockPayee` function to not have to use the internal budget manager cached height. The cached height could or not be on the previous block to the one that we are trying to fill in this function.

[Refactor] Removing prev index pointer from FillBlockPayee flow.

---

.travis.yml
src/rpc/blockchain.cpp
test/functional/sapling_mempool.py
test/functional/test_framework/test_framework.py
test/functional/test_runner.py

This adds a functional test to check the bahavior of sapling transactions with the mempool.
Specifically, it verifies the nullifiers/anchor management introduced in #1958:
- If a transaction spends a sapling note, already spent by another in-mempool transaction, it's not accepted in the mempool.
- Same if it tries to double-spend a note already spent on chain.
- If, after disconnecting a block, the sapling merkle tree root changes, any transaction that spends a note referencing the old root must be evicted from the mempool.
In order to verify the last point, a simple RPC `getbestsaplinganchor` is introduced in the "blockchain" category.
It returns the `pcoinsTip` best anchor.
Note: without 1958, the test crashes the node, as two transactions spending the same note can …

[RPC][Tests] Add sapling mempool test + getbestsaplinganchor

---

test/functional/test_framework/blocktools.py
test/functional/test_framework/messages.py

Quick one.
Update the message classes in the functional testing framework, with new serializations for v8 blocks (adding the sapling root) and v2 transactions (adding sapData).

[Tests] Add support for sapling txes and v8 blocks in the framework

---

src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/script/standard.cpp
src/script/standard.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/wallet/rpcwallet.cpp

Refactor `SaplingOperation`, abstracting the separation between shielded and transparent outputs inside `SendManyRecipient`.
Instead of using strings for the internal representation, save the recipients as either `CTxOut` (for transparent outputs) or a tuple comprising SaplingAddress, Amount and Memo (for sapling outputs).
This has the following pros:
- __Cleaner__: No extra "dummy" variables (such as the memo field for transparent outputs). Plus, as the separation between shielded/transparent recipients is implemented only in the TransactionBuilder, SaplingOperation effectively has an higher level of abstraction. 
- __Faster__: removes the need for extra encoding-decoding operations to go back and forth between strings and scripts.
- __More flexible__: since a `CTxOut` can be any kind of …

[Refactor] SaplingOperation: support for multisig, cold-staking, and OP_RETURN outputs

---

.travis.yml
src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/utilstrencodings.cpp
src/utilstrencodings.h
src/wallet/rpcwallet.cpp
test/functional/sapling_wallet_listreceived.py

- Don't require to input the memo in hexadecimal format in `shielded_sendmany`/`raw_shielded_sendmany`, accept human readable strings.
- Add a simple function to check valid UTF-8 encoded strings.
- Re-enable `memoStr` field in `viewshieldedtransaction` output (skip if not valid utf-8)
- Trim trailing zeros for the raw `memo` field in `listshieldedunspent`/`viewshieldedtransaction` output.
- Update unit and functional tests

[RPC][Tests] Memo field for sapling transactions

---

src/addrman.cpp
src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/rpc/masternode.cpp
src/sapling/sapling_operation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Base initial work in order to be able to generalize `CoinControlDialog` up to the point of introducing shielded notes selection (being developed in the Sapling GUI PR #1963).
Found several redundancies and not so good code over the overall `CoinControlDialog` class.  So.. have re-structured it in a large percentage, aiming to improve the performance and clean all of the inefficiencies.

Coin control dialog utxo processing/update flow large cleanup and improvements

---

src/rpc/blockchain.cpp
src/rpc/misc.cpp
test/functional/mining_pos_reorg.py

Add the shielded pool value (at the chain tip) to `getsupplyinfo`/`getinfo` output.
Rename `moneysupply` --> `transparentsupply`
Remove `zPIVsupply`/`zerocoinbalance` from `getinfo` output.

[RPC] shielded supply in getsupplyinfo and getinfo

---

src/masternode.cpp
src/masternodeman.cpp
src/tiertwo_networksync.cpp

Small decoupling from #1935 work.
Focused on the mnb and mnp misbehaving ban score increment.

[TierTwo] Missing misbehaving + ban score not introduced on the new msg dispatcher flow

---

.github/workflows/build-and-test.yml

This is a near 1:1 re-creation of our TravisCI workflow implemented in Github Actions.
TravisCI recently rolled out un-announced changes that have made it extremely difficult for open source projects to continue using the free build jobs they are supposed to able to use.
No artifacts are made available here due to the need to use a specific zk-params path at configure time so our unit/functional tests can run properly. The resulting binaries would not be easily portable to other systems.
See the workflow results in my repo to view the build logs for this: https://github.com/Fuzzbawls/PIVX/actions/runs/378462901

[Build] Replicate TravisCI tests in Github Actions

---

.github/workflows/build-and-test.yml

fixes an issue with a stale variable in the lint part of GA

[Build] Pass proper commit range to linter

---

src/util.cpp
util/fetch-params.sh

Don't initialize the sprout circuit. Don't load sprout parameters. Don't download them (saving 692 MB on disk).

[Sapling] Remove Sprout parameters

---

.github/workflows/build-and-test.yml
.travis.yml
src/consensus/consensus.h
src/policy/policy.cpp
src/policy/policy.h
src/rpc/rawtransaction.cpp
src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/sapling/sapling_transaction.h
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/test/librust/sapling_wallet_tests.cpp
src/test/librust/transaction_builder_tests.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
test/functional/mining_pos_coldStaking.py
test/functional/sapling_changeaddresses.py
test/functional/sapling_key_import_export.py
test/functional/sapling_wallet.py
test/functional/sapling_wallet_listreceived.py
test/functional/sapling_wallet_nullifiers.py
test/functional/test_runner.py

This PR proposes a mitigation for the attack known as "Sapling Woodchipper" (CVE-2019-11636).
Some references:
- https://nvd.nist.gov/vuln/detail/CVE-2019-11636
- https://github.com/zcash/zcash/issues/3983
Here we:
1) Define a dynamic minimum fee for shielded txes, based on the value of `minRelayTxFee` and the transaction size.
The minRelayTxFee is multiplied by a factor `K` (currently set to `1000`, and in the future could be variable based on the number of transactions in the mempool).
With the default value for minrelaytxfee (0.0001 PIV/kB), a shielded tx costs 0.0064 PIV plus:
- 0.0148 PIV per transparent input (P2PKH spend)
- 0.0384 PIV per shielded spend
- 0.0034 PIV per transparent output
- 0.0948 PIV per shielded output
A simple shielded-to-shielded transaction (with shielded …

[Consensus][Validation] Dynamic Fee for Shielded Transactions + Max Size.

---

src/activemasternode.cpp
src/masternode.cpp

Removed a not needed balance check in `CActiveMasternode::ManageStatus` (the remote masternode doesn't need to have balance), plus added better logging for the `notCapableReason`.
long talk with zebra about this ☕ , will need further cleanup but this is going for the right track.

CActiveMasternode::ManageStatus remove unneded GetAvailableBalance check

---

src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
test/functional/sapling_wallet.py

Fixing the currently not working shielded spending from multiple notes with different spending keys. Plus, added test coverage for this scenario.
Essentially, the issue was that we were using the same spending key for all of the spending proofs. It was a remanent from the previous workflow when we only were able to spend shielded coins from a single source.
This obviously enables the new notes coin control feature that is being introduced in 1963. So.. as soon as we merge this one, will rebase 1963 on top.
Extra note: the functional test coverage was added before the fix so it can easily be checked before and after the solution.

[Sapling][Bug] Fixing multi-source notes spending

---

src/validation.cpp

Quite straightforward, even with the spork enabled, we still need to add the final deprecation height for zerocoin so we can remove the spork need as well after v5.

[Validation] v5 zerocoin final deprecation.

---

src/qt/coincontroldialog.cpp

**Problem:**
The total selected and "after fee" amounts in coin control are not updated when selecting utxos (or shield notes) that have value greater than 10K PIV.
Bug found by @NoobieDev12 
**Cause:**
Bug  introduced with the coin-control wrapper enhancement.
In `CoinControlDialog::viewItemChanged`, we are taking the text __string__ of the amount, and passing it to `ParseFixedPoint`, which of course craps out when it finds a white space (which is added as thousands separator for values > 9999).
**Solution:**
Consider directly the data of the `QTreeWidgetItem` (at `COLUMN_AMOUNT`), rather than taking the text and parsing it (it's also faster).
Before:
After:

[BUG][GUI] CControl: cache utxo amount values properly

---

test/functional/sapling_mempool.py

Alice should receive the block mined, and expect a different message when trying to spend a note with a nullifier that has already been spent on-chain (rather than spent in the mempool).
These two bugs (not receiving the block, and expecting the wrong error message) nullify each other, so this is usually hidden and the test passes.
Although, sometimes, due to timing differences, Alice **does** receive the mined block, and this bug shows  (as can be seen in https://github.com/PIVX-Project/PIVX/runs/1465681420?check_suite_focus=true).
Fix the expected message, sync the nodes, and check the mined tx with alice.

[Tests] Fix double bug in sapling_mempool functional test

---

src/chainparams.cpp
src/consensus/params.h
src/consensus/upgrades.cpp
src/miner.cpp
src/policy/policy.cpp
src/qt/walletmodel.cpp
src/sapling/sapling_validation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/transaction_builder.cpp
src/test/librust/utiltest.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
test/functional/mining_pos_coldStaking.py
test/functional/mining_v5_upgrade.py
test/functional/sapling_changeaddresses.py
test/functional/sapling_key_import_export.py
test/functional/sapling_mempool.py
test/functional/sapling_supply.py
test/functional/sapling_wallet.py
test/functional/sapling_wallet_anchorfork.py
test/functional/sapling_wallet_listreceived.py
test/functional/sapling_wallet_nullifiers.py
test/functional/test_framework/test_framework.py

Rename the NU param info/index removing the "dummy" label.
```
-BEGIN VERIFY SCRIPT-
sed -i 's/v5_dummy/v5_shield/g' src/*.h src/*.cpp src/*/*.h src/*/*.cpp src/*/*/*.h src/*/*/*.cpp test/functional/*.py ;
sed -i 's/v5 dummy/v5 shield/g' test/functional/*.py test/functional/*/*.py;
sed -i 's/UPGRADE_V5_DUMMY/UPGRADE_V5_0/g' src/*.h src/*.cpp src/*/*.h src/*/*.cpp src/*/*/*.h src/*/*/*.cpp ;
-END VERIFY SCRIPT-
```

[Trivial] Rename placeholder for v5 network upgrade info

---

src/validation.cpp
src/version.h
test/functional/test_framework/messages.py

On eve's of v5 testnet, bumping the network protocol version.

[Consensus] Bump active protocol version to 70920

---

src/qt/addresstablemodel.cpp

Pretty straightforward, fixing the missing address type in the export address book for shielded addresses.

[GUI] Fixing export addressbook, shielded addresses missing type

---

src/activemasternode.cpp
src/budget/budgetmanager.cpp
src/budget/budgetproposal.cpp
src/budget/finalizedbudget.cpp
src/masternode-payments.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/masternodeman.h
src/messagesigner.cpp
src/qt/pivx/mnmodel.cpp
src/rpc/budget.cpp
src/rpc/masternode.cpp
src/serialize.h
src/validation.cpp

Currently we check whether a masternode collateral is spent, in `CMasternode::Check()`, which is called in a time-based polling fashion, looking for the collateral outpoint in the coins view cache (and countless other times on-demand, when we want an up-to-date status).
This is highly expensive, and inconsistent (peers check masternodes at different times, thus have slightly different masternode states).
Collaterals, as all coins/outpoints, can only be spent inside blocks.
So we should do this check only when connecting new blocks, not *every x seconds*, or **every time that we need to count the number of enabled masternodes**, just to name the most glaring example (`CMasternodeMan::CountEnabled`).
This can be done very efficiently if we change the data-structure to store them inside the …

[Core] Masternode collateral index

---

src/qt/pivx/sendconfirmdialog.cpp
src/qt/pivx/sendconfirmdialog.h

The transaction detail dialog was trying to show the shielded inputs of a transaction when the tx was not from the wallet. Which is impossible as it has no information about them. This fixes it.

[GUI] Tx detail, don't show inputs if there is no information for them.

---

.github/workflows/build-and-test.yml

A few build jobs weren't using the expected "goal" config parameter, most notably the macOS job, which is supposed to test `make deploy` to create a `.dmg` file.
Further, there was a typo in the macOS config area that incorrectly used `apt-get` instead of `apt_get`

[Build] Address more issues with GA

---

src/qt/pivx/send.cpp

Simple visual bugfix.
`labelAmountRemaining` not being updated with the proper coin-type "shielded", after selecting notes in coin control.
Closes #2002

[BUG] label of coin type in send widget after shielded coin control

---

src/init.cpp

**Problem**:
Starting the wallet with `--reindex`  (w/wo `--zapwallettxes`) causes a crash if the wallet has shield transactions.
**Cause**:
`g_IsSaplingActive` is used to select the proper serialization for v2 txes (with or without sapData).
During init, `g_IsSaplingActive` is set to true in `LoadBlockIndexDB` when connecting a post-enforcement block.
When `--reindex`ing, though, `LoadBlockIndexDB` is skipped in `LoadBlockIndex`, and the global flag remains false.
Therefore `g_IsSaplingActive` is false when init gets to `InitLoadWallet` and the deserialization of shield transactions throws.
**Solution**:
Set `g_IsSaplingActive` to true when `--reindex`.
This way the wallet can be loaded, and then the flag switches back to false as soon as the first pre-enforcement block is connected …

[BUG] g_IsSapling active flag during reindex

---

src/sapling/saplingscriptpubkeyman.cpp
src/test/librust/sapling_wallet_tests.cpp

No need to. We will never spend them.

[Wallet] Sapling: don't update witnesses for external notes

---

src/net.cpp

Coming from [btc/9671 ](https://github.com/bitcoin/bitcoin/pull/9671)
> Once the CNode has been added to vNodes, it is possible that it is
> disconnected+deleted in the socket handler thread. However, after
> that we now call InitializeNode, which accesses the pnode.
> 
> helgrind managed to tickle this case (somehow), but I suspect it
> requires in immensely braindead scheduler.

[Backport] P2P open network connection, fix race condition

---

src/activemasternode.cpp
src/masternode-payments.cpp
src/masternode-payments.h
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/masternodeman.h
src/qt/pivx/mnmodel.cpp
src/rpc/masternode.cpp

This is the second part of #2000 , and it's based on top of it.
Here we remove `CMasternode::check()` and `CMasternode::activeState`, replacing it with a function `GetActiveState()`, which returns the state in real time.

[Refactor] Masternode activeState on-demand

---

src/qt/pivx/sendmemodialog.cpp

bug found by @jakimanboy (https://github.com/PIVX-Project/PIVX/pull/1999#issuecomment-736984982)
>  Click `Add encrypted memo`, enter some text, then click save, then click `Update memo`, and now `RESET` doesn't actually clear the memo content, and the `Update memo` button also does not change back to `Add encrypted memo`.
cause: operationResult not set to true in `SendMemoDialog::reset()`, thus entry never updated in the send widget.

[BUG][GUI] memo not reset after hitting reset button

---

src/coincontrol.h
src/wallet/wallet.cpp

Removed unused and redundant flows from `CWallet::CreateTransaction`. Like the utxo splitter that isn't used anywhere and the coin age calculation that was previously being used for free transaction calculation (which we don't have anymore).
It will speedup the transaction creation process for v1 transactions removing one loop over all of the available utxo and help on the v1-v2 transaction creation processes unification goal.

[Wallet] Initial cleanup to the v1 transparent CreateTransaction flow.

---

src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/wallet/rpcwallet.cpp
test/functional/sapling_wallet.py
test/functional/test_runner.py

Instead of throwing an error, let's repack the json request and send it to `shieldedsendmany`.
This makes the integration of send-to-shield-address much easier for third-party services.
We keep the old implementation of `sendmany` for `t->t` transactions, until the two flows are properly abstracted.
Also fix a minor bug found in `sendmany` (not properly considering the `fIncludeDelegated` flag), and add capability to spend P2CS inside `SaplingOperation`.
Note:  the same thing proposed here, could be done with the RPC `sendtoaddress` (future).

[RPC] redirect sendmany to shieldedsendmany when recipient is shielded

---

test/functional/test_runner.py

Trivial, as per title.
```
./test_runner.py --all
```
for the complete run of all the 62 (!) scripts in our suite.

[Tests] Add --all option to test_runner for complete functional tests coverage

---

src/masternode-payments.cpp
src/masternode-payments.h
src/masternodeman.cpp
src/masternodeman.h
src/qt/clientmodel.cpp
src/rpc/masternode.cpp

Fixes the following inconsistency (https://github.com/PIVX-Project/PIVX/runs/1491040884):
```
2020-12-03 07:55:03 POTENTIAL DEADLOCK DETECTED
2020-12-03 07:55:03 Previous lock order was:
2020-12-03 07:55:03  (1) cs masternodeman.cpp:481 (in thread pivx-msghand)
2020-12-03 07:55:03  (2) cs_mapMasternodeBlocks masternode-payments.cpp:483 (in thread pivx-msghand)
2020-12-03 07:55:03 Current lock order is:
2020-12-03 07:55:03  cs_mapMasternodePayeeVotes masternode-payments.cpp:619 (in thread pivx-masternodeman)
2020-12-03 07:55:03  (2) cs_mapMasternodeBlocks masternode-payments.cpp:619 (in thread pivx-masternodeman)
```
Remove the "cleanup" during DB read (move it at the beginning of the thread).
Pass the masternode-count and current-height to `CleanPaymentList`, so there is no call to the …

[BUG] Fix lock order issue with CMMan::CheckAndRemove and CMPayments::CleanPaymentList

---

src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/masternodeman.h
src/rpc/masternode.cpp

Fixing
```
2019-10-31 22:53:22 POTENTIAL DEADLOCK DETECTED
2019-10-31 22:53:22 Previous lock order was:
2019-10-31 22:53:22  (1) cs masternodeman.cpp:481 (in thread pivx-msghand)
2019-10-31 22:53:22  (2) cs_main validation.cpp:193 (in thread pivx-msghand)
2019-10-31 22:53:22 Current lock order is:
2019-10-31 22:53:22  (2) cs_main validation.cpp:2318 (TRY) (in thread )
2019-10-31 22:53:22  (1) cs masternodeman.cpp:465 (in thread )
```
Move `GetLastPaid`/`SecondsSincePayment` to the manager and clean up.

[BUG] GetLastPaid/SecondsSincePayment locking cs_main

---

src/budget/budgetmanager.cpp
src/budget/budgetproposal.h
src/budget/finalizedbudget.h

If `submitbudget` RPC fails for an issue with the collateral (e.g. not enough confirmations), it returns a generic (and confusing) 
```
invalid budget proposal - (code -1)
```
Fix: save the error returned by `CheckCollateral` inside the invalid-reason-string of the budget/proposal object (so it is returned in the RPC with `IsInvalidReason()`.

[BUG][RPC] Save collateral errors into proposals/budgets strInvalid

---

src/qt/pivx/forms/sendmultirow.ui
src/qt/pivx/sendmultirow.cpp

No available memo in the delegation process, hiding the memo button in the cold staking screen.

[GUI] Cold staking screen, hide memo entry button. 

---

src/qt/pivx/topbar.cpp
src/qt/pivx/topbar.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/wallet/wallet.cpp
src/wallet/wallet.h

HD wallets (`FEATURE_PRE_SPLIT_KEYPOOL`) automatic upgrade to `FEATURE_SAPLING` to support shielded functionality by default.
This is an straightforward version bump because only the seed is needed to generate the sapling keys tree. More info in #1553.
Plus added a version guard in the shielded addresses generation method, so pre-HD wallets show the proper error when they cannot generate shielded addresses (essentially, will notify the user that he/she needs to upgrade their wallet to support shielded operations).
As an extra information, pre-HD wallets who upgrade to HD running v5, will automatically be upgraded to support sapling features. This was done in #1553 as well.

[Wallet] HD wallets automatic upgrade to sapling features.

---

src/addrman.h

Another quick one, from bitcoin/bitcoin#11252
> Power failure on my machine resulted in a corrupted addrman that would hit bad assertions when trying to serialize the "cleared" addrman to disk:

[P2P] When clearing addrman clear mapInfo and mapAddr

---

src/sapling/sapling_operation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/saplingscriptpubkeyman.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/wallet/wallet.cpp

This is a contingency plan, in case of missing cached nullifier of a spent note in the wallet.
Since, during the spend, the wallet is unlocked, and we have the spending key, we can directly recover the nullifier from the note (provided that we have a valid cached witness) and fix the issue in the background, without requiring any user intervention.
If we don't have the witness, we can still provide a better log and error message in the gui, than a generic, and probably obscure
```
bad-txns-shielded-requirements-not-met
```

[Sapling] Try to recover corruption of notes cache during send operation

---

src/wallet/rpcdump.cpp
test/functional/wallet_dump.py

Since people don't seem to be paying attention to the general console
warning, this adds an explicit warning to the output JSON object of the
dumpwallet command.
Also disallows 2 common keywords from being used in the filename.

[RPC] Add additional warning to dumpwallet result object

---

.github/workflows/build-and-test.yml

Now that we can run the functional test suite with "--all", we don't
need to have 3 separate jobs to get full test coverage.

[GA] Reduce number of concurrent jobs

---

src/masternode.h

`Status()` calls `GetActiveState()`, which already locks cs.

[Masternodes] remove recursive lock in CMasternode::Status()

---

src/qt/pivx/mnmodel.cpp

As #2019 got little bit big and we are entering into a freeze period, this is a quick fix to the "MISSING" state invalidly shown as "REMOVE" in the masternodes screen. Introduced by #2006.
This affects the GUI as it makes masternodes that are not started to appear as "REMOVE" instead of "MISSING" as it was before (could be a MN in the configuration file only or even with the collateral accepted but not started).

[GUI] Workaround to the MN MISSING/REMOVE labeling

---

src/sapling/saplingscriptpubkeyman.cpp

On block disconnection, notes that aren't from the wallet are currently passing through the witness decrement process causing a crash on reorgs. The note data cached height will be different than the disconnected block height, `witnessHeight` is never updated for external notes as them don't need a witness at all.

[SSPKM] Crash fix, external notes witness decrement

---

src/qt/pivx/forms/sendconfirmdialog.ui
src/qt/pivx/res/css/style_dark.css
src/qt/pivx/res/css/style_light.css
src/qt/pivx/send.cpp
src/qt/pivx/sendconfirmdialog.cpp

**Problem:**
Memo word-wrap in the txdetails dialog works only with white-spaces.
But with a single too-long word the frame is stretched, messing up the layout:
**Fix:** 
switch from QLabel to QPlainTextEdit (read-only), so the text is properly wrapped, and can also be conveniently selected for copying specific parts.
To copy the whole message, a copy-to-clipboard button is also added:
Big thanks to @NoobieDev12 for his extensive testing of all the features :pray:

[BUG][GUI] TxDetail dialog memo: plain text edit + copy button

---

src/qt/pivx/receivewidget.cpp
src/qt/pivx/send.cpp
src/qt/pivx/send.h
src/qt/pivx/settings/forms/settingsfaqwidget.ui

Gathered a crash fix with some GUI corrections in the PR.
Covering the following points:
1) Fixed a runtime error when the GUI tries to generate a shielded address with the wallet locked.
2) Cleaned an unused member and function in the send screen.
3) Corrected the total available that can be shielded on the shield all process (subtracting the locked coins).
4) Added text styling for the "No available address" error text in the receive widget (could happen only if the wallet is locked and there is no other shielded address to show).
5) Remove zerocoin mention from the FAQ.

[GUI] Address generation error on locked wallets fix plus extra corrections.

---

doc/build-windows.md

This is a cherry-pick from Bitcoin upstream. 
bitcoin/bitcoin#19408
```
This is a solution for the issues described in #17277 and #18348
When cross compiling Bitcoin Code for Windows the Autoconf configure scripts attempt to execute Win32 PE files. The configure scripts expect the attempt to fail, however, WSL supports forking the execution of Win32 PE files out to the underlying Windows OS. This can result in the executions failing for unanticipated reasons, which is the case in the two referenced issues.
This PR adds an explanatory note and additional instructions to temporarily disable WLS's Win32 support.
```
Anyways I am making a pull request for this as it would be nice to be able to cross-compile pivx using the docs in the repo instead of checking bitcoin upstream for fixes and …

doc: Windows WSL build recommendation to temporarily disable Win32 PE support

---

build-aux/snap/snapcraft.yaml
params/Makefile.am
params/install-params.sh
src/util.cpp

Followup to #2022 to resolve the lingering issues with ppa/snapcraft builds.
build-log of a PPA build can be seen [here](https://launchpadlibrarian.net/510054528/buildlog_ubuntu-bionic-amd64.pivx_4.3.99~202012060757+gitdc5ad4478~ubuntu18.04.1_BUILDING.txt.gz)
This also introduces proper `desktop-launch` wrapping for the nightly snapcraft builds, which is required to successfully open the GUI wallet from the snap commands.

[Build] Proper coverage for ppa, local, and snapcraft

---

src/qt/pivx/settings/settingsconsolewidget.cpp
src/qt/pivx/settings/settingsconsolewidget.h
src/qt/pivx/settings/settingswidget.cpp

Another attempt to alert users about scams, added a second confirmation dialog after requesting a `dumpwallet` or `dumpprivkey` in the internal GUI wallet console. 
Want to emphasize that this is a GUI only change, command line RPC call will continue exactly as before.
After typing `dumpwallet`, the application will launch the following confirmation dialog:
So, in other words, the command will only be executed if the user presses "OK" on this "**DON'T DO THIS**" warning

[GUI] Double confirmation dialog for dumpwallet command.

---

src/chainparams.cpp

Set final enforcement height for Testnet's `Consensus::UPGRADE_V5_0` at block `1873550`

[Consensus] Set final enforcement height for V5 on Testnet

---

CMakeLists.txt
src/test/CMakeLists.txt

Without the framework include, CMake isn't able to find the `CFBundleGetMainBundle` and relative classes/functions. Thus why isn't compiling pivxd and the unit test target. Dependency included due #2022 changes.

[Build] CMake pivxd and unit tests: fixing missing MacOS framework.

---

src/test/CMakeLists.txt
src/test/validation_tests.cpp

Added unit test coverage for the sapling validation flow.
Checking the following errors being thrown:
1) Empty vin/spends transaction.
2) Empty outs transaction.
3) Duplicate nullifiers in the same transaction.
4) Coinbase/coinstake shielding PIVs.

[Test] Adding sapling transaction validation unit test coverage.

---

src/sapling/sapling_operation.cpp

Shield transaction transparent coin selection, sort decrementally instead of incrementally.

[Sapling] Transparent inputs selection, fixing inverted order.

---

src/tiertwo_networksync.cpp

Removing an extra not needed logging.

[TierTwo] Remove unneeded extra logging.

---

src/miner.cpp
src/primitives/block.h

Avoids an upgrade warning from being triggered after 100 v8 blocks are
on chain. Moved the network upgrade consensus check further up too.

[Miner] Update block header's current version to v8

---

src/wallet/rpcwallet.cpp

A wallet could have an SSPKM, but not the latest version.
Check for `FEATURE_LATEST` support at the beginning of `upgradewallet` RPC.

[BUG][RPC] Fix check in wallet upgrade RPC

---

src/wallet/rpcwallet.cpp
test/functional/sapling_wallet_listreceived.py

Add the nullifier to the output of `listshieldedunspent`.
Verify it in `sapling_wallet_listreceived` functional test.

[RPC] Add nullifiers to listshieldedunspent output

---

src/wallet/wallet.cpp

Essentially there is a problem in unlocked wallets running HD version when them start running v5. The SSPKM seed is set but the version isn't being updated to reflect the sapling features support. Ending up with a wallet with all of the sapling capabilities with the only exception of marking spent notes as spent..
This fixes it plus adds a guard into the activation mechanism to be a 100% sure that the version is set when the SSPKM is activated.

[Wallet] BugFix: automatic upgrade for unlocked wallet

---

src/test/rpc_tests.cpp

Fixing `rpc_ban` unit test, failing in master due an invalid timestamp. 
Coming from #13061

[Test] Make rpc_ban unit test pass again

---

src/qt/pivx/sendconfirmdialog.cpp

`QPlainTextEdit` cursor always scroll down up to the bottom if the view is scrollable, this force it to start from the top in the transaction detail screen over the memo field so it can be read properly.

[GUI] Transaction detail, scroll memo fix, starting from the top.

---

src/netbase.cpp

Made a set of back ports to make Socks5 connection failures less noisy and less unnecessarily scary.
Plus added a straightforward removal of `getaddrinfo_a` which was never available at configure time.
Back ported PRs list:
#8033
#9229
#9539

[Net] Socks5 netbase back ports, less scary failures.

---

src/activemasternode.cpp
src/activemasternode.h
src/budget/budgetmanager.cpp
src/masternode-payments.cpp
src/masternodeman.h
src/rpc/budget.cpp
src/util.cpp

Performance improvement for masternodes, instead of having to parse the global private key string, decode it once and cache it on the active masternode class, plus remove the global mn privkey string.
As this was decoded and re-decoded everywhere, this will have a direct effect on the ping send process, vote on finalized budgets, masternode payments block processing, and budget proposal vote flow.

[Masternode] Encapsulate global and do not parse privkey redundantly everywhere.

---

src/validation.cpp
src/validation.h

Cleaning up two unused functions in the validation area. `DisconnectBlocks` and `ReprocessBlocks`.

[Cleanup] Removing unused DisconnectBlocks and ReprocessBlocks

---

src/activemasternode.cpp
src/masternode.cpp
src/masternode.h

Check the pinged blockhash at the beginning of `CMasternodePing::CheckAndUpdate`.
So we don't ask new broadcasts when it's wrong, and we can immediately detect stale mnbs.
Also, explicitly pass the signature time when constructing `CMasternode` and `CMasternodePing` objects (instead of automatically setting it to the current time, which might be error prone, leading to unintended updates).

[BUG][MN] Immediately detect forked masternodes

---

src/wallet/rpcwallet.cpp
test/functional/sapling_wallet.py

Same as we did with `sendmany` on #2014 .
Keep old implementation for transparent recipients.
Add test case in `sapling_wallet` functional test (also currently running live on https://faucet.pivx.link/).

[RPC] redirect sendtoaddress to shieldedsendmany for shielded recipient

---

src/consensus/consensus.h
src/miner.cpp
src/validation.cpp
test/functional/sapling_fillblock.py
test/functional/test_runner.py

Given the results of the stress tests performed, limit it to 750 kB (at least for this first iteration).
Add functional test.
Note: this causes a fork on `testnet4` if an "old" client mines a block with more than 750kB (cumulative size) of shielded txes.
Although, in order to do so, the staker should set a `-blockmaxsize` at startup, higher than the default (and there should be enough txes available in the mempool).

[Consensus] Max block space available for shielded txes

---

src/qt/coincontroldialog.cpp

For example, if user is running a masternode, after 100+ days of receiving rewards and not moving them, there will be more than 100 different UTXOs. Default column width when starting a wallet is currently not wide enough to show 3 digit amount of UTXOs. This PR fixes it.
**Before:**
**After:**

[GUI][Trivial] Adjust CoinControl column widths for readability

---

CMakeLists.txt
src/Makefile.am
src/guiinterface.h
src/init.cpp
src/pivx-cli.cpp
src/pivx-tx.cpp
src/pivxd.cpp
src/qt/clientmodel.cpp
src/qt/pivx.cpp
src/qt/pivx/pivxgui.cpp
src/rpc/client.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/test/test_pivx.cpp
src/timedata.cpp
src/util.cpp
src/util.h
src/validation.cpp
src/validation.h
src/warnings.cpp
src/warnings.h

Back ported two different PRs from upstream to solve possible races over the `strMiscWarning` and `fLargeWork*Found` global fields plus some small cleanup.
#6022: to not depend on `guiinterface.h` every time that a back end text needs translations.
#9236: eliminating data races for strMiscWarning and fLargeWork*Found and making QT `runawayException` call `GetWarnings("gui")` instead of directly access `strMiscWarning`.
Extra information:
This work is part of a larger rabbit hole that i'm working on to be able to solve #1973 current issues and compile the project in macOS again (solving the newer boost version errors).

[Backport] Fix races for strMiscWarning and fLargeWork*Found

---

src/miner.cpp
src/validation.cpp
src/validation.h

1) fix a bug in `CreateNewBlock` where we check the PoW before mining the correct nonce (only for upcoming testnet5, no effect on main-net or testnet4)
2) Reject blocks with version below 8 after v5 enforcement (same as we do for the other block versions)
3) Set the proper block version in `CreateNewBlock` based on the current chain height (only for upcoming testnet5, no effect on main-net or testnet4)
4) Remove unneded check for block-version-4 based on zerocoin activation time, and cleanup `CheckBlockHeader`.

[Consensus][Validation] Reject outdated block version after v5 enforcement

---

src/consensus/upgrades.cpp
src/init.cpp
src/primitives/transaction.h
src/sapling/sapling_validation.cpp
src/sapling/sapling_validation.h
src/wallet/wallet.cpp

To hopefully clean up the tx serialization from the contextual flag after v5 enforcement.
Note: This PR marks the end of `testnet4` (clients compiled from master branch would no longer be able to run there) so it should be merged last, before starting `testnet5` alongside.

[Consensus] Bump TxVersion::SAPLING to 3

---

src/sapling/sapling_operation.cpp
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/uint256.h
src/wallet/wallet.cpp

First commit backports bitcoin/bitcoin#9465.
Following commits adapt the same idea to sapling transactions, including also the spend/output descriptors.
This gives a **huge** speed-up in the transaction-creation process (especially with many inuputs and/or outputs).
Down-side: less time for the awesome shield animation in the GUI :)
~~Built on top of #2064 to remove the conflicts.~~

[Wallet][Sapling] Dummy ECDSA sigs and zk-proofs during fee calculation loop

---

src/qt/pivx/receivewidget.cpp

Fix a nice bug found by @vampyren.
If `AddressTableModel::dataChanged` is fired, check the address `TypeRole` inside `ReceiveWidget::refreshView`, and skip the update for un-related roles.

[BUG][GUI] Receive widget: check typeRole before refreshing view

---

src/budget/budgetproposal.cpp
src/budget/budgetproposal.h

- raise the threshold required to 30%
- never kill a proposal before its first superblock.
Closes #1852

[Consensus] Budget: Fix instant killing of proposals

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/miner.cpp
src/validation.cpp

Update chainparams for `testnet5`.

[Consensus] Start new Testnet (v5)

---

src/qt/pivx/dashboardwidget.cpp

The combobox shouldn't get hide when there are transactions in the wallet, independently on the selected filter. If the user selects a type that it isn't in the wallet, the filter combobox will disappear, leaving the tx list empty and not allowing any other movement.

[GUI] Dashboard, fix type filtering disappearance.

---

src/wallet/wallet.h

(thus including also unconfirmed, delegated balance).
One immediate effect is that, this way, delegations are reflected under "Pending balance" in the GUI (owner-side), before being included in a block (so this closes #2072)

[BUG][Wallet] return unconfirmed balance for all spendable coins by default

---

src/budget/budgetmanager.cpp
src/masternode-payments.cpp

Edge case where the consensus is not aligned between the block producer and the block verifier.
Verifier: (`CheckBlock` --> `IsBlockPayeeValid` --> `IsBudgetPaymentBlock`), during a superblock, expects a payment to a budget proposal, even with the case of N<20 active masternodes on the network, provided that all N voted on the finalized budget (the threshold is N-1).
The block producer, instead, is paying a masternode (`GetPayeeAndAmount`). 
Fix it, using the same flow of the verifier: first check the threshold, adjusting it for the case of N<20 (5% = 0), setting it to N-1, and then check that there is a finalized budget with enough votes. 
Also remove the extra call to `IsBudgetPaymentBlock` directly from `FillBlockPayee` (now called by `CBudgetManager::FillBlockPayee` --> …

[BUG][Masternode] Miner not paying valid finalized budget if <20 active masternodes

---

src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/net.cpp
src/wallet/rpcwallet.cpp

This fixes a typo, and cleans up some inconsistencies in the RPC help output.
namely, a typo in `getsaplingnotescount`, the errant display of multisig being disabled, and the styling/formatting of command arguments

[RPC] Cleanup RPC help output

---

src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h

Addresses the comment in https://github.com/PIVX-Project/PIVX/pull/2033#pullrequestreview-545967813
Always use the minimum width in list-mode.
Save the current width when switching from tree-mode to list-mode, and restore it switching back.

[GUI] coin-control: remove column checkbox extra white space in tree-mode

---

src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/pivx/settings/settingsinformationwidget.cpp
src/qt/pivx/settings/settingsinformationwidget.h

The count isn't updated on every widget show, only via the event (which only happen every 40 minutes as Masternodes updates aren't regular at all).
This PR fixes it updating the masternode count every time that the screen is visible, then the event is in charge of update it if the user stays there long enough.

[GUI] Settings information, fix missing initial masternodes count value.

---

src/script/sign.cpp

Exceptions/errors caught should be passed by reference.
If the catch-block is not modifying the exception/error, the reference should be `const` (same as we did way back in #979)
Fix one instance in `TransactionSignatureCreator::CreateSig` where we are passing a logic_error by copy, causing the `catching polymorphic type` warning reported in #2076

[Trivial][Refactor] Pass caught logic_error by reference in CreateSig

---

src/qt/pivx/send.cpp

Hiding the "shield all" functionality for now.
Would be good to expand this functionality later on splitting big transactions into smaller ones, dividing it across blocks, adding decoys etc.

[GUI] Hide shield all coins button.

---

src/sapling/sapling_core_write.cpp
test/functional/sapling_mempool.py
test/functional/sapling_wallet.py
test/functional/sapling_wallet_listreceived.py

One user-facing string left out in #2086

[Trivial][RPC] Drop 'ed' suffix from vShielded* in TxSaplingToJSON

---

src/qt/transactionrecord.cpp

Finally found it, fixing the duplicate record issue. 
Briefly explained: As is now, `decomposeDebitTransaction` can return false even when the outputs parsing was done correctly due the non-existency of shielded outputs. If this happens, the caller `decomposeTransaction` process it as if `decomposeDebitTransaction` didnt parse it successfully, appending an extra all-in-one record.

[GUI][BugFix] Duplicate transaction records.

---

src/qt/coincontroldialog.cpp

Resizing column checkbox to contents in coin-control (introduced in #2070) seems to be cutting off part of the lock icon, for locked utxos, on windows, as reported by @NoobieDev12 .
Let's set a default width of 70 then.
Here's how it looks on linux/gnome

[Trivial][GUI] coin control: Fixed column size in list-mode

---

src/qt/walletmodel.cpp

Bug found in current master.
Steps to reproduce
1) Unlock the wallet `for staking only`.
2) Try to send a transaction
3) The wallet asks to insert the password (to fully unlock).
4) Insert the password, and then accept the confirmation dialog.
**Issue**:
Instead of sending the tx, the wallet asks again for the password, and still doesn't send the transaction (without any feedback) even when the password is entered a second time.
**Cause**:
By the time the flow reaches `WalletModel::sendCoins`, the UnlockContext is lost, and the wallet has been relocked (for staking only) already.
This is correct, as the transaction is created and signed in `WalletModel::prepareTransaction`, and `sendCoins` only commits the transaction, therefore it doesn't need a fully-unlocked wallet.
The function, …

[BUG][GUI] Don't return StakingOnlyUnlocked from WalletModel::sendCoins

---

src/interface/wallet.cpp

Another great find by @NoobieDev12 .
Shielded balance is counted twice in the GUI when "pending".
Since we have a separate cached amount (`unconfirmed_shielded_balance`) in the `WalletBalances` struct, we should save in `unconfirmed_balance` only the sum of *transparent* unconfirmed outputs.

[BUG][GUI] Cache unconfirmed_balance only for transparent outs

---

src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
test/functional/sapling_malleable_sigs.py
test/functional/sapling_mempool.py
test/functional/sapling_wallet.py

Improve code readability, ensure that we're including the wallet unlock notice where appropriate, remove some redundant help output lines, and finally, make the return output of `rawshieldsendmany` be just the transaction's hex string rather than the full JSON object (functional tests are updated to reflect this change).

[RPC] Fix more RPC help output

---

src/activemasternode.cpp
src/init.cpp
test/functional/test_framework/test_framework.py

Do not return an error if a different peer port is used for Masternodes running over tor.
The peer is behind a hidden service which has the public port fixed to the default port already. The local port can be used freely, the network cannot prevent it.

[Startup] Do not block local peer port selection for Masternodes running over tor.

---

src/budget/budgetmanager.cpp
src/budget/budgetproposal.cpp
src/budget/budgetproposal.h
src/chainparams.cpp
src/consensus/params.h
src/rpc/budget.cpp
src/test/budget_tests.cpp
test/functional/rpc_budget.py
test/functional/tiertwo_governance_sync_basic.py

Set it to `6` on main-net and `20` on testnet.
Consider "expired" a proposal 1 and a half cycles after the last payment (instead of 1 cycle + a number of blocks equal to the number of payments) and enforce that block start is a superblock (currently checked only in the RPC, but not in consensus).
Update the functional test to check improper inputs during the creation of a budget proposal.
Also fix a bug with invalid total budget amount on testnet.

[Consensus] Max payment count for budget proposals

---

src/policy/policy.cpp
src/test/librust/sapling_wallet_tests.cpp
src/test/librust/transaction_builder_tests.cpp
src/validation.cpp
src/validation.h
test/functional/sapling_mempool.py
test/functional/sapling_supply.py
test/functional/sapling_wallet.py
test/functional/sapling_wallet_listreceived.py

Thus reduce default minimum fee for shielded txes by 10x

[Policy] Set DEFAULT_SHIELDEDTXFEE_K to 100 (from 1000)

---

src/wallet/wallet.cpp

The list of StakeableCoins is growing with every incomming block.
In f935801f73839a668a94bdd39b73d2499df4582f a slightly different StakeableCoins initialization was introduced, but the list of StakeableCoins is not cleared before initializing, which causes the list of StakeableCoins to grow with every incomming block.
Clear StakeableCoins before initializing.
```UpdateTip: new best=0770a4dcbd516819056934cc472689bbdd89d97f785cc659bee6ae5591b55687  height=5449 version=8  log2_work=58.3823621202891658  tx=10854  date=2020-12-21 09:41:00 progress=0.999994  cache=0.1MiB(581txo)
ProcessNewBlock : ACCEPTED Block 5449 in 7 milliseconds with size=511
CreateCoinStake: attempted staking 1 times
SolveProofOfStake : stake not found
CreateCoinStake: attempted staking 1 times
SolveProofOfStake : stake …
```

[Wallet] clear StakeableCoins before initializing

---

src/chainparams.cpp

Set final enforcement height for Mainnet's `Consensus::UPGRADE_V5_0` at block 2,700,500.

[Consensus] Set v5 enforcement height for mainnet

---

src/rpc/rawtransaction.cpp

Documenting each of the Sapling transaction elements returned by `getrawtransaction` and `decoderawtransaction` RPC commands.

[Doc] RPC getrawtransaction and decoderawtransaction, sapling tx data.

---

src/test/librust/wallet_zkeys_tests.cpp

Trying to determine the inconsistent failing, linux-only, unit test case.
The hypothesis is that the diversified address is equal to the the default address (empty diversified).
As I haven't been able to replicate it locally, this PR is printing the error if happens in GA. The error is the following:
```
Test cases order is shuffled using seed: 1449329889
2325
Entering test module "Pivx Test Suite"
2326
test/librust/wallet_zkeys_tests.cpp(23): Entering test suite "wallet_zkeys_tests"
2327
test/librust/wallet_zkeys_tests.cpp(122): Entering test case "WriteCryptedSaplingZkeyDirectToDb"
2328
test/librust/wallet_zkeys_tests.cpp(122): Leaving test case "WriteCryptedSaplingZkeyDirectToDb"; testing time: 1675295us
2329
test/librust/wallet_zkeys_tests.cpp(32): Entering test case …
```

[Test] Print error if shield diversified address is equal to the default address

---

src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h

Two minor issues addressed here:
- the expected size is 2 bytes off if there are more than 253 inputs and/or outputs (compact size), thus the "after fee" label returns an amount slightly bigger, and the transaction creation fails when copy-pasting it.
- the fDust label is not being updated properly for shield recipient. The fDust tooltip reports an invalid, hardcoded, dust threshold.

[BUG][GUI] coin-control dialog: more accurate "after fee" + fDust for shield recipient

---

src/qt/pivx/qtutils.cpp
src/qt/pivx/txrow.cpp
src/qt/pivx/txviewholder.cpp
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/rpc/budget.cpp
src/wallet/wallet.h

As the GUI is showing OP_RETURN output records as "no information", proposals fee outputs aren't being presented properly.
Proposal fee outputs only store the proposal hash in the op_return data and can't be distinguished only with the network data (proposals data is ephemeral), this PR aims to tackle it storing the proposal name inside the "comments" field of the wallet transaction.

[GUI] Support for op_return proposal output records.

---

src/qt/pivx/addresseswidget.cpp

Cold-staking contacts are only saved when sending a delegation (with label for staker address), but they cannot be added directly in the addresses widget.
Remove the check preventing this.

[GUI][Trivial] Save cold-staking address in contacts

---

src/qt/pivx/settings/settingsconsolewidget.cpp

Fix an issue with the double confirmation dialog introduced in #1928 
Currently the confirmation pop-up is shown only when the RPC command string is exactly "dumpwallet"/"dumpprivkey" (with no arguments).
Such command strings are not valid, as both RPC functions require one argument (the filename for "dumpwallet" and the PIVX address for "dumpprivkey").
So, when the user confirms the dialog, the RPC console returns an error (as the argument is missing), showing the RPC help.
When, instead, the user enters the correct RPC strings (`dumpwallet <filename>`/`dumpprivkey <pivxaddress>`), then **the warning dialog is NOT presented** and the command is executed immediately.
Fix it by doing a pre-validation for the potentially dangerous commands.
Bonus: include `exportsaplingkey` to the list. …

[BUG][GUI] Fix double conf dialog for RPC commands that expose privkeys

---

src/qt/pivx/balancebubble.cpp
src/qt/pivx/forms/balancebubble.ui
src/wallet/db.h

Fixing a small visual bug in the tooltip balance dialog (imperceptible in mainnet but still a bug). When the value surpass the 1kk range, the text gets cropped.

[GUI] Fixing tooltip balance amount cropped 

---

src/test/librust/wallet_zkeys_tests.cpp

Follow up investigation to #2116. Based on GA results, the diversified address is equal to the default address.
The code now will try to create a different address to the default one in a loop increasing the diversifier by one on each round.
This issue will need a deeper investigation in the future if/when we add diversified addresses features (at this moment, is pretty irrelevant as we aren't using diversified addresses at all). I have seen it only happening randomly on GA on linux and doesn't seems to be a library issue, if we provide the same seed to the process, the error isn't being thrown. It seems more to be an issue with the data pointer.

[Test] Attempt to fix the diversified address equal to default address test scenario

---

src/net.cpp
src/net.h

Removing the `RecvLine` unused function in net.cpp.

[Net] Remove unused RecvLine function.

---

src/net.cpp
src/net_processing.cpp
src/spork.cpp

Adapted from #11583, following the same rationale:
We have to be much more conservative when using LogPrintf/error or other things which unconditionally log to debug.log, It should not be the case that an inbound peer can fill up a users disk with debug.log entries (DoS).
This rule should be applied in many other areas of the sources as well (not only on the net area). But well, step by step.

[Backport][Net] Do not make it trivial for inbound peers to generate log entries

---

src/protocol.cpp
src/protocol.h

**Issue**
Some p2p message is being logged with the improper command name. E.g. masternode pings logged as `fbs` (finalized budgets):
```
2021-01-11 11:52:16 got inv: fbs 6a3faa173c022f03268cbcd6f877ba935a0cfd3a7d1cc14a834bc3f335b4d349  new peer=17
2021-01-11 11:52:16 askfor fbs 6a3faa173c022f03268cbcd6f877ba935a0cfd3a7d1cc14a834bc3f335b4d349  1610366775535727 (12:06:15) peer=17
2021-01-11 11:52:16 received: mnp (151 bytes) peer=21
2021-01-11 11:52:16 mnp - Masternode ping, vin: 33996bf6cb102b73baacfe5cbfa178c0e1d47013cf46dd8b2fc0a7467220c36c
2021-01-11 11:52:16 CheckAndUpdate: New Ping - 6a3faa173c022f03268cbcd6f877ba935a0cfd3a7d1cc14a834bc3f335b4d349 - 0afbb2fc22536f5abc518475113ba945a902f6742112a3aaf79bf3408f22a3c4 - 1610365936
```
**Cause**
The `ppszTypeName` array is not properly …

[P2P][BUG] Incorrect name logged for inventory messages

---

src/net.cpp

Coming straight from #10215.
As the description says there, this could be a cause of long waits at shutdown.

[Backport] Check interruptNet during dnsseed lookups

---

src/budget/budgetdb.cpp
src/init.cpp
src/masternode-payments.cpp
src/masternode.cpp
src/masternodeman.cpp
src/version.h

Which is currently causing excessive banning.
Add a "database" version at the beginning of cache files.
Also, for this reason, do not ban when receiving invalid ping block hashes before the enforcement of protocol 70921.

[BUG][Masternodes] Prevent broadcast of pre-5.0 stale masternode data

---

test/functional/feature_blockhashcache.py

`random.randint` is an alias for `randrange`, which includes the endpoint:
https://github.com/python/cpython/blob/998ae1fa3fb05a790071217cf8f6ae3a928da13f/Lib/random.py#L371-L375
In the test, we want a number strictly below 200, so we either use `randint(1, 199)` or `randrange(1, 200)`.
This fixes the GA failures like <https://github.com/PIVX-Project/PIVX/runs/1714017123>

[Tests][BUG] Fix random range in feature_blockhashcache

---

src/masternodeman.cpp
src/masternodeman.h
src/rpc/masternode.cpp

Due to the recursive call, `cs_main` may be locked after `CMasternodeMan::cs` (via `GetChainTip`).
This might cause the following deadlock:
```
2021-01-16 20:47:44 Previous lock order was:
2021-01-16 20:47:44  (1) cs masternodeman.cpp:472 (in thread bitcoin-httpworker)
2021-01-16 20:47:44  (2) cs_main validation.cpp:194 (in thread bitcoin-httpworker)
2021-01-16 20:47:44 Current lock order is:
2021-01-16 20:47:44  (2) cs_main validation.cpp:2276 (TRY) (in thread pivx-msghand)
2021-01-16 20:47:44  (1) cs masternodeman.cpp:454 (in thread pivx-msghand)
```
Note: This is a quick fix for the moment. The entire winner-selection flow will be refactored soon.

[BUG] Fix deadlock in GetNextMasternodeInQueueForPayment

---

src/wallet/rpcwallet.cpp

Fixing an issue with `getbalance`, which at the moment is not including the transparent watch-only balance.
`getbalance` includes or not the shield balance, it will never return the shield balance only as the modified if/else block was doing. To get every specific balance type separately we use `getwalletinfo`.

[RPC] fix getbalance transparent watch-only amount.

---

src/masternode.h
src/messagesigner.cpp
src/messagesigner.h
src/policy/feerate.h
src/primitives/transaction.h
src/txmempool.cpp
src/txmempool.h

Fix the `-Wdeprecated-copy` warnings listed in #2076 
**Background**
While perfectly valid in C++98, implicit generation of the copy constructor is declared as deprecated in C++11, when there is already a user-defined copy assignment operator, or vice-versa.
The rationale behind this is the "rule of three" (https://en.cppreference.com/w/cpp/language/rule_of_three)
> If a class requires a user-defined destructor, a user-defined copy constructor, or a user-defined copy assignment operator, it almost certainly requires all three.
**Issue - Fix**
We have several places that define redundant copy assignment operators (and then use the implicit copy constructor), or that do need non-default ctors/dtors but don't define copy assignment.
(See also bitcoin/bitcoin#11161, which is also …

[Refactor] Fix some -Wdeprecated-copy warnings

---

src/protocol.cpp
src/protocol.h

Fix the `-Wstringop-truncation` warning reported in #2076, cherry-picking the first commit of bitcoin/bitcoin#16995
> Replace the memset/strncpy dance in `CMessageHeader::CMessageHeader` with explicit code that copies then name and asserts the length.
>
> This removes a warning in g++ 9.1.1 and IMO makes the code more readable by not relying on strncpy padding and silent truncation behavior.

[Net] Fail instead of truncate command name in CMessageHeader

---

src/blob_uint256.h
src/qt/pivx/settings/settingsbittoolwidget.cpp
src/test/uint256_tests.cpp
src/uint256.h
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Keep going with the migration started in #1395 and #1414.
This time migrate the whole class `uint160`, so it is defined as a child of `base_blob` (essentially replace `uint160` with `blob_uint160`), thus migrating `CKeyID` and `CScriptID` as well.
Since opaque blobs (unlike the `arith_uint` classes) have trivial copy-assignment operator, this fixes the "scary" `-Wclass-memaccess` warning reported in #2076 (tested before/after patch, with gcc v9.3.0)
Bonus: this fixes also a minor bug found along the way: few places where we are checking the result of `boost::get<CKeyID>` over the pointed `CKeyID`, which shouldn't even have a `bool operator()`, and might even be un-initialized (though we always verify `IsValidDestination` before, so this is mostly redundant) instead of checking the pointer …

[Core] Migrate uint160 (CKeyID/CScriptID) to opaque blobs

---

src/cuckoocache.h
src/prevector.h
src/serialize.h
src/test/prevector_tests.cpp

Backports bitcoin/bitcoin#12324.
The `DeserializeAndCheckBlock` benchmark (introduced in #2146) shows a speedup of about 4% (not as much as the upstream PR, due to the optimizations already included in #2083).
Cherry-picks also
- bitcoin/bitcoin#8671 (with minimal changes to the random context, due to bitcoin/bitcoin#8914 and bitcoin/bitcoin#9792 being already ported out of order).
- bitcoin/bitcoin#11151

[Core] Prevector Optimizations 2

---

src/rpc/misc.cpp

Bug in `validateaddress`, is returning the address value twice for regular addresses. The first value is added before calling the visitor and the second one inside it.

[RPC] `validateaddress` remove duplicate return address value.

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/core_read.cpp
src/core_write.cpp
src/kernel.cpp
src/pivx-tx.cpp
src/qt/coincontroldialog.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/rawtransaction.cpp
src/rpc/server.cpp
src/rpc/server.h
src/test/crypto_tests.cpp
src/test/netbase_tests.cpp
src/test/transaction_tests.cpp
src/wallet/rpcwallet.cpp

Nukes the dependency on Boost's `list_of.hpp`
Also introduce UniValueType
UniValueType is a wrapper for UniValue::VType which allows setting
a typeAny flag. This flag indicates the type does not matter.

[Refactoring] Use c++11 list initialization for maps/vectors

---

test/functional/test_runner.py

Speed up GA by executing the longest tests (such as tiertwo and sapling scripts) first.

[Trivial][Tests] Fix tests order on test_runner --all

---

src/test/librust/wallet_zkeys_tests.cpp

Same issue as in #2123 but in a different place.
Apply the same fix.

[Tests] Check for diversified address equal to default one in zkeys_test

---

src/primitives/transaction.h
src/qt/pivx/coldstakingmodel.cpp
src/qt/pivx/masternodewizarddialog.cpp
src/qt/pivx/sendconfirmdialog.cpp
src/qt/transactionrecord.cpp
src/qt/walletmodel.cpp
src/sapling/sapling_operation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/test/librust/sapling_rpc_wallet_tests.cpp
src/test/librust/sapling_wallet_tests.cpp
src/test/librust/utiltest.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_shielded_balances_tests.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Instead of inheriting from `CTransaction`, now `CWalletTx` will store it as member. Another step forward over the transaction complete immutability goal.
An adaptation of c3f5673a6304e3ea9fa56fff66b6ea1cb73cc98f with further needed changes, essentially:
> it makes it actually fully immutable and never modifies any of its elements (apart from wit) after construction.
> 
> To do so, we heavily rely on C++11. CTransaction gets a (CMutableTransaction&&) constructor that efficiently converts a CMutableTransaction into a CTransaction without copying. In addition, CTransaction gets a deserializing constructors.
> 
> One downside is that CWalletTx cannot easily inherent from CTransaction anymore, as CWalletTx needs a way to modify the CTransaction data inside. By turning the superclass into a …

[Wallet] Making CWalletTx store TransactionRef.

---

src/wallet/scriptpubkeyman.cpp
test/functional/test_runner.py
test/functional/wallet_hd.py

**Problem**
If a HD wallet uses some keys, and is later restored to a previous state (initial backup), it correctly recognizes the used keys and relative transactions, and spending from the relative addresses works fine.
Although, these addresses are not shown in the receive widget of the GUI, so their label cannot be edited, and they cannot be easily selected/copied.
**Cause**
When adding a transaction in `AddToWalletIfInvolvingMe`, the wallet loops over the outputs and checks if it affects any key from the keypool (supposed to be "unused"), in which case, it removes the key from the pool (`ScriptPubKeyMan::MarkUnusedAddresses`).
After restoring the old backup, when initializing the receive widget (and address table model), with `getAddressToShow`, there is no unused address in the …

[BUG][Wallet] Restore AddressBook when marking used keys in the keypool

---

configure.ac
doc/release-notes.md
src/rpc/mining.cpp

This adds a configure flag to skip compiling the PoW-related mining RPC
commands, which aren't ever used outside of the initial PoW phase.
The `generate` command is retained for regtest compatibility.

[Build] Don't compile PoW mining RPC commands by default

---

src/init.cpp
src/miner.cpp
src/net.cpp
src/net_processing.h
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/saplingscriptpubkeyman.h
src/scheduler.cpp
src/scheduler.h
src/test/mempool_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/validationinterface.cpp
src/validationinterface.h
src/wallet/test/wallet_shielded_balances_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h
src/zmq/zmqnotificationinterface.cpp
src/zmq/zmqnotificationinterface.h
test/functional/feature_notifications.py

Revamped the validation interface interaction with the wallet, encapsulating and improving the mempool and block signaling and each of the wallet signals handler.
Restructured the Sapling witnesses and nullifiers update under the new signals.
Solved several bugs that found on the way as well (Check each commit description).
This PR concludes with #1726 long road :). Pushing our repository around 2 years ahead in btc time in the mempool and validation interface areas (without including RBF). 
The new validation -> wallet interaction architecture will enable further, and much more user facing important, improvements for the syncing process, overall software responsiveness and multithreading locking issues.
Adapted backports:
#6464 --> Always clean up manual transaction prioritization …

Revamping block validation interface interaction with wallet

---

src/init.cpp

Fix an edge case where the 'M' key is removed from the blockTree DB but the chainstate still contains the invalid entries, due to it not being flushed after the update.

[BUG] Flush the chainstate after pruning invalid entries.

---

src/test/sighash_tests.cpp

Create random txes, then add/modify/remove inputs, outputs, sapling data fields, and check the hash of the data serialized for transparent signatures.

[Tests] Add more cases to sighash_tests for malleated txes

---

src/init.cpp

In case of pivxd, if there is for example an invalid masternode private key or an invalid masternode address we are only logging the error (In case of pivx-qt, a visual error popup notification is triggered).
This PR improves the Masternode data error detection exiting early at the node startup (same as we do on every other bad data provided by the user at startup).

Better pivx.conf Masternode data error notification

---

src/qt/pivx/dashboardwidget.cpp

Guard against any not expected `transactionType` value retrieved from the setting that doesn't map to any available filter type.
Can be tested changing the value manually inside the settings file and starting the wallet again, the tx filter type combobox will be shown empty without this fix.

[GUI] Prevent invalid dashboard txs list filter value loaded from settings

---

src/netbase.cpp

cherry-picked from bitcoin/bitcoin#11397.
> Make the SOCKS code more consistent, and document the constants used.

[Net] Improve and document SOCKS code

---

test/functional/feature_fee_estimation.py

`small_txpuzzle_randfee` function (in `feature_fee_estimation` functional test) can rarely create raw transactions with dust outputs, which cause the test failure (https://github.com/PIVX-Project/PIVX/runs/1745765860).
Prevent this by checking the change value, and adding it to the fee, if it is below the threshold, same as we do in internally in `CWallet::CreateTransaction`.

[Tests] Don't create dust outputs in small_txpuzzle_randfee

---

src/logging.cpp
src/logging.h
src/spork.cpp

The "net" category is overly cluttered right now, so this introduces a
new "sporks" logging category specifically intended to catch spork
message errors.

[Logs] Add new "sporks" debug logging category

---

src/qt/walletmodel.cpp
src/qt/walletmodeltransaction.cpp

Fix random GUI segfault during send.
Since #2044 , we cannot cast `CWalletTx*` directly to `CTransaction*` (as `CMerkleTx` no longer inherits from `CTransaction`).
We must use the `CTransactionRef` stored within it.

[BUG][GUI] Fix CWalletTx* casts to CTransaction*

---

src/activemasternode.cpp
src/net.cpp
src/net.h

Focused on two changes inside the active masternode state manager function:
1) Removed a redundant MN address parsing and port validation (both are covered at startup inside `initMasternode`).
2) Modified the inbound connection availability test to not add the self-connection to the connection manager peers vector (as it makes no sense to have it, nor maintain it). This change fixes the scenario in which the node connection already exists locally and the node invalidly logs the "Could not connect to xxx". Plus, changed the logging in the area to be more understandable as well.

[Masternode] Manage status cleanup

---

CMakeLists.txt
src/Makefile.am
src/Makefile.test.include
src/blockassembler.cpp
src/blockassembler.h
src/miner.cpp
src/miner.h
src/rpc/mining.cpp
src/test/CMakeLists.txt
src/test/miner_tests.cpp
src/validation.h

Have rewritten the miner code sources, dividing the miner thread from the block assembling process, encapsulating the block creation state inside a new `BlockAssembler` class (adapting #7598).
Cleaned several mempool redundant checks inside the assembly process (adaptation of #6898):
> The mempool is explicitly assumed to be responsible for maintaining consistency of transactions with respect to not spending non-existent outputs, not double spending, script validity and coinbase maturity. Only finality of transactions is checked before assembling a block.
Another point added here is the rework of the previously non-functional `miner_tests` unit test. Which.. have essentially made it work, adding coverage for the miner process, updating it to a fairly recent point down upstream's path + …

[Miner] Rewrite miner code with proper encapsulation + test coverage

---

src/test/test_pivx.cpp
src/test/test_pivx.h

This introduces a new testing setup fixture, which pre-creates a blockchain with N (100 or 400) pow blocks.
It allows us to use the unit-test framework in a lot of cases, which we would usually test with the functional framework.

[Tests] Introduce TestChainSetup fixture, pre-creating a N-blocks chain

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h

Refactored the process message area, improving the code readability decoupling every message processing into its own function and unifying every `misbehaving` call in one single place, so we don't have `cs_main` locks spread around many functions that could require internal cs locks (which could be a deadlock cause).

[Refactor] Grouping misbehaving / cs_main lock calls into a single place

---

src/qt/pivx/send.cpp
src/qt/pivx/send.h

Fixing crash reported in #2160 .
Inside the send screen the "clear all" event removes every row and there by every entry from the widget, as the contacts menu stores a local pointer to the entry where is being open and the data being pointed does't exist anymore, it was occasioning a crash there.
The solution is simple, close the menu contacts when the clear button is pressed.

[GUI] send widget, hide contacts menu when clear event is triggered.

---

src/qt/guiutil.cpp
src/util.cpp

backport of https://github.com/bitcoin/bitcoin/pull/13734 to use the wchar API for windows startup function. This is the first in a long list of upstream PRs that aim to bring full Unicode support to Windows clients as detailed in https://github.com/bitcoin/bitcoin/issues/13869
Also included here is the relevant parts of https://github.com/bitcoin/bitcoin/pull/5793, to use per-network auto startup shortcuts.

[GUI] Use wchar_t API explicitly on Windows

---

src/rpc/blockchain.cpp
test/functional/feature_blockindexstats.py
test/functional/test_runner.py

The fee statistics returned by the rpc are broken with shield txes.
Add proper calculation for shield txes (and skip zerocoin txes, as they have fixed fee).
Functional test included.

[RPC][BUG] Fix getblockindexstats-getfeeinfo with shield txes

---

src/Makefile.test.include
src/blockassembler.cpp
src/blockassembler.h
src/test/CMakeLists.txt
src/test/txvalidationcache_tests.cpp
src/wallet/test/wallet_sapling_transactions_validations_tests.cpp

Added unit test coverage for double spend inputs and double spend notes in the mempool and in new blocks.

[Test] Double spend inputs and notes unit tests coverage

---

doc/build-windows.md

When building the client on WSL using depends, the configure option
`--disable-online-rust` should be used to prevent a linker issue with
`librustzcash`
Closes #1846

[Doc] WSL Depends builds need --disable-online-rust

---

.github/workflows/build-and-test.yml
CMakeLists.txt

Fixes the GA descriptor to work with the macOS 10.15 image that GA uses.
Note: Uses clang 11 instead of clang 12 due to a compiler error with the image's clang 12.
Also adds early error reporting for CMake if the `configure` script fails for any reason.

[GA] Enable CMake macOS Build

---

src/init.cpp

In the shutdown process, stop every thread before dump data to disk, otherwise threads will continue modifying data structures while and after the dump process is being / was executed, ending up not storing all of the data and/or corrupting the node state.

[BugFix] Shutdown, stop threadGroup before dump data to disk.

---

src/wallet/db.cpp

Coming from https://github.com/bitcoin/bitcoin/pull/11017
> This PR intends to plug some leaks. It specifically implements adherence to the requirement in BDB to close a handle which failed to open (https://docs.oracle.com/cd/E17276_01/html/api_reference/C/dbopen.html):
> 
> >   The DB->open() method returns a non-zero error value on failure and 0 on success. If DB->open() fails, the DB->close() method 
> >   must be called to discard the DB handle.

[Wallet] Close DB on error

---

.gitignore
src/sapling/address.h
src/sapling/note.cpp
src/sapling/note.h
src/sapling/sapling_transaction.h
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/wallet/wallet.cpp

Fixes three minor issues with sapling notes and txes:
- Possible uninitialized fields (with empty ctor)
- Big parameters passed by value
- Unchecked return value of ReadBlockFromDisk
Note: these were reported by Synopsys Coverity® (more to come). The `cov-int` folder is added to .gitignore, so the tool can be run directly on the cloned repository, without the risk of staging its files.

[Refactoring] Sapling classes - initialize fields and pass parameters by reference

---

src/addrman.h
src/core_read.cpp
src/httpserver.cpp
src/net.cpp
src/net_processing.cpp
src/netaddress.cpp
src/netbase.cpp
src/primitives/block.h
src/protocol.h
src/qt/coincontroldialog.cpp
src/qt/coincontroltreewidget.cpp
src/qt/pivx.cpp
src/qt/pivx/pivxgui.cpp
src/qt/winshutdownmonitor.cpp
src/script/script.h
src/torcontrol.cpp
src/txdb.h
src/wallet/wallet.h

Coming straight from #10498 with minimum adaptations.

[Backport] Use static_cast instead of C-style casts for non-fundamental types

---

src/net_processing.cpp
test/functional/test_runner.py

Another DoS vector patch coming straight from #8078.
Plus, enabled and connected the `p2p_mempool.py` functional test and reordered the `mempool_persist.py` in the list based on its time, favoring running tests in parallel.

[Backport] Disable the mempool P2P command when bloom filters disabled

---

src/masternode.cpp
src/masternode.h
src/masternodeman.cpp

Improvements to the check inputs and add process:
* Removed an unneeded disk lookup (`GetTransaction` function call).
* Removed an unneeded `cs_main` lock.
* Added a missing `chainActive` guard.
* Cleaned a redundant pcoinsTip access.

Improving masternode check inputs and add process

---

src/chain.cpp
src/test/librust/sapling_rpc_wallet_tests.cpp
src/test/librust/sapling_wallet_tests.cpp
src/validation.cpp
src/wallet/test/wallet_shielded_balances_tests.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Solving two topics here:
1) Wallet: As `CMerkleTx` isn't inheriting from `CTransaction` anymore, need to use the tx member in the ATMP function call. (Same rule was applied to all of the unit tests that required the changes).
2) Move-Only: moved the `CBlockIndex` related methods from `validation.cpp` to `chain.cpp` as should had been there in the first place.

Solve an incorrect MakeTransactionRef usage for ATMP call inside the wallet and unit tests

---

src/bloom.cpp
src/bloom.h
src/net_processing.cpp

From bitcoin/bitcoin#7113
> For each 'bit' in the filter we really maintain 2 bits, which store either:
>
>0: not set
>1-3: set in generation N
>After (nElements / 2) insertions, we switch to a new generation, and wipe entries which already had the new generation number, effectively switching from the last 1.5 * nElements set to the last 1.0 * nElements set.
>
>This is 25% more space efficient than the previous implementation, and can (at peak) store 1.5 times the requested amount of history (though only 1.0 times the requested history is guaranteed).
>
>The existing unit tests should be sufficient.
Also included bitcoin/bitcoin#13948

[Core] More efficient rolling Bloom filter

---

src/init.cpp
src/scheduler.cpp
src/scheduler.h
src/test/test_pivx.cpp
src/test/test_pivx.h
src/validation.cpp
src/validation.h
src/validationinterface.cpp
src/validationinterface.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/zmq/zmqabstractnotifier.cpp
src/zmq/zmqabstractnotifier.h
src/zmq/zmqnotificationinterface.cpp
src/zmq/zmqnotificationinterface.h
src/zmq/zmqpublishnotifier.cpp
src/zmq/zmqpublishnotifier.h

Another step forward in the wallet signals processing in the background thread + node validation <--> wallet separation long working paths.
Adapting:
* #10178
* #10179
* #10221
* #10914
* #11783
* Plus added an extra cleanup to the validation interface removing unused `NotifyTransactionLock` signal and its respective slots.

Support for validation interface signals in background thread

---

src/budget/budgetproposal.cpp
src/budget/budgetproposal.h
src/budget/budgetvote.cpp
src/budget/finalizedbudget.cpp
src/budget/finalizedbudget.h
src/budget/finalizedbudgetvote.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
src/rpc/budget.cpp
test/functional/tiertwo_governance_sync_basic.py

`BaseOutPoint` has a member variable named `hash`, but `GetHash()` does not return its value. 
It returns the hash of the serialized class (`hash` and `n`) instead. 
This is confusing and might lead to sneaky bugs (in fact, it already did in the past: https://github.com/PIVX-Project/PIVX/pull/1963#discussion_r530033452)
Further, the implementation of `GetHash()` is rather ugly, as it accesses the singleton pointer `&this->n` as an array (with `BEGIN()`/`END()`), which could result in misinterpretation or corruption of adjacent memory locations.
This function is used only in two places:
- in the RPC `getbudgetvotes` for the key `"nHash"`. This is wrong, as nHash is supposed to be the **vote** hash (as described in the help), and not the collateral outpoint hash.
- to index `mapVotes` …

[Refactoring] Remove BaseOutPoint::GetHash

---

contrib/devtools/check-doc.py
src/chain.cpp
src/chain.h
src/coins.cpp
src/coins.h
src/httpserver.cpp
src/init.cpp
src/legacy/validation_zerocoin_legacy.cpp
src/legacy/validation_zerocoin_legacy.h
src/net_processing.cpp
src/txdb.cpp
src/txdb.h
src/validation.cpp
src/validation.h
test/functional/feature_dbcrash.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py
test/functional/test_runner.py
test/functional/wallet_dump.py

> This patch adds an extra "head blocks" to the chainstate, which gives the range of blocks for writes may be incomplete. At the start of a flush, we write this record, write the dirty dbcache entries in 16 MiB batches, and at the end we remove the heads record again. If it is present at startup it means we crashed during flush, and we rollback/roll forward blocks inside of it to get a consistent tip on disk before proceeding.
> If a flush completes succesfully, the resulting database is compatible with previous versions. If the node crashes in the middle of a flush, a version of the code with this patch is needed to recovery.
An adaptation of the following PRs with further modifications to the `feature_dbcrash.py` test to be up-to-date with upstream and solve RPC related bugs.
* #10148. …

Use non-atomic flushing with block replay

---

src/logging.cpp
src/logging.h

Bug introduced in b3a1d84a86888b68aaca954cd1529e651adc24c1: `LogPrintStr` no longer returning the character count, because bitcoin/bitcoin#13148 should have been included in the backport.

[Logging] remove unused return value from LogPrintStr

---

src/activemasternode.cpp
src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/budget/budgetproposal.cpp
src/budget/budgetproposal.h
src/budget/budgetvote.h
src/budget/finalizedbudget.cpp
src/budget/finalizedbudget.h
src/budget/finalizedbudgetvote.h
src/masternode-payments.cpp
src/masternode-payments.h
src/masternode.cpp
src/masternode.h
src/messagesigner.cpp
src/messagesigner.h
src/qt/pivx/masternodewizarddialog.cpp
src/rpc/budget.cpp
src/rpc/masternode.cpp
src/spork.cpp
src/spork.h
src/test/validation_tests.cpp
src/tiertwo/specialtx_validation.cpp
src/validation.cpp
src/validation.h
src/wallet/wallet.cpp
test/functional/feature_blockindexstats.py

Some refactoring around the tiertwo code.
- use CKeyIDs instead of plain pubkeys to verify signed messages. Remove redundant code.
- Move proposal/budgets CleanAndRemove inside CBudgetManager
- define a constant for the masternode collateral amount

[Refactoring] Verify MessageSigner signatures with keyIDs

---

src/primitives/transaction.cpp
src/primitives/transaction.h
src/script/interpreter.cpp
src/script/interpreter.h
src/test/script_P2CS_tests.cpp

Fix and rework CheckColdStake, removing it from the CTransaction primitive, and implementing directly inside `TransactionSignatureChecker`.
Add unit test.

[Refactor] Implement CheckColdStake in TransactionSignatureChecker

---

src/qt/pivx/settings/forms/settingsfaqwidget.ui

Removing old freshdesk and swiftx mention from the FAQ. fixing #2217 .

[GUI] FAQ remove freshdesk and SwiftX mention.

---

src/qt/pivx/qtutils.cpp

When in dark mode there's redundant 4 pixel indentation from
each side of the qr code in Receive dialog and widget. This
reduces it to 1 pixel, this way it still works as intended,
but looks nicer.
closes #1562

Qt: Reduce whitespace around qr code fixes #1562

---

src/legacy/validation_zerocoin_legacy.cpp
src/legacy/validation_zerocoin_legacy.h
src/validation.cpp

Since v5 the network is not longer accepting zc transactions. No need to continue having the zerocoin dead code in the accept to mempool function.
This PR cleans it up, removing the unneeded zc mentions in the ATMP process.

[Validation] Remove dead zc checks from ATMP

---

src/init.cpp

Two changes:
1) Guarding `pwalletMain` access from init.cpp, so in the future we could enable pivxd to run without the wallet.
2) BugFix: `Wallet::LockCoin` verifying that the MN collateral utxo is in the wallet's map before add it to the locked set. Printing the correct error if the transaction is unknown for the wallet.

Guarding wallet access from init and print error for unknown MN collaterals

---

src/script/script.h
src/test/net_tests.cpp
src/test/scriptnum_tests.cpp
src/wallet/test/wallet_tests.cpp

Fix `scriptnum_tests` currently failing with debug enabled, due to integer overflow, backporting bitcoin/bitcoin#9512.
Last commit coming from bitcoin/bitcoin#18413.

[Tests] Fix various things -fsanitize complains about

---

src/core_write.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/rawtransaction.cpp
src/script/ismine.cpp
src/script/sign.cpp
src/script/standard.cpp
src/script/standard.h

The `TX_ZEROCOINMINT` output type is not needed, nor used anywhere. Same as the function `ScriptPubKeyToJSON` that is a plain copy of `ScriptPubKeyToUniv` without cold staking scripts support.

Removing `TX_ZEROCOINMINT` and `ScriptPubKeyToJSON`

---

src/init.cpp
src/test/test_pivx.cpp
src/validation.cpp
src/validation.h

Had this segfault when trying to shut down the wallet before the coins cache is loaded.
```
CCoinsViewCache::DynamicMemoryUsage (this=0x0) at coins.cpp:60
60	    return memusage::DynamicUsage(cacheCoins) +
(gdb) bt
#0  0x0000555555bb8b44 in CCoinsViewCache::DynamicMemoryUsage() const (this=0x0) at coins.cpp:60
#1  0x0000555555996bc1 in FlushStateToDisk(CValidationState&, FlushStateMode) (state=..., mode=mode@entry=FLUSH_STATE_ALWAYS) at validation.cpp:1730
#2  0x0000555555997540 in FlushStateToDisk() () at validation.cpp:1806
#3  0x000055555582516c in PrepareShutdown() () at init.cpp:266
#4  0x0000555555826005 in Shutdown() () at init.cpp:339
```
This is due to a bug introduced in 64c525b8d697028b02e2735c55a788e518dac6ec (we should null-check `pcoinsTip` before calling `FlushStateToDisk` …

[BUG] Fix some chainstate-init-order bugs

---

test/functional/rpc_invalidateblock.py

Straightforward back port from upstream, updated `rpc_invalidateblock.py` to a more recent version.
Adding test coverage for block ancestors and descendants reconsideration.

[test] updating rpc_invalidateblock.py to latest upstream.

---

contrib/gitian-build.py
contrib/gitian-descriptors/gitian-win-signer.yml
doc/release-process.md

Error:
```
inputs/osslsigncode-Backports-to-1.7.1.patch: OK
inputs/osslsigncode-1.7.1.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
subprocess.CalledProcessError: Command '["echo 'f9a8cdb38b9c309326764ebc937cba1523a3a751a7ab05df3ecc99d18ae466c9 inputs/osslsigncode-1.7.1.tar.gz' | sha256sum -c"]' returned non-zero exit status 1.
```
Related to #17315. Back ported #16669 and #17671 to solve it.
-- testing needed --

[build] fixing gitian build fail with checksum mismatch

---

.github/workflows/build-and-test.yml

This test takes over an hour to run and is susceptible to timeout
failures, which require re-running all jobs.
Exclude it for GA jobs.

[GA] Dont run the feature_dbcrash test in GA

---

src/wallet/wallet.cpp

Have re-organized the `CWallet::ScanForWalletTransactions` code to lock `cs_main` and `cs_wallet` only where is needed, preparing the ground to be able to almost completely remove `cs_main` lock dependency after merging #2209 (it will only be needed to advance the index to the next block, the rest of the process will run `cs_main` lock free).
Plus, corrected an unneeded forced scan of the entire chain after zerocoin activation, was happening even when the first key in the wallet could had occurred way after it. Moving through the chain without any purpose.

[wallet] Rescan chain for wallet transactions process re-written

---

src/init.cpp
src/qt/pivx.cpp
src/qt/pivx/topbar.cpp
src/qt/walletmodel.cpp
src/qt/walletmodel.h

First commit was decoupled from #2131, the topbar staking status polling should not try to refresh data if shutdown was requested.
Second commit is coming from #12377.
Third commit is starting the shutdown process and returning early (without starting the import thread) if the best chain cannot be activated during the node's initialization.

Fixing few shutdown problems

---

src/qt/pivx/settings/settingsexportcsv.cpp
src/qt/transactionfilterproxy.cpp
src/qt/transactionfilterproxy.h
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h

Added the following changes:
1) Removed the redundant `TxIDRole` from the transaction table model. It's just a duplication of `TxHashRole`.
2) Improved the transaction filter proxy to only request data from the model when is needed, not before-hand.
3) Added a validation to not invalidate the filter if the input type isn't modifying the type that the filter already has.
4) Removed unused `IsZPIVType()`, `setShowZcTxes()` and `setOnlyColdStake` functions.

[GUI] Transaction filter, minimize model data request + cleanup.

---

test/functional/test_framework/address.py

fixing `keyhash_to_p2pkh` using cold staking address mainnet version for regular testnet pubkey addresses.

[Test] address.py: fix invalid `keyhash_to_p2pkh()`

---

src/util.cpp

Coming straight from https://github.com/bitcoin/bitcoin/pull/12923. 
Fixes a bug introduced in #2212 for **some** POSIX linux systems (observed on CentOS 7 currently)
Original upstream text:
> Nowhere in the man page of pthread_setschedparam it is mentioned that 0 is a valid value. The example uses pthread_self(), so should we.

[Util] Pass pthread_self() to pthread_setschedparam instead of 0

---

src/qt/pivx/sendmultirow.cpp

This PR makes the box of the PIVX address in the send widget turn back to purple when previously filled and made empty.
Issue: #1639 
Before fix: 
After fix:

[Qt] Make box of PIVX Send address return to purple when it's empty

---

src/qt/pivx/balancebubble.cpp

Fixes double fade-in animation when clicking the question mark next to the 'Available' label in the top bar. 
Issue: #2216
Video of issue:
https://user-images.githubusercontent.com/36901185/109182893-12d9de80-7796-11eb-8ad7-cecb9d0c9286.mp4
After fix:
https://user-images.githubusercontent.com/36901185/109183124-4d437b80-7796-11eb-926d-06108a1713a1.mp4

[Qt] Fix double fade-in Topbar Available click animation. Issue 2216

---

src/qt/pivx/sendcustomfeedialog.cpp

Set custom transaction fee to highest possible value in case input is too big number.
#fixes 2234

[GUI] Set fee to highest possible if input is too big

---

src/qt/pivx/dashboardwidget.cpp

Obsolete `QComboBox::currentIndexChanged(QString)` signal in QT 5.15 replaced for `QComboBox::currentTextChanged`.

[GUI] fix QT 5.15 `currentIndexChanged(QString)` obsolete method call.

---

doc/README.md
doc/reduce-memory.md

There are a few parameters that can be dialed down to reduce the memory usage of `pivxd`. This can be useful on embedded systems or small VPSes.
Back ported + adapted `reduce-memory.md` document created in #16339.

[docs] add reduce-memory.md

---

src/guiinterface.h
src/init.cpp
src/validation.cpp

Essentially, we are re-serializing every new connected block tip, locking `cs_main` for its whole time, just to calculate the block size and broadcast a notification for external listeners if the block size is above 1mb..
Which well.. can easily be done from outside of the core, listening the new block arrival signal without having the most important node's processing thread calculating it, blocking `cs_main` for its whole time.
Plus, block arrive serialized from the network and from disk, there was no need to waste resources forcing a re-serialization for this neither.
What this fix means: 
The synchronization process will be faster. So, this can easily get into v5.1.0 release.

[validation] Removing unneeded block serialization and signal from ABC

---

src/qt/pivx/settings/settingsbittoolwidget.cpp
src/rpc/client.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/wallet_hd.py

Added the following changes:
1) The wallet scan chain for transactions process will now return null if scan was successful. Otherwise, if a complete rescan was not possible (due to corruption or abort), returns pointer to the most recent block that could not be scanned.
2) New `rescanblockchain` RPC command with two arguments `start_height` `end_height` to trigger a chain rescan at any time during runtime + test case (adaptation of #7061).
3) New `abortrescan` RPC command to stop any long running rescan if needed at runtime (this is helpful for example in case of importing a private/sapling key that if the user is not aware of the extra "scan" boolean argument, it will rescan the complete chain). Coming from #10208.

[RPC][wallet] Add `rescanblockchain` RPC command functionality

---

configure.ac

`LIBSAPLING_LIBS` is defined but never used (`LIBZCASH_LIBS` is what is
used instead). Also, `LIBZCASH_LIBS` is needlessly including
`CRYPTO_LIBS` so clean that up.

[Build] Remove un-used variable

---

src/memusage.h
src/txmempool.h
src/validation.cpp
src/validation.h

Extracted from #2267.
This backports bitcoin#9208.
As highlighted by zcash/zcash#2951, this "performance improvement" actually includes a fix for the following bug:
> Currently, AcceptToMemoryPool is called inside DisconnectTip after the block has been disconnected, but before chainActive has been updated. This means that height-dependent consensus rules are checked assuming the height is one greater than it actually is, which is a problem when disconnecting the last block before a network upgrade (e.g. during a reorg across the upgrade boundary).
This has additional consequences with special transactions (that's why it was discovered in #2267), as, during a reorg, `ProUp*` transactions, included in the block, might not be resurrected in the mempool, due to the inconsistent state of …

[Core] Store disconnected blocks txes outside mempool during reorg

---

src/qt/guiutil.h
src/qt/optionsmodel.cpp

Qt 5.15 has deprecated QString::SplitBehavior, this provides a
work-around that is still compatible with our baseline Qt version.

[GUI] fix 'split is deprecated' warnings

---

src/chain.cpp
src/chain.h
src/rpc/client.cpp
src/test/skiplist_tests.cpp
src/validation.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
test/functional/test_runner.py
test/functional/wallet_importmulti.py

Essentially backport bitcoin#7551 and bitcoin#9490, with more recent changes to adapt to the current sources.
Fix and re-enable the `wallet_importmulti.py` functional test.

[RPC] Add `importmulti` RPC command and functional test

---

src/Makefile.qt.include
src/qt/CMakeLists.txt
src/qt/pivx/settings/settingsconsolewidget.cpp
src/qt/pivx/settings/settingsconsolewidget.h
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h
src/qt/rpcexecutor.cpp
src/qt/rpcexecutor.h
src/rpc/blockchain.cpp

Backports a pretty cool feature for the GUI rpc-console from bitcoin#7783, which makes testing much faster, removing the need for copying/pasting the outputs of the commands.
> Commands can be executed with bracket syntax, example: `getwalletinfo()`.
> Commands can be nested, example: `sendtoaddress(getnewaddress(), 10)`.
> Simple queries are possible: `listunspent()[0][txid]`
> Object values are accessed with a non-quoted string, example: [txid].
>
> Fully backward compatible. `generate 101` is identical to `generate(101)`
> Result value queries indicated with `[]` require the new brackets syntax.
> Comma as argument separator is now also possible: `sendtoaddress,<address>,<amount>`
> Space as argument separator works also with the bracket syntax, example: `sendtoaddress(getnewaddress() …

[GUI] RPC-Console support nested commands and simple value queries

---

src/addrman.h
src/bench/crypto_hash.cpp
src/chain.h
src/coins.h
src/compressor.h
src/hash.h
src/primitives/block.h
src/protocol.h
src/rpc/blockchain.cpp
src/script/bitcoinconsensus.cpp
src/script/script.h
src/serialize.h
src/streams.h
src/test/addrman_tests.cpp
src/test/script_tests.cpp
src/test/serialize_tests.cpp
src/txdb.cpp
src/txdb.h
src/undo.h

Back ported some pretty concise PRs from upstream over the data serialization area.
* #9305.  --> removal of pre c++11 compatibility functions.
* #9693.  --> prevent integer overflow in `ReadVarInt`.
* #9753.  --> compile error if VARINT is called with a signed value.
* #12683. --> fixing constness violations
* #12731. --> support for `READWRITEAS` macro.

[Backport] Serialization updates

---

src/addrman.cpp
src/addrman.h
src/net.cpp

Two pretty direct back ports for the address manager.
Coming from #13115 and #15486.

[Backport] Ensure tried collisions resolve, and allow feeler connections to existing outbound netgroups

---

src/wallet/rpcwallet.cpp
test/functional/mining_pos_coldStaking.py
test/functional/mining_pos_reorg.py
test/functional/sapling_wallet_anchorfork.py
test/functional/wallet_basic.py

Added `last_processed_block` return value to the `getwalletinfo` RPC command.
This will be useful to debug wallets, help users in case of non-updated wallet balances/txs (example: the worker thread not able to process blocks) and for functional testing.

[RPC] `getwalletinfo`: Add last_processed_block return value.

---

src/rpc/mining.cpp
src/rpc/server.cpp
test/functional/wallet_disable.py

Simple change, to address the feature requested by @furszy here: https://github.com/PIVX-Project/PIVX/pull/2282#issuecomment-814992542

[RPC] Return command name with 'Method not found' errors

---

src/validation.cpp
test/functional/feature_abortnode.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py
test/functional/test_runner.py

Coming from upstream #15305 with some adaptations.
> If we're unable to disconnect a block during normal operation, then that is a
failure of our local system (such as disk failure) or the chain that we are on
(eg CVE-2018-17144), but cannot be due to failure of the (more work) chain that
we're trying to validate.
We should abort rather than stay on a less work chain.

[validation] Crash if disconnecting a block fails

---

src/blockassembler.cpp
src/blocksignature.cpp
src/blocksignature.h
src/net_processing.cpp
src/primitives/block.h
src/test/main_tests.cpp
src/validation.cpp
src/validation.h

Grouped several improvements to the block processing workflow. Cleaning redundancies, extra data requests, unneeded pieces of code and adding missing locks to critical sections.
Briefly describing the commits:
1) Remove the now unneeded, due v5 enforcement, P2PKH flag from `CheckBlockSignature`.
2) Move `CheckBlockSignature` inside `CheckBlock`.
3) Remove redundant `fAlreadyCheckedBlock` and exclusively use the `CBlock::fChecked` correct flag.
4) Add missing `cs_main` lock for `CheckBlock` function call in `ProcessNewBlock`.
5) Remove redundant, and never used, block sync request in `ProcessNewBlock` (check commit message for the precise description).
6) Add missing `cs_main` lock for block sync request in `ProcessMessage`.
This is part of a chain of PRs over the area that will continue …

[Net_Processing] Cleaner block processing workflow

---

src/qt/pivx/sendcustomfeedialog.cpp

Automatically set the lowest possible Custom Fee when user type in fee that is too low.
More details: https://github.com/PIVX-Project/PIVX/issues/1836
Demonstration:

[GUI] Automatically set the lowest possible Custom Fee when user provided fee is too low

---

src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

Making the wallet db nicer to work with, grouping all the keys in a single spot.
Also, removed `CWalletKey` that was never supported in the whole project history.

[Refactor] Wallet db keys enum + old CWalletKey removal.

---

CMakeLists.txt
src/Makefile.am
src/chainparams.cpp
src/consensus/params.h
src/consensus/tx_verify.cpp
src/consensus/tx_verify.h
src/consensus/zerocoin_verify.cpp
src/consensus/zerocoin_verify.h
src/evo/specialtx.cpp
src/evo/specialtx.h
src/qt/walletmodel.cpp
src/rpc/rawtransaction.cpp
src/sapling/sapling_validation.cpp
src/sapling/sapling_validation.h
src/serialize.h
src/test/budget_tests.cpp
src/test/sighash_tests.cpp
src/test/transaction_tests.cpp
src/test/validation_tests.cpp
src/validation.cpp
src/validation.h
src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Extracted from #2267. 
This is a collection of small refactorings around the validation code, which will make future additions easier to review.
See individual commit's description.

[Refactor] Mix refactoring in preparation for DMN lists

---

src/chain.h
src/net.cpp
src/qt/rpcconsole.cpp
src/rpc/misc.cpp
src/utiltime.cpp
src/utiltime.h
src/validation.cpp
src/validation.h
src/wallet/rpcdump.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
test/functional/test_runner.py
test/functional/wallet_import_rescan.py
test/functional/wallet_importmulti.py

Keep going down the rabbit hole...
Fix and resurrect `wallet_import_rescan` functional test.

[RPC][Test] Fix wallet_import_rescan

---

src/qt/pivx/settings/forms/settingsfaqwidget.ui
src/qt/pivx/settings/settingsfaqwidget.cpp
src/qt/pivx/settings/settingsfaqwidget.h

Each FAQ answer content is formatted as a self-contained HTML page for
styling purposes, however, having raw HTML in the `.ui` file's
`<string>` properties means that said HTML tags are also exported to
Transifex. This leads to a very ugly and confusing translation
experience that is prone to errors.
Here, we split up the content into shorter HTML-less strings: each list
item is it's own string, and each paragraph is it's own string. No HTML
tags are exported to Transifex.
The necessary HTML tags are added by way of helper functions that wrap
each string programmatically.
------ 
Avoids strings such as this one from being passed to Transifex, where spacing, line breaks, and ambiguous numbered "tags" must be carried over to the translated string precisely in order for the translated string …

[GUI] Generate FAQ answer content programmatically

---

src/pivxd.cpp
src/qt/pivx/settings/settingsbittoolwidget.cpp
src/util.cpp
src/validation.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Backports bitcoin#10412, and bitcoin#11281

[Wallet] Improve rescan API + avoid permanent locks during RescanFromTime

---

CMakeLists.txt
src/Makefile.am
src/budget/budgetproposal.cpp
src/budget/budgetproposal.h
src/budget/finalizedbudget.h
src/dbwrapper.h
src/evo/evodb.cpp
src/evo/evodb.h
src/init.cpp
src/masternode-payments.h
src/test/test_pivx.cpp
src/validation.cpp
test/functional/test_framework/test_framework.py

Extracted from #2267.
This introduces the new database, used for all DMN-related things, and updates the dbWrapper.
Builds on top of:

[DB] Introduce EVO database

---

src/init.cpp
src/test/librust/sapling_rpc_wallet_tests.cpp
src/test/librust/sapling_wallet_tests.cpp
src/test/policyestimator_tests.cpp
src/test/test_pivx.cpp
src/test/validation_block_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/validationinterface.cpp
src/validationinterface.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/zmq/zmqnotificationinterface.cpp
src/zmq/zmqnotificationinterface.h
test/functional/feature_notifications.py

PR built on top of #2209, #2235 and #2240 (don't get scared by the amount of commits, most of them are coming from 2209. Will disappear as soon as that one gets merged).
Based on the brief talk originated in https://github.com/PIVX-Project/PIVX/pull/2209#discussion_r586493886 .
Solving the conflicted transactions external listeners notification. Adapting the following PRs: bitcoin#14384, bitcoin#17477 and bitcoin#18982. Without functional test support, for the time being, for the lack of RBF functionality.

[wallet] Conflicted transactions external listeners notification fix

---

src/qt/addresstablemodel.cpp
src/qt/transactiontablemodel.cpp
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_sapling_transactions_validations_tests.cpp

This complements #2293, trying to achieve the same goal on the sapling code (remove all rogue accesses to `pwalletMain`).
Save a pointer to a wallet inside `SaplingOperation`, initialized in the constructor, and passed directly to the `TransactionBuilder` (which needs a keystore to produce signatures for the transparent inputs).

[Sapling][Refactoring] Save wallet reference inside SaplingOperation

---

src/net_processing.cpp
src/net_processing.h
src/test/DoS_tests.cpp

Upgraded the orphan transactions management process, getting us much closer to upstream. Skipped several intermediate PRs because our code is way too far ahead of them in some areas like the validation interface and block processing after #2209. Plus added a net_processing zc cleanup. 
Important changes:
* The elimination of a leak in the orphan map, which was not connected to the block connection process, always growing to its maximum size.
* Early detection and discard of zc txs received as single tx message.
* Removal of the ATMP check of zc txs received as single tx message.
* Removed the need of `cs_main` lock for accessing `mapOrphanTransactions` and `mapOrphanTransactionsByPrev`.

[net_processing] Improve/upgrade orphan transactions handling

---

src/qt/pivx/settings/settingsconsolewidget.cpp
src/qt/rpcexecutor.cpp

Generated `moc_*.cpp` files are implicitly included by the build systems
and explicitly including them causes build failures on launchpad.
master build log: https://code.launchpad.net/~pivx/+archive/ubuntu/pivx-unstable/+build/21374623/+files/buildlog_ubuntu-xenial-amd64.pivx_5.0.99~202104091521+git7a538fde9~ubuntu16.04.1_BUILDING.txt.gz
this PR build log: https://code.launchpad.net/~fuzzbawls/+archive/ubuntu/piv-test/+build/21373712/+files/buildlog_ubuntu-xenial-amd64.pivx_5.0.99~202104091140+git696b3c922~ubuntu16.04.1_BUILDING.txt.gz

[Build] Don't explicitly include generated moc file

---

doc/release-notes.md
src/chain.cpp
src/legacy/stakemodifier.cpp
src/wallet/wallet.cpp

This flag was supposed to provide detailed logging for the construction of the old modifier, but it makes the system barely usable: a full sync with this option would take weeks.
Since its related to the old peercoin modifier, which we abandoned years ago (and never use on testnet5), let's just remove this option.

[Cleanup] Remove obsolete --printstakemodifier startup option

---

src/dbwrapper.cpp

This change significantly increases IBD performance by increasing the amount of the UTXO index that can remain in memory. To ensure this doesn't cause problems in the future, a static_assert on the LevelDB version has been added, which must be updated by anyone upgrading LevelDB.
In upstream, this resulted in a substantial difference in the sync time. A 50% reduction in the reindex time.
So.. **2x speedup improvement**.
Coming straight from #12495.

Increase LevelDB max_open_files unless on 32-bit Unix.

---

src/validation.cpp

The log message for evodb_cache Memory Usage is missing a newline character, therefore the next log message is concatenated.
Combining  evodb_cache Memory Usage with previous UpdateTip log message.
Before
2021-04-18 07:36:46 UpdateTip: new best=c58f3103a1614981c5ff8fa9738ca2fba90dfcabd80e054b1b5111e5bf439e62  height=2810012 version=8  log2_work=70.0675345724608150  tx=6589582  date=2021-04-18 07:36:45 progress=1.000000  cache=0.0MiB(189txo)
2021-04-18 07:36:46 UpdateTip: evodb_cache=0.0MiBProcessNewBlock : ACCEPTED Block 2810012 in 50 milliseconds with size=686
After
2021-04-18 08:01:07 UpdateTip: new best=afc6d575259aa012ce168872e788c7df8f683a475e30494bd5eccb03b7b32e1b  height=2810042 version=8  log2_work=70.0675359284255421  tx=6589646  date=2021-04-18 08:00:45 progress=1.000000 …

[Trivial] Move evodb_cache Memory Usage logging

---

src/qt/pivx/coldstakingwidget.cpp

#2209 (specifically https://github.com/PIVX-Project/PIVX/pull/2209/commits/c2d66d024e03012e2be90c3c012c7340e0180eda) introduced a visual bug with the display of cold staking addresses. Instead of showing the address as intended, the label was being duplicated. This restores the intended behavior.
Without this patch:
With this patch:

[GUI] Fix Cold Staking address list

---

src/sapling/saplingscriptpubkeyman.cpp
src/test/librust/sapling_wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

This particular flow calls `SaplingScriptPubKeyMan::GetNotes` (instead of `GetFilteredNotes`), which calls `CWalletTx::GetDepthInMainChain` without holding `cs_wallet` (requirement introduced via `AssertLockHeld` in https://github.com/PIVX-Project/PIVX/commit/1386ab74933071600b53b6b37501239ce9acff71).
Add a simple unittest to cover `GetNotes`/`GetFilteredNotes`, do a bit of refactoring (removing some code duplication), and fix the missing lock.

[BUG] Fix crash when sending shield notes from the GUI with coin control

---

src/chain.cpp
src/test/dbwrapper_tests.cpp

Back ported the following PRs from upstream (adaptations were needed because we aren't obfuscating the db):
* #7992.
* #9867.
* #11422.
* #17206

[Test] Expand dbwrapper unit test coverage

---

src/qt/pivx/coldstakingwidget.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/test/librust/sapling_wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Backport the following bug fixes PRs to the 5.1 branch:
#2321 
#2327
After having this one and #2333 merged, we are good to go with the final v5.1.0 production release.

[Backport] 5.1.0 bug fixes backports

---

src/validation.cpp

Fixing a possible blocks db corruption cause.
> Previously, the undo weren't being flushed during a reindex because
fKnown was set to true in FindBlockPos. That is the correct behaviour
for block files as they aren't being touched, but undo files are
touched.
> This changes the behavior to always flush when switching to a new file
(even for block files, though that isn't really necessary).
Coming from #6948.

Always flush block and undo when switching to new file

---

doc/release-notes.md
src/chainparamsbase.cpp
src/chainparamsbase.h
src/httprpc.cpp
src/init.cpp
src/pivx-cli.cpp
src/pivx-tx.cpp
src/pivxd.cpp
src/qt/guiutil.cpp
src/qt/pivx.cpp
src/rpc/protocol.cpp
src/test/util_tests.cpp
src/util.cpp
src/util.h
test/functional/feature_config_args.py
test/functional/rpc_users.py
test/functional/test_framework/test_node.py
test/functional/test_framework/util.py
test/functional/test_runner.py

It is now possible for a single configuration file to set different options for different networks. This is done by using sections or by prefixing the option with the network, such as:
```
main.uacomment=pivx
test.uacomment=pivx-testnet
regtest.uacomment=regtest
[main]
mempoolsize=300
[test]
mempoolsize=100
[regtest]
mempoolsize=20
```
The `addnode=`, `connect=`, `port=`, `bind=`, `rpcport=`, `rpcbind=`, and `wallet=` options will only apply to mainnet when specified in the configuration file, unless a network is specified.
Also 
- fix cookie-based authentication for the functional tests, and re-enable `feature_config_args.py` 
- add `-rpcauth` startup flag, for multiple RPC users, and re-enable `rpc_users.py`.
Backports relevant commits from:
- bitcoin/bitcoin#8856 Globals: Decouple …

[Core] Network specific configuration sections

---

test/functional/sapling_wallet.py

Fixing a race condition inside the `sapling_wallet.py` functional test.
As the wallet now is processing blocks in a worker thread and not in the main one, if the scheduler thread tasks processing isn't fast enough to process the new block, there can be a race condition between the `reconsiderblock` and the wallet `getshieldedbalance` check that comes right after it inside the test.
Solved it adding the validation interface queue sync call.
This issue happened in master's GA --> https://github.com/PIVX-Project/PIVX/runs/2426500390 .

[BugFix] Fixing sapling_wallet.py getshieldbalance race condition.

---

CMakeLists.txt

Linux systems installing the Rust toolchain via rustup place the
binaries in `~/.cargo/bin`, which CMake doesn't always check by default.
This addresses the issue by adding that path to the HINTS directive.
-----------------
This issue presents itself most notably in windows WSL environments where the underlaying WSL system
has installed a rust toolchain via rustup, and should have zero effect on depends/CI/gitian based builds.

[CMake] Add hints path for user-installed cargo bindir

---

doc/release-notes/release-notes-5.1.0.md

Trivial maintenance PR. Save old release-notes file in `/doc/release-notes/` folder as usual.
No need to cleanup `/doc/release-notes.md` this time, as the file was edited in the 5.1 branch only.

[Doc] Save historical release notes for v5.1.0

---

depends/builders/darwin.mk

Fixes errors like `fatal error: 'unistd.h' file not found` when building depends on macOS.
Coming from #17118.

[build] depends macOS: point --sysroot to SDK

---

depends/packages/miniupnpc.mk
depends/patches/miniupnpc/dont_leak_info.patch
doc/dependencies.md

Coming from https://github.com/bitcoin/bitcoin/pull/20421
Creating the dll subdir is no-longer required.
We can also drop our wingen patch.

[Depends] Bump miniupnpc to 2.2.2

---

src/qt/pivx/forms/receivewidget.ui
src/qt/pivx/receivewidget.cpp
src/qt/pivx/receivewidget.h

This is an updated version of #2250 :
- remove un-needed width increment in receivewidget.ui
- squashed the commits down to one
- push under @PicklesRcool's authorship

[GUI] Add search option to My Addresses list in receive widget (PicklesRcool)

---

src/stakeinput.cpp
src/stakeinput.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/zpiv/zpos.h

Since v5 activation, #1700 is active and there is no need to continue checking for the v5 NU enforcement during the coinstake generation in the mining process. This PR removes the extra validations and script conversion inside the wallet.

[wallet] Remove now unneeded stake P2PKH->P2PK output forced conversion

---

doc/release-notes.md
src/dbwrapper.cpp
src/init.cpp
src/qt/intro.cpp
src/qt/pivx.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
src/test/validation_block_tests.cpp
src/txdb.cpp
src/util.cpp
src/util.h
src/validation.cpp
src/validation.h
src/wallet/db.cpp
test/functional/feature_blocksdir.py
test/functional/test_runner.py

Grouped two different, zero risk, modifications here to not have to create two/three small and straightforward PRs:
* Fixing basic unit test setup issue, was not initializing the libsecp256k1 context. Thus why we have been forced to use the extended unit testing setup for almost every test case (which includes CConnman, scheduler, validation interface, etc.. that are not needed so often).
* Refactor: `BasicTestingSetup` receiving the network in the constructor.
> Since the actual block files taking up more and more space, it may be desirable to have them stored in a different location then the data directory (use case: SSD for chainstate, etc., HD for blocks).
This PR adds a -blocksdir option that allows one to keep the blockfiles external from the data directory (instead of creating …

[Test][Misc] Fix libsecp256k1 init for unit test setup + Allow to specify blocks storage directory

---

src/chainparams.cpp
src/chainparams.h
src/init.cpp
src/validation.cpp
src/validation.h
test/functional/p2p_invalid_block.py
test/functional/p2p_invalid_tx.py
test/functional/test_framework/blocktools.py
test/functional/test_framework/messages.py
test/functional/test_framework/mininode.py
test/functional/test_runner.py

Introduced the `P2PDataStore` class into the functional test suite and updated it up to a point where was able to enable the `p2p_invalid_block.py` and `p2p_invalid_tx.py` functional tests. Plus updated both tests to a much recent version, expanding its testing coverage as well.
Now the test suite is covering the primary CVE that btc had in the past.
As both tests were simply unusable before and we have a different synchronization process than upstream, plus we didn't have some params and init/global flags, this work isn't following a PR by PR back port path. Had to made my own way up to the complete tests support.
Main pilar PRs from upstream from where this work was based:
* #6329.
* #11771.
* #14119 (only `p2p_invalid_tx.py`, `p2p_invalid_block.py` and `mininode.py` changes).
* #14247 …

[QA] Test suite update + P2P invalid blocks and invalid tx functional tests coverage.

---

src/blockassembler.cpp
src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/chainparams.cpp
src/consensus/params.h
src/evo/deterministicmns.cpp
src/kernel.cpp
src/masternode-payments.cpp
src/masternode-payments.h
src/masternodeman.cpp
src/masternodeman.h
src/primitives/block.h
src/primitives/transaction.h
src/rpc/masternode.cpp
src/spork.cpp
src/spork.h
src/stakeinput.cpp
src/stakeinput.h
src/test/budget_tests.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/zpiv/zpos.h

Extracted from #2267.
This PR introduces an important consensus change. As per title, mn/budget payments are now outputs of the coinbase transaction, rather than the coinstake (which, now, contains only outputs belonging to the staker).
The block version is bumped to 10.
Also refactor the budget-payment functions, in preparation for the compatibility code and the new payment logic.

[Consensus][Refactoring] Blocks v10: TierTwo payments in the coinbase transaction

---

test/functional/p2p_invalid_block.py

Fixing the master's failing `p2p_invalid_block.py` functional test. It's due a recently merged error code name modification: `bad-cb-amount` -> `bad-blk-amount`.
PD: Will work on the area in the upcoming days, planning to do some structural changes and add coverage for the new coinbase amount errors at least.

[BugFix] Fix failing p2p_invalid_block.py.

---

src/legacy/validation_zerocoin_legacy.cpp
src/txdb.cpp
src/txdb.h
src/validation.cpp

We should have never databased the "public coins" in the first place, and it's beyond useless now.
With this simple removal we get a 20~25% speedup during they sync of the interested blocks [`863787` -> `1880000`], and, as bonus, we save 60MB of disk space.

[Cleanup] Remove zerocoin mints databasing

---

src/test/validation_tests.cpp
src/validation.cpp

Safe-belt for the post-v5 zerocoin cleanup that is being done. Unit test ensuring that we are rejecting zc txs in the mempool and inside new blocks.

[Test] Coverage for zc transactions rejection in mempool and blocks.

---

src/test/validation_block_tests.cpp

Bug discovered checking GA failing reason in #2314 --> [job](https://github.com/PIVX-Project/PIVX/pull/2314/checks?check_run_id=2509761057)
Essentially, `BOOST_ASSERT_MSG` only prints static string messages. As we are inputting a dynamic message, the value isn't being printed if the test fails.
So, have added a new function `ASSERT_WITH_MSG(cond, msg)`  to support dynamic error messages.

[test] validation_block_tests: Correcting BOOST_ASSERT_MSG usage for dynamic messages.

---

contrib/devtools/symbol-check.py

This export was introduced in #2278 which added
```
//! Necessary on some platforms
extern char** environ;
```
Which is one of the causes of the current broken gitian build.
Coming from f6e42256fe8900ed90f9644906b77f97e1600952

[build] Allow export of environ symbols

---

CMakeLists.txt
src/Makefile.am
src/activemasternode.cpp
src/chainparams.cpp
src/consensus/params.h
src/evo/deterministicmns.cpp
src/evo/providertx.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/qt/pivx/masternodewizarddialog.cpp
src/rpc/masternode.cpp
src/rpc/rawtransaction.cpp
src/rpc/register.h
src/rpc/rpcevo.cpp
src/test/evo_deterministicmns_tests.cpp
src/wallet/wallet.cpp
test/functional/test_framework/test_framework.py
test/functional/tiertwo_masternode_activation.py
test/functional/tiertwo_masternode_ping.py

Extracted from #2267. Based on top of
Implement `protx_register` and `protx_list` RPC commands. 
Add DMN support to `listmasternodes`.
Deprecate `startmasternode` after SPORK_21 activation.

[RPC] Provider-Register transactions

---

test/functional/mining_pos_coldStaking.py
test/functional/mining_pos_reorg.py

instead of `generate_pos()`, which could result in `Couldn't create new blocks` errors, if no stake is found in the current time slot (it can be seen in [this GA job](https://github.com/PIVX-Project/PIVX/runs/2512558131) failure).
Also fix another bug in `mining_pos_reorg`: last tx (spending `stakeinput`) is not mined, due to missing `sync_mempools`.

[BUG][Tests] mining_pos_* tests calling `generate()` or `generate_pow()`

---

src/randomenv.cpp

Follow-up to #2278 now that #2300 has been merged. This pulls in one of the aforementioned commits (https://github.com/bitcoin/bitcoin/commit/64e1e022cedf6776c5dffd488ca2e766adca5dc3) that was purposely left out of #2278

[Rand] Use thread-safe atomic in perfmon seeder

---

.github/workflows/build-and-test.yml

Github Actions recently released new image versions for Ubuntu 16.04 and
18.04 that introduced a missing package dependency issue.
This is a workaround that simply re-adds the dependent PPA repository
back to the apt sources.
Ref: https://github.com/actions/virtual-environments/issues/3317

[GA] Workaround missing apt dependency

---

doc/release-notes.md
src/rpc/client.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/walletdb.cpp
test/functional/test_runner.py
test/functional/wallet_autocombine.py

The current `autocombine` command is limited to whole numbers only, and infringes on our RPC standards by not providing deterministic output even when successfully changing the setting.
This PR addresses the deterministic issue as well as makes the setting information available to `getwalletinfo`

[RPC] refactor autocombine into specific commands

---

src/script/interpreter.cpp
src/script/script.cpp
src/script/script.h
src/test/script_P2CS_tests.cpp
src/validation.cpp

This PR is the result of a responsible disclosure for a vulnerability, related to the cold-staking code, made by Flowzzz (of https://keyboardwarrior.be/), on March 15th. After the initial discussion and analysis, along with @furszy  and Flowzzz, a critical exploit has been identified and unit-tested.
For this report and collaboration, PIVX has granted the biggest bounty reward of its history (https://twitter.com/_PIVX/status/1372032360636502019).
This PR contains the PoC unit-test, used to reproduce the exploit, and the successive fix. 
The validation for P2CS scriptPubKey is incomplete and doesn't check all the opcodes.
This opens up a possible exploit. A script could be crafted so that:
* it is identified as P2CS (passing `IsPayToColdStaking`), and recognized by the wallet as …

[Script] Fix "split P2CS" vulnerability

---

configure.ac
contrib/cmake/FindMiniupnp.cmake
doc/release-notes.md
src/net.cpp

Backport of https://github.com/bitcoin/bitcoin/pull/15993
This results in a rejection of older versions of miniupnpc for both autotools and CMake build systems. API Version 10 was used to maintain compatibility with Ubuntu Xenial (which uses a patched version of miniupnpc but still reports API version 10) and Debian 8 (which is not fully patched).
Miniupnp support as a whole remains disabled by default

[Net] Drop support of the insecure miniUPnPc versions

---

Makefile.am
depends/Makefile
depends/hosts/default.mk
depends/packages/boost.mk
depends/packages/native_b2.mk
depends/packages/packages.mk
doc/dependencies.md

Backports the following upstream PRs to clean up and update the Boost dependency
- https://github.com/bitcoin/bitcoin/pull/17087
- https://github.com/bitcoin/bitcoin/pull/17231
- https://github.com/bitcoin/bitcoin/pull/17928
- https://github.com/bitcoin/bitcoin/pull/18820
- https://github.com/bitcoin/bitcoin/pull/19764

[Depends] Bump boost to 1.71.0 and optimize flow

---

src/init.cpp
src/qt/pivx/pivxgui.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

Simple refactoring. First two commits are coming from bitcoin#8768.
Other commits break up a big chunk of code from init.cpp into more manageable functions in wallet/walletdb.
This will make the implementation of auto-backups for multi-wallets cleaner (will now rebase #2337 on top of this one).

[Refactoring] Move automatic-wallet-backup code out of init.cpp

---

src/validation.cpp

Found this bug fix investigating master's GA test failure reason. Not related to it but still a bug-fix.
> When an invalid block is found during a reorg, we know the last of the blocks in
the was-to-be-connected chain is invalid, but not necessarily the first. As
vpIndexToConnect is ordered in decreasing height, the end of the reorg is the
front of the vector, and not the back.
This has no direct impact, only affects the warning logging system.
Coming from #13185.

[Bugfix] the end of a reorged chain is invalid when connect fails

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/spork.cpp
src/spork.h
src/test/budget_tests.cpp

Extracted from:
and based on top of it.
Forcing the update of the spork message and finalized budget, we can test the actual `IsBlockValueValid` function.
This also refactors the spork code to update the maps in a single place, as suggested by @furszy here https://github.com/PIVX-Project/PIVX/pull/2274#discussion_r623126302.

[Tests][Refactoring] Remove mocked budget manager in budget_tests

---

doc/release-notes.md
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/sapling/sapling_operation.h
src/script/interpreter.cpp
src/script/interpreter.h
src/script/script.cpp
src/script/script.h
src/script/standard.cpp
src/script/standard.h
src/test/script_P2CS_tests.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
test/functional/mining_pos_coldStaking.py

Extracted from #2267, and rebased on top of #2258.
Given the consensus change, introduced in #2274, we can define a more secure `OP_CHECKCOLDSTAKEVERIFY` opcode, which doesn't leave the last output of the coinstake "free" (as we no longer pay masternode/budgets in the coinstake tx).

[Consensus] New cold-staking opcode

---

src/qt/guiutil.cpp

From bitcoin#11156
> on macOS:
> listSnapshot was leaking in findStartupItemInList()
> bitcoinAppUrl was leaking in [Get|Set]StartOnSystemStartup()

[Backport] Fix memory leaks in qt/guiutil.cpp

---

src/miner.cpp
src/miner.h
src/rpc/client.cpp
src/rpc/mining.cpp

Introducing a new RPC command `generatetoaddress`. Useful mostly for functional testing and a good number of updates that are coming from upstream.

[RPC] Implement generatetoaddress RPC command

---

src/qt/walletmodel.cpp

The problem arises when the model triggers the balance update task and the chain tip changes (due a reorg) before one of the threadpool's threads starts executing the job. As the tip, in this situation, has the same height that the one cached inside the model, the `processBalanceChangeInternal` returns true even when the balance update wasn't executed, which never sets the processing flag to false again, blocking every future balance update.
Solves #2371.

[BugFix] fix "not updating GUI balance" race condition.

---

depends/packages/qt.mk

Straightforward, updating archived qt 5.9 url. #21932

[depends] update Qt 5.9 source url

---

src/qt/pivx/pivxgui.cpp

> To ensure the GUI closes when the "Minimize on close" window option is disabled, and the "Minimize to the tray instead of the taskbar" window option is enabled, remove a check made against the "Minimize to the tray instead of the taskbar" value, made during GUI closure.
To ensure the GUI minimizes to the taskbar when the "Minimize on close" window option is enabled, and the "Minimize to the tray instead of the taskbar" window option is disabled, minimize the GUI and ignore the closure event.
Small adaptation of 05242e937d3fc0144029ccf3b14f98662400dd60
refs https://github.com/PIVX-Project/PIVX/issues/2371#issuecomment-835833535

[BugFix][GUI] Fix minimize and close bugs

---

test/functional/mining_pos_fakestake.py

Same issue as in #2367, another test (should be the last one).
Test failure can be seen on GA [here](https://github.com/PIVX-Project/PIVX/runs/2568150653).

[BUG][QA] Use generate_pos() after POW phase end in mining_pos_fakestake

---

src/Makefile.am

Ensure that coverage files are properly cleaned from the `budget` and `evo` paths during `make clean` or `make distclean`

[Build] Clean coverage files from budget and evo paths

---

doc/release-notes.md
src/rpc/client.cpp
src/rpc/server.cpp
src/rpc/server.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/wallet_basic.py

Adaptation of #8952
This PR adds a new optional JSON options for `listunspent` RPC call:
* Return unspents greater or equal than a specific amount in PIV: minimumAmount.
* Return unspents lower or equal than a specific amount in PIV: maximumAmount.
* Return unspents with a total number lower or equal than a specific number: maximumCount.
* Return unspents which total is greater or equal than a specific amount in PIV: minimumSumAmount.
```
> pivx-cli help listunspent
...
5. query options    (json, optional) JSON with query options
{
"minimumAmount"    (numeric or string, default=0) Minimum value of each UTXO in PIV
"maximumAmount"    (numeric or string, default=unlimited) Maximum value of each UTXO in PIV
"maximumCount"     (numeric or string, default=0=unlimited) Maximum number of UTXOs …
```

[RPC] Add query options to listunspent rpc call.

---

test/functional/feature_fee_estimation.py

Otherwise, since this test takes more than 250 blocks, some of the  last `generate()` call might raise an exception if the stake isn't found in the first time slot.
Test failure can be seen in this [GA job failure](https://github.com/PIVX-Project/PIVX/runs/2602362137).

[BUG][QA] Don't switch to POS in feature_fee_estimation

---

src/wallet/rpcwallet.cpp

Fixing
```
wallet/rpcwallet.cpp:3964:17: warning: ‘fEnable’ may be used
uninitialized in this function [-Wmaybe-uninitialized]
if (fEnable && request.params.size() > 1) {
```
Also, update help text, specifying that the second argument is required when `enable` is `True`.

[Trivial][RPC] Remove compiler warning in autocombinerewards and update help text

---

src/budget/budgetmanager.cpp

Moved `TRY_LOCK` to `LOCK` to perform the budget maps check every 14 blocks without exception. If peers doesn't perform the validation and update proposals, votes and budget finalization maps at a similar network time, there could be a peer sending votes that aren't longer valid and end up being banned.
This is just an initial small mitigation, have seen peers banning other peers for this race condition. This area needs a further rework later on.
Budget data is being validated on every new arriving block while the masternodes status is being checked and updated every 5 seconds (which is way too fast and not needed but that is another topic). The budget data update should be done right after the masternode removal/invalidation, so the peer updates the budget maps and does not send the …

[budget] partially fixing a race condition that could cause a good peer to be banned

---

src/net_processing.cpp
src/validation.cpp
test/functional/feature_block.py

Fix a couple bugs discovered with `feature_block`.
Nodes not being disconnected after sending a block rejected during `ConnectBlock`, as the block source is not updated yet, and nodes not being disconnected after sending a block with invalid PoW (this only affects regtest chain).

[P2P][Bug] Fix expected disconnections after not-connectable block

---

src/init.cpp
src/wallet/db.cpp
src/wallet/wallet.cpp
test/functional/feature_uacomment.py

This adds translation where it was previously missing for some `UIError`
and `UIWarning` calls. in the case that the string is a pointer, the
base string has had translation added.
Also parameterized some translation strings to filter out string
literals that we DON'T want to be translated (eg '`-wallet`',
'`-paytxfee`', etc)

[GUI] Ensure that all UI error/warning texts pass through translation

---

src/blockassembler.cpp
src/blockassembler.h
src/masternode-payments.cpp
src/spork.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/test_pivx.cpp

Estracted from #2267
This implements the new payment logic for deterministic masternodes, to be used after the deactivation of the legacy system with SPORK_21.

[Consensus] New masternode payment logic

---

src/chainparamsbase.cpp
src/chainparamsbase.h

Coming from https://github.com/bitcoin/bitcoin/pull/12128
> There's no need for class hierarchy with CBaseChainParams, it is just a struct with 2 fields.
> This starts as a +10-43 diff
Since we already require c++14, can use `std::make_unique` directly.
Note: I did not change the regtest RPC port here, but maybe this is the perfect opportunity to do so if we want it to not conflict with testnet's RPC port

[Refactor] One CBaseChainParams should be enough

---

src/test/script_P2SH_tests.cpp
src/test/transaction_tests.cpp
src/validation.cpp
src/validation.h

Straightforward. Coming from bitcoin#10953
> This simplifies CScriptCheck by combining scriptPubKey and amount

[Refactor] Combine scriptPubKey and amount as CTxOut in CScriptCheck

---

src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/evo/providertx.cpp
src/evo/providertx.h
src/init.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
src/tiertwo_networksync.cpp
src/validation.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/test_framework/messages.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/util.py
test/functional/test_runner.py
test/functional/tiertwo_deterministicmns.py
test/functional/tiertwo_reorg_mempool.py

Another one coming from #2267
This PR introduces a "auto-locking" feature for masternode collaterals:
- at startup, the wallet is scanned, and any masternode collateral coin found gets locked. Can be disabled setting `-mnconflock=0` (although, there is no need for a `masternode.conf` anymore, so we might want to consider defining and using a new flag here, and removing `mnconflock` after 6.0).
- during runtime, when a ProRegTx is processed by `CWallet::AddToWalletIfInvolvingMe`, the wallet checks for ownership of the collateral, and automatically locks it in case.
Here, we also add two more functional tests (`tiertwo_deterministicmns.py`, `tiertwo_reorg_mempool.py`), update the other tests, checking the auto-locking feature, and fix a couple bugs:
- Missing special tx processing in …

[TierTwo] Masternode collateral auto-locking + more tests

---

src/qt/walletmodel.cpp
src/rpc/masternode.cpp
src/sapling/sapling_operation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Negative PR ☕, applying the same functionality cleaner. Removing the old and redundant `AvailableCoinsType` enum.

[wallet] Kill AvailableCoinsType enum

---

src/qt/pivx/dashboardwidget.cpp
src/qt/pivx/qtutils.cpp
src/qt/pivx/qtutils.h
src/qt/pivx/res/css/style_dark.css
src/qt/pivx/res/css/style_light.css

Essentially, every combo box in the application has set the selection-color property to transparent, so the text "disappear" (turns invisible) when the mouse highlight it.
Fixes #1172.

[GUI] BugFix, disappearing text in comboboxes.

---

src/base58.cpp
src/base58.h
src/chainparams.cpp
src/chainparams.h
src/compressor.cpp
src/hash.cpp
src/key.cpp
src/net.cpp
src/net.h
src/net_processing.cpp
src/netaddress.cpp
src/netaddress.h
src/netbase.cpp
src/rpc/net.cpp
src/serialize.h
src/streams.h
src/test/net_tests.cpp
src/test/netbase_tests.cpp
src/torcontrol.cpp
src/utilstrencodings.cpp

Grouped some net updates (plus a miscellaneous one) coming from upstream.
Part of another deep rabbit hole that i'm doing in parallel of the tier two work.
PRs List:
* #7079.
* #9804.
* #10424
* #10446.
* #10564.
* #14728.

Net code updates [Step 2]

---

src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h

Straightforward, cleaning up the unused `hasZcTxes` flag and several compiler warnings from the transaction model class.

[GUI] transaction model, cleanup unused hasZcTxes flag

---

.github/workflows/build-and-test.yml
configure.ac

Pretty straight forward; this adds a GA macOS build job that runs on macOS 10.15 natively using syslibs.
The unit and functional tests are currently disabled due to an unresolved GA environment issue

[GA] Add native macOS build job

---

src/evo/deterministicmns.cpp
src/evo/providertx.cpp
src/evo/providertx.h
src/evo/specialtx.cpp
src/primitives/transaction.h
src/rpc/rawtransaction.cpp
src/rpc/rpcevo.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/evo_specialtx_tests.cpp
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
test/functional/tiertwo_deterministicmns.py
test/functional/tiertwo_reorg_mempool.py

Exctracted from #2267
This PR:
- introduces the `PROUPSERV` payload and transaction type.
This special transaction is submitted by the operator (the payload must be signed with the operator key) to update the IP/port fields.
If the original ProReg transaction set a non-zero operatorReward, this payload can also be used to update the operator's payout address.
- adds the new RPC `protx_update_service` to create ProUpServ transactions
- adds unit and functional testing
Builds on top of:

[Validation][RPC] Provider-Update-Service special tx type

---

src/chainparams.cpp
src/consensus/params.h
src/consensus/upgrades.cpp
src/script/interpreter.cpp
src/script/script.cpp
src/script/script.h
src/test/script_P2CS_tests.cpp
src/validation.cpp

As per title:
- first commit introduces `UPGRADE_V5_2` params (with `NO_ACTIVATION_HEIGHT` for now).
- second commit sets the `g_IsV6Active` flag (used to guard the new P2CS rules) based on 5.2 enforcement, and renames it to `g_newP2CSRules`.

[Consensus] Introduce 5.2 nuparams and use them to guard new P2CS rules

---

src/validation.cpp
src/version.h
test/functional/test_framework/messages.py

Bump active protocol to `70922` for v5.2.0 release.
Note: the comments inside `ActiveProtocol()` weren't updated, but we used SPORK_15 to enforce a bump of two versions: 70920 (v5.0.0 - #1994) and 70921 (v5.0.1 - #2137)

[Consensus] Bump active protocol version to 70922

---

src/validation.cpp
src/version.h
test/functional/test_framework/messages.py

Backport #2431 to `5.2` branch

[Backport] Bump active protocol version to 70922

---

src/chainparams.cpp
src/consensus/params.h
src/consensus/upgrades.cpp
src/script/interpreter.cpp
src/script/interpreter.h
src/script/script.cpp
src/script/script.h
src/test/script_P2CS_tests.cpp
src/validation.cpp

[Backport] 5.2.0 cs backports

---

contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml

Based on top of #2429 so that GA tests pass properly, this sets the gitian descriptor version to `5.2` to match the branch version.

[Build] Bump gitian descriptor version to 5.2

---

src/blockassembler.cpp
src/primitives/block.h
test/functional/test_framework/messages.py

Backports 84261bcc6c4b58db4e36ef6ef1838d2743e19f3a (#2434)

[Backport] Bump default block version to 10 (no enforcement)

---

src/validation.cpp
test/functional/test_framework/test_framework.py
test/functional/test_runner.py
test/functional/tiertwo_governance_reorg.py

First commit backports the functional test of #2436.
Second commit extracts from f6aa6add3df43f660e9b92d32cbef1afab49b2a9 (#2345) the fix to make it pass.

[Backport] Add tiertwo_governance_reorg functional test

---

test/functional/test_runner.py
test/functional/tiertwo_governance_reorg.py

Functional test to check chain reorganization during superblock.

[QA] Add tiertwo_governance_reorg functional test

---

src/Makefile.test.include
src/miner.cpp
src/net_processing.cpp
src/rpc/mining.cpp
src/test/CMakeLists.txt
src/test/budget_tests.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/miner_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
src/test/util/blocksutil.cpp
src/test/util/blocksutil.h
src/test/validation_block_tests.cpp
src/test/validation_tests.cpp
src/validation.cpp
src/validation.h

Adding important missing test coverage for invalid block budget payee script.

[Test] Add test coverage for invalid block budget payee script

---

src/chainparams.cpp

Establishing the v5.2 enforcement height for mainnet and testnet.

[Consensus] v5.2 upgrade enforcement height.

---

src/chainparams.cpp

Backports #2441 to the `5.2` branch

[Backport] v5.2 upgrade enforcement height.

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/rpc/budget.cpp
test/functional/test_runner.py
test/functional/tiertwo_governance_invalid_budget.py

Backports 96a4fad, 18a5bc5 and 21f6d0e into v5.2.

[Backport] Align budget payee validity to highest voted budget check.

---

src/blockassembler.cpp
src/budget/budgetmanager.cpp
src/masternode-payments.cpp
src/masternode-payments.h
src/primitives/block.h
src/validation.cpp
test/functional/test_framework/messages.py
test/functional/tiertwo_mn_compatibility.py

New rules shouldn't be enforced with a new block version (e.g. IsCoinbaseValueValid), because there might be blocks with that version *before* the relative network enforcement.
And in this case we don't need to, as the check is already contextual.
First commit removes the dependency on block version 10, and restores the default version to 9.
Second commit simply bumps back the default version to 10. This commit is meant to be backported to 5.2 in order to signal the new release.

[Refactor] Decouple enforcement of cbase payment from block version

---

src/activemasternode.cpp
src/activemasternode.h

If the node already has the MN stored and the activation process is triggered (via the startup flag or the RPC command), the node's `activeMasternode` will get stalled waiting until (1) the MN list gets cleaned/refreshed and someone else in the network sends the MN again or (2) until someone else enable the MN (which is not possible as this node is being enabled solely to send the ping to enable the MN..)
This is the reason why someone in the past added the `activeMasternode::EnableHotColdMasterNode` call inside the mnb message receive (which now is redundant), to force the activation as the MN enablement process was totally stalled.

Fix MN activation when the node received the mnb before initialize the MN.

---

src/wallet/wallet.cpp

Do not try to access to `fStakeDelegationVoided` in `CWallet:: CreateTransaction` if it's not provided (nullptr).
The wallet crash can be triggered from every `CreateTransaction` call that does not provide the `fStakeDelegationVoided` pointer (The auto-combine dust flow, RPC functions like `sendtoaddress`, `legacy_sendmany`, `CreateBudgetFeeTX`, etc etc). Of course the wallet need to have delegated coins (be the owner of the P2CS outputs) and the wallet's utxo selection algorithm needs to select them for spending.
Will back port this fix to v5.2 as well.

[wallet] fix segfault for P2CS inputs in CreateTransaction

---

src/activemasternode.cpp
src/activemasternode.h

Backports #2402 to the 5.2 branch for a subsequent minor version v5.2.1 / v5.2.0.1 release.

[Backport] Fix MN activation when the node received the mnb before initialize the MN

---

doc/release-notes.md
src/consensus/zerocoin_verify.cpp
src/init.cpp
src/qt/optionsmodel.cpp
src/rpc/blockchain.cpp
src/txdb.h
src/validation.cpp
src/validation.h
src/wallet/wallet.cpp
test/functional/feature_reindex.py
test/functional/test_runner.py

This was attempted already in #1864 and #1907.
Third time's a charm.
Now the speed is acceptable and (unlike what was happening in #1907) the process can be interrupted.
Further, as it is performed in ThreadImport, the GUI is open and functional during the chainstate reindex, instead of being seemingly stuck at the splash screen.
This PR also includes a few improvements coming from bitcoin#10919, bitcoin#8273, bitcoin#8136 and bitcoin#8611.
Here's a quick comparison of the data I had testing here (empty wallet with GUI, empty pivx.conf / default values).
The reindexes have been performed with 0 network connections.
<table>
<tr>
<th>Mainnet (height=2847011)</th><th>Master</th><th>this PR</th>
</tr><tr>
<td>online sync</td><td>8 hr 13 min</td><td>6 hr 42 min</td>
</tr><tr>
<td>-reindex …

[Core] Add reindex-chainstate startup option

---

src/net.cpp
src/net.h
src/net_processing.cpp
test/functional/example_test.py
test/functional/feature_block.py
test/functional/feature_cltv.py
test/functional/feature_nulldummy.py
test/functional/mining_pos_coldStaking.py
test/functional/p2p_feefilter.py
test/functional/p2p_fingerprint.py
test/functional/p2p_invalid_block.py
test/functional/p2p_invalid_messages.py
test/functional/p2p_invalid_tx.py
test/functional/p2p_leak.py
test/functional/p2p_mempool.py
test/functional/p2p_timeouts.py
test/functional/p2p_unrequested_blocks.py
test/functional/test_framework/messages.py
test/functional/test_framework/mininode.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py
test/functional/test_runner.py

Part of the deep and long net and ser work that I'm doing (and Tor v3 onion addresses support). Friend of #2359.
Focused on the end goal of implementing the `p2p_invalid_messages` functional test which validates that invalid msg headers, msg types, oversized payloads and inventory msgs aren't accepted nor can cause a resource exhaustion. And an extra covered scenario, in `p2p_invalid_tx.py`, for the orphan pool overflow.
Plus, to get up to the goal, had to work over the functional test framework as well.
So.. adapted list:
* #9045.
* #13512.
* #13517.
* #13715.
* #13747.
* #14456.
* #14522.
* #14672.
* #14693.
* #14812.
* #15246.
* #15330.
* #15697.
* #16445.
* #17931.
* #17469.
* #18628 (only `p2p_invalid_tx.py` and `p2p_invalid_messages.py`. We don't support the other tests yet).
* …

[Test] Add p2p invalid messages functional test (and test framework update)

---

src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/pivx/forms/masternodewizarddialog.ui
src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/masternodewizarddialog.cpp
src/qt/pivx/masternodewizarddialog.h
src/qt/pivx/pivxgui.cpp
src/qt/pivx/settings/settingsfaqwidget.cpp
src/qt/pivx/settings/settingsfaqwidget.h
src/wallet/wallet.cpp

Since #2296, we have a different masternode collateral output amount for regtest. As the GUI has the 10k value harcoded in some places, the masternode creation wizard got broken and there are some misaligned strings as well.
This PR fixes it and aligns every static 10k PIV string to be set dynamically consuming the chain params value.

[GUI] Fix invalid MN collateral amount and align every static 10k PIV strings.

---

src/init.cpp
src/net.cpp
src/net.h
src/net_processing.cpp
src/net_processing.h
src/test/DoS_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h

Another decouple from #2411. Coming from #10756.
> See individual commits.
> Benefits:
> * Allows us to begin moving stuff out of CNode and into CNodeState.
> * Drops boost dependency and overhead
> * Drops global signal registration
> * Friendlier backtraces

[net processing] Swap out signals for an interface class

---

test/functional/wallet_encryption.py

The wallet is being unlocked for 2 seconds, need to wait at least 3 seconds to be sure that it gets locked again. Then test the automatic lock status.
Failed in master's GA:
https://github.com/PIVX-Project/PIVX/runs/2883390877

[Test] Fix wallet_encryption.py race condition.

---

params/install-params.sh

Coming from #2457, cherry-picked from https://github.com/binance-chain/PIVX/commit/08281d4db421319baea23ee502db9032380ffeb2 , authored by @w20089527.
Thanks for the contribution 👌.
fixes #2457

Fix install-params.sh "popd: directory stack empty".

---

contrib/macdeploy/README.md
depends/builders/darwin.mk
depends/hosts/darwin.mk
depends/packages/bdb.mk

Fixing macOS depends builds, solving #2456 issue.
Back porting:
* #18743.
* #20195.
* #21793.

[Build] fix macOS depends deployment

---

doc/build-osx.md

Also add the execution of install-params.sh prior to running
`make check`

[Doc] Remove OpenSSL instructions in build-osx.md

---

src/wallet/init.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

Was checking #2362 and wasn't able to contain myself from cleaning redundancies and code deduplication on the wallet auto-backup "feature".

[Wallet] Clean wallet auto-backup "feature"

---

.github/workflows/build-and-test.yml

The random seed value, used in boost for shuffling the unit tests order, is interpreted as an unsigned int inside the boost test framework and the current value is overflowing the type range, thus why GA is failing in every PR and commit.
Solution: use the framework functionality to select a random seed based on the current time (can check it inside boost documentation [link](https://www.boost.org/doc/libs/1_76_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/random.html)).

[Build] fix GA boost test random seed number overflow

---

src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/evo/providertx.cpp
src/evo/providertx.h
src/evo/specialtx.cpp
src/primitives/transaction.h
src/random.h
src/rpc/rawtransaction.cpp
src/rpc/rpcevo.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/evo_specialtx_tests.cpp
src/test/test_pivx.h
src/txmempool.cpp
test/functional/test_framework/messages.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/util.py
test/functional/test_runner.py
test/functional/tiertwo_deterministicmns.py
test/functional/tiertwo_reorg_mempool.py

This concludes the first DMN-milestone list https://github.com/PIVX-Project/PIVX/pull/2267#issuecomment-807546678.
Here we introduce the last two payloads and transaction types, adding relative RPC commands, and updating the tests:
- `PROUPREG` (provider-update-registrar) submitted by the owner (the payload must be signed with the owner key) to update the operator key and/or the voting key and/or the payout address.
- `PROUPREV` (provider-update-revoke) submitted by the operator, to revoke the service, and put the mn in PoSe-banned state (e.g. in case of compromised keys). The masternode can be "revived" later, by sending a ProUpReg tx, which sets a new operator key, and then a ProUpServ tx (signed with the new operator key), which sets the new IP address for the …

[Validation][RPC] ProUpReg and ProUpRev special tx types

---

src/net.cpp
src/net.h
src/net_processing.cpp
src/net_processing.h
src/test/DoS_tests.cpp
src/test/net_tests.cpp
test/functional/mining_pos_coldStaking.py
test/functional/mining_pos_fakestake.py
test/functional/mining_pos_reorg.py
test/functional/test_framework/test_framework.py
test/functional/tiertwo_mn_compatibility.py
test/functional/wallet_listtransactions.py

Another decouple from Tor's v3 addresses support (#2411).
First two commits are introducing and connecting a helper poisson method so the trickle logic works with mocked time as well (from #17243).
The third and fourth commit solves missing `cs_processing` locks in the DoS tests and compiler checks.
The fifth commit solves mempool sync issues in the functional tests that utilize a mocked time.

[Net] Mockable PoissonNextSend helper and tests mempool sync fixes

---

doc/release-notes.md

This is the current state of my DMN branch.
Deterministic masternodes fully working on regtest (except for proof of service, which will come later), with a good number of tests covering registration, update, revocation, revival, collaterals auto-locking, consistency after reorgs, compatibility with the old system, payments, and governance voting. :coffee: 
There are several differences with Dash code, mostly in the RPC, mempool, block assembler, compatibility code, wallet, deployment logic, and unit/functional testing (which led to the discovery of a few bugs, including a non-trivial one, reported upstream).
But, overall, this remains respectful of the specification given here (at least for now... we'll have to modify the spec a bit when introducing shield rewards later):
- …

[Doc] Introducing Deterministic Masternodes

---

src/Makefile.qt.include
src/qt/pivx.qrc
src/qt/pivx/forms/sendmultirow.ui
src/qt/pivx/res/css/style_dark.css
src/qt/pivx/res/css/style_light.css
src/qt/pivx/res/img/ic-check-box-light.svg
src/qt/pivx/send.cpp
src/qt/pivx/send.h
src/qt/pivx/sendconfirmdialog.cpp
src/qt/pivx/sendmultirow.cpp
src/qt/pivx/sendmultirow.h
src/qt/pivx/tooltipmenu.cpp
src/qt/pivx/tooltipmenu.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/qt/walletmodeltransaction.cpp
src/qt/walletmodeltransaction.h

Follow up to #2341.
As per title, add controls for this feature in the graphical interface.
For the moment, it's a simple checkbox, which is visible in case of single recipient.
The confirmation dialog shows the difference in the "total amount" (paid) when the fee is subtracted, or not, from the recipient amount (in the example, sending `1.00 PIV`).
<div>
</div>
---
When there are multiple recipients, the checkbox is hidden, and controlled by a checkable button inside the contextual menu.
<div>
</div>
Maybe this is not very intuitive, or pretty, but it does the job.
Later on, possibly with the help of @Neoperol, we can design a better placement for these controls.
Closes #894
Closes #2196 
Obviously based on top of
which must be reviewed before this one.

[GUI] Add GUI controls for subtract-fee-from-amount

---

src/primitives/transaction.cpp
src/primitives/transaction.h

Adapts bitcoin#8330.
`sizeof(CTransaction)` and `sizeof(CMutableTransaction)` show a reduction of 8 bytes.

Reorder C{,Mutable}Transaction for better packing

---

src/Makefile.bench.include
src/bench/checkblock.cpp
src/bench/data.cpp
src/bench/data.h

Small decoupled from #2411.
Fixing issues with the raw generated files in the benchmarking framework.
1) Specify correct raw data name.
2) Backports #16299.
3) Make clean now removes the file/s.

[Build] bench build, raw generated file improvement and fixes.

---

doc/developer-notes.md
src/attributes.h
src/messagesigner.cpp
src/qt/pivx/settings/settingssignmessagewidgets.cpp
src/span.h
src/uint256.h
src/utilstrencodings.cpp
src/utilstrencodings.h
src/wallet/rpcwallet.cpp

Another decouple from #2411.
Purely focused on updating the Span sources to be up-to-date with current upstream.
Following PRs/commits were back ported:
* #13697 (only 29943a904a11607787d28b1f4288f500bd076dde)
* 2b0fcff7f26d59fed4bcafd1602325122a206c67 (only span changes).
* #18591 (only 0fbde488b24f62b4bbbde216647941dcac65c81a).
* #18468 (without 2676aeadfa0e43dcaaccc4720623cdfe0beed528).
* #19367.
* #19387.
* #19326 (only 56782504 and e63dcc3a here). 
* #19687 (only e2aa1a585a83971639572cd2c84565ec360deac9 here, 2bc20719 is inside #2411 and require net related commits that are introduced down the commits line there).
Extra side note:
Some of the current serialization compiler warnings in master will be fixed with this, other ones are coming down 2411 commits line as they need other …

 Span sources updates, up-to-date with current upstream.

---

test/lint/git-subtree-check.sh

Pulled latest `git-subtree-check.sh` changes from upstream. So it's easier to verify the new subtree that is being included in #2419.

[Backport] git-subtree-check.sh updated to latest upstream

---

src/blockassembler.cpp
src/blockassembler.h
src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/rpc/budget.cpp
src/rpc/client.cpp
src/test/budget_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
test/functional/test_runner.py
test/functional/tiertwo_governance_invalid_budget.py

Built on top of #2427..
Expanded unit test coverage for the blockchain reorg during superblock range (parallel work of #2436), budget proposal payments distribution in different order and the creation of an invalid budget finalization.

[Test] Extended test coverage for chain reorg during superblock and payments order.

---

src/base58.cpp
src/base58.h
src/bip38.cpp

Which is only used by bip38 code, and it's calling `bool DecodeBase58(const char*, std::vector<unsigned char>&, int)` ignoring its return value.
Replace with proper implementation, `bool Base58ToHex(const std::string&, std::string&)`, and make it static in bip38.cpp.

[Refactor] remove std::string DecodeBase58(const char*, int)

---

src/test/budget_tests.cpp

broken due to merges of #2438 + #2464

[Tests] Fix ProcessNewBlock signature in budget_tests.cpp

---

src/qt/pivx.cpp

The GUI tutorial screen (where the user selects the language and gets the first few "beginner tips") is supposed to be fired when the wallet.dat file is not found, before creating it for the first time.
In case of multiple wallets (using the `wallet` option in the config file, or as startup flag), the tutorial screen should not be fired if *at least* one wallet.dat already exists.
The check to decide whether or not to prompt the tutorial screen was broken in #2423.
The `-wallet` arguments can now represent paths to existing directories or symlinks (by default it is empty, representing the path relative to the datadir, i.e. the datadir itself).
It does not include the *filename* anymore (unless explicitly provided to `-wallet`).
Therefore the tutorial screen is never created on the first …

[BUG][GUI] Fix broken tutorial screen

---

doc/release-notes.md

Trivial. Codeblock in release notes file is not closed, messing up the rest of the markdown.

[Trivial][Doc] Add missing codeblock triple backtick in relnotes file

---

test/functional/feature_blockhashcache.py

Simple fix to prevent test failures such as in [this GA job](https://github.com/PIVX-Project/PIVX/pull/2480/checks?check_run_id=3162468067).

[BUG][Tests] Delay POS activation in feature_blockhashcache test

---

src/qt/pivx.cpp
src/util/system.cpp

As the intro dialog check is executed before calling the 'WalletParameterInteraction()' function in the GUI, the '-wallet' arg soft set is not being performed, skipping the for-loop wallet path check. Always launching the tutorial dialog even when there is an already existent wallet.

[BugFix] fix app always triggering the tutorial dialog if no manual '-wallet' arg is provided.

---

src/qt/coincontroldialog.cpp
src/qt/walletmodel.h

**Problem**
Some coins in coin-control are marked as cold-utxos when they aren't.
Or vice-versa some delegated coin is not marked as it should.
More specifically, If a coin is sent to an address A, and another coin is delegated using A as owner, both coins will be listed under the same address (in treemode), and they will either be both marked as cold-utxos, or both marked as regular utxos (depending on which coin was added first to the map).
**Cause**
Bug in `ListCoinsKey::operator<`, which is not comparing the staker address.
Thus, in `CoinControlDialog::updateView`, coins sent to A (`{A, false, nullopt}`) and coins delegated with owner A and staker B (`{A, false, B}`) have the same key in `mapCoins`, therefore are added to the same list.
**Fix**
Complete `ListCoinsKey::operator<` so …

[BUG][GUI] Fix P2CS grouping in coin control

---

src/Makefile.test.include
src/fs.cpp
src/fs.h
src/init.cpp
src/logging.h
src/masternodeconfig.cpp
src/netbase.cpp
src/pivx-cli.cpp
src/pivxd.cpp
src/qt/guiutil.cpp
src/qt/pivx.cpp
src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/masternodewizarddialog.cpp
src/rpc/protocol.cpp
src/test/CMakeLists.txt
src/test/fs_tests.cpp
src/test/util_tests.cpp
src/util/system.cpp
src/util/system.h
src/wallet/db.cpp
src/wallet/rpcdump.cpp
test/functional/feature_filelock.py
test/functional/feature_uacomment.py
test/functional/test_runner.py

As the software is currently using the ANSI encoding on Windows, the user's language settings could affect the proper functioning of the node/wallet, to the point of not be able to open some non-ASCII name files and directories.
This solves the Windows encoding issues, completing the entire #13869 work path (and some other required backports). Enabling for example users that use non-english characters in directories and file names to be accepted.
Backported PRs:
* #12422.
* #12630.
* #13862.
* #13866.
* #13877.
* #13878.
* #13883.
* #13884.
* #13886.
* #13888.
* #14192.
* #13734.
* #14426.
This is built on top of other two PRs that i have open #2423 and #2369.
Solves old issues #940 and #2163.
TODO:
* Backport `assert_start_raises_init_error` and `ErrorMatch` in TestNode` …

Solve filename and command line encoding issues on Windows

---

src/fs.cpp

Straight forward backport of https://github.com/bitcoin/bitcoin/pull/15782 and https://github.com/bitcoin/bitcoin/pull/18700 to address a bug in WSL1 environments that results in improper locking behavior; ie, a directory lock is not made exclusive as intended, thus resulting in multiple instances of the wallet/daemon being able to access the same datadir simultaneously instead of erroring out due to a locking conflict as intended.
This is specific to WSL1 environments, as WSL2 (not yet fully supported/documented), standard linux, and macOS environments behave as intended.

[Bug] Fix improper locking on Windows WSL1 environments

---

src/Makefile.test.include
src/chainparams.cpp
src/consensus/params.h
src/consensus/upgrades.cpp
src/masternode-payments.cpp
src/masternode-payments.h
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/test/CMakeLists.txt
src/test/budget_tests.cpp
src/validation.cpp
src/wallet/test/pos_test_fixture.cpp
src/wallet/test/pos_test_fixture.h
src/wallet/test/pos_validations_tests.cpp

Grouped the consensus changes for the coming v5.3 upgrade.
There is no enforcement height defined to not set it until everything is ready but.. we aren't far from be able to enforce it on testnet and start testing the release deeply, only have to merge #2411 and can be done.

[Consensus] v5.3 network upgrade.

---

contrib/devtools/update-translations.py
contrib/gitian-build.py
contrib/linearize/linearize-data.py
contrib/linearize/linearize-hashes.py
share/qt/extract_strings_qt.py
test/functional/combine_logs.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/util.py
test/functional/test_runner.py
test/functional/tiertwo_masternode_ping.py
test/functional/wallet_multiwallet.py
test/lint/check-doc.py
test/lint/lint-python-utf8-encoding.sh
test/lint/lint-whitespace.sh
test/lint/logprint-scanner.py

Unspecified encoding can lead to inconsistent behavior or results across platforms when dealing with ascii files.
This resolves such issues and adds a CI lint script to also ensure no regressions occur in the future.
---------
Note: the 3rd commit is included to explicitly exclude the unused and outdated linearize scripts from the whitespace linter, as both of them use tabs instead of spaces, and have not been updated to use python3. Alternatively, we can remove the linearize scripts entirely (as they are currently not used) now, and update/re-add them later if or when their use is needed.

[Scripts] Ensure UTF8 encoding for ASCII file operations in python scripts

---

doc/release-notes.md
src/addrman.cpp
src/addrman.h
src/net.cpp
src/net.h
src/net_processing.cpp
src/netaddress.cpp
src/netaddress.h
src/rpc/client.cpp
src/rpc/net.cpp
src/test/addrman_tests.cpp
test/functional/rpc_net.py

Implement a new RPC command (`getnodeaddresses`) that provides RPC access to the node's addrman. It may be useful for PIVX wallets to broadcast their transactions over tor for improved privacy without using the centralized DNS seeds.
I've included upstream improvements to this feature here as well, and this RPC command was used to scrape the Tor v3 hardcoded seed nodes added in #2502
---------
Based on the following upstream PRs:
* https://github.com/bitcoin/bitcoin/pull/13152
* https://github.com/bitcoin/bitcoin/pull/19658
* https://github.com/bitcoin/bitcoin/pull/21594
* https://github.com/bitcoin/bitcoin/pull/21843

[RPC][Net] Add getnodeaddresses RPC command

---

src/qt/pivx/settings/settingsfaqwidget.cpp

Fixing a typo, the command line interface is "pivx-cli" not "pivx-core".

GUI: bugfix, the command line interface is called "pivx-cli" not "pivx-core".

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/init.cpp
src/masternode-payments.cpp
src/masternode-payments.h
src/rpc/masternode.cpp
src/validation.cpp
test/functional/tiertwo_governance_sync_basic.py

Fix a couple RPC bugs related to masternode calls:
- rank for not-ENABLED masternodes in `listmasternods` should be `-1`
- `getmasternodewinners` not returning all payees (in case of multiple winners).
Also move the update of the cached height for the tiertwo managers to `ConnectTip` (and the block processing to the background thread).

[BUG][RPC] Fix listmasternodes and getmasternodewinners

---

src/spork.cpp
src/sporkid.h

As per title, spork5 is already unused, we can remove its definition.

[Cleanup][Trivial] Remove unused SPORK_5

---

src/masternode.cpp
src/net.cpp
src/net.h
src/net_processing.cpp
src/protocol.h
src/version.h

After the version handshake the protocol version must be >= `MIN_PEER_PROTO_VERSION_BEFORE_ENFORCEMENT` (or `MIN_PEER_PROTO_VERSION_AFTER_ENFORCEMENT`, depending on the sporks value).
Therefore we can drop all constants below `70922`.
Most of them are already unused. For the others we can just remove the checks `if (pnode->nVersion > x)`.

[Cleanup] Drop unneeded protocol version checks and constants

---

src/core_write.cpp
src/evo/providertx.cpp
src/net_processing.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/masternode.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/protocol.cpp
src/rpc/rawtransaction.cpp
src/sapling/sapling_core_write.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/test/coins_tests.cpp
src/test/sighash_tests.cpp
src/test/util_tests.cpp
src/uint256.cpp
src/utilstrencodings.cpp
src/utilstrencodings.h
src/wallet/db.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/crypto_tests.cpp

Follow up to #2470. Only the last two commits are from this work.
Make `HexStr` take a span of bytes, instead of an awkward pair of templated iterators. Simplifying most of the uses.
Adaptation of #19660 and #15573.

[Refactor] Make HexStr take a span

---

src/masternode.cpp
src/masternodeman.cpp

After v5.3 NU enforcement reject mnb/mnp messages with `MESS_VER_STRMESS` nMessVersion, and clean up the maps.

[TierTwo] Enforce MessageVersion::MESS_VER_HASH (mnb/mnp) with 5.3

---

src/masternode-payments.h
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/net_processing.cpp
src/protocol.cpp
src/protocol.h
src/version.h

Essentially the mnb node address is not being serialized/unserialized properly after the enforcement for the new BIP155 format (can be easily be seen adding a return value to `listmasternodes`. It will return an invalid addr for onion v3 established MNs).
The new ser/unser to the new format is not done automatically, was missing the `ADDRV2_FORMAT` version flag to the data stream.
So, after this PR, testnet nodes that are running the master branch will need to be refreshed.

[BugFix] Correct mnb ser/unser of BIP155 node addresses.

---

src/qt/rpcexecutor.cpp

#2372 broke the support for empty arguments `""` (which is required as first argument of `sendmany`).
Backport the fix from bitcoin#9329
Thanks to @NoobieDev12 for reporting this bug.

[GUI][BUG] Console: allow empty arguments

---

src/masternode.cpp
src/qt/pivx/masternodeswidget.cpp

Tiny bugfix that appeared walking through the wallet..
None of the mnb creation error strings contain a jump line because the returned string is used as command line output and in the GUI snackbar. None of them are expecting it, in the GUI, the snackbar notification text is being cut.

[GUI] Remove extra jump line in mnb creation error message

---

src/masternode-payments.cpp
src/masternodeman.cpp
src/masternodeman.h
src/net_processing.cpp

Dug over the recurrent "mnw - invalid signature" error during the initial MNs list synchronization, made a large performance improvements to the `GetMNList` process and solved a bug in the inventory vector size calculation.
1) Most of the "mnw - invalid signature" errors,  during the initial tier two synchronization, are due a not synced MNs list, not because the signature is invalid (the two statement are logging the same error string).
As the tier two initial sync use to not relay the complete MNs list at once (it slowly syncs up while the node receives different messages such as `mnwinner` and `mnvote`), we have to request the missing MN without increasing the misbehaving score as this can/will ban a good peers invalidly.  Single MN requests to a certain peer are guarded to be done …

[TierTwo][BugFix] Fix peer banning for not synced tiertwo + GetMNList and inv performance improvements.

---

src/blockassembler.cpp
src/chainparams.cpp
src/primitives/block.h
test/functional/test_framework/messages.py

Set the v5.3 network upgrade enforcement height for mainnet and bump the block version number to "notify" nodes about the update.
```
v5.3 enforcement at block `3,014,000` --> around 9/10 Sept.
```
Some dates that have in mind, we can pack the release candidate this weekend Aug 21/22th, and moving forward, pack the final release at Aug 27/28th, leaving a ~14 days window till the HF enforcement. Then celebrate and enjoy the network improvements with a good beer/coke.

[Consensus] Establish v5.3 NU enforcement height for mainnet

---

src/rpc/rpcevo.cpp

These commands cannot be used before v6.0 NU.
Their name (and category) is likely going to change (see issue #2385) before v6.0 release.
So, it is better to just disable them for now (for release 5.3).
I kept the registration on RegTest, so we can keep running the functional tests.

[RPC] Do not register DMN-related RPC commands

---

src/chainparams.cpp

Added a new DNS seeder, it's already crawling the network and exposing a list of reliable nodes to be used as entry point.
Check it calling to `nslookup pivx-seed.furszy.net`.
As every other sipa's based seeder, it's only supporting v1 addresses. A good future goal will be to add v2 addresses support as well.

[Network] Add mainnet DNS seeder from furszy.

---

src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/masternodeswidget.h

Fix impossibility to start Masternodes using the GUI.
This was introduced by beb1cf61 (curiously enough, no one noticed it up until now..), the `walletModel` is provided to the widget in `loadWalletModel`, so it can't be used in the `MasternodesWidget` constructor to construct the `mnmodel` object.

[GUI][BugFix] Masternodes screen, fix impossibility to start Masternodes

---

src/qt/walletmodel.cpp
src/sapling/sapling_operation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/test/librust/wallet_zkeys_tests.cpp
src/wallet/db.cpp
src/wallet/db.h
src/wallet/init.cpp
src/wallet/rpcwallet.cpp
src/wallet/scriptpubkeyman.cpp
src/wallet/scriptpubkeyman.h
src/wallet/test/pos_test_fixture.cpp
src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
src/wallet/test/wallet_shielded_balances_tests.cpp
src/wallet/test/wallet_test_fixture.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h
test/functional/wallet_multiwallet.py
test/lint/commit-script-check.sh

Scripted diff to rename "some" wallet classes.
Backports #11851
Pushing it now because this is one of those annoying text-only rename backports that touch many files that we should try to avoid during the development/review period and only merge right after the release gets packed (aka now).

[scripted-diff] Rename wallet database classes

---

.gitignore
share/genbuild.sh
src/clientversion.cpp
src/clientversion.h
src/init.cpp
src/obj/.gitignore
src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/forms/rpcconsole.ui
src/qt/rpcconsole.cpp
src/wallet/rpcdump.cpp

>Putting the build date in the executable is a practice that has no place in these days, now that deterministic building is increasingly common.
Back porting:
* #7732.
* #8181.

[Build] Get rid of CLIENT_DATE

---

src/qt/pivx/mnmodel.cpp

Follow up to the discussion in #2529.
If walletModel is null, then `MNModel::data` returns true at `WAS_COLLATERAL_ACCEPTED`.
Fix the bug removing the duplicated check (`getWalletTxDepth > MasternodeCollateralMinConf()` is already checked every 30 seconds in `MNModel::updateMNList`).

[GUI][BUG] remove duplicated coll. confirmation check in MNModel::data

---

src/wallet/rpcwallet.cpp

Missing first argument (bolean, required, "enable").

[RPC][Doc] Fix RPC/cli example in setautocombinethreshold help

---

contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml

This file gets overwritten during the autotools build process, but we don't actually want to track changes to it in our repo.
Currently, gitian builds will see that this file has changes, and thus mark the build as "dirty". This PR tells gitian builds to ignore any changes to the file via `update-index --assume-unchanged` so that release versions are no longer marked as "dirty".

[Gitian][Bug] Ignore changes to relic_conf.h.in

---

build-aux/snap/local/patches/X003-fix-use-snap-instead-of-dirty.patch

#2525 introduced changes to the genbuild.sh script, which gets patched
during the nightly snap builds. This follows up #2525 to create a new,
compatible patch.

[Snap] Fix nightly build's genbuild.sh patch

---

.github/workflows/build-and-test.yml
src/support/allocators/secure.h
src/support/lockedpool.cpp
src/support/lockedpool.h
src/test/allocator_tests.cpp

Follow up to #2276. Completing the locked memory manager todo list.
Back porting:
* #9063.
* #9070.
* #12048.
* #15117.
* #16161.

 Locked memory manager updates

---

src/masternode-payments.cpp
src/masternode.cpp
src/masternodeman.cpp
src/net_processing.cpp
src/test/budget_tests.cpp
src/validation.cpp

Enforcement passed. We can do some cleanup.

[Validation] Remove temporary guard for 5.3 rules pre-enforcement

---

src/logging.h

This commit combines together bitcoin#14209 [MarcoFalke] and bitcoin#17218 [jkczyz]
- The first one replaces `LogPrintf` and `LogPrint` macros with functions:
> It is not possible to run the full test suite when configured with --enable-lcov, since logging is disabled currently so that "unnecessary branches are not analyzed". (See c8914b9)
>
> Fix this instead by replacing the macros with functions.
- The second one restores the `LogPrint` macro:
> Calling LogPrint with a category that is not enabled results in evaluating the remaining function arguments, which may be arbitrarily complex (and possibly expensive) expressions. Defining LogPrint as a macro prevents this unnecessary expression evaluation.
>
> This is a partial revert of 14209. The decision to revert is discussed in 16688, …

[Util] Replace LogPrintf (but not LogPrint) macro with regular function

---

src/test/util_tests.cpp
src/utilstrencodings.cpp
src/utilstrencodings.h
test/functional/rpc_budget.py

We validate (user side) the URL of budget proposals before their submission via RPC, and [#soon](https://github.com/PIVX-Project/PIVX/pull/2406) via the GUI.
As noted by @NoobieDev12  in [this comment](https://github.com/PIVX-Project/PIVX/pull/2406#issuecomment-892702119), this URL validation is too limited. Essentially we are only checking that the string begins with the protocol.
This PR changes the implementation of the function `validateURL()` , using C++11 `std::regex` (which was the original intention of #950, but discarded to avoid bumping the minimum supported ABI at the time).
I've used the following pattern to match `^(https?)://[^\s/$.?#][^\s]*[^\s/.]\.[^\s/.][^\s]*[^\s.]$`, which is far from a complete validation, but it should cover the basic cases.
We can refine it in the …

[Util] Better URL validation

---

src/masternode-payments.cpp
src/test/budget_tests.cpp

This was removed in #2549 but we need to restore it, as there are blocks in the past violating this rule.

[Validation] Restore pre-v5.3 guard for under-minting blocks rule

---

src/spork.cpp
src/spork.h

The spork signer accesses `CSporkManager::UpdateSpork` from the rpc, saving the new value only to memory, while keeping the old one in the DB.

[BUG] Spork signer doesn't persist new spork value to DB

---

src/qt/pivx/forms/send.ui

Replaces #2238, which is abandoned. 
Closes #1637.

[Trivial] Update labelSubtitleAddress text in send widget ui

---

src/masternode-sync.cpp

the current asset should be checked, not the "next" one.
Introduced in 8b10fc22c292604bdbb8cc8e7a757eed4120d431

[BUG][TierTwo] Clear fulfilled requests when mnsync fails

---

src/qt/transactiontablemodel.cpp

Should put the final nail in this coffin, allowing us to finally close #1480.
This bug is caused by the fact that, if at startup the wallet has more than 4000 (`SINGLE_THREAD_MAX_TXES_SIZE`) transaction records, then chachedWallet is loaded not properly ordered, therfore the binary search (used later in `updateWallet`, to check whether a tx is already in the model) is unreliable.
When the wallet has more than 4000 records, in fact, the list of records in `TransactionTablePriv::refreshWallet()` is split in batches, each one processed in a separate thread, processing the last batch in the main thread at the beginning, thus without preserving the original order (by hash) of `walletTxes`. Further, if the wallet has more than 200k records (`MAX_AMOUNT_LOADED_RECORDS`), then the list is also …

[BUG][GUI] Fix random double/triple transaction record issue

---

src/masternode-sync.cpp

This bug accompanied with #2559 (and a sync threshold timeout), causes that the local node marks every new connected peer's tier two request message as fulfilled without sending the sync request to it.
e.g: do not mark the sync request as fulfilled before fail for a timeout. Only do it when the node is sure that the message will be broadcasted.

[Bug][TierTwo] Mark peer sync request msg fulfilled only if the broadcast was performed

---

src/qt/addresstablemodel.cpp
src/qt/addresstablemodel.h
src/qt/pivx/addresseswidget.cpp
src/qt/pivx/addresseswidget.h
src/qt/pivx/addressfilterproxymodel.cpp
src/qt/pivx/addressfilterproxymodel.h
src/qt/pivx/addresslabelrow.cpp
src/qt/pivx/addresslabelrow.h
src/qt/pivx/myaddressrow.cpp
src/qt/pivx/myaddressrow.h
src/qt/pivx/receivedialog.cpp
src/qt/pivx/receivedialog.h
src/qt/pivx/receivewidget.cpp
src/qt/pivx/receivewidget.h
src/qt/pivx/requestdialog.cpp
src/qt/pivx/requestdialog.h

As the addresses widget only takes into account the transparent addr contacts size in the list visibility update, the view is not presented if the wallet only has shield and/or cold staking addr contacts stored.
The first commit is the bug fix, the others are purely code cleanups that made while was digging over the bug cause.

[GUI] Fix not visible contacts list for shield/CS addrs

---

doc/release-notes/release-notes-5.3.1.md

Now that 5.3.0 has been tagged, add the 5.3.0 historical release notes to the master branch.

[Doc] v5.3.1 release-notes.

---

src/blockassembler.cpp
src/masternodeman.cpp
src/masternodeman.h
src/primitives/transaction.cpp
src/primitives/transaction.h
src/rpc/masternode.cpp

This simplifies the 'getmasternodecount' workflow that was walking through the 'mapMasternodes' 3 times locking the manager mutex when it can gather the information looping over it just once.
Plus, added a second commit cleaning the `HasZerocoinPublicSpendInputs` unused function and `ScoreCompare` unused class.

[TierTwo] Unify MNs info gathering into a single getMNsInfo() call

---

CMakeLists.txt
src/Makefile.am
src/blockassembler.cpp
src/budget/budgetmanager.cpp
src/budget/budgetvote.h
src/budget/finalizedbudgetvote.h
src/evo/deterministicmns.cpp
src/logging.cpp
src/logging.h
src/masternode.h
src/messagesigner.cpp
src/messagesigner.h
src/net_processing.cpp
src/primitives/block.h
src/qt/pivx/settings/settingssignmessagewidgets.cpp
src/rpc/budget.cpp
src/rpc/misc.cpp
src/rpc/rpcevo.cpp
src/util/blockstatecatcher.h
src/util/validation.cpp
src/util/validation.h
src/validation.cpp
src/validation.h
src/validationinterface.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
test/functional/mining_pos_coldStaking.py

Backports bitcoin#16688 [jkczyz], which should help us debug some intermittent failures on GA (e.g. for `feature_reindex` or `wallet_basic` tests).
> Add logging of CValidationInterface callbacks using a new VALIDATION log flag (see 12994). A separate flag is desirable as the logging can be noisy and thus may need to be disabled without affecting other logging.
>
> This could help debug issues where there may be race conditions at play, such as 12978.

[Util] Add validation interface logging

---

src/qt/pivx/coldstakingwidget.cpp
src/qt/pivx/coldstakingwidget.h
src/qt/pivx/forms/coldstakingwidget.ui
src/qt/pivx/receivewidget.cpp

Same as the one introduced for the receive widget in #2353.
Closes #2499.

[GUI] Add address search option in cold-staking widget

---

src/coins.h
src/dbwrapper.h
src/httpserver.cpp
src/key.cpp
src/key.h
src/pivx-tx.cpp
src/rpc/server.h
src/test/key_tests.cpp
src/test/script_tests.cpp

Straightforward unused code cleanup coming from #9987 and #10075.

Cleaning unused code

---

src/qt/pivx/settings/settingssignmessagewidgets.cpp
src/rpc/misc.cpp
src/wallet/rpcwallet.cpp

Simple refactoring commit to remove some code duplication. No functional changes.
note: 
currently this PR includes
for easier rebase later: as here we replace the `util/validation.h` header include (introduced in #2548) with `messagesigner.h`, where `strMessageMagic` was accessed directly.

[Refactor] Remove code duplication in sign/verify message rpc/gui

---

src/activemasternode.cpp
src/budget/budgetmanager.h
src/init.cpp
src/pivxd.cpp
src/util/system.cpp
src/util/system.h

Straightforward cleanup of global variables from `system.h` that are not needed to be global.

[Cleanup] Remove and deglobalize system.h global variables.

---

src/activemasternode.cpp
src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/budget/budgetproposal.cpp
src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/masternode-sync.cpp
src/masternodeman.cpp
src/masternodeman.h
src/qt/clientmodel.cpp
src/rpc/masternode.cpp
src/test/evo_deterministicmns_tests.cpp
test/functional/tiertwo_deterministicmns.py
test/functional/tiertwo_mn_compatibility.py

Bug introduced in #2308.
We are considering the total masternode count, inclusive of deterministic masternodes, only in `GetNextMasternodeInQueueForPayment`, but not in other places.
Fix this by updating directly the function `CountEnabled`, using the legacy-only count exclusively for the masternode list sync.

[BUG] Consider also DMNs in CountEnabled and CountNetworks

---

depends/config.guess
depends/config.sub

Allows the depends system to properly identify M1 Mac systems as `aarch64-apple-darwin`.

[Depends] Use latest config guess/sub

---

src/qt/pivx/dashboardwidget.cpp

Fixing #1235.
The `QDateTime` comparators are tricky as it uses the number of seconds in a day. 
The day filtering window is from 00:00:00 to the last second of the day 23:59:59.

[GUI] dashboard chart, fix last day of the month not being shown.

---

test/functional/test_framework/netutil.py

Straight forward backport of https://github.com/bitcoin/bitcoin/pull/13963
> tostring() is deprecated as of python 3.7 and results in stderr output
> causing tests to fail

[Tests] Replace usage of tostring() with tobytes()

---

src/qt/pivx/welcomecontentwidget.cpp

On the Welcome screen, when users change the language, a call to Qt's
internal `retranslateUi()` is made. This, however does not take into
consideration any arguments in a source string, and instead treats them
as string literals (ie, `%1` is not considered an argument, but rather a
literal string)
Fix this by adding a supplemental call to `setText()` that DOES allow
for argument processing directly after the retranslation.
Fixes #2570

[GUI] Force argument insertion when switching languages

---

src/chainparams.cpp
src/consensus/params.h

`nPoolMaxTransactions` and `height_ZC_RecalcAccumulators` are no longer needed.

[Cleanup] Remove unused chain params

---

src/budget/budgetmanager.cpp
src/masternode.cpp

Solving a last edge case race condition for the tier two initial sync process:
if a `fbvote` or `fbs` message is received before or while we are synchronizing the MN list, there can be a race where the node will move to single items requests instead of requesting the full list (which is not what we want in the initial sync process as single items requests sync is a reactive approach while full list requests is a proactive one).
Plus, decreased the DoS score for a bad mnb signature during the initial synchronization process, so we don't end up banning pre v5.3.3 nodes too fast for an invalidly serialized mnb (this issue was solved in #2611 removing the mnb BIP155 flag, this is only an extra guard to give a bit more time to non-updated peers to upgrade while the network is upgrading).

[TierTwo] Do not ask for single MN items if the node is in initial sync state

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/masternode-payments.cpp
src/masternode-sync.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/masternodeman.h
src/net.cpp
src/net.h
src/net_processing.cpp
src/qt/pivx/welcomecontentwidget.cpp
src/rpc/budget.cpp
src/rpc/client.cpp
src/version.h
test/functional/test_framework/messages.py
test/functional/tiertwo_governance_sync_basic.py

Backports #2611 for v5.3.3
So we do a release focused on solving tier two network synchronization and re-synchronization issues that are mainly affecting the superblock payments window and causing network forks.
Update:
Added #2617 and #2622 as well.

[Backport] 5.3.3 backports

---

src/Makefile.bench.include
src/bench/CMakeLists.txt
src/bench/checkblock.cpp
src/bench/walletprocessblock.cpp
src/evo/evonotificationinterface.h
src/init.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/test/test_pivx.cpp

This work aims to improve the structure and performance of the wallet's Sapling increment witnesses flow.
The process is essentially walking through the entire wallet's txs map a minimum of 2 times, if there is no shield tx in the arriving block, and adds one more for each shield tx inside the block. Which affects mainly to wallets with a large number of transactions as the wallet is locked while this operation is being executed.
So, straight to the point, the current increment witness workflow is:
```
1) for-each tx in wallet : call CopyPreviousWitnesses.
2) for-each tx in block:
a) for-each note in tx:
      a1) for-each tx in wallet : call AppendNoteCommitment.
      a2) if note is mine : call WitnessNoteIfMine.
3) for-each tx in wallet : call UpdateWitnessHeights.
```
And, have …

[Wallet] Sapling, restructure increment witnesses workflow

---

src/qt/pivx/governancemodel.cpp

Small follow-up to #2406, solving zebra's comment: https://github.com/PIVX-Project/PIVX/pull/2406#discussion_r741183095.
Fixing the not schedule of waiting proposals for broadcast at startup. Which caused that if the wallet was restarted in the middle of the broadcast process, the waiting proposals will not enter in the broadcast queue.

[GUI][BugFix] Schedule proposal broadcast only if the block has not passed yet

---

src/qt/pivx/forms/proposalcard.ui
src/qt/pivx/proposalcard.cpp

Found it while was testing #2626, a small bug that occurs when the app window width isn't big enough to automatically expand the three column grid proposal cards. So the last letter of proposals with large names are being cut.
For example, look at the proposal in the middle:
Before the fix:
After the fix:

[GUI] Correct proposal large title for being cut when the app window width isn't big enough

---

src/masternode-payments.cpp
src/masternode-payments.h
src/test/mnpayments_tests.cpp

Extracted from #2421 (and based on top of it) so #2550 can be merged in between.

[Refactor] Reorder mnw processing and validation

---

src/blockassembler.cpp
src/blockassembler.h
src/chainparams.cpp
src/wallet/test/pos_validations_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/mining_pos_coldStaking.py

```
Chains diagram:
A -- B -- C -- D -- E -- F -- G -- H
\
-- D1 -- E1 -- F1
\
-- D2 -- E2 -- F2
\
-- D3 -- E3 -- F3 -- G3 -- H3 
\
-- D4 -- E4 -- F4
```
Coverage added on this work:
1) coins created in D1 and spent in E1. --> expected result: pass.
2) coins created in E, being spent in D4 --> expected result: reject.
3) coins created and spent in E2, being double spent in F2. --> expected result: reject.
4) coins created in D and spent in E3. --> expected result: reject.
5) coins create in D, spent in F and then double spent in F3. --> expected result: reject.
6) coins created in G and G3, being spent in H and H3 --> expected result: pass.

[Test] Secondary chains acceptance test coverage

---

src/wallet/wallet.cpp
src/wallet/walletdb.cpp

New created wallets have no name set by default, thus why the `GetUniqueWalletBackupName` function returns "null", and the automatic backup process creates backup files with a name in the form of "null+date".
Changed the label to "wallet_backup" instead of "null" if the wallet has no name, plus fixed the rolling functionality that was not cleaning old files.

[wallet] Fix "null" backup file name.

---

src/budget/finalizedbudget.cpp
src/budget/finalizedbudget.h
test/functional/tiertwo_governance_sync_basic.py

Currently we keep (and relay) finalized budgets for a whole cycle after the superblock.
These finalization messages (and relative votes) might be rejected (they might include expired proposals at that point) by new peers, syncing after the budget payments are over.
There is no need to keep and sync finalized budgets for a whole cycle of 43200 blocks.
This PR sets the expiration to 200 blocks after the last budget payment.

[Refactor] Remove finalized budgets earlier

---

test/functional/sapling_wallet_nullifiers.py

Have seen this test failing in GA due a not synchronized mempool across nodes. Which has nothing to do with the test purpose, so this will let every node by-pass the trickle logic and directly relay the known transactions.

[test] sapling_wallet_nullifiers.py whitelist peers to speed up tx relay.

---

src/bench/bls_dkg.cpp
src/bench/walletprocessblock.cpp
src/evo/evonotificationinterface.h
src/masternodeman.cpp
src/qt/walletmodel.cpp
src/sapling/sapling_operation.cpp
src/sapling/sapling_operation.h
src/sapling/transaction_builder.cpp
src/sapling/transaction_builder.h
src/support/allocators/mt_pooled_secure.h
src/test/librust/sapling_rpc_wallet_tests.cpp
src/test/librust/sapling_wallet_tests.cpp
src/test/librust/transaction_builder_tests.cpp
src/test/librust/utiltest.cpp
src/test/test_pivx.cpp
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
src/wallet/test/wallet_shielded_balances_tests.cpp

Simple cleanup of unused private field `TransactionBuilder::nHeight` and few local variables.

[Cleanup] Remove unused variables and private fields

---

src/serialize.h
src/test/serialize_tests.cpp

Backport of bitcoin#16730, fixing the following clang warning:
```
./serialize.h:631:44: warning: loop variable 'elem' is always a copy because the range of type 'const
std::vector<bool, std::allocator<bool> >' does not return a reference [-Wrange-loop-analysis]
for (const typename V::value_type& elem : v) {
^
./serialize.h:484:77: note: in instantiation of function template specialization
'VectorFormatter<DefaultFormatter>::Ser<CHashWriter, std::vector<bool, std::allocator<bool> > >'
requested here
template<typename Stream> void Serialize(Stream &s) const { Formatter().Ser(s, m_object); }
^
./serialize.h:806:7: note: in instantiation of function template specialization
'Wrapper<VectorFormatter<DefaultFormatter>, const std::vector<bool, std::allocator<bool> >
&>::Serialize<CHashWriter>' …
```

[Util] Support serialization of std::vector<bool>

---

doc/release-process.md
src/qt/intro.cpp

This introduces per-network required disk space into the intro UI in the
least intrusive way for now. Mainnet and Testnet have their own static
const variables, whereas Regtest is always set to "0"
This is intended as a temporary fix for #2618, with future intention on
moving these over to chainparams a la upstream and using a node IPC
interface layer, which we do not have yet.
Can be tested by passing `-choosedatadir` with a combination of `-testnet`,
`-regtest`, or standalone, and this has zero impact on translation strings.

[GUI] Show disk space requirement per-network

---

src/wallet/test/pos_validations_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Fixing an inconsistency in the PoS validations unit tests, specifically in the secondary chain branches acceptance test cases.
As the wallet is not prepared to follow several chains at the same time, need to manually remove from the stakeable utxo set the coinstake inputs that were used on the previous blocks of the parallel chain so they are not used again in the block that is being crafted.

[test] fix coinstake input selection on secondary chains.

---

test/functional/sapling_wallet_nullifiers.py

Still (somewhat frequent) mempool sync failures in this test, even after #2633.
This is because `node1` might still be in IBD when he receives the first tx INV message, and, with #2611, nodes no longer send (non-block) getdata requests during initial sync.

[QA] Fix intermittent mempool sync failures in sapling_wallet_nullifiers

---

doc/release-notes.md
src/wallet/rpcwallet.cpp
test/functional/wallet_labels.py

This adds shield address support to the `setlabel` and
`getaddressesbylabel` RPC commands. `setlabel` now accepts and validates
shield address input argument, where `getaddressesbylabel` now returns
shield addresses with a label matching the input argument.
Companion to #2600 that allows CLI users to set a label for shield addresses
after-the-fact, as well as see shield addresses with an assigned label in the
response of `getaddressesbylabel`
Also added relevant release notes for the changes in #2600.
Regression tests added as well to cover the `setlabel` command.

[RPC] Shield address setlabel/getaddressesbylabel

---

CMakeLists.txt
src/Makefile.am
src/Makefile.test.include
src/httpserver.cpp
src/pivx-cli.cpp
src/support/events.h
src/test/CMakeLists.txt
src/test/raii_event_tests.cpp

Backported the following PRs from upstream:
* #8722.
* #9265.
* #9073.
* #9387.
* #9517.
* #9647.
* #13394.

pivx-cli better error handling + libevent RAII upstream backports

---

doc/release-notes.md
src/activemasternode.cpp
src/init.cpp
src/net.cpp
src/net.h
src/net_processing.cpp
src/netbase.cpp
src/netbase.h
src/rpc/net.cpp
test/functional/p2p_disconnect_ban.py

More net updates from upstream, this time focused on:
1) The `addnode` functionality will have its own connections slots, there will be no interference between `addnode` connections and automatic outbound connections.
2) Divides the address resolving logic from the connection logic.
3) Divides the socket create and connect logic.
Adapted the following PRs from upstream:
* #9319
* #9487
* #9953
* #10663
* #10234
* #11363
* #12329

[Net] Split resolve out of connect and add addnode parallel outbound connections limit

---

src/txmempool.cpp
src/txmempool.h
src/wallet/init.cpp
src/wallet/test/wallet_tests.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/test_runner.py
test/functional/wallet_basic.py
test/functional/wallet_resendwallettransactions.py

Work originated from a third party service hitting the mempool ancestors count limit.
Focused on two main topics (plus some extra cleanup):
1) The wallet's utxo selection process will now predilect coins that have fewer ancestors.
2) Add functional test for the wallet transactions rebroadcast.
Based on the following backports:
* #6669 (only 6b0e622c).
* #9262.
* And ported the wallet transactions rebroadcast functional test, skipping and grouping few intermediate PRs up to faf6f156.
This PR is not meant to be included in the shortly coming v5.3.2.1. Which is good enough as is, the `sendmany` min depth arg fix is already by-passing the issue automatically without human interaction (mempool utxo will not be selected by default).
This is a follow up work to fully prevent the issue from …

[Wallet] Prefer coins that have fewer ancestors, sanity check txn before ATMP and rebroadcast functional test

---

src/qt/pivx/coldstakingwidget.cpp
src/qt/pivx/coldstakingwidget.h
src/qt/pivx/dashboardwidget.cpp
src/qt/pivx/dashboardwidget.h
src/qt/pivx/forms/dashboardwidget.ui
src/qt/pivx/res/css/style_dark.css
src/qt/pivx/res/css/style_light.css
src/qt/transactionfilterproxy.cpp
src/qt/transactionfilterproxy.h
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h

Revival of #1362 with further cleanup.
As we don't have zPIV anymore, this PR removes it from the dashboard chart and include the Masternodes rewards instead.

[GUI] Include MN Rewards in the dashboard chart

---

src/masternodeman.cpp
test/functional/p2p_invalid_messages.py
test/functional/test_framework/messages.py

Follow-up work to #2611. 
Adding a regression test case for one of the issues solved in #2611:
As none of the mnp inv requests were being removed from the waiting for response inv set and map when the item arrives.
The set was growing non-stop for the entire node life cycle up to the point where no subsequent inv msg were accepted anymore.
After v6.0, as the mnp message will be removed, the test can be moved to be based on quorum inv msgs.

[Test] Add test case for node with a full "ask for" inv set.

---

src/sapling/address.cpp
src/sapling/address.h
src/sapling/incrementalmerkletree.cpp
src/sapling/note.cpp
src/sapling/note.h
src/sapling/noteencryption.cpp
src/sapling/noteencryption.h
src/sapling/sapling_operation.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/zip32.cpp
src/sapling/zip32.h
src/util/system.h
src/wallet/test/wallet_shielded_balances_tests.cpp

As per title: scripted commit (plus cleanup) to remove last remaining direct usages of `boost::optional`, mostly in the sapling files.

scripted-diff: replace boost::optional with Optional<> wrapper

---

src/blocksignature.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
test/lint/lint-circular-dependencies.sh

by moving `GetKeyIDFromUTXO` out of `CTxOut`, making it a static function of `blocksignature.cpp`, which is the only place using it.
based on top of:

[Refactoring] remove circular dependency primitives/transaction <-> script/standard

---

src/activemasternode.cpp
src/activemasternode.h
src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/evo/evonotificationinterface.cpp
src/init.cpp
src/rpc/masternode.cpp
src/test/evo_deterministicmns_tests.cpp
src/validation.cpp
src/validationinterface.h

As this has direct consensus implications, it cannot be updated in the background thread (in fact, the tests must pass without having to resort to `SyncWithValidationInterfaceQueue`).
The manager's tip must be updated on the caller's thread and, on the other hand, what is being called by `UpdatedBlockTip` (on the background), such as `CActiveDeterministicMasternodeManager::Init` or `CActiveDeterministicMasternodeManager::Reset`, shouldn't rely on the manager's tip, but use `pindexNew` instead.

[Validation] Synchronous update for CDeterministicMNManager::tipIndex

---

src/qt/coincontroldialog.cpp

[BUG] GUI: invalid locking of shield notes in coin control

---

src/qt/coincontroldialog.cpp

Note locking is not yet implemented, as such there is no reason to show
any of the locking related actions in the coin control dialog.

[GUI] Don't show UTXO locking options for shield notes

---

src/activemasternode.cpp
src/init.cpp
src/net.cpp
src/net.h
src/net_processing.cpp

More groundwork for the LLMQ sessions connections work, built on top of #2586 and #2587 (starts in 10efb72a).
Focused on cleaning the connman init/start by decoupling the command line arguments.
Backported PRs list:
* #10467.
* #10496.
* #10596.
* #10977.
* #11301.
* #11744 (partially, without the outbound members changes as we don't have them).

[net] Connman options encapsulation

---

src/qt/pivx/forms/governancewidget.ui
src/qt/pivx/forms/proposalcard.ui
src/qt/pivx/forms/proposalinfodialog.ui
src/qt/pivx/forms/votedialog.ui
src/qt/pivx/proposalinfodialog.cpp

The new governance UI has introduced some item naming conflicts that result in build-time warnings. This cleans up the issue as well as sanitizes the various layout/spacer item names to be in sequential order within respective files.

[Build] Sanitize governance UIs item naming

---

src/chainparams.cpp
src/consensus/params.h
src/qt/pivx/qtutils.cpp
src/qt/pivx/txrow.cpp
src/qt/transactionfilterproxy.cpp
src/qt/transactionrecord.cpp
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/validation.cpp

Fixes #2667. Created a new transaction record type `BudgetPayment` to distinguish MN block rewards from budget payments
In order to do this without duplicate code, moved the MN reward amount value to chainparams.

[GUI] Differentiate Budget payment output records from MNs block reward records.

---

src/qt/pivx/governancewidget.cpp

When there are enough proposals to need the GUI to scroll down to see
them all, the location of the tooltip menu gets skewed to the point of
it not being visible. This is because it's location was being based on
the initial position of the proposal card, even for off-screen ones.
This fixes the issue by taking the scrollarea's vertical scrollbar value
into consideration.
-------
Before:
After:

[GUI] Fix proposal tooltip menu location skewing

---

src/qt/pivx/governancewidget.cpp

Straightforward PR: blocking proposals submission during IBD. 
The wallet could not be able to create the fee transaction for the lack of chain tip coins view and the impossibility to calculate the next superblock height.
Fixes #2669.

[GUI] Governance, do not open the proposal creation wizard if node is in IBD.

---

src/budget/budgetproposal.h
src/qt/pivx/createproposaldialog.cpp
src/qt/pivx/governancemodel.cpp
src/qt/pivx/governancemodel.h

Fixes #2666 crash. Which is related to the size, in bytes, of the proposal name and/or the URL that can exceed the maximum allowed size, then crash during the limited string unserialization process.

[GUI] Fix proposal name and URL size limit validation

---

src/net_processing.cpp

If when the peer is responding to a series of tx or tier two data requests in `getdata` hits the send buffer limit and set `fPauseSend`, it will skip one request per call to `ProcessGetData` (a tx or any of the tier two items).
This is an adaptation of #12392, meaning more for us as the peer will skip tier two items requests.

[net_processing] Fix ignoring get data requests when fPauseSend is set on a peer

---

src/net_processing.cpp
src/protocol.h
src/validation.cpp

Grouped few findings that discovered testing #2659.
* The "not found" message is not being processed properly. Logging an unnecessary "unknown message type" error.
It become even more evident syncing a peer running 2659 from a normal network peer, because of the non-updated peer blockage from relaying budget items that described there (the `ClearSeen` bug..). 
* Then some extra refactoring, removing unneeded chain height argument in `PushTierTwoGetDataRequest` and adapted 2c09a520 to our sources as well.

[Net_processing]  Do not log "notfound" msg as unknown.

---

src/wallet/wallet.cpp
src/wallet/wallet.h

So they are rebuilt via `ScanForWalletTransactions` --> `ChainTipAdded`, and a corrupted cache can be fixed with a simple `-rescan` of the chain data (instead of a complete reindex).

[Wallet] Clear Shield notes witness cache before a full rescan

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/budget/budgetproposal.cpp
src/budget/finalizedbudget.cpp
src/init.cpp
src/masternode-sync.cpp
src/masternode-sync.h
src/net_processing.cpp
src/tiertwo_networksync.cpp
test/functional/tiertwo_governance_sync_basic.py

A never ending story, more improvements and corrections for the tier two initial synchronization.
This time, the following points are tackled:
1) Fix a bad workflow that causes the budget data initial synchronization to be skipped.
if we received for example a proposal +50 seconds ago, while we are synchronizing another asset, then once the budget sync starts, it will look like the sync is finished when it's not. Not waiting to receive any budget data, declaring the sync completed.
2) Decrease `mnw` sync threshold to 4 peers to "minimize" the insane amount of network flood and initial tier two sync delay.
MNW initial sync is mostly for historical reasons, getting +20k items per peer (+120k items total for the previous threshold of 6) is a high amount of duplicated data relayed over the …

[TierTwo] Fix and improve several synchronization problems

---

src/rpc/budget.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Completes the backport of bitcoin#11039 (which was partially done elsewhere)
Also extends it to pivx-specific code (sapling, budget).
> All calls to mapWallet.count() have the intent to detect if a txid exists and most are followed by a second lookup to retrieve the CWalletTx.
>
> This PR replaces all mapWallet.count() calls with mapWallet.find() to avoid the second lookup.

[Wallet] Avoid second mapWallet lookup

---

src/budget/budgetmanager.cpp
src/budget/budgetmanager.h
src/budget/budgetproposal.cpp
src/budget/budgetproposal.h

The function is already counting the votes, just need to return the value.
Plus, removed `budgetproposal` dependency on `masternodeman`.

[budget] Do not count votes twice after calling GetBudgetWithHighestVoteCount.

---

src/init.cpp
src/validation.cpp

Backported
- bitcoin#12349
- bitcoin#12367

[BUG] Fix possible crashes at shutdown

---

src/net.cpp

Backports #9008.
> nMaxInbound might very well be 0 or -1, if the user prefers to keep a small number of maxconnections.
>
> Note: nMaxInbound of -1 means that the user set maxconnections
to 8 or less, but we still want to keep an additional slot for
the feeler connection.
Have faced this assertion crash few times in testnet already.

[net] Remove assert(nMaxInbound > 0)

---

src/sapling/saplingscriptpubkeyman.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Does the same for other Sapling-related maps (`mapSaplingNoteData`, `mapSaplingNullifiersToNotes`).

[Refactor] Avoid double lookups in sapling maps

---

src/net_processing.cpp
test/functional/p2p_leak.py
test/functional/test_runner.py

More updates, corrections and test coverage to the network layer for the LLMQ MNs connections work (deep rabbit hole..). Built on top of #2587.
PR starts in cd00e312, focused on:
1) Correctly ban before the handshake is complete (c45b9fb5).
2) Require a `verack` before responding to anything else (cbfc5a67).
3) Update and enable `p2p_leak.py` functional test (check commit, the functional test framework was too ahead of it).
4) Move `SENDADDRV2` msg processing so it can be processed before a verack.

[net] disallow sending messages before receiving verack + enable p2p_leak.py test

---

test/functional/sapling_changeaddresses.py
test/functional/test_runner.py

Same problem as #2638, on a different test (GA failed run [here](https://github.com/PIVX-Project/PIVX/runs/4383720230)).
Since there's no need to use two nodes to perform this test, instead of adding the missing `sync_blocks`/`sync_mempools` calls, just remove the second node (which also speeds the test up).

[QA] Use single node in sapling_changeaddresses

---

src/budget/budgetproposal.cpp
src/budget/budgetproposal.h

Cleaning pre-v5 consensus guards for the proposal start block and max payment amount validation.

[budget] Clean pre-v5 consensus guards for proposal start block and max payment amount

---

src/wallet/rpcwallet.cpp

As per title, instead of returning all coins (after checking the availability of each one) and then filtering by address in the rpc code.

[RPC] listunspent: pre-filter coins by destination in AvailableCoins

---

CMakeLists.txt
src/Makefile.am
src/blockassembler.cpp
src/chainparams.cpp
src/consensus/params.h
src/consensus/tx_verify.cpp
src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/evo/specialtx_validation.cpp
src/init.cpp
src/llmq/quorums_blockprocessor.cpp
src/llmq/quorums_blockprocessor.h
src/llmq/quorums_commitment.cpp
src/llmq/quorums_commitment.h
src/llmq/quorums_init.cpp
src/llmq/quorums_init.h
src/llmq/quorums_utils.cpp
src/llmq/quorums_utils.h
src/logging.cpp
src/logging.h
src/net_processing.cpp
src/primitives/transaction.h
src/protocol.cpp
src/protocol.h
src/serialize.h
src/test/evo_deterministicmns_tests.cpp
src/test/evo_specialtx_tests.cpp
src/test/test_pivx.cpp
src/tiertwo_networksync.cpp
test/lint/lint-circular-dependencies.sh

This PR lays the groundwork for the implementation of [DIP6](https://github.com/dashpay/dips/blob/master/dip-0006.md).
Here we introduce the concept of "quorum final commitment", which is the result of a DKG round.
This object is serialized and relayed to the network via a new message, `qfcommit`. Then, it is mined on chain as payload of a new type of special transaction, `LLMQComm` tx (which is the last phase of the DKG protocol).
With this, it is possible to implement (and test) the masternode proof-of-service, based on the DKG participation.
Intra-quorum communication and signing sessions will be part of future pull requests.

[TierTwo] Long Living Masternode Quorums - Part 1

---

src/pivx-cli.cpp

The error message enum `evhttp_request_error` was introduced in libevent
2.1.3, which we do not necessarily require, and is not available to some
older but still supported linux distros (namely Ubuntu Xenial 16.04
LTS).
Add a version guard to maintain compatibility with the 2.0.x branch of
libevent.

[CLI][Build] Guard libevent error messages

---

CMakeLists.txt
src/Makefile.am
src/budget/budgetmanager.cpp
src/init.cpp
src/masternode-payments.cpp
src/masternodeman.cpp
src/spork.cpp
src/tiertwo/init.cpp
src/tiertwo/init.h
src/util/system.cpp
src/util/system.h
src/validation.cpp
src/wallet/wallet.cpp

It's primarily a move-only refactoring, breaking up a bit more the long monolithic `init.cpp`. Placing the tier two components initialization in a separate `tiertwo/init.cpp` file.
This will make future inclusions easier, like #2647 introducing the new tier two MN metadata manager and the network sync requests manager.
And, as an extra cleanup, removed the broken `litemode` flag. Because, as is now, it simply makes no sense.. it's a "turn this on to fork your node".

[Refactor] Move tier two managers initialization from init.cpp to tiertwo/init.cpp

---

src/guiinterface.h
src/net.cpp
src/net.h
src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
src/qt/pivx/settings/settingsinformationwidget.cpp
src/qt/pivx/settings/settingsinformationwidget.h
src/qt/pivx/settings/settingswalletoptionswidget.cpp
src/qt/pivx/settings/settingswalletoptionswidget.h
src/qt/pivx/topbar.cpp
src/qt/pivx/topbar.h
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h
src/rpc/client.cpp
src/rpc/misc.cpp
src/rpc/net.cpp
src/test/rpc_tests.cpp

Allowing the user/test to stop and restart the network activity.
Pretty useful for some manual isolation test cases.
When the network activity is disabled the client will close all connections, stop accepting inbound connections, and stop opening new outbound connections, until the network activity is reenabled.
Quick demo video:
https://user-images.githubusercontent.com/5377650/137732464-02624285-2e62-483d-bf79-6df9cb0162f1.mp4
TODO:
Add release-notes for the new RPC command and the GUI control.

[Net][GUI][RPC] Add enable/disable network activity feature

---

src/blockassembler.cpp
src/blockassembler.h
src/test/evo_deterministicmns_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h
src/validation.cpp

As per title (and discussion here: https://github.com/PIVX-Project/PIVX/pull/2607#issuecomment-1001244951) do not accept quorum commitment txes in the mempool. 
Add test coverage.

[QA] Reject in-mempool llmqcomm transactions

---

test/functional/sapling_key_import_export.py

Same rationale as #2633, whitelist peers so the trickle mechanism does not delay the mempool txs relay.
Saw this test failing here https://github.com/PIVX-Project/PIVX/runs/4643010485?check_suite_focus=true .

[test] sapling_key_import_export.py whitelist peers to speed up tx relay.

---

src/support/lockedpool.cpp

Backports of bitcoin#15600 and bitcoin#18443 patching [CVE-2019-15947](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15947).

lockedpool: avoid sensitive data in core dumps

---

src/qt/pivx/dashboardwidget.cpp

As per the title says, as the staking date filter is not being initialized at startup the chart shows the entire staking history as it would have happened in the same year.

[GUI][BugFix] Fix missing dashboard chart date filter initialization at startup

---

src/txdb.cpp

Simple fix of missing argument type specifiers in LogPrintf string.

[Trivial] Fix LogPrintf arguments in WipeAccChecksums

---

src/consensus/params.cpp
src/consensus/params.h
src/consensus/validation.h
src/evo/deterministicmns.cpp
src/evo/deterministicmns.h
src/evo/specialtx_validation.cpp
src/evo/specialtx_validation.h
src/llmq/quorums_blockprocessor.cpp
src/llmq/quorums_commitment.cpp
src/llmq/quorums_commitment.h
src/llmq/quorums_init.cpp
src/llmq/quorums_utils.cpp
src/llmq/quorums_utils.h
src/test/evo_deterministicmns_tests.cpp
test/lint/lint-circular-dependencies.sh

And remove circular dependency `evo/deterministicmns` <-> `llmq/quorums_utils`.

[Refactor] Deduplicate final commitment validity checks

---

build-aux/m4/l_atomic.m4
src/Makefile.am
src/bls/bls_worker.cpp
src/bls/bls_worker.h
src/ctpl_stl.h
src/util/threadnames.cpp

Coming from https://github.com/dashpay/dash/pull/4240, https://github.com/bitcoin/bitcoin/pull/20938, and https://github.com/bitcoin/bitcoin/pull/21920, this resolves numerous compile-time inconsistencies/failures on certain combos of gcc and cpu arch that were observed on launchpad.net over the 5.4.0 release cycle.

[Core][Build] Fix atomic data races in BLS operations

---

src/masternode-payments.cpp
src/masternodeman.cpp

Since this function is called "10 blocks in advance", the status of SPORK-21 should be checked with `nBlockHeight`, not with the current chain tip height.

[BUG] Fix SPORK-21 check in CMasternodePayments::ProcessBlock

---

src/qt/askpassphrasedialog.cpp
src/test/librust/sapling_rpc_wallet_tests.cpp
src/wallet/db.cpp
src/wallet/db.h
src/wallet/rpcwallet.cpp
src/wallet/test/wallet_test_fixture.cpp
src/wallet/test/wallet_test_fixture.h
src/wallet/wallet.cpp
test/functional/rpc_fundrawtransaction.py
test/functional/sapling_wallet_nullifiers.py
test/functional/test_framework/test_node.py
test/functional/wallet_bumpfee.py
test/functional/wallet_dump.py
test/functional/wallet_encryption.py
test/functional/wallet_keypool.py

An improvement for the wallet UX: Stop requiring a wallet shutdown after the initial encryption. Now the process can safely continue running without any fear of leaking unencrypted keys.
PRs backported from upstream:
* #12493.
* #13161.
* #14320.

[wallet] Reopen CDBEnv after encryption instead of shutting down

---

src/evo/specialtx_validation.cpp
src/llmq/quorums_blockprocessor.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/test_pivx.cpp
src/test/test_pivx.h

As discussed in #2699 , split `bad-qc-quorum-hash` reject reason in two different cases for "hash not found" and "hash not in active chain" and add unit test coverage.

[Refactor] differentiate bad-qc-quorum-hash: not-found/not-active-chain

---

src/qt/pivx/requestdialog.cpp
src/qt/pivx/requestdialog.h

For new payment requests via the UI, it doesn't make sense to have an empty/zero value for the amount being requested, but when creating a new cold staking address it is up to the sender how much they want to delegate, so the value at address creation time is completely optional.
This fixes the hard requirement of setting a non-zero value for cold staking address creation, and will no longer throw an error when the amount value is omitted (as the GUI indicates it is optional, which should be the intended behavior).
Also fixes a variable shadowing issue.

[GUI] Don't error on zero amount for new cold staking address

---

src/budget/budgetmanager.cpp
src/budget/finalizedbudget.cpp
src/evo/specialtx_validation.cpp
src/init.cpp
src/net_processing.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/mining.cpp
src/rpc/rawtransaction.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Adaptation of 92fabcd for our sources.
> Replacing all mapBlockIndex lookups with a new `LookupBlockIndex()`. In some cases it avoids a second lookup.

[Refactor] Add LookupBlockIndex

---

src/init.cpp
src/pivx-cli.cpp
src/pivxd.cpp
src/qt/pivx.cpp
src/util/system.cpp
src/util/system.h

Backporting:
* #15278.
* #15864.

Improve PID file error and datadir handling

---

src/bench/checkblock.cpp
src/evo/specialtx_validation.cpp
src/evo/specialtx_validation.h
src/init.cpp
src/net_processing.cpp
src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/rawtransaction.cpp
src/rpc/rpcevo.cpp
src/test/checkblock_tests.cpp
src/test/evo_deterministicmns_tests.cpp
src/test/evo_specialtx_tests.cpp
src/txdb.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

#2715 introduced a locking assertion in `InsertBlockIndex`, which is currently failing (with debug enabled) because `cs_main` is not held during the blockindex load in `AppInitMain` (https://github.com/bitcoin/bitcoin/pull/11041/commits/c651df8b32d82695b497c969bfc9f2b1374081a8).
Also, `LookupBlockIndex` is being called without cs_main in `LoadExternalBlockFile` (https://github.com/bitcoin/bitcoin/pull/11041/commits/f814a3e8fa0d99c3d95ae7866c707617a1dd3d4e).
Finally there's a couple of missing locks in rest.cpp (which can be removed later, porting bitcoin#12151).

Bug: fix missing cs_main lock in AppInitMain and LoadExternalBlockFile

---

src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/pivx/governancemodel.cpp
src/qt/pivx/governancemodel.h
src/qt/pivx/proposalcard.cpp
src/qt/pivx/proposalcard.h
src/qt/pivx/settings/settingsinformationwidget.cpp

Simply checking that there are more "yes" votes than "no" votes isn't
enough context to determine if a proposal should be in a passing state
(`PASSING` or `PASSING_NOT_FUNDED`)
Also, Set a unique label text for proposals that are passing but there aren't
enough funds left in the budget to find them.
-----------
Also includes some very light refactoring/cleanup in related files and a compile-time warning fix.
There is some follow-up refactoring to be done, but will do that in a separate PR as it falls out-of-scope for this PR.

[GUI][Bug] Don't set a proposal's status to PASSING_NOT_FUNDED prematurely 

---

CMakeLists.txt

Adds a CMake option to enable debug flags (default is OFF), and
additionally adds a compiler support check for `thread_local`, which is
required for `DEBUG_LOCKCONTENTION` flags.

[Build] Add CMake option to compile with debug flags

---

src/crypter.cpp
src/crypter.h
src/keystore.cpp
src/keystore.h
src/sapling/crypter_sapling.cpp
src/wallet/wallet.cpp

Grouped some updates to the wallet crypter sources.
* Cleaned Sapling crypter code.
* Backported #11272.
* Return result in `GetKeys()` instead of writing to reference (#10916).

[Wallet] Crypter code cleanup, updates and styling corrections

---

src/init.cpp
src/tiertwo/init.cpp
src/tiertwo/init.h
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/p2p_quorum_connect.py
test/lint/lint-circular-dependencies.sh

Follow-up to #2684, built on top of #2647. Starting in 296e6fa0.
Focused on the following points:
1) Move init arguments help messages to a new `GetTierTwoHelpString()`, the tier two objects initializers and the Masternodes collateral output locking process to the tiertwo/init files.
2) Improve DMN collateral locking process:
* Walking through the DMN list only once instead of one-time per wallet.
* Removing the wallet dependency on `evo/deterministicmns.h`.
3) Add `-disabledkg` init argument so the `p2p_quorum_connect.py` functional test does not get affected by the automatic DKG sessions processes (coming in #2722). The same flag will be used in other future tests that perform manual operations as well.

Finish moving tier two initialization code from init.cpp to tiertwo/init.cpp and add disabledkg init flag

---

src/compat.h
src/init.cpp
src/net.cpp
src/net.h
src/netbase.cpp
test/functional/p2p_timeouts.py
test/functional/test_runner.py

More tier two p2p network required updates. Focused mainly on porting the sockets poll functionality to eliminate the maximum socket descriptor number restriction.
Following points tackled:
1) Backported #13212 to fix a race condition on the network disable process.
2) Disconnect peers that have not send a VERACKs for more than 60 secs (coming from 2cbd1196), and enabled the `p2p_timeouts.py` functional test which validates the functionality.
3) Implement sockets poll functionality:
* bitcoin#14335.
* bitcoin#14336.

[Net] Implement poll(), fix race condition and enable p2p_timeouts.py test

---

src/chainparams.cpp
src/consensus/params.h
src/evo/specialtx_validation.cpp
src/test/evo_deterministicmns_tests.cpp

Built on top of #2713.
Added a depth limit for the acceptance of LLMQ final commitments to prevent spam attacks like the relay of old valid qfc through the inv system.

[validation] Reject valid qfc older than a certain depth.

---

src/validation.cpp
src/zpiv/zpivmodule.cpp
src/zpiv/zpivmodule.h

Essentially a zerocoin coinSpends cache layer to speedup the blockchain synchronization process during the period of time where blocks contained zerocoin transactions (which is the slowest period).
The reason behind this is that the sources are parsing and re-parsing the same zc transaction coinspend script over and over in different parts of the block validation circuit such as:
(1) block signature validation, (2) CheckZerocoinSpend, (3) ParseAndValidateZerocoinSpends, (4) CheckInBlockDoubleSpends, (5) IsUnspentOnFork, (6) ZPoS contextual checks, (7) NewZPivStake.
Pending to do: measure the blocks synchronization time improvement.

[validation] Create zerocoin coinspends cache

---

test/functional/wallet_zapwallettxes.py

Same rationale as #2633, whitelist peers so the trickle mechanism does not delay the mempool txs relay.
Saw it failing for this reason in master: https://github.com/PIVX-Project/PIVX/runs/4821849471?check_suite_focus=true

[test] wallet_zapwallettxes.py whitelist peers to speed up tx relay.

---

src/chainparams.cpp
src/consensus/params.h
src/evo/deterministicmns.cpp
src/masternode.cpp
src/masternode.h
src/masternodeman.cpp
src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/pivx/guitransactionsutils.cpp
src/qt/pivx/guitransactionsutils.h
src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/masternodeswidget.h
src/qt/pivx/masternodewizarddialog.cpp
src/qt/pivx/masternodewizarddialog.h
src/qt/pivx/mnmodel.cpp
src/qt/pivx/mnmodel.h
src/qt/pivx/pivxgui.cpp
src/qt/pivx/pivxgui.h
src/qt/pivx/send.cpp
src/qt/pivx/settings/settingsfaqwidget.cpp
src/qt/pivx/settings/settingsfaqwidget.h
src/wallet/wallet.cpp

Encapsulating the legacy Masternodes code that is spread over the GUI widgets inside the MN module.
Plus, as is a value shared between legacy and deterministic Masternodes, moved the collateral min conf field to `chainparams`. Which allowed to remove the following circular dependency: `"evo/deterministicmns -> masternode -> wallet/wallet -> evo/deterministicmns"`
Part of the building blocks for adding visual support for the new deterministic Masternodes features.

[GUI] Decouple legacy MNs code from the GUI elements

---

src/rest.cpp
src/rpc/blockchain.cpp
src/rpc/rawtransaction.cpp

Follow-up to #2728.
This pull makes blockToJSON, blockheaderToJSON, and TxToJSON free of cs_main locks by passing the chainTip and using `GetAncestor` to check if a block is part of the active chain (as per bitcoin#12151).

RPC: Remove cs_main lock from blockToJSON, blockHeaderToJSON and TxToJSON

---

CMakeLists.txt
src/Makefile.am
src/activemasternode.cpp
src/bls/bls_wrapper.h
src/bls/key_io.cpp
src/bls/key_io.h
src/chainparams.cpp
src/chainparams.h
src/evo/deterministicmns.cpp
src/evo/providertx.cpp
src/llmq/quorums_blockprocessor.cpp
src/llmq/quorums_commitment.cpp
src/rpc/rpcevo.cpp
src/test/bls_tests.cpp
test/functional/p2p_quorum_connect.py
test/functional/test_framework/messages.py
test/functional/test_framework/util.py

Instead of exporting the BLS keys as plain hex strings, encode them into proper bech32 strings.
Gaining the following benefits:
1) Easily recognizable unique prefix for each BLS key type:
"bls-sk" for secret keys and  "bls-pk" for public keys.
2) The character set minimizes ambiguity, all characters are lowercase.
3) Error detection algorithm.
More info about the bech32 format can be found at [BIP173](https://en.bitcoin.it/wiki/BIP_0173)

Bech32 export/import encoding format for BLS keys

---

src/rpc/blockchain.cpp
src/rpc/budget.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/server.cpp
src/wallet/rpcwallet.cpp
test/functional/rpc_blockchain.py
test/functional/rpc_rawtransaction.py

Backports bitcoin#13424
> ParseHashV validates the length and encoding of the string and throws an informative RPC error on failure, which is as good or better than these alternative calls.
>
> Note I switched ParseHashV to check string length first, because IsHex tests that the length is even, and an error like: "must be of length 64 (not 63, for X)" is much more informative than "must be hexadecimal string (not X)"

[RPC] Consistently use ParseHashV to validate hash inputs in rpc

---

src/init.cpp
src/masternode.cpp
src/pivxd.cpp
src/qt/pivx.cpp
src/tiertwo/init.cpp
src/tiertwo/init.h
src/wallet/wallet.cpp
src/wallet/wallet.h
test/lint/lint-circular-dependencies.sh

Built on top of #2721, decoupled from the DMN GUI branch.
Focused on the following points:
* Unify `masternodeconfig` duplicated initialization inside `tiertwo/init.cpp`. Same for the `pEvoNotificationInterface` class.
* Simplify and unify `CWallet::GetMasternodeVinAndKeys` and `CWallet::GetVinAndKeysFromOutput` functions.
* Bug fix: remove 'evodb' dir during `-resync`.
* Fix the following circular dependencies:
--> "masternode -> wallet/wallet -> masternode"
--> "chain -> legacy/stakemodifier -> stakeinput -> wallet/wallet -> evo/deterministicmns -> chain"
Next PR will be exclusively focused on the new tier two module.

Further TierTwo init encapsulation, '-evodir' resync bugfix and more circ dependencies fixes

---

src/bench/bench.h
src/bench/bench_pivx.cpp
src/qt/pivx/settings/settingssignmessagewidgets.cpp
src/test/fuzz/deserialize.cpp
src/test/reverselock_tests.cpp
src/test/scheduler_tests.cpp
src/test/torcontrol_tests.cpp
src/torcontrol.cpp
test/lint/lint-includes.sh

This brings in the `lint-includes.sh` shell script from upstream (first introduced in https://github.com/bitcoin/bitcoin/pull/11878) to automatically check for duplicate includes and expanded in https://github.com/bitcoin/bitcoin/pull/13301 and https://github.com/bitcoin/bitcoin/pull/13385 to check for the inclusion of `.cpp` files and the introduction of new boost includes, respectively.
The check for enforcing bracket include syntax (https://github.com/bitcoin/bitcoin/pull/13230) is also included, but currently disabled, as we have yet to systematically switch to that syntax preference.
Three other upstream PRs are backported here as they are directly related to the removal of some boost dependencies and are very straight forward:
- https://github.com/bitcoin/bitcoin/pull/10547
- …

[Lint] Introduce lint-includes.sh script

---

CMakeLists.txt
src/Makefile.am
src/Makefile.test.include
src/chainparams.cpp
src/chainparams.h
src/init.cpp
src/masternode-payments.cpp
src/masternode-sync.cpp
src/net.h
src/test/CMakeLists.txt
src/test/netfulfilledman_tests.cpp
src/tiertwo/init.cpp
src/tiertwo/init.h
src/tiertwo/netfulfilledman.cpp
src/tiertwo/netfulfilledman.h

Built on top of #2684
An object in charge of cache and store tier two network requests information, preventing possible bans for asking the same data too often.

[TierTwo] Introduce network requests manager

---

src/tiertwo/init.cpp

From v6.0, Deterministic Masternodes have to be connected to as many DMNs as possible (ideally, to all of them) to execute the DKG protocol, the Proof of Service, successfully and not end up being banned.
So, added a guard for the `-maxconnections` argument, to prevent headaches from any user that mistakenly decreases the value (already have seen one that copy-pasted the pivx.conf file).

Guard "-maxconnections" arg if the node is a Masternode.

---

src/rpc/masternode.cpp
src/rpc/rpcevo.cpp
src/tiertwo/init.cpp
test/functional/test_framework/test_framework.py
test/functional/tiertwo_deterministicmns.py
test/functional/tiertwo_mn_compatibility.py

Following points tackled:
1) Enabled the v6.0 DMN commands for testnet and mainnet.
2) Removed the 'deterministic' flag from `initmasternode` RPC command.
The masternode type is differentiated using the encoded key prefix.
3) Small fix to the  '-mnoperatorprivatekey' help message.
Another small decoupling from the DMN GUI branch.

[RPC] Enable v6.0 commands and remove 'deterministic' flag from initmasternode command

---

src/wallet/wallet.cpp

As `AcceptToMemoryPool` does not set the invalid state if the tx inputs requirements are not met, the wallet returns an empty validation state which ends up with an unknown/empty error message being presented to the user.

[wallet] fix ATMP call not contemplating the "missing inputs" error

---

src/activemasternode.cpp
src/activemasternode.h
src/net.cpp
src/net.h
src/netbase.cpp
src/netbase.h

Correcting two issues on the Deterministic Masternode operator side:
1) The DMN service address connectivity check was not being performed (due a non-initialized socket), failing all-the-time on testnet and mainnet. Erring out at startup.
2) `CActiveMasternodeManager::GetLocalAddress` will prefer IPv4 if there are multiple addresses available locally. --> #3304.
3)  `CActiveMasternodeManager::Init` connectivity check was missing to set the error cause.
Plus, now that i'm here, ported #12569 as well.

Fix DMN operator connectivity check and local address lookup

---

src/Makefile.test.include
src/llmq/quorums_connections.cpp
src/llmq/quorums_connections.h
src/llmq/quorums_dkgsession.cpp
src/llmq/quorums_dkgsessionhandler.cpp
src/llmq/quorums_dkgsessionhandler.h
src/llmq/quorums_dkgsessionmgr.h
src/test/CMakeLists.txt
src/test/net_quorums_tests.cpp

Follow-up work to my on-going review of https://github.com/PIVX-Project/PIVX/pull/2722#pullrequestreview-880202607. Starts in eeefe79c.
The current intra-quorum relay members selection algorithm receives a quorum member and selects a number of relay connections equals to the quorum size bits count.
So, for example: each DMN, in a quorum of 400 members, deterministically selects 9 other members and mark them as intra-quorum-relay members.
In the test LLMQ params case, with a quorum of 2, this algorithm falls into an infinite loop. Blocking the node's LLMQ session forever.
The process cannot select the input member for intra-quorum relay and expects to return a minimum of 2 elements.
Added a test case commit first so the issue can be easily verified/tested.
Aside from that, added some other …

[LLMQ][BugFix] Fix infinite loop in quorum relay members selection algorithm

---

src/activemasternode.cpp
src/init.cpp
src/masternode-payments.cpp
src/net.cpp
src/tiertwo/init.cpp

Follow-up to #2742.
1) Notify user if the Deterministic MN initialization failed for a local non-recoverable error.
2) Moved the startup Masternode activation after the connection manager initialization.
Without it, as the network module isn't initialized, the MN connectivity check always fails.
3) Removed an overkill check that was rejecting incoming connections on Masternodes if the node wasn't, tier two wise, synchronized.
The tier two sync preference for outbound connections can, and will, be achieved differently on a subsequent PR.

Error out at startup if there was an internal problem during DMN init

---

test/functional/p2p_quorum_connect.py
test/functional/test_framework/bech32.py
test/functional/test_framework/util.py

As per title, completes the rudimentary python implementation introduced in #2733

QA: Add proper bech32 encoding/decoding utilities to python framework

---

src/stakeinput.cpp
src/stakeinput.h
src/wallet/wallet.cpp
src/wallet/wallet.h
test/lint/lint-circular-dependencies.sh

Fixing the circular dependency:
"kernel -> stakeinput -> wallet/wallet -> kernel"

[Refactor] Create coinstake outputs moved from stakeInput to the wallet class.

---

.github/workflows/build-and-test.yml

More recent GA environments have broken the ability to run the win64 build's unit tests via Wine. Disable for now.

[GA] Disable Unit tests for win64 build in GA

---

.github/workflows/build-and-test.yml
test/functional/wallet_multiwallet.py

Bump our native macOS GA runner to macOS 11 (as 10.15 is now deprecated and will cease to function in December), as well as enable unit and functional tests for our native macOS runner, and fix an issue with Boost 1.78+ compatibility for the multiwallet functional test.
Last commit inspired by https://github.com/bitcoin/bitcoin/pull/24104
> Lastly, fs::create_directories now has an error message saying create_directories instead of create_directory. This caused wallet_multiwallet.py to fail. The error message check has been updated to be able accept either string.

[GA] Run unit/functional tests on native macOS 11

---

test/functional/feature_block.py
test/functional/mining_pos_coldStaking.py
test/functional/mining_pos_fakestake.py
test/functional/test_framework/key.py
test/functional/test_framework/messages.py
test/functional/test_framework/script.py
test/functional/test_framework/test_framework.py

This removes the dependency on OpenSSL for our functional regression
test suite by using a native python secp256k1 implementation.
Coming from https://github.com/bitcoin/bitcoin/pull/15826

[Tests] Native secp256k1 for functional tests

---

src/budget/budgetproposal.cpp
src/budget/budgetproposal.h
src/qt/pivx/forms/createproposaldialog.ui
src/qt/pivx/governancemodel.cpp
src/utilstrencodings.cpp
src/utilstrencodings.h

Remove the hard input cap of the name/URL inputs in the proposal creation UI so that the underlaying validation methods can give visual feedback when input lengths are too long (prevents silent cut-offs when pasting a too-long string).
Sanitize both fields to ensure that no illegal characters are accepted, matching the RPC interface's functionality.
introduce a future-forward (not yet implemented) method of verifying name/url fields on the network level.

[GUI][BUG] Properly validate proposal creation Name/URL

---

src/budget/budgetmanager.cpp
src/chainparams.cpp
src/consensus/params.h
src/consensus/upgrades.cpp
src/masternode-payments.cpp
src/qt/transactionrecord.cpp
src/test/budget_tests.cpp
src/test/evo_deterministicmns_tests.cpp
src/validation.cpp
src/validation.h
src/version.h
test/functional/test_framework/test_framework.py
test/functional/tiertwo_dkg_errors.py

Adjust block rewards for staking, masternode and budget to change to new values when V5.5 upgrade block is reached.
Adds UPGRADE_V5.5 block height value to chainparams, currently set to placeholder values for mainnet and testnet.
Adds nNewMNBlockReward value to chainparams--note the planned refactoring to call Params().GetConsensus().nMNBlockReward directly would need to be rethought or wait until after change has taken effect since there are now two parameters which is selected in GetMasternodePayment.
Unit tests for these changes are still WIP.

[Consensus] New block rewards

---

src/qt/CMakeLists.txt

CMake has an internal function (`qt5_generate_moc`) that can be used to
forcibly generate a `.moc` file. Use that instead of the generic
`execute_process` function.
This fixes an issue on systems (fe, Arch Linux) where Qt's moc binary
are placed in a different location than debian based distros.

[Build][CMake] Use CMake internal instead of custom command for moc

---

.github/workflows/build-and-test.yml

GA's macOS image update has once again clobbered the llvm compiler environment variable, so we need to set an explicit version to be installed via homebrew.

[GA] Use explicit llvm version for macOS CMake build.

---

src/chainparams.cpp

Sets the 5.5 new rewards changeover block for testnet to 925056.

[Consensus] Set testnet new rewards height

---

src/masternode-payments.cpp
src/masternode-payments.h

use the requiredMasternodePayment of the new block 
in CMasternodeBlockPayees::IsTransactionValid [masternode-payments.cpp]

bugfix new block reward payment and verification

---

src/rpc/client.cpp

Spending with ```sendmany``` and ```include_delegated``` parameter, results in ```JSON value is not a boolean as expected``` error
```
./pivx-cli sendmany "" "{\"<address>\":1}" 1 "" true
error code: -1
error message:
JSON value is not a boolean as expected
``` 
```include_delegated``` is missing from vRPCConvertParams
```include_delegated``` was added to vRPCConvertParams
```
./pivx-cli sendmany "" "{\"<address>\":1}" 1 "" true
<transaction hash>
```
The transactions got added

add include_delegated to vRPCConvertParams

---

src/rpc/blockchain.cpp
src/rpc/client.cpp
src/rpc/server.cpp
test/functional/rpc_blockchain.py
test/functional/rpc_named_arguments.py

Changes the boolean 'verbose' parameter of the getblock rpc command to an integer.
Enables getblock output to include full transaction details.
Backported from Bitcoin v15
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md

rpc: Backport getblock verbosity

---

CMakeLists.txt
src/Makefile.am
src/rpc/blockchain.cpp
src/rpc/client.cpp
src/script/descriptor.cpp
src/script/descriptor.h
src/script/sign.cpp
src/script/sign.h
test/functional/rpc_scantxoutset.py
test/functional/test_runner.py

As I didn't like the idea of backporting partial functionality of an upstream feature I looked at how `scantxoutset` and descriptors where implemented in BitCoin Core. Thanks to @tecnovert in #2778 I was able to easily locate the introduction point of `scantxoutset` and descriptors into BitCoin Core. As there were only a few files involved I tried to backport the complete functionality from [BitCoin Core v0.17.2](https://github.com/bitcoin/bitcoin/tree/v0.17.2).
- added `script/descriptor.cpp` and `script/descriptor.h` from BitCoin Core
- removed non PIVX compatible code from `script/descriptor.cpp`
- changed `#include <util.h>` to `#include <util/system.h>`
- removed wpkh, wsh support
- added `scantxoutset` related code to `rpc/blockchain.cpp` and `rpc/client.cpp`
- made some minor …

RPC: Backport scantxoutset from BitCoin Core v0.17.2

---

src/chainparams.cpp

Mainnet activation height set to 3672000

[Consensus] Set v5.5 activation height for mainnet

---

src/chainparams.cpp

Gives more time for users to update given the holiday season. Mainnet activation height set to 3715200

[Consensus] Bump v5.5 activation height for mainnet

---

.github/workflows/build-and-test.yml
CMakeLists.txt

Node 12 actions have been depreciated. Update actions to use Node 16 based versions.
Ref: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
`save-state` and `set-output` have been depreciated. Update GA workflow to no longer use these functions.
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Use shorter ccache cache identifiers
Use explicit CMAKE language launcher variable names

[GA] Update depreciated actions

---

Makefile.am
doc/Doxyfile.in

In-tree dependency libraries don't need to be included in Doxygen or Coverage reports, as doing so only adds extra "fluff" with no real purpose.

[Doc] Don't include dependency paths in Doxygen or Coverage

---

src/chainparams.cpp

Hard codes the correct block hash for the mainnet v5.5.0 superblock.
A network fork occurred at this block. The forked chain expected **NO** proposal payouts whatsoever, when there was clearly MN consensus for proposal payouts. It was clear that the forked chain that didn't want any proposal payouts was "in the wrong" here, so this PR hard codes the proper block hash of the first superblock of this particular round, which **does** include the expected proposal payouts.

[Consensus] Set v5.5.0 superblock checkpoint block hash.

---

src/wallet/wallet.cpp

The UTXO value of a stake split is sometimes smaller then the stake split threshold
The help description for `setstakesplitthreshold` states:
```
This will set the stake-split threshold value.
Whenever a successful stake is found, the stake amount is split across as many outputs 
(each with a value higher than the threshold) as possible.
```
So you would not expect the value of the UTXOs to be lower then the threshold value
This happens because the number of stake split outputs is calculated including the masternode payment
An example (for testnet) with a UTXO with a value of 9992 and the stake split threshold set to 500:
```
9992 + 10 (total block reward: 4 stake reward + 6 masternode payment) = 10002
10002 / 500 = 20.004
(int) 20.004 = 20
```
However the staker only receives the stake …

Wallet: Fix stake split output count calculation

---

src/rpc/mining.cpp

Build fails with configure flag "--enable-mining-rpc"
When attempting to build using the "--enable-mining-rpc" flag, the build fails.
- add include warnings.h
- change uint256 to arith_uint256
Build fails
```
CXX      rpc/libbitcoin_server_a-mining.o
rpc/mining.cpp: In function 'UniValue GetNetworkHashPS(int, int)':
rpc/mining.cpp:238:39: error: conversion from 'const base_uint<256>' to non-scalar type 'uint256' requested
uint256 workDiff = pb->nChainWork - pb0->nChainWork;
~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
rpc/mining.cpp:241:31: error: 'class uint256' has no member named 'getdouble'
return (int64_t)(workDiff.getdouble() / timeDiff);
^~~~~~~~~
rpc/mining.cpp: In function 'UniValue getmininginfo(const JSONRPCRequest&)':
rpc/mining.cpp:395:26: error: 'GetWarnings' was not declared in this …
```

[Build] Fix build with configure flag --enable-mining-rpc

---

src/httpserver.cpp

Added `#include <deque>` as it throws the error:
```
httpserver.cpp:74:10: error: 'deque' in namespace 'std' does not name a template type
74 |     std::deque<WorkItem*> queue;
|          ^~~~~
```

[Build] Update httpserver.cpp

---

.github/workflows/build-and-test.yml
CMakeLists.txt
src/bench/CMakeLists.txt
src/test/CMakeLists.txt

This is the final (for now) PR needed to fully update our GA workers/actions to non-deprecated versions.
Previous work was done in the following PRs:
#2787
#2807

[GA] Bump GA linux workers to Ubuntu 20.04

---

src/rpc/client.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h
test/functional/rpc_deprecated.py
test/functional/wallet_autocombine.py

AutoCombineDust has been bugged since an old PR see (https://github.com/PIVX-Project/PIVX/pull/953  https://github.com/PIVX-Project/PIVX/pull/518).
To make an example of what's happening let's consider for simplicity  nAutoCombineThreshold = 100 and let's say that the user has 2 UTXOs one of 90 PIVs and the other of 15 PIVs.
With the current code of AutoCombineDust we will therefore try to send a total of 90+15 = 105 PIVs to ourself, more precisely to avoid the "Insufficient funds" the primary output will contain only the 90% =94.5 PIVs and the remaining 10% = 10.5 PIVs is used to pay fees + sent as a change to ourself. As you can see we end up with two new UTXOs, which are still both smaller than the threshold. 
This process is iterated block by block until we end up with a single UTXO …

[Wallet] Fix AutoCombineDust and improve setautocombinethreshold

---

configure.ac

Systems that have OpenSSL 3.x installed cause the lib's openssl based tests to fail. We don't use OpenSSL in PIVX anymore, so these tests are not of much interest.
Ref: https://github.com/bitcoin/bitcoin/pull/23314

[Build] Disable libsep256k1's openssl tests

---

depends/packages/zlib.mk

zlib v1.2.11 is no longer available from official sources. Bump to latest available version (v1.2.13).

[Depends] Bump zlib to v1.2.13

---

src/.clang-format

Boolean values in clang-format are case-sensitive, this fixes a typo that resulted in an incorrect value.

[Tools] Fix case typo in .clang-format

---

test/functional/test_framework/ripemd160.py
test/functional/test_framework/script.py

OpenSSL 3.x removed support for ripemd160, which is what python's hashlib library was using to provide this feature. As such, systems that ship with or have otherwise installed OpenSSL 3.x (Ubuntu 22.04+ for example) will encounter functional test failures.
We only use hashlib in functional tests specifically for ripemd160, so can just replace the dependency with a native implementation of ripemd160.
Ref: https://github.com/bitcoin/bitcoin/pull/23716, https://github.com/bitcoin/bitcoin/issues/23710

[Tests] Replace hashlib.ripemd160 with native implementation

---

src/qt/pivx/governancemodel.cpp

The bug:
If you create a governance proposal from the GUI and close the wallet before the proposal has 5 confirmations, when you open again the wallet will partially recover and FAIL to relay the proposal.
Why this is happening:
Basically the `wtx->mapValue.find("proposal");` does not contain the hash of the 50 PIVs fee tx.
How I fixed:
I simply added manually the fee hash.
How to test:
Create a proposal close the wallet before the proposal has 5 confirmation, reopen the wallet and make sure that the proposal is relayed to the network when it reaches 5 confirmations

[GUI] Fix bug in proposal creation

---

test/functional/test_runner.py

Running the functional test suite script without any options was previously only running the BASE_SCRIPTS, leading to an under-representation of test coverage.

[Tests] Run tiertwo and sapling functional tests by default

---

src/bls/bls_worker.cpp

Partial backport of https://github.com/dashpay/dash/pull/5202
In term of trying to keep memory down, this is a potential bug where if the object was never entered into the queue it just starts to bloat the memory.

[Core] Solve BLS Memleak

---

contrib/macdeploy/macdeployqtplus

Modified backport of https://github.com/bitcoin/bitcoin/pull/22199.
Github Action's latest macOS 11 runner image has introduced a Qt plugin dylib issue that results in build failures for non-depends based builds (ref: https://github.com/PIVX-Project/PIVX/actions/runs/4610757401/jobs/8206287998). The particular dylib (`libwebp.dylib`) is one that PIVX doesn't use, but the `macdeploy` script was originally written in a way that newer plugins that weren't explicitly excluded were linked, even if not necessarily needed.
This PR changes the logic/process to instead only link explicitly defined needed plugins that PIVX Core directly uses. Depends based builds are unaffected by this change, as depends builds Qt as static libraries, which don't use Qt plugins.

[Build] Minor fixups and simplifications for macdeploy

---

.github/workflows/build-and-test.yml

Base re-organization work for our GitHub Actions flow.
- Removed syslibs from x64 linux depends builds. This was a holdover from when we were using Travis CI, which had a very restrictive job length.
- Split syslib-only builds out from depends builds. There is no reason to require depends cache to succeeded for syslib-only builds.
- syslib builds can benefit from enabling debug options.
- standardize job naming to NOT include the distro name. This will make future runner OS bumps easier as protected branches use the job name as the standard for job matching purposes.
This is a precursor to additional work that will add more GA jobs to the syslib-only section, which will further benefit from parallelization.
--------------------
Note to reviewers: Because this PR changes the names of jobs, …

[GA] Reorganize and optimize GA runner flow

---

src/blocksignature.cpp

I know that we are no longer POW but nevertheless mining in POW phase would no longer work since we are signing the block

[Core] Remove unused PoW block signing code

---

src/bench/bench_pivx.cpp
src/pivx-cli.cpp
src/pivx-tx.cpp
src/pivxd.cpp
src/qt/pivx.cpp
test/functional/feature_help.py

* `--help`, `--version` etc should exit with `0` i.e. no error ("not enough args" case should still trigger an error)
* error reading config file should exit with `1`
Ref: https://github.com/bitcoin/bitcoin/pull/9067, https://github.com/bitcoin/bitcoin/pull/9120, https://github.com/bitcoin/bitcoin/pull/13349

[Core] Unify binary exit codes

---

src/qt/transactionrecord.cpp

Solves #2838
With the current code we already show the memo for a self t->s transaction but not for a self s->s transaction. With this PR I fix that issue

[GUI] Show memo in self s->s txs

---

src/rpc/blockchain.cpp
src/rpc/budget.cpp
src/rpc/client.cpp
src/rpc/masternode.cpp
src/rpc/mining.cpp
src/rpc/misc.cpp
src/rpc/net.cpp
src/rpc/rawtransaction.cpp
src/rpc/rpcevo.cpp
src/rpc/rpcquorums.cpp
src/wallet/rpcwallet.cpp

We use a more human-friendly visual layout for RPC tables in our source code that doesn't play nicely with `clang-format`.
This does a sweep of whitespace cleanup in the various tables and adds guard macros so that `clang-format` will not try to automatically reformat the code layout.

[Misc] Cleanup whitespace and guard RPC tables from clang-format

---

src/chainparams.cpp

This is a newly setup DNS Seeder to help the PIVX network in peer discovery. Furszy’s old seeder is now defunct and not working, in order for everything not to fall onto @Fuzzbawls shoulders(and seeders), I have created another instance.

[Net] Add Liquid DNS Seeder for mainnet

---

src/qt/utilitydialog.cpp

Remove the `(64-bit)` from the pivx-qt help message.
Since removing the Windows 32-bit builds, it is no longer information that is often useful for troubleshooting. This never worked for other architectures than x86, and the only 32-bit x86 build left is the Linux one. Linux users tend to know what architecture they are using.
It also accidentally ends up in the pivx-qt manpage.
Ref: https://github.com/bitcoin/bitcoin/pull/17503

[Doc] Remove bitness from pivx-qt help message and manpage

---

src/qt/pivx/forms/proposalinfodialog.ui
src/qt/pivx/proposalinfodialog.cpp

Solves Issue #2792
A button is added to the proposal card screen to copy to clipboard the recievers address for any type of cehcking a user may want to do

[Qt] Adds copy button to proposal recipient address

---

src/qt/pivx/createproposaldialog.cpp
src/qt/pivx/createproposaldialog.h
src/qt/pivx/forms/createproposaldialog.ui

This adds a new button to page 2 of the proposal creation process and uses the proposal name from the first page to assign a label to the newly generated address.
This streamlines proposal creation process for users not wanting to re-use addresses and be able to start the process without realizing they may not have copied an address, after having say copied the short URL if they created one and can just continue forward.
As well as tagging the newly created address with the Proposal Name so its easy to find in the Receive tab.

[GUI] Proposal Generate Address

---

.github/workflows/build-and-test.yml
.github/workflows/pr-cache-cleanup.yml
CMakeLists.txt

Re-work the GA cache naming to be more straight forward and efficient overall. The previously attached timestamping was actually working against us, and leading to much wasted cache usage.
At the same time, this adds 4 additional jobs to test `ubuntu-latest` and `macos-latest` runners for both cmake and native autotools, which can help provide early detection of build issues on the newest runner OSes.
A new workflow is also added that will function as a "cache maintenance" workflow to delete PR branch caches when a PR is closed/merged. This is primarily a step to prevent us from exceeding the cache storage size limit and having more useful caches evicted needlessly.
Finally, the last commit is a macOS-latest only workaround to address a bug on Apple's end which was introduced in Xcode …

[GA] Overhaul GA caches

---

src/qt/pivx/send.cpp

Another trivial bug fix:  On creating a transaction with the GUI don't clear the Coin Control if the user presses the "Transparent" button when the transaction is already set on "Transparent" and same for "Shielded" (see the picture)

[Qt] Don't always clear coin control

---

src/qt/rpcconsole.cpp

For quite some time in the PIVX GUI we have the old UX for the peer list, and it has not been functional to ban peers using the context menu. 
See below:
Any amount of clicks, it will not ban said peer nor will it update the ban list. 
With this PR it is now working as intended again
Clicking ban node for X time, will automatically disconnect the peer and update the GUI/ban list
Changes:
We now track the nodes address in the NodeStats class, and so now we do not need to resolve the IP but rather pull it from the stats we have access to after syncing the information from the node.

[GUI] Fix ban actions in peer list

---

src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h

This PR solves issue #2159 
The Lock functionality has been extended to tree mode view
(See the picture)

[Bug] Fix toggle lock button

---

src/addrman.cpp

This PR actually opens up our need for some more fuzzing and testing to integrate while catching up to various Bitcoin improvements. 
It is a partial back port of #22974 , reasons being we have to isolate more of the fuzz integrations so we can add them into the code base. Although this provides an improvement of over a factor of 100 for the population of the addrman 'good' peers because we iterate the table twice in order to accomplish this.
First loop is modified because in MakeTried() we can speed this up by stopping it mainly at nRefCount == 0, any further it would absolutely hit an assert. And then we can also check from the bucket that it is originating from peer wise, giving us less buckets to check.
Second loop is removed because in Good_() we look for the entry but if it is not …

Increase performance of Good

---

src/qt/pivx/forms/masternodeswidget.ui
src/qt/pivx/masternodeswidget.cpp
src/qt/pivx/masternodeswidget.h
src/qt/pivx/mnmodel.cpp
src/qt/pivx/mnmodel.h
src/qt/pivx/pivxgui.cpp

This PR add a Coin contol interface for masternode creation. This addition is particularly useful when a user wants to spend a P2CS delegation (or locked coins) to create a masternode.
Solves issues #1608 and #2498

[Qt] CoinControl for masternodes

---

src/net.h
src/net_processing.cpp
src/net_processing.h
src/rpc/net.cpp
test/functional/p2p_addr_relay.py
test/functional/p2p_addrv2_relay.py
test/functional/p2p_invalid_messages.py
test/functional/test_runner.py

As of recent there was a release on https://www.halborn.com/blog/post/halborn-discovers-zero-day-impacting-dogecoin-and-280-networks
We want to address potential situation that can cause network instability and node attacks.
This PR back ports
https://github.com/bitcoin/bitcoin/pull/22387
https://github.com/bitcoin/bitcoin/pull/15617
This implements a token bucket for rate limiting addresses, allowing up to 1000 in one request. Getaddr requests are exempt from this rate limiting. Then we are also no longer going to relay to other nodes peers we have banned. Functional tests included.

[P2P] Rate limiting rumored address processing

---

src/net_processing.cpp

This PR offers some performance improvement when dealing with peers and networking. Rather than creating a map of every address being relayed and picking the top ones, we can just compute the top ones directly. This will save a good amount of the heavy computation and leave it to a quote artimethic
bitcoin#8690

Do not fully sort all nodes for addr relay

---

src/support/lockedpool.h
src/sync.h
src/util/string.h

PIVX no longer compiles on arch based distros due to missing header files.
This PR adds the necessary header files

Add header files

---

src/coincontrol.h
src/qt/pivx/send.cpp
src/qt/pivx/sendchangeaddressdialog.cpp
src/qt/pivx/sendchangeaddressdialog.h
src/sapling/sapling_operation.cpp

This PR extends the functionality of CoinControl change by adding shield addresses.
In particular: 
- In a transparent transaction user can select either a transparent or a sapling shield change
- In a shield transaction user can only use a shield address as change (to preserve privacy)
(NB: with transparent transaction I mean a transaction in which inputs are transparent and analogous definition for shield transaction) 
In addition this PR fixes #2245

[GUI] CoinControl Change

---

src/rpc/masternode.cpp

With some work being done in PIVX-Labs by @Duddino we noticed that the RPC's for decoding and creating master node broadcasts are in Pre-BIP 155 format or AddrV1 serialization.
In order for us to create support for Tor master nodes in MPW, we need these RPC's to be able to serialize a TorV3 address.
There's a few caveats for decoding that there may be other solutions provided by someone else, but for now since receiving the stream, we cannot tell if its PreBIP155 or not, so we unserialize by AddrV1 first and if it fails, we check and attempt AddrV2.

[RPC][MN] Serialize in ADDRV2 for TorV3 in RPC's

---

test/functional/feature_blockindexstats.py

The librustzcash update (PR #2870) made shield txs slightly increase in size, this led the functional test feature_blockindexstats.py to fail when the (random) generated fee is too low. With this PR I simply increase the minimum generated fee in order to avoid the issue.

[TEST] Fix random fee generation

---

src/evo/evonotificationinterface.cpp
src/llmq/quorums.cpp
src/llmq/quorums.h
src/llmq/quorums_connections.cpp
src/llmq/quorums_signing.cpp
src/llmq/quorums_utils.cpp
src/rpc/rpcquorums.cpp
test/functional/tiertwo_chainlocks.py
test/functional/tiertwo_signing_session.py

Cleanup and various optimizations for the quorum class in particular:
- Cleanup unused code/ function parameters
- Don't lock cs_main when it is not needed
- Huge speed up on the ScanQuorums function

[DMNs] Quorums optimizations

---

src/Makefile.am
src/llmq/quorums.cpp
src/llmq/quorums.h
src/llmq/quorums_blockprocessor.cpp
src/llmq/quorums_blockprocessor.h
src/llmq/quorums_utils.cpp
src/llmq/quorums_utils.h
src/unordered_lru_cache.h

A LRU cache is an (unordered) map where, once it is full, the least recently used element is removed. 
This PR adds a LRU cache that maps  `quorumHash` -> `bool` where `bool` is `true` iff the quorum has been mined on chain.
It is a big optimization compared to checking the database each time

[DMNs] Implement lru cache

---

src/rpc/blockchain.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/sapling/saplingscriptpubkeyman.h
src/wallet/wallet.cpp
test/functional/rpc_invalidateblock.py

Invalidateblock has not been working since sapling came out. This happens because the current maximum witness cache has a depth of only 100 blocks. With this PR I want to fix this issue by manually building the witness cache if the block has a depth bigger than the cache size.
Since this operation can become pretty lengthy, the RPC will just return error if your oldest sapling note is older than 1 month (43200 blocks behind the chain tip).
Note: After using invalidateblock the user might need to do
`-> debug ->wallet repair -> recover transactions `  in order to recover the correct balance. This is not a limit of this PR and you can test that it already happens with the current implementation of invalidateblock.
Anyways "recover transactions" also cleans the wallet GUI from "conflicted" …

[RPC] Fix Invalidateblock

---

src/dbwrapper.cpp
src/dbwrapper.h
src/evo/deterministicmns.h
src/evo/evodb.cpp
src/llmq/quorums_signing.cpp
src/primitives/transaction.h
src/test/dbwrapper_tests.cpp
src/txdb.cpp

This PR upgrades the `evoDB` and `llmqDB` serializer version to V2 in order to support TOR DMNs. In order to keep a potential backward compatibility all others databases (like spork, blocks...) kept the old V1 serializer.
The PR also also upgrades to V2 the way `extraPayload` in transaction is serialized  and the way keys of `mnUniquePropertyMap` are serialized

[DB] Upgrade evoDB and llmqDB to V2 serializer

---

.github/workflows/build-and-test.yml
CMakeLists.txt
src/bench/CMakeLists.txt
src/qt/CMakeLists.txt
src/test/CMakeLists.txt
test/functional/p2p_invalid_messages.py

Homebrew no longer supports pre-built (binary) packages on macOS 11.
Some binary packages remain (for now). This means that packages are
built from source instead, which causes a runner timeout to occur when
trying to build the Qt and ZMQ packages.
A secondary issue came up with the newer Boost 1.83 version supplied by
homebrew for all macOS versions that was causing build errors.
To work around this, I've re-worked the CI and CMake workflows to
not include Qt/ZMQ on macOS 11 runners, and also set a specific Boost
version (1.76) that is still binary compatible with macOS 11.
llvm 13 ships with macos 11 runners natively, but is still not working for our
CMake builds (we previously used Homebrew's `llvm@13` package, which is
also no longer available on macos 11 runners in binary format), so …

[GA] Fix macOS runs

---

doc/build-unix.md

In order to cut down on ppa clutter/size, I have setup a new ppa specifically for BerkeleyDB 4 independent from the pivxd/pivx-qt ppa repositories.
This new ppa repo will be the default place to install db4.8 dependencies moving forward for LTS versions of Ubuntu. It currently has package support for Xenial, Bionic, Focal, Jammy, and the upcoming Noble LTS versions.
New CPU architecture riscv64 has been added for OS versions starting from Focal and newer.

[Doc] Update Ubuntu ppa source for db4.8

---

.github/workflows/build-and-test.yml
.github/workflows/pr-cache-cleanup.yml

GA has recently deprecated node16 version actions and has started issuing warning messages on action summaries. Simple update to newer node20 versions.

[GA] Update actions to node20 versions

---

.github/workflows/build-and-test.yml

GA's macos-11 runner images have been inconsistent in their inclusion of
a pre-installed version of the Boost library, and trying to gracefully
unlink a non-existent package results in an error.
Skip the unlink step and just force overwrite linking boost 1.76.

[GA] Link Boost 1.76 regardless of pre-existing version

---

src/validation.cpp
src/version.h
test/functional/test_framework/messages.py

As we integrate new Exchange Addresses into our system, its crucial to ensure compatibility and prevent potential conflicts arising from the new address prefix. So we are updating the protocol version to eliminate any compatibility issues or potentials to fork.

[Core] Bump Protocol Version to 70927

---

src/chainparams.cpp

This will restore the Mainnet prefix to `EXM` from the current `EX` setting that is returning `44` in production.

Restore Mainnet 'EXM' Prefix

---

src/qt/transactionrecord.cpp

Memos return Nullopt instead of empty string when empty.

Fix optional memo not being checked

---

.github/workflows/build-and-test.yml
CMakeLists.txt
doc/build-osx.md

Homebrew recently removed the legacy symlinks for the `qt5` package and is now only using the versioned `qt@5` naming. Adjust accordingly.

[GA] Use new versioned qt@5 homebrew package name

---

test/functional/p2p_invalid_messages.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py
test/functional/test_framework/util.py

The aim of this PR is making functional test run faster
First commit:
Sleeping inside `wait_for_rpc_connection`  is useless since in case of failure it will try again rather than throwing error.
Second commit:
profiling showed that waiting for all nodes to connect to each other was very slow (`8` nodes took about ~`32` seconds on my PC). If we connect them in parallel time is much faster ( more or less `4` seconds on my PC)
Third commit:
sleeping inside `is_node_stopped` is useless since it is always used in operations like `wait_until_stopped`, and in case a node is not stopped it will wait and try again rather than throwing error.
Fourth commit:
removed many other big `time.sleep()` that made everything go overall much slower. This is the only commit that I'm not 100% sure so if we see …

[Test] Speed up functional tests

---

src/wallet/wallet.cpp

Fix the data race in which a thread is trying to write `pcoinsTip.cacheSaplingAnchors`:
`CWallet::BlockConnected -> pcoinsTip->GetSaplingAnchorAt(...)`
At the same time another thread is trying to read `pcoinsTip.cacheSaplingAnchors`:
`ActivateBestChain -> FlushStateToDisk -> pcoinsTip->DynamicMemoryUsage()`.
The fix is trivial `CWallet::BlockConnected` was not locking the mutex `cs_main` that guards `pcoinsTip`.
This data race was causing the functional test `wallet_basic.py` to randomly fail: To see this I created two test branches where I ran `wallet_basic.py` 50 times in parallel. One branch has this fix the other doesn't.
The github action for the branch without this fix failed many times
https://github.com/panleone/PIVX/actions/runs/8428460478
The github action for the branch with …

[Bug] Fix data race

---

test/functional/test_framework/test_framework.py
test/functional/tiertwo_governance_sync_basic.py

`tiertwo_governance_sync_basic` is by far the slowest test that we have. Profiling showed that most of the time was spent in the function stake() which slept for a total of 2 seconds in each call.
Those 2 seconds sleep were actually useless and have been removed.
With this simple change the total running time of the test on my machine dropped from `15` minutes to only `6` minutes.
To prove that indeed sleeping was useless I tried to run the same test in parallel 15 times, and it never failed, see here:
https://github.com/panleone/PIVX/actions/runs/8420343441

[Test] speed un tiertwo_governance_sync_basic

---

src/init.cpp
src/llmq/quorums_chainlocks.cpp
src/llmq/quorums_chainlocks.h
src/llmq/quorums_init.cpp
src/llmq/quorums_init.h
src/llmq/quorums_signing.cpp
src/llmq/quorums_signing.h
src/llmq/quorums_signing_shares.cpp
src/llmq/quorums_signing_shares.h
src/test/test_pivx.cpp
src/tiertwo/init.cpp
src/tiertwo/init.h

Fix some issues in the LLMQ threads handling, that might be also causing some problems in some tests that randomly fail during the final `ShutDown()` phase. 
First 3 commits are just trivial refactor:
Use unique pointers in place of normal pointers to be consistent with the style used for other llmq managers.
Fourth commit:
In `CSigSharesManager` the function `StopWorkerThread()` was being called twice. The wrong call was the one in the destructor which has been removed.
The rest of the diff is basically a copy and paste from [net_masternodes.cpp](https://github.com/PIVX-Project/PIVX/blob/master/src/tiertwo/net_masternodes.cpp) (the variable `interruptNet` of that file plays the exact same role of the variable `interruptSigningShare` that I have added). 
This new version should be the …

[LLMQ] Improve thread handling 

---

src/httpserver.cpp
src/init.cpp
src/rpc/client.cpp
src/rpc/server.cpp
test/functional/feature_shutdown.py
test/functional/test_framework/test_framework.py
test/functional/test_framework/test_node.py
test/functional/test_runner.py

The aim of this PR is fixing the functional test errors that we get sometimes during shutdown, for example the failure of this action  https://github.com/PIVX-Project/PIVX/actions/runs/8429115630/job/23082877380
In a few words, on HTTP server shutdown, sometimes 2 seconds are not enough time to finish handling all the RPC requests.
`2024-03-26T01:35:26Z HTTP event loop did not exit within allotted time, sending loopbreak`
So after this point all existing RPC requests (in particular the `stop()` one) does not receive any answer...  And this lead to functional tests failing at the end.
For more info see the discussion in each backported PR.
Backport bitcoin PRs #11006 #14670 #14993 #14413

[Http] [Test]  Fix test failures on shutdown

---

src/net_processing.cpp
src/validation.h
src/wallet/wallet.cpp
src/wallet/wallet.h

First commit is a small refactor:  the global variable `nTimeBestReceived` is now a private member of the `CWallet` class, as it was used only there.
Second commit: fix the following data race by making `nTimeBestReceived` atomic
```
WARNING: ThreadSanitizer: data race (pid=18270)
Write of size 8 at 0x7b6800000ed8 by thread T16:
#0 CWallet::UpdatedBlockTip(CBlockIndex const*, CBlockIndex const*, bool) wallet/wallet.cpp:2094 (pivxd+0x5058c9)
#1 void std::__invoke_impl<void, void (CValidationInterface::*&)(CBlockIndex const*, CBlockIndex const*, bool), CValidationInterface*&, CBlockIndex const*, CBlockIndex const*, bool>(std::__invoke_memfun_deref, void (CValidationInterface::*&)(CBlockIndex const*, CBlockIndex const*, bool), CValidationInterface*&, CBlockIndex const*&&, CBlockIndex …
```

[Bug] Fix wallet data race

---

src/miner.cpp
src/rpc/mining.cpp
src/test/miner_tests.cpp
src/test/mnpayments_tests.cpp
src/test/util/blocksutil.cpp
src/test/validation_block_tests.cpp
src/test/validation_tests.cpp
src/util/blockstatecatcher.h
src/validation.cpp
src/validationinterface.cpp
src/validationinterface.h
src/wallet/test/pos_validations_tests.cpp

first commit:
Partially backport bitcoin PR https://github.com/bitcoin/bitcoin/pull/18338 which introduce the functions
`RegisterSharedValidationInterface` and `UnregisterSharedValidationInterface`.  See that PR why using normal pointers is problematic, and how `shared_ptr` solve the issue
(In a few words the problem is that it can happen that the pointed memory is freed before all signals have been processed, while with shared pointer we are sure that  memory will be freed after the last signal is handled)
second commit:
Utilize the new functions to the validation interface `BlockStateCatcher`.  In order to keep everywhere the logic unchanged (Registering on creation and Unregistering when the object goes out of scope) I created the wrapper class `BlockStateCatcherWrapper` which contains …

[Bug] Fix validation interface data race

---

.github/workflows/build-and-test.yml

Latest batch of GA runner images have introduced some more minor bugs that were preventing builds from finishing.
first two commits address the halting bugs, second two are a semi-related optimization.

[GA] Fix minor issues with latest GA runner images

---

src/budget/budgetmanager.cpp

When the wallet is configured for budget submission, an issue arises where the keypool gets exhausted when the wallet is locked, causing a crash. This prevents such behavior.

[Bug] Exit early for budget submission when the wallet is locked

---

src/llmq/quorums_signing.cpp
src/llmq/quorums_signing.h
src/llmq/quorums_signing_shares.cpp
src/llmq/quorums_signing_shares.h
src/netmessagemaker.h

Backport dash PRs (in the following order):
dashpay#2640
dashpay#2672
dashpay#2674
dashpay#2702
dashpay#2705
dashpay#2706
dashpay#2707
NB: Some or them are partial backports since most of our llmq files are already updated to a more recent upstream version. So I basically ended up picking the commits that touch only the files `quorums_signing_shares.*` and `quorums_signing.*`
I suggest to review by checking each individual commit against the corresponding upstream one

Dash llmq backports

---

src/qt/addresstablemodel.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

first commit: filter sapling credit/debit only when the appropriate flag has been set in the filter
second commit: in the qt wallet don't generate shield addresses that have already been used

[Wallet] Some sapling wallet improvements

---

.github/workflows/build-and-test.yml
build-aux/m4/bitcoin_qt.m4
src/qt/notificator.cpp

GA updated the version of XCode used for their macos-14 runners to a version that has known compatibility issues. For now, we can get around this by pinning the XCode version the runner's environment uses.
Semi-related: included a commit to remove un-used macOS framework libs (ref: https://github.com/bitcoin/bitcoin/pull/20496)
And lastly, while finalizing this PR, GA's apt cache decided to go out of sync, so now force an apt update prior to package installation.

[GA] Resolve latest macos-14 runner build failures

---

src/mapport.cpp

See: https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f
The return value of 2 now indicates:
"A valid connected IGD has been found but its IP address is reserved (non routable)"
We continue to ignore any return value other than 1.
---
Upstream: https://github.com/bitcoin/bitcoin/pull/30283

[Net]: Add compatibility for miniupnpc 2.2.8

---

src/activemasternode.cpp
src/budget/budgetmanager.cpp
src/init.cpp
src/kernel.cpp
src/llmq/quorums.cpp
src/llmq/quorums_signing_shares.cpp
src/masternode-payments.cpp
src/miner.cpp
src/net.cpp
src/primitives/block.cpp
src/qt/pivx/governancemodel.cpp
src/sapling/crypter_sapling.cpp
src/sapling/saplingscriptpubkeyman.cpp
src/tiertwo/init.cpp
src/timedata.cpp
src/txmempool.cpp
src/validation.cpp
src/wallet/wallet.cpp
src/zpiv/zpos.cpp
test/lint/lint-logs.sh

Ensure that every Logprint(f) call is properly terminated with a newline (`\n`). Not doing this leads to conjoined lines in the log output, which should not happen. There are few instances where an unterminated call is intentional (ie, inside a for loop, with a final call at the end of the loop)
Multi-line calls and daisy-chained calls can use a descriptor comment at the end of the code line (`/* Continued */`) to denote the log line is continued afterwards.
To prevent future instances of un-terminated log lines, add a linter specifically to check for this.

[Cleanup] Properly terminate printed log lines

---

src/llmq/quorums_chainlocks.cpp
src/llmq/quorums_init.cpp
src/llmq/quorums_signing.cpp
src/llmq/quorums_signing.h
src/llmq/quorums_signing_shares.cpp
src/llmq/quorums_signing_shares.h
src/protocol.cpp
src/protocol.h
src/tiertwo_networksync.cpp

Follow up of #2921
each commit backports a PR. you can find the number of the PR in the commit description

More Dash llmq backports

---

.github/workflows/build-and-test.yml

GA had deprecated `macos-12` runners and will be removing them in December.
This migrates our current `macos-12` runners to use `macos-13`.
The second commit is added because due to GA removing support for python 3.9 and 3.10 in their macos arm64 based runners later this month due to a dependency mismatch with their packaging systems. We currently use arm64 based `macos-14` runners.

[GA] Bump standard macOS runners to macos-13

---

contrib/cmake/FindMiniupnp.cmake

Fixes a CMake warning regarding package naming mismatch. No functional change.

[CMake] Fix typo in FindMiniupnp.cmake

---

src/chainparams.cpp
src/consensus/params.h
src/evo/evonotificationinterface.cpp
src/llmq/quorums.cpp
src/llmq/quorums_chainlocks.cpp
src/llmq/quorums_chainlocks.h
src/llmq/quorums_init.h
src/llmq/quorums_signing.cpp
src/llmq/quorums_signing.h
src/llmq/quorums_signing_shares.cpp
src/llmq/quorums_signing_shares.h
src/net.cpp
src/net.h

each commit backports a different PR

Dash LLMQ backports part 4

---

src/llmq/quorums.cpp
src/llmq/quorums.h
src/llmq/quorums_chainlocks.cpp
src/llmq/quorums_chainlocks.h
src/llmq/quorums_connections.cpp
src/llmq/quorums_signing.cpp
src/llmq/quorums_signing.h
src/llmq/quorums_signing_shares.cpp
src/llmq/quorums_signing_shares.h
src/net.cpp
src/net.h
src/net_processing.cpp
src/protocol.cpp
src/protocol.h
src/rpc/blockchain.cpp
src/rpc/rpcquorums.cpp
src/tiertwo_networksync.cpp
src/version.h
test/functional/tiertwo_signing_session.py

as usual each commit backports a different PR

Dash LLMQ backports part 5

---

depends/packages/boost.mk

The jfrog.io repository is no more, and a new boost.io repository has been made in it's place.

[Depends] Update Boost source URL

---

params/install-params.sh

Adjusts the installl-params.sh script to be able to function from outside the direct path.

Make install-params script work when called from other dirs

---

.github/workflows/build-and-test.yml

GA recently pushed out a silent update to the version of CMake bundled into it's runner images that broke backwards compatibility.
This pins the version of CMake used in our workflow to maintain backwards compatibility and avoid future silent breaking changes made by GA's bundled cmake version.

[CI] Pin CMake version to 3.31.6

---

contrib/install_db4.sh

Looks like savannah deprecated the `git` subdomain in favor of `gitweb`, and curl doesn't follow DNS redirects. Additionally, their servers seem to be having stability issues.
Update the URLs to using a github gist instead.

[Tools] Fix urls to new config.guess/sub
