src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp
This is a rough PoC of user editable wallet themes. It only provides the technical infrastructure to allow user definable themes. The themes itself must be edited by hand.
**How to add a new theme to the Darknet wallet:**
- locate your darknet-qt's data folder (usually '.darknet' in your users home folder) and create a new folder "themes" there.
- get a copy of Darknets source from https://github.com/Darknet-Crypto/Darknet. Just click on the "Clone or download" button.
- copy Darknets resource folder ('Darknet/src/qt/res') into the "themes" folder you have create above, so you  have a folder '.darknet/themes/res' now
- rename this folder from 'res' to the name of your theme, e.g. 'MySexyTheme'
- edit the theme to your liking. Colors, fonts, location/size/width of most UI-elements can be …
=> [UI] Wallet User Editable Themes: (PoC)

.gitignore, src/main.cpp, src/masternode-budget.cpp, src/masternode-payments.cpp, src/masternode.cpp, src/masternode.h, src/masternodeman.cpp, src/obfuscation.cpp, src/rpcmasternode.cpp, src/swifttx.cpp
Fixes the pubkey as seen in masternode tab
=> Mn list fix

Makefile.am, contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx-signer.yml, contrib/gitian-descriptors/gitian-win.yml, src/Makefile.qt.include, src/compat/glibc_sanity.cpp, src/compat/glibcxx_compat.cpp, src/qt/darknet.cpp, src/qt/guiutil.cpp, src/qt/optionsdialog.cpp
All 3 operating systems should build fine now.
Pls test!
=> Fix Gitian build issues

src/main.cpp, src/main.h, src/masternode-budget.cpp, src/masternode-payments.cpp, src/miner.cpp, src/pow.cpp
- Testnet integrated into master-branch (kudos to @presstab for the base work) + some error fixes.
- Special code for testnet added to track down the current superblock issues.
=> Testnet integration into master-branch + probable superblock-issue-fix

src/qt/tradingdialog.cpp
Nasty bug which crashed only on OSX.
=> Bittrex trading memory corruption fix

src/masternode-payments.cpp, src/miner.cpp
=> Stake debug

src/masternode.cpp, src/masternode.h
It's actually part of my MN-syncing fix, but it doesn't hurt to have it now.
=> Typo fix for pubKeyMasternode

src/miner.cpp
We don't need this any more and we avoid forks of staking wallets while syncing.
=> Revert temporary staking workaround (we have enough masternodes now)

configure.ac, contrib/macdeploy/fancy.plist
Followup to #53 
Natively compiling on OS X needed some special hand-holding to generate the background image properly. ;)
=> Fix OS X Native deploy target

configure.ac, contrib/devtools/split-debug.sh.in
The linux gitian target uses the included split-debug.sh script to generate two sets of tarballs for each host, one containing debug symbols and one without.
=> Add missing split-debug script for gitian builds

.travis.yml
- NO_WALLET builds aren't working right now, so lets not test that
scenario at all.
- Use OS X 10.11 SDK
- Disable CHECK_DOC and USE_TESTS for now
=> Update the .travis.yml file

src/qt/bitcoingui.cpp
Having the block explorer menu items associated with the "Trade"
menu didn't make much sense to me, so I've relocated it to the
"Tools" menu.
Also adjusted positioning in the dock/tray icon menu to match.
fixes #61
=> Reposition the Block Explorer menu items

src/qt/transactionview.cpp
The two mentioned transaction types already existed, but there was no
option of selecting them as a filter in the UI dropdown.
resolves #46
=> Add "Minted" and "Masternode Reward" to TX list filter

.travis.yml, depends/packages/packages.mk, depends/packages/qt.mk, depends/patches/qt/aarch32-qmake.conf
aarch32 (aka armv7) build targets now also build a Qt wallet binary by default, allowing the GUI client to be included with gitian release builds.
=> Enable aarch32 Qt builds

src/init.cpp, src/walletdb.cpp
For older versions of Boost, which tend to be linked differently, use std::ifstream and std::ofstream to backup the wallet file instead of using boost copy_file which produces compile errors https://github.com/PIVX-Project/PIVX/issues/65
=> Do not use boost copy_file if Boost < 1.58

src/main.cpp
#70 is primarily caused by unguarded function calls with NULL variables for reindexing (ie, we don't have a peer to request a previous block from nor do we have a previous block hash for the genesis block)
This adds two simple guarding conditionals in CheckWork() and ProcessNewBlock() to take into account these special circumstances.
Fixes #70
=> Protect block processing against reindexing

src/chain.h, src/chainparams.cpp, src/chainparams.h, src/kernel.cpp, src/main.cpp
This addresses https://github.com/PIVX-Project/PIVX/issues/51 in which CBlockIndex is improperly downcast to CBlockHeader upon construction. This lead to some issues downstream, such as the blockindex being considered to be PoW for part of its life. 
Note that Block Header syncing is not currently part of pivx, because it is incompatible with PoS unless we make some heavy modifications. Some of this code touched headers syncing code, which needed to be changed in order for this to compile. I added HeadersFirstSyncingActive() to Params().
=> refactor CBlockIndex constructor

src/qt/transactionfilterproxy.h
Needs thorough testing with wallets that have a wide range of existing transaction types.
fixes #78
=> Include SendToSelf in COMMON_TYPES Tx filter

src/qt/transactionrecord.cpp
CoinStake transactions were inconsistently being marked as watch only
in the Recent Transactions list. Added some more logic to
decomposeTransaction() to make the results more consistant.
fixes #77
=> Refactor decomposeTransaction()

src/init.cpp, src/main.cpp
When the client is not properly shutdown it can cause the database to get into a state where a block and index have been written to disk, but the corresponding metadata has not been written to disk. This adds various assertions and attempts to correct the faulty state when the client is initialized. This addresses https://github.com/PIVX-Project/PIVX/issues/69
=> Fix the major block corruption issues

src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/masternodelist.cpp
**Summary**: Fixes #92 
**Details:**
1.  The Masternodes tab in the qt wallet had a small bug where
the "Active" time listed for each node was being sorted by
the string value of the human friendly elapsed time which
typically reads DDd:HHh:MMh:SSs versus the harder to read
XYZWABCD seconds.  However the QTableWidgetItem was blindly
sorting this list by it's textual representation.
2.  This change adds a simple subclass of QTableWidgetItem that
is specifically used for DHMS-type time specifications which
require ordering.  The subclass is constructed with the elapsed
time, and sets the appropriate human friendly text.  It then
stores the time as an elapsed amount of seconds and uses that
for the overloaded < operator (sort et al).
=> [QT Wallet] Correctly sort by "Active" duration in mn tab

src/qt/overviewpage.cpp, src/qt/transactionview.cpp
Conflicted transactions can get stuck at the top of the transaction
table views when sorting by Status (confirmations), this fixes that.
Fixes #111
=> [Qt] Sort transactions by date

src/crypto/scrypt.cpp
FreeBSD declares be32enc natively, causing a build error when attempting
to declare it again.
This PR explicitely excludes FreeBSD from the in-tree declaration
and instead uses the system declaration.
Fixes #73
=> [Build] Don't (re)delcare be32enc on FreeBSD

src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/qt/transactionrecord.h
The trailing output-index can lead to cases where the user can't
look-up the transaction ID with  various systems.
The context menu item to copy the transaction ID will also only put the transaction hash into the user's clipboard with this change.
Before:
After:
=> [Qt] remove trailing output-index from transaction-id

build-aux/m4/bitcoin_qt.m4, configure.ac, src/Makefile.qt.include, src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/walletframe.cpp, src/qt/walletframe.h, src/qt/walletview.cpp, src/qt/walletview.h
Since Qt versions prior to Qt5 do not include the QJson* classes, we need to conditionally enable/disable the trading ui feature.
This wraps the feature around a new conditional that is set when the build system detects/uses Qt5.
- Qt4 builds are now possible as a result, though they don't have the trading ui enabled.
- Qt5 builds see no change in result.
- New output line in `configure` to tell user if the trading dialog will be enabled.
I've also changed the default version of Qt to search for, bumping it up to Qt5 to be in-line with what TravisCI and Depends/Gitian use.
fixes #93
=> [Build] Enable Trading UI only when Qt5 is used

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md
The included `ISSUE_TEMPLATE.md` file will be inserted into any new issue creations for users to have as a guideline when creating issue reports.
The included `CONTRIBUTING.md` is also used by GitHub's web UI and offers some more detail about the contribution process.
=> [Docs] Add GitHub Issue template and Contributor guidelines

src/rpcmisc.cpp, src/rpcserver.cpp, src/rpcserver.h
`getstakingstatus` method allows for a user to check the conditions
for activating staking. These are the same conditions used in
`miner.cpp`. Any check that returns false will prevent the staking
thread from creating new blocks.
This will (hopefully) provide an easier support path for those having
difficulty getting staking to activate.
=> [RPC] Add `getstakingstatus` method

src/rpcwallet.cpp
Currently you can dump private keys and perform other wallet actions that should be forbidden if the wallet is unlocked for anonymization only/staking only.
This is a big security risk for active stakers.
=> [RPC] Require password when using UnlockAnonymizeOnly

src/qt/forms/addressbookpage.ui, src/qt/forms/masternodelist.ui, src/qt/forms/receivecoinsdialog.ui, src/qt/forms/tradingdialog.ui, src/qt/guiconstants.h, src/qt/overviewpage.cpp, src/qt/receiverequestdialog.cpp, src/qt/res/css/default.css, src/qt/transactiontablemodel.cpp
Fixes https://github.com/PIVX-Project/PIVX/issues/114
Specifically:
* Defines text color individually for each QTableWidget instance other
than transactions history, to avoid overriding conditional formatting
applied in TransactionTableModel::data.
* Always return a QColor instance from TransactionTableModel::data,
even if no conditional formatting is applied. This is necessary since
we cannot define a text color for this element in CSS without
overriding any conditional formatting applied here.
* Fixes erroneous CSS comments using invalid hash mark (#) syntax. This
was preventing a number of existing style defintions from working.
* Changes COLOR_BLACK constant definition to rgb(51, 51, 51).
* Replace usages of QPalette::Text in overviewpage.cpp with COLOR_BLACK.
* Defines hyperlink text …
=> [Qt] Adds base CSS styles for various elements, to prevent bleed-through of system color theme.

src/activemasternode.cpp, src/masternodeconfig.cpp, src/masternodeconfig.h, src/qt/masternodelist.cpp, src/rpcmasternode.cpp, src/util.cpp, src/wallet.cpp
CWE-190: Integer Overflow or Wrap around https://cwe.mitre.org/data/definitions/190.html
example from FlawFinder:
`
../pivx/src/activemasternode.cpp:375:  [2] (integer) atoi:
Unless checked, the resulting number can exceed the expected range
(CWE-190). If source untrusted, check both minimum and maximum, even if the
input had no minus sign (large numbers can roll over into negative number;
consider saving to an unsigned value if that is intended).
../pivx/src/activemasternode.cpp:442:  [2] (integer) atoi:
Unless checked, the resulting number can exceed the expected range
(CWE-190). If source untrusted, check both minimum and maximum, even if the
input had no minus sign (large numbers can roll over into negative number;
consider saving to an unsigned value if that is intended).
`
Using …
=> [Wallet] Reduce usage of atoi to comply with CWE-190

src/main.cpp
This addresses https://github.com/PIVX-Project/PIVX/issues/106
=> [Wallet] Look at last CoinsView block for corruption fix process

src/qt/paymentserver.cpp, src/qt/paymentserver.h
- Correctly manage the X509 and X509_STORE objects lifetime.
=> qt: Avoid OpenSSL certstore-related memory leak

src/main.cpp
The genesis block has no prevhash, and no pindexPrev (which CheckWork
uses heavily), and doesn't require it's work being checked.
fixes #153
=> [Consensus] Don't pass the genesis block through CheckWork

src/chainparams.cpp
…gits
To send an alert requires both the private key and recompiling pivxd with additional code.
This effectively disables the private key by basing the public key on the old key with a few digits set to zero.
Later we will remove the complete mechanism, but this should be sufficient to prevent anyone from using the current mechanism
=> [P2P] Change alert key to effectively disable it

contrib/init/pivxd.service
With no stop command defined `systemctl stop pivxd` will send SIGTERM
which can cause database corruption. With this change `pivx-cli stop`
will be used to stop the daemon process gracefully.
=> [Utils] Add ExecStop= to example systemd service

src/rpcwallet.cpp
This is a proposal from a friend for the use-case _"want to unlock a remote daemon for staking AND have an encrypted wallet.dat in case it gets stolen"_.
Makes sense IMO.
If you do a `pivx-cli walletpassphrase <your_passphrase> 0` the wallet/daemon gets unlock until the end of times or until it crashes, whatever comes first .
=> [RPC] Allow infinite unlock

src/init.cpp
=> [Wallet] Add parameter interaction between -disablewallet and -staking

.gitignore, src/masternode-budget.cpp, src/rpcmasternode-budget.cpp
So far when a proposal was removed from the proposal list the reason was logged, but not the name of the proposal itself. Proposal name is now logged as well.
'IsValidReason' was also added to 'mnbudget getinfo' output to make it a bit more verbose.
(...the update of .gitignore is not related to this PR, but needed...)
=> [RPC] Add proposal name to removal log

src/rpcclient.cpp, src/rpcmasternode-budget.cpp
For whatever reasons `vote-alias` was in the RPC help for quite some time, but never implemented.
Please test.
=> [RPC] Add missing 'vote-alias' implementation

src/main.cpp
Old text was _"do not use for mining or ..."_
Mining is sooo 2016....
=> [Trivial] Pre-release warning message fixed.

.travis.yml, contrib/devtools/README.md, contrib/devtools/check-doc.py, src/init.cpp, src/pivx-cli.cpp, src/pivx-tx.cpp, src/qt/forms/helpmessagedialog.ui, src/qt/guiconstants.h, src/qt/intro.h, src/qt/utilitydialog.cpp, src/util.cpp, src/util.h
Help messages are formatted programmatically with FormatParagraph
in order not to break existing strings in Transifex.
The new format works even if the translation of the strings
modifies the length of the message.
I've also included here the `check-doc.py` script to test coverage of command line arguments and run it through TravisCI.
*BEFORE:*
CLI: 
Qt: 
*AFTER:*
CLI: 
Qt: 
Most noticeable change is with the Qt help dialog, notice there is now no horizontal scroll bar.
=> [Output] Reformat help messages

src/qt/forms/rpcconsole.ui, src/qt/rpcconsole.cpp
Improve readability of the `rpcconsole.ui` form file by reordering
layout elements for the Information and Wallet Repair tabs. Also
convert the Wallet Repair tab to a QGridLayout format similar to
how the Information tab is.
Benefit of using the QGridLayout is that we no longer pass the
repair commands in the description string to Transifex, which we
shouldn't have been doing anyways.
Before: 
After:
=> [Qt] Refactor layout for rpcconsole UI

src/rpcmisc.cpp
The `getstakingstatus` RPC call showed everything BUT the staking-status.
That's fixed now:
=> [RPC] Add active/incative flag to getstakingstatus RPC call

src/qt/forms/masternodelist.ui, src/qt/masternodelist.cpp, src/qt/masternodelist.h
This information has little to no use cases as a GUI element. All
masternode information is still available via RPC for application
integrations.
Maintaining, and sorting, a list of thousands of masternodes simply
for the sake of non-digestible UI display is a waste of resources.
=> [Qt] Remove the All Masternodes UI tab/list

src/qt/intro.cpp, src/qt/intro.h, src/qt/pivx.cpp
When running pivx-qt with the `-help` flag, the intended operation
is to output the help contents then exit cleanly. However, this is
currently resulting in a segfault due to the return status of a
method in intro.
This Fixes the segfaulting behavior and now cleanly exits after
displaying the help contents.
=> [Qt] Fix segfault when running with `-help`

src/qt/askpassphrasedialog.cpp, src/qt/askpassphrasedialog.h, src/qt/sendcoinsdialog.cpp, src/qt/sendcoinsdialog.h, src/qt/walletmodel.cpp, src/qt/walletview.cpp, src/rpcwallet.cpp
This is a fix for https://github.com/PIVX-Project/PIVX/issues/181
Since this fix was more complex than expected I would appreciate tests by other users/devs.
Use cases I've covered:
**UI:**
- unlock for staking only, stake and send coins after complete unlock
- complete unlock, stake and send coins
**CLI:**
- unlock for staking with/without timeout and stake
- complete unlock with/without timeout, staking and send coins 
- complete unlock with/without timeout and start a masternode
Just comment here If I should have missed a use case.
=> [UI] Improved unlock usability

src/masternode-budget.cpp, src/masternode-payments.cpp, src/masternode-sync.cpp, src/masternode.cpp, src/masternodeman.cpp
This is a general re-classification and re-formatting of log messages
relating to masternode events. A number of messages have been put into
a specific debug category (instead of the general logging category),
and/or have had their output string reformatted to be more clear.
=> [Trivial] Reduce debug.log spam for masternode messages

src/init.cpp, src/main.h, src/net.cpp, src/protocol.cpp, src/protocol.h
As the title says:
- Bloom filter enabled by default.
- New nService for light clients added, NODE_BLOOM_WITHOUT_MN means that the node doesn't want to receive master nodes related messages (The amount of messages flood light client if it's not controlled and in some cases client doesn't need that information.)
=> [P2P] Enable Bloom filter and add new nService for light clients.

src/qt/guiutil.cpp
This prevents listing peers as supporting service(s) "UNKNOWN"
=> [Qt] Add "NODE_BLOOM" and "NODE_BLOOM_WITHOUT_MN" to guiutil

src/qt/rpcconsole.cpp, src/qt/rpcconsole.h, src/rpcserver.cpp, src/rpcserver.h
This adds autocomplete to command names for the GUI's debug console.
Sourced from bitcoin#7613 bitcoin#7772 and bitcoin#8129
=> [Qt] Add autocomplete to Qt client's debug console

src/init.cpp
This was missed earlier, the default is now stored in a constant
so we can use that instead of a hard true/false here.
=> [Output] Update default value for -peerbloomfilters in help

contrib/devtools/update-translations.py
Prior to this, strings coming in from transifex that had a `%` at the end would cause the script to error out.
=> [Utils] Fix update-translations.py to allow % at end of string

src/qt/pivx.cpp
This was missed in the bump to Qt 5.6 and should resolve issues
with window/text scaling on High DPI devices such as #228.
=> [Qt] Enable support for Qt's HighDpiScaling

contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx.yml, contrib/gitian-descriptors/gitian-win.yml
Now that 2.3 branch has been split off, bump gitian descriptor
versions to 3.0 preemptively to avoid having to rebuild caches
at the last minute.
=> [Gitian] bump version to 3.0

src/rpcmasternode.cpp
If a masternode isn't yet activated the current error message ("Masternode not found") confuses every masternode owner but one.
The error message now includes the status of the (not-yet-activated) masternode, in this case "Node just started, not yet activated".
=> [RPC] Make 'masternode status' more verbose

src/masternode.cpp
When a masternode can't be started with the error message _"Invalid IP address"_ it might help to include the IP in the error log.
The IP is only logged (in your own local `debug.log`) when you start your own masternode via `masternode start-alias` or `masternode start-all` and is not publicly visible or broadcasted.
=> [Debug Log] Increase verbosity of error-message when starting a masternode fails

src/main.cpp, src/masternode-budget.cpp, src/masternodeman.cpp
This fixes payment disagreements when the masternode count is very unstable, e.g. when a big masternode hosting provider has issues, or a possible DDoS attack.
=> [Consensus] fix payment disagreements, reduce log-verbosity

src/qt/masternodelist.cpp
Small correction to https://github.com/PIVX-Project/PIVX/pull/241
Not MISSING/EXPIRED masternodes are visible in the UI again.
Thanks @Fuzzbawls 👍
=> PR 241 correction

src/qt/guiutil.cpp, src/qt/paymentrequestplus.h
Mac/clang complains about LSSharedFileListItemResolve() being
depreciated during the build process, but it must be retained for
backwards compatibility. 
So selectively suppress these warnings and also
introduce the updated function call when applicable.
=> [Build] Selectively suppress depreciation warnings

src/chainparams.cpp
Add three additional hardened checkpoints.
- 791150: Block occured right around the time of the v2.3.0 mandatory
update deadline.
- 795000: Incremental checkpoint.
- 799000: Incremental checkpoint.
=> [Net] Update Checkpoints

src/qt/clientmodel.cpp, src/qt/forms/rpcconsole.ui
Line no longer displays the OBF compat / enabled count, but rather shows
the count of each network protocol (IPv4 / IPv6 / Tor).
Also makes the line contents selectable with the mouse :)
New layout:
=> [Qt] Adjust masternode count in information UI

contrib/gitian-build.sh
Even though aarch64 builds are technically linux, we want the sigs and
output to be in it's own path.
=> [Scripts] Fix location for aarch64 outputs in gitian-build.sh

src/qt/bitcoingui.cpp, src/rpcmasternode.cpp
=> [GUI/RPC] Changed bubblehelp text + RPC startmasternode help text fixed

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/walletframe.cpp, src/qt/walletframe.h, src/qt/walletmodel.cpp, src/qt/walletview.cpp, src/qt/walletview.h
This makes the lock icon a clickable button that will do the following:
- Bring up the AskPassphrase dialog when the wallet is locked
- Lock the wallet when the wallet is unlocked or unlocked for anon
Also fixes a pre-existing issue where attempting to lock the wallet from
an unlocked for anon state didn't set the proper flag indicating this
change fully.
=> [Qt] Make lock icon clickable to toggle wallet lock state

src/miner.cpp, src/rpcmining.cpp
`auto_ptr` is deprecated, replace with `unique_ptr`.
=> [Minting] Replace deprecated auto_ptr.

src/qt/bitcoingui.cpp
The Privacy tab and the Transactions tab had swapped shortcuts and were
being created in reverse order to how they were being added to the UI's
menubar.
=> [Qt] Fix UI tab order and shortcuts

src/rpcdump.cpp
The previous ordering of parameters for `bip38decrypt` didn't make much logical sense, and also were inconsistent with the ordering from `bip38encrypt`.
=> [RPC] Change Parameter Order of bip38decrypt

src/bip38.cpp, src/bip38.h, src/qt/bip38tooldialog.cpp, src/rpcdump.cpp
Previously BIP38 tool was leaving the final 4 bytes of the encrypted key blank. These 4 bytes are where the base58 checksum is supposed to be inserted. Tools that check the base58 checksum of the encrypted key were finding the key invalid because of the blank checksum.
Also add an additional check for address compression.
=> Append BIP38 encrypted key with an 4 byte Base58 Checksum

src/main.cpp, src/main.h, src/rpcwallet.cpp, src/wallet.cpp
-Mempool has been rejecting zPiv spends as non standard.
-Fixed issue with incomplete spends being marked as spent in the zerocoinDB.
-Add more functionality to resetmintzerocoin, which allows for coins with the above issues to be restored.
=> [Wallet] Fix zPiv spending errors.

src/qt/walletmodel.cpp, src/rpcmisc.cpp, src/rpcwallet.cpp, src/wallet.cpp, src/wallet.h
Auto mint was not accounting for non-mature zPiv mints.
=> [Wallet] Count pending zPiv balance for automint.

src/qt/privacydialog.cpp, src/qt/privacydialog.h
Previously, pressing the `Esc` key while on the Privacy tab would
destroy the tab. This is due to the tab being a `QDialog` object that
naturally inherits this behavior.
Fix by ignoring the keyevent generated by the `Esc` key.
fixes #285
=> [Qt] Don't allow the Esc key to close the privacy tab

src/primitives/block.h
nAccumulatorCheckpoint added to the CBlockHeader copy.
=> Bad CBlockHeader copy.

src/qt/zpivcontroldialog.cpp
zPiv control no longer counts pending mints and top level denom rows when calculating amount and quantity selected
=> [Qt] zPiv control quantity/amount fixes

src/test/zerocoin_denomination_tests.cpp
warning: variable ‘set’ set but not used [-Wunused-but-set-variable]
zerocoin_denomination_tests.cpp:[89,168,247,343,443]:14: warning: variable ‘set’ set but not used [-Wunused-but-set-variable]
Signed-off-by: rejectedpromise <rejectedpromise@gmail.com>
=> [Cleanup] Remove unused variables

src/main.cpp
Reference: https://github.com/PIVX-Project/PIVX/issues/305
When investigating the issue above I found an upstream-change (https://github.com/dashpay/dash/blob/v0.12.2.x/src/net_processing.cpp#L839) which we should implement as well, even when this issue most probably was just a corrupt block-file, not a missing block.
=> [Core] Don't send not-validated blocks

src/kernel.cpp, src/main.cpp, src/miner.cpp
- Clear the mempool if CheckBlockValidity() fails.
- Add more verbose logging for errors of the same serial contained multiple times in one block.
- Make minting code iterate to the next block right when a new block is added to the chain.
=> [Minting] Clear mempool after invalid block from miner

src/chainparams.cpp
The new checkpoint at block `867733` didn't update the related
checkpoint data (timestamp and number of transactions), this corrects
that omission.
=> [Main] Update last checkpoint data

src/denomination_functions.cpp, src/denomination_functions.h, src/primitives/zerocoin.cpp, src/primitives/zerocoin.h, src/qt/forms/privacydialog.ui, src/qt/privacydialog.cpp, src/test/zerocoin_denomination_tests.cpp, src/wallet.cpp
This should give the user a better idea why a zPIV transaction failed.
Additional error in spending to local address (with empty 'Pay To' field) fixed.
New error message:
=> [UI] Better error message when too much inputs are used for spending zPIV

configure.ac
This adds a summary of compiler and linker flags, as well as information
about which features are enabled/disabled to the end of the configure
script.
Doesn't change any functionality, and is strictly informational.
Example Output:
```
Options used to compile and link:
with wallet   = yes
with gui / qt = yes
qt version  = 5
with qr     = yes
with zmq      = yes
with test     = yes
with upnp     = yes
debug enabled = no
target os     = darwin
build os      = darwin
CC            = /usr/local/bin/ccache gcc
CFLAGS        = -g -O2
CPPFLAGS      = -Qunused-arguments -I/usr/local/opt/openssl/include -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -I/usr/local/opt/berkeley-db@4/include -DMAC_OSX  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DHAVE_QT5
CXX           = …
```
=> [Build] Add compile/link summary to configure

src/init.cpp, src/qt/forms/rpcconsole.ui, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h
This option was requested by @s3v3nh4cks , so blame him if you don't like it :-)
When executed, this repair option restarts the wallet with the parameter `-resync` and will delete the folders `blocks`, `chainstate`, `sporks` and `zerocoin` and the wallet starts to synchronize from scratch.
This should help users to reinitialize their local blockchain-data into a consistent state without the need to explain where those folders are and which folders to delete.
It's also available as command line parameter `-resync` if the wallet-UI isn't usable for whatever reasons.
**Please(!) test this on OSX and Windows and report back (both positive and negative results)**
Since resync needs a lot of time and temporary missing funds might scare users I've added an appropriate warning:
=> [UI] Wallet repair option to resync from scratch

src/miner.cpp
When the miner detects the same zPiv serial already including in the block it is creating, it was not correctly continuing to the next transaction, and therefore was ultimately adding the tx to the block, which would later be rejected as invalid.
=> [Minting] Better filtering of zPiv serials in miner.

src/qt/zpivcontroldialog.cpp, src/wallet.cpp
Additionally the "Insufficient Funds" error message when minting zPIV was made more verbose so the user knows why he seems to have enough PIV for minting but can't.
=> [UI] zPIV-Control: disable negative confirmation numbers.

src/main.cpp
Since zPIV spends have no fee associated with them (fees are paid up
front during the minting process), the built in rate limiter for
zero-fee transactions was kicking in when it shouldn't have.
This change will allow zPIV spends in `AcceptToMemoryPool()` and
`AcceptableInputs()` to bypass the zero-fee rate limiter.
At the same time, also double the default number of bytes to allow per
minute before rate limiting. Previous default equated to 15000 bytes per
minute, new default is 30000 bytes per minute (exclusive of zPIV
spends).
=> [Main] Don't limit zPIV spends from getting into the mempool

src/qt/forms/overviewpage.ui, src/qt/forms/privacydialog.ui, src/qt/overviewpage.cpp, src/qt/overviewpage.h, src/qt/privacydialog.cpp, src/qt/privacydialog.h, src/qt/res/css/default.css, src/qt/sendcoinsdialog.cpp, src/qt/sendcoinsdialog.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/qt/walletview.cpp, src/wallet.cpp, src/wallet.h
Includes:
- fix of wrong/inconsistent display of balances
- tons of bubble-help to explain what's displayed to the end user
- include unconfirmed/immature/mature zPIV balances on the Overview-tab
- distinguish between unconfirmed and immature zPIV on Privacy-tab
- general usability improvements
Visuals:
Overview-Tab:
Privacy-Tab:
Please check spelling, grammar and lyrical virtue and report back...
=> [UI] Balance fix + bubble-help + usability improvements

src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/main.cpp, src/txdb.cpp, src/txdb.h
-Coin supply incorrectly was counting spent zPiv as newly minted coins that are added to the coin supply, thus resulting in innacurate coin supply data.
-CBlockIndex.vMintDenominationsInBlock was not being cleared before having mints added to it. This caused it to have a bad accounting of mint meta data if any blocks go through ConnectBlock() more than once.
-Reindex both aspects of all block indexes from zerocoin start block until chain tip. Trigger this indexing on first client start with new wallet, and track progress of reindexing in case wallet client is shutdown so that it will not lose its progress.
=> Reindex zPiv blocks and correct stats.

doc/build-osx.md, src/accumulators.cpp, src/init.cpp
Squashed version of #304. Original description follows:
This really amounts to a small, hacky fix for the reported problem. I feel a bit uncomfortable with the coupling between accumulators.cpp and init.cpp, so very much open to feedback in this category.
For the future, I propose implementing a task interface with a [heartbeat design pattern](https://www.codeproject.com/Articles/851944/The-Heartbeat-Pattern) that allows for more elegant, decoupled interruptions. This is possible + relatively easy with [Boost's threading API](http://www.boost.org/doc/libs/1_53_0/doc/html/thread/thread_management.html#thread.thread_management.tutorial.interruption).
=> [Main] PIVX not responding on user quitting app

doc/swifttx.md, src/init.cpp, src/main.cpp, src/qt/forms/sendcoinsdialog.ui, src/qt/pivxstrings.cpp, src/qt/sendcoinsdialog.cpp, src/qt/transactiondesc.cpp, src/qt/walletmodel.cpp, src/swifttx.cpp, src/swifttx.h, src/util.cpp, src/wallet.cpp
Fixes https://github.com/PIVX-Project/PIVX/issues/338 and the wrong name in general.
**Changed:**
- all texts
- debug categories refactored
- documentation
**NOT changed:**
- RPC commands (backward compatibility)
- filenames (swifttx.h and swifttx.cpp)
=> [UI] Rename SwiftTX -> SwiftX

src/Makefile.qt.include, src/coincontrol.h, src/keystore.cpp, src/keystore.h, src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/forms/coincontroldialog.ui, src/qt/forms/multisigdialog.ui, src/qt/multisigdialog.cpp, src/qt/multisigdialog.h, src/qt/walletframe.cpp, src/qt/walletframe.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/qt/walletview.cpp, src/qt/walletview.h, src/wallet.cpp, src/wallet.h, src/wallet_ismine.cpp, src/wallet_ismine.h, src/walletdb.cpp, src/walletdb.h
<h1>Multisignature GUI</h1>
<h4>Provides functionality which is currently only available through raw transactions. Multisignature addresses require signatures from multiple parties before coins belonging to the address are spent. Accessed through the File dropdown menu.</h4>
<h3>Address Creation</h3>
<ul>
<li>addresses allow up to 15 owners</li>
<li>from 1 to all owners may be configured as required to sign</li>
<li>with the provided redeem script, addresses can be imported by all owners after it has been created once</li>
</ul>
<h3>Spending</h3>
<ul>
<li>coin control</li>
<li>multi-destination spends</li>
<li>raw input entry option</li>
<li>automatic fees</li>
<li>automatic change return</li>
</ul>
<h3>Signing/Committing Transaction</h3>
<ul>
<li>one click signing of transactions</li> …
=> [Qt] Multisig GUI

src/Makefile.am, src/accumulatormap.cpp, src/accumulatormap.h, src/accumulators.cpp, src/accumulators.h, src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/main.cpp, src/miner.cpp, src/qt/forms/privacydialog.ui, src/qt/privacydialog.cpp, src/qt/zpivcontroldialog.cpp, src/test/zerocoin_implementation_tests.cpp, src/txdb.cpp, src/wallet.cpp, src/walletdb.cpp
This refactors the accumulator code. It removes the singleton structure that was used before and replaces it with a new class `AccumulatorMap` which is comprised of an accumulator for each zerocoin denomination.
This also reconfigures when `PublicCoin`'s are verified. Instead of having them verified everytime you pull them out of the blockchain, it is only necessary to verify them when they are being checked before being placed into the blockchain. Once it is in the chain, it is fair to assume it is valid. This saves a large amount of computation, by some tests it speeds up accumulator checkpointing by 5x.
=> [Main] Refactor Accumulator Code

src/qt/pivx.cpp
With this change, if a user tries to open on High Sierra from official gitian build, they'll see the following
However, could will let users on High Sierra still build and use as long as they are using Clang version 4 or higher
=> Gitian hack so gitian Mac builds notify user about incompatibility on High Sierra

src/chainparams.cpp
Makes testnet work with the new libzerocoin patch that was added.
=> [Testnet] Adjust testnet chainparams to new hard coded values.

src/script/script.cpp
https://github.com/PIVX-Project/PIVX/issues/363
There are no further op codes in zerocoinspends. When parsing through the data, the ToString() method often see's the zPiv spend data as an OP code. Since RPC getrawtransaction prints the hex of the CScript anyways, it is redundant to print all of the spend data in this to string and then again in the hex dump.
Before:
```
"vin" : [
{
"txid" : "0000000000000000000000000000000000000000000000000000000000000000",
"vout" : 4294967295,
"scriptSig" : {
"asm" : "OP_ZEROCOINSPEND 20776 000000ee19dc8cb8dc008d72c1cd6256efb534834f3e9e8f383a600ee753b6b65a820b8635e34b466f0e33477b6c37508870 OP_OVER OP_UNKNOWN OP_EQUAL 5feae073134555cc765f5e5566b8 OP_NOT 6d9f52375fc78ca85b4440c5e0f251316d1033d2aba5643d389b484f1232dac7976a OP_RIPEMD160 …
```
=> Do not stringify beyond OP_ZEROCOINSPEND for CScript::ToString()

src/accumulators.cpp
zPIV that were minted between block 891730 and 895400 experience an error initializing the accumulator witness data correctly.
=> Fix "accumulator does not verify" when spending zPIV.

share/genbuild.sh
This slightly changes the usage of git calls in genbuild.sh to get a better description of what is built during development / building. Rather than just always get 3.0.99-g8fa5f125e, you'll get something more descriptive such as '3.0.5.1-branchpoint-1-g8fa5f125e', where the '1' is the number of commits after the "3.0.5.1-branchpoint" tag. This also makes it easier to locate the commit in the git tree and compare to others who are using slightly different versions.
Since this is only using git calls from a shell script it should work on all of the same platforms as the current script.
As before, when we build from a tag for releases then you should simply get something like "v3.0.6" without the extra fields.
Finally I believe this tag/description just goes to the splash screen and for …
=> Change git info in genbuild.sh

src/wallet.cpp
`CWalletTx::GetAmounts` needs to check if a tx is a zerocoinmint, coinbase, and coinstake before it prints this warning to log `CWalletTx::GetAmounts: Unknown transaction type found, txid`.
=> Handle debug.log "CWalletTx::GetAmounts: Unknown transaction type" spam.

contrib/devtools/README.md, contrib/devtools/logprint-scanner.py
Script to identify errorneous LogPrint and LogPrintf calls (calls that do not have matching number of format specifiers and supplied arguments to the calls).
=> [Scripts] LogPrint(f) scanner script

src/wallet.cpp, src/wallet.h
It is possible for a spend of 7 to be larger than the max transaction size. Catch these cases and send a correct error report up the chain to the GUI.
=> Double check tx size when creating zPIV tx's.

src/rpcclient.cpp, src/rpcrawtransaction.cpp, src/rpcserver.cpp, src/rpcserver.h
Accepts transaction hash and input index as parameters and returns amount of spent zerocoin input (if input is not zerocoin spend, returns -1).
=> getspentzerocoinamount RPC call. 

src/main.cpp
There is no point in doing a "slow" search for a transaction if it isn't
found in the txindex (if enabled).
We run with txindex enabled by default, so this could see some performance increase in the form of faster response times when searching for a transaction that doesn't exist.
=> [Main] Avoid slow transaction search with txindex enabled

src/main.cpp
It is possible to access a map element that DNE if you force quit without downloading any blocks and then restart the wallet.
=> Fix edge case segfault.

.travis.yml, src/miner.cpp, src/wallet.cpp
This fixes the two instances of mismatched specifiers that already existed in-tree as well as tells TravisCI to run the `logprint-scanner.py` script if `CHECK_LOGPRINT` is true (currently this is only done for the arm build, similar to `CHECK_DOC`
=> [Travis] Add logprint-scanner.py to TravisCI

src/init.cpp
The zerocoin database should be wiped on reindex. If leftover information from a fork is left in the db it can lead to potential validation issues in the future and isolated forks.
=> Wipe zerocoin DB on reindex.

src/rpcclient.cpp, src/rpcrawtransaction.cpp
Raw transactions can now be passed a boolean to send them as SwiftX.
=> [RPC] Add SwiftX to rpcrawtransaction.

src/rpcblockchain.cpp, src/rpcclient.cpp, src/rpcserver.cpp, src/rpcserver.h
This allows for a user (such as a third party integration) to query the blockchain for the current fee rate per kb, and also get a suggested rate per kb for high priority tx's that need to get added to the blockchain asap.
=> [RPC] Add getfeeinfo RPC.

.github/ISSUE_TEMPLATE.md, doc/README.md, doc/translation_process.md
Being connected on the main Slack you only get the bot telling you it's no longer supported and to head to discord. Code documentation should do the same.
=> [Trivial] Updated texts referencing slack to point to discord instead

src/masternodeconfig.cpp
The port number used for the example in a freshly created `masternode.conf` file was the testnet port. Should be the mainnet port istead.
Fixes #425
=> [Docs] Use mainnet port for example in masternode.conf file

src/rpcwallet.cpp
UniValue doesn't like `ParseInt()` or `ParseBool()` when reading JSON
arrays or objects as part of user-submitted data. Use native `get_int()`
and `get_bool()` instead.
Also add a pre-check for `d` to make sure it is a number value.
=> [RPC] Fix `importzercoins` for use with UniValue

src/qt/res/css/default.css
CheckBox outlines are not visible on lubuntu 16.04 (and possibly other platforms, not tested). This fix removes the background transparency from default.css and improves visibility of checkboxes.
Also Fixes #127  
Before:
After:
=> [Qt] Improve checkbox visibility 

src/rpcblockchain.cpp, src/rpcserver.cpp, src/rpcserver.h
Search the zerocoin database for a zerocoinspend transaction that contains the given serial. This will be a helpful tool for the PIVX support group, which often times sees users say "I didn't spend that zPIV". This RPC call allows for support to grab the serial, and then find the spend tx on the chain.
=> [RPC] Findserial

src/chainparams.cpp, src/qt/privacydialog.cpp, src/qt/zpivcontroldialog.cpp
Require 1 mint to be accumulated to the same accumulator after making a zPIV spendable. Also require that the 'second' mint is at least two checkpoints deep in the chain (this was already the case, but the logic was not as precise and just used a value of `chainActive.Height() - 30`).
For example:
- I mint 5 zPIV on block 105
- Fuzz mints 5 zPIV on block 115
- My mint becomes *confirmed* at block 125 (20 confs)
- My mint becomes *spendable* at block 140 (1 checkpoint after the checkpoint which contains Fuzz's mint)
=> Only require 1 mint to be added before spending zPIV.

src/qt/bitcoingui.cpp
On lubuntu 16.04 the system tray menu is empty. This fix shows the system tray menu populated.
(Side-effect the system tray icon is shown after the splash screen disappears)
=> [Qt] Fix empty system tray menu

doc/release-notes.md, src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/pivx-cli.cpp, src/rpcprotocol.cpp, src/rpcprotocol.h, src/rpcserver.cpp
When no -rpcpassword is specified, use a special 'cookie' file for authentication. This file is generated with random content when the daemon starts, and deleted when it exits. Read access to this file controls who can access through RPC. By default this file is stored in the data directory but it be overridden with -rpccookiefile.
This is similar to Tor CookieAuthentication: see https://www.torproject.org/docs/tor-manual.html.en
This allows running pivxd without any manual configuration.
I've also removed the chain-specific setting in chainparams that dictates wither or not an RPC password is required as it is not needed with this.
=> [RPC] Implement random-cookie based authentication

src/main.cpp
When you only check for `nHeight < 325000` and `nHeight > 325000` you obviously run into troubles when `nHeight == 325000` :-)
Fixes https://github.com/PIVX-Project/PIVX/issues/459
Successfully tested a sync from scratch on testnet.
=> [Core] (testnet-) blockchain stuck at block 325000

doc/build-unix.md
I had to install libevent-dev on both an Ubuntu Ubuntu 16.04.2 LTS and a LinuxMint 18.2 to build the wallet, so I guess others will need this as well.
=> [Build] libevent-dev dependency added to build-documentation

src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/res/css/default.css
This is the implementation of the feature request #424 
Requested feature has been completed considering current architecture of CWallet class.
This architecture raised few concerns that we would like to bring to everyone's attention. We believe some attention should be paid to the future possibility of refactoring done for this class and setting up a separate issue if approved by core team task specifically for that purpose.
We would like to bring current implementation with public fields in this class to core team's attention. The way it's currently implemented may result in the possibility of future unstable code and ultimately bugs in application in general.
CWallet class as a Base class allows the derived classes to get direct access to CWallet class fields and alter their status …
=> [Qt] Feature: setstakesplitthreshold value set in Qt GUI

src/test/scriptnum_tests.cpp
Fixed compilation errors in pivx-3.0.6 [#450](https://github.com/PIVX-Project/PIVX/issues/450)
Instead of simply casting UINT_MAX to long (which may be as large as int), it is probably better to replace all types with a 64bit ones as it is in dash https://github.com/dashpay/dash/blob/master/src/test/scriptnum_tests.cpp.
This is an updated PR, previous discussion [here](https://github.com/PIVX-Project/PIVX/pull/455)
=> [TESTS] Fixed compilation errors

src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h
This is the implementation of the feature request #433. Solution has controls in the options dialog for enable or disable auto-minting and set required level.
This is an updated PR, previous discussion [here](https://github.com/PIVX-Project/PIVX/pull/457)
=> [Qt] Feature: Added controls to the options dialog for enable or disable auto-minting and set required level

src/qt/privacydialog.cpp
Currently if you use the zPIV Control Dialog to select the zPIV units to send, then it does not clear the associated "zPIV selected" labels after sending.
=> [QT] Clear PrivacyDialog "zPiv Selected" labels after sending.

configure.ac, src/Makefile.am, src/Makefile.test.include, src/init.cpp, src/init.h, src/main.cpp, src/net.cpp, src/net.h, src/netbase.cpp, src/netbase.h, src/pivxd.cpp, src/qt/pivx.cpp, src/reverselock.h, src/rpcclient.cpp, src/rpcnet.cpp, src/rpcprotocol.h, src/rpcserver.cpp, src/rpcserver.h, src/scheduler.cpp, src/scheduler.h, src/test/netbase_tests.cpp, src/test/reverselock_tests.cpp, src/test/rpc_tests.cpp, src/test/scheduler_tests.cpp, src/util.h
Work in progress for now, This PR will be used to add in-wallet ban management capability that doesn't require a client restart. See individual commit messages for more details until this can be finalized.
=> [RPC] Allow in-wallet management of peer bans

src/qt/forms/sendcoinsdialog.ui, src/qt/res/css/default.css
- wrong placement of UTXO split-size label fixed
- left toolbar: horizontal  gradients removed, vertical gradient for bottom part added
- general cleanup of `default.css`
Thanks to @Fuzzbawls and @Sieres for their feedback.
New look:
=> [UI] Minor changes and fixes

src/qt/guiconstants.h, src/qt/overviewpage.cpp, src/qt/transactiontablemodel.cpp
Colors changed and both Overview tab and Transaction tab have now the same colors for the individual transaction types.
How the colors are chosen (in that order, first matching rule decides the color): 
- if a transaction is conflicted or orphaned: red 
- if a transaction is unconfirmed or immature: dark purple with [bracket] around it 
- if it's a spent transaction: fuchsia (don't ask)
- everything else: black
=> [UI] Consistent trx colors for Overview + Transaction tabs

src/wallet.cpp
This PR fixes #487 
The problem was that activating autocombinerewards after cumulating a lot of rewards was generating TXs above the max size. They were refused and the wallet was looping trying to generate them.
Here we limit the number of input in an autocombinereward TX. 
Using this code I got my wallet back to normal in a few seconds. See testnet block 349533 to check the generated TXs.
=> [wallet] Fixes an autocombinerewards bug with above max size TXs

src/qt/forms/multisenddialog.ui, src/qt/multisenddialog.cpp
#446 
Added a Label section to the MultiSend GUI
MultiSend GUI will now show labels if address is selected from addressbook
MultiSend GUI now allows users to add or change the label to the address they are creating a multisend for
View MultiSend Button now displays the label in the print out along with the address and percentage
=> [UI] Update MultiSend GUI to allow address labels

src/wallet.cpp
Investigate a potential bug with multisend not working with Master Node rewards.
The conclusion was that in order for multisend to work the following must be true:
- The wallet the 10000 pivx are located in must be unlocked
- The wallet the 10000 pivx are located in must be connected to the pivx network
- The wallet the 10000 pivx are located in must have multisend enabled
Also, found a potential memory leak and updated the multisend code to fix the memory leak issue.
=> [MultiSend] Remove potential memory leak, update multisend code

src/qt/forms/sendcoinsdialog.ui, src/qt/sendcoinsdialog.cpp
This addresses https://github.com/PIVX-Project/PIVX/issues/404
Since Obfuscation was replaced by the Zerocoin protocol the additional warning is obsolete now and was removed.
New popups:
1: **Normal Send**:
2: **SwiftX**:
Additionally one forgotten `SwiftTX` was changed to `SwiftX`.
=> [UI] Send popup simplified + SwiftTX -> SwiftX

src/qt/test/paymentservertests.cpp
Remove use of variable length buffer from `paymentservertests.cpp`.
This removes the warning of: 
`stack protector not protecting local variables: variable length buffer`
raised by the `-Wstack-protector` compilation flag.
As noted in issue: https://github.com/PIVX-Project/PIVX/issues/387
=> [Bug] remove use of variable length buffer

src/qt/privacydialog.cpp
The status output on the "Privacy" page does now automatically scroll to the end of the output when it's very long to directly show the most important information, whether there's an error or not.
Useful when e.g. spending zPIV with 7 denominations.
=> [UI] Autoscroll to end of zPIV status output

src/Makefile.qt.include
The file `qt/winshutdownmonitor.cpp` is for Windows only. Excluding it on other systems prevents a linker warning about missing/no symbols at compile time such as:
```
/usr/bin/ranlib: file: qt/libbitcoinqt.a(qt_libbitcoinqt_a-winshutdownmonitor.o) has no symbols
```
=> [Build] compile/link winshutdownmonitor.cpp on Windows only

src/wallet.cpp
MultiSend and AutocombineDust are called after each new block is found. This is highly inefficient during initial sync. So this PR propose to wait for blockchain and MN sync to call this functions.
It also avoid AutocombineDust trying to iterate on UTXO > to its threshold.
Lastly it does not Autocombine in cases where the threshold is not reached and fees would be incurred.
=> [Wallet] Call AutocombineDust less often

src/qt/multisenddialog.cpp, src/qt/privacydialog.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet.cpp
#493 - Link to issue. 
While working on updating the labels in the address book. I saw that we were using duplicate code to complete the same task which was to "Updating the address book labels in the database"
Created a function in the wallet model class that you can call and it will update the address book labels. Then replaced the duplicate code with a call to the function.
=> [Qt] Remove duplicate code for updating address book labels.

src/rpcrawtransaction.cpp
If there are any script verification errors, when using `signrawtransaction`, they are shown in the RPC result.
Example:
```bash
./pivx-cli "signrawtransaction" "0100000002d8fde545ff10eec10a6bef0c293c892b556aaa8c9e2f5f4c8545ca5c88e41c930100000000ffffffff62a717b7379c9fd900bf8cd42d6cbe1992f51aac2edff637dd291ec0b710acf23800000000ffffffff01a0410000000000001976a9142d0242ee11731e1fb95f3917b61a11aa400f6d5388ac00000000" "[{\"txid\":\"931ce4885cca45854c5f2f9e8caa6a552b893c290cef6b0ac1ee10ff45e5fdd8\",\"vout\":1,\"scriptPubKey\":\"512102a6bce06d76dfa05974f50e71660936966be40fceee99fed481a526016b3b240e21160000000100000001d865ecba07d000000000000000000000000000000000000052ae\"},{\"txid\":\"f2ac10b7c01e29dd37f6df2eac1af59219be6c2dd48cbf00d99f9c37b717a762\",\"vout\":56,\"scriptPubKey\":\"01\"}]" …
```
=> [RPC] Show script verification errors in signrawtransaction result

src/activemasternode.cpp, src/masternode.cpp, src/masternode.h
The check if a masternode communicates via the correct (default-) port was broken for all networks other than MAINNET.
This PR fixes the check for TESTNET, REGTEST and UNITTEST.
Especially TESTNET will be important with hardware-wallets which support testnet.
The check was wrong in 3 different places, so I also refactored the whole thing to have it consistent.
=> [core] Fix masternode broadcast for networks != MAINNET

src/wallet.cpp
This is firstly to fix #496. Ensuring autocombine stops failing with `Insufficient funds` error messages. (Thanks to @Mrs-X for the help)
It also ensure that when a change address is provided in coin control the change is going to this address in an already existing output.
Last, it gives autocombine transactions the address being combined as a change address. Thus lowering TX size and avoiding generating new change addresses when trying to reduce UTXO fragmentation.
=> [Wallet] Combine fees when possible and fix autocombine insufficient funds

src/main.cpp, src/main.h, src/miner.cpp
Prevent zerocoinspends from remaining in the mempool for extended periods of time to prevent their serial numbers from floating in the mempool instead of being solidified into the blockchain and unable to be trolled.
Track zerocoinspends from the time the wallet sees them enter the mempool until the time they are included in the blockchain.
=> Give high priority to zerocoinspends to make it into the next block.

src/qt/macnotificationhandler.h, src/qt/macnotificationhandler.mm, src/qt/notificator.cpp, src/qt/notificator.h
Growl hasn't been free nor needed for many years. MacOS versions since
10.8 have the OS notification center, which is still supported after
this.
=> [Qt] Remove Growl support

doc/build-osx.md
`brew install libzmq` fails with 
`
Error: No available formula with the name "libzmq" 
`
but `brew install zmq` resolves the issue. Also, `libevent` is missing from the brew install list. Finally added notes to handle the possible `/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory` error.
=> [Doc] Update OSX build notes: zmq, libevent, and notes to handle possible glibtoolize error

src/qt/blockexplorer.cpp
We have `txindex` enabled by default, but the check here was expecting
it to be disabled by default so the warning dialog was being displayed
informing users that they would need to enable a setting that was
already enabled.
Trivial change.
=> [Qt] Fix warning dialog popup for the Blockchain Explorer

src/init.cpp, src/net.cpp, src/net.h
I was looking for the problem with #373. Turns out it's a network issue where reachability was not properly assessed and it's been fixed upstream in bitcoin and dash. So that's a simple backport of bitcoin/bitcoin@110b62f to fix #373 .
=> [Network] Remove vfReachable and modify IsReachable to only use vfLimited.

src/accumulators.cpp, src/accumulators.h, src/main.cpp, src/main.h, src/miner.cpp
Refactor ConnectBlock() to segregate state tracking items from the 'Just Check' section.
------
- Remove a `WriteBlockIndex` that was in the middle of `ConnectBlock()`. This really shouldn't be in this code at all because the index is written by adding it to a list of dirty. This is very likely what has caused PIVX to especially likely to corrupt on force close.
- Remove the auto-repair db code on init. This seems to actually cause more problems than it fixes.
- Do not write serials as spent until after the 'Just Check' section. Hold them in a vector until the just check section has passed.
- Do not write the accumulator checkpoints until the 'Just Check' section has passed.
- Refactor aspects of the zerocoin checks to be within their own functions external to `ConnectBlock()`. …
=> Refactor ConnectBlock() to segregate state tracking items

src/qt/bip38tooldialog.cpp, src/qt/bip38tooldialog.h, src/qt/forms/bip38tooldialog.ui, src/qt/forms/coincontroldialog.ui, src/qt/forms/multisenddialog.ui, src/qt/forms/privacydialog.ui, src/qt/forms/signverifymessagedialog.ui, src/qt/forms/zpivcontroldialog.ui, src/qt/multisigdialog.cpp, src/qt/res/css/default.css
This pulls out some UI refactoring and unrelated additions from #509 so they don't get held back.
- Standardize the use of QToolButton over QPushButton in instances where the button was being 
used as a utility button (copy/paste/addressbook) buttons interacting with text inputs.
- Standardize the CSS styling of all QToolButton elements.
- Remove nefarious (empty) `placeholderText` properties from `.ui` files.
- Update strings in BIP38 dialog to match the functionality there.
- Change from returning Hex to returning WIF private key for decrypted BIP38 key.
- Update MultiSig/MultiSend UI's to use QToolButton
See individual commit comments for full details.
Tool buttons are never required to be used. They merely offer a shortcut (copy/paste/delete) or a utility to pull an address from the …
=> [Qt] Standardize and clean up new UI elements

src/rpcmisc.cpp
Calling `pivx-cli getinfo` during the initial blockindex-load results in a segmentation fault.
There are lots of places where `chainActive.Tip()` is not explicitly checked, but I tested them (hopefully) all and only getinfo seems to have problems.
=> [RPC] Segfault pivx-cli getinfo while loading block index

src/rpcclient.cpp, src/rpcrawtransaction.cpp, src/wallet.cpp, src/wallet.h
Fix for - #476 
When multisig was added we changed listunspent to only show coins that you owned. It didn't list watchonly address. 
This change added an optional option to the listunspent rpc call that allows the user to get transactions in the following ways
1. default transactions (doesn't include watchonly transactions)
2. Only watchonly transactions
3. All transactions ( default and watchonly)
Examples:
`listunspent 1 9999999 [] 1` which is also `listunspent`
`listunspent 1 9999999 [] 2`
`listunspent 1 9999999 [] 3`
=> [RPC] Allow watchonly coins to be shown for listunspent

src/wallet.cpp
Add debug messages detailing why exactly a specific _archived_ mint is not considered valid.
=> [Trivial] Add debug info for CWallet::ReconsiderZerocoins().

src/main.cpp
The `LogPrint()` at the end of this function was missing a `,` separator
between the category and the message, as well as returning the two
paramaters in reverse order when compared to similar log prints.
The missing `,` was causing a segfault when running with `-debug` or
`-debug=zero`
=> [Trivial] Fix errant LogPrint in UpdateZPIVSupply

src/chainparams.cpp
This brings testnet more in-line with the consensus requirements that
are present on mainnet.
=> [Consensus] Require standard transactions for testnet

src/qt/addresstablemodel.cpp, src/qt/askpassphrasedialog.cpp, src/qt/askpassphrasedialog.h, src/qt/bip38tooldialog.cpp, src/qt/bitcoingui.cpp, src/qt/masternodelist.cpp, src/qt/multisigdialog.cpp, src/qt/privacydialog.cpp, src/qt/sendcoinsdialog.cpp, src/qt/signverifymessagedialog.cpp, src/qt/walletframe.cpp, src/qt/walletframe.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/qt/walletview.cpp, src/qt/walletview.h
This PR addresses https://github.com/PIVX-Project/PIVX/issues/515, the "For anonymization, automint and staking only" checkbox is now checked by default.
Downside is that it's also checked when you try to send coins and the wallet is still locked, so you have to uncheck it before you enter the passphrase. 
Since the passphrase-dialog does not have a context from where it's called this can't be easily changed.
It's up to you guys to discuss if we can live with that.
=> [GUI] Make "For anonymization and staking only" checked by default

share/genbuild.sh
The previous change required tagging on `master`, which we don't do. As
a result, the version string displayed in-wallet was always displaying
based off of a dummy tag that was pushed during the review of #402.
This PR restores the functionality to generate the version string
without relying on superficial tags.
This reverts commit 8fa5f125e558bc4951e8af0ecea4f066813e4a66.
=> [Build] Revert #402 "Change git info in genbuild.sh"

doc/release-notes.md
Simple release notes for PRs #497, #508 and #518.
=> [Docs] Added release notes for autocombine and proxy GUI.

src/qt/pivx.cpp
Finding the actual problem will be easier when we are able to run those Gitian builds for OSX.
=> [Core] Remove Gitan-OSX warning for High Sierra builds

configure.ac, src/crypter.cpp, src/ecwrapper.cpp, src/libzerocoin/bignum.h, src/qt/paymentrequestplus.cpp
What prompted me to address the situation is related to issue #149 
Let's give a bit of context:
In bitcoin, openssl was used in consensus critical code. Following the infamous heartbleed vulnerability discovered in openssl code, libressl was created as a fork to refactor and improve ssl code. To this day, libressl is used as default instead of openssl in the os openBSD. As far as crypto are concerned: the openssl hotfix was integrated into bitcoin promptly. The change in consensus code triggered a fork. bip 66 was then decided, removing openssl code from consensus critical area and using custom implementation by core team instead. This bip was backported in dash commit 3d004ab which we inherited. So good so far. 
The thing is, before this bip a limitation was put into the autoconf to …
=> [Consensus] Fix compilation with OpenSSL 1.1

src/init.cpp
String references with a value of `(int) 0` considered harmful.
=> [Bug] Segfault with -enableswifttx=0 / -enableswifttx=false

src/rpcclient.cpp, src/rpcwallet.cpp, src/wallet.cpp, src/wallet.h
This PR allows to use an extra argument when calling the `mintzerocoin` RPC function. 
The argument is optional and takes a json formated array of UTXOs. If the argument is provided, the minting will only use inputs from this UTXO set.
=> [Wallet/RPC] Add argument to mint zerocoin from specific UTXO

src/init.cpp, src/qt/forms/optionsdialog.ui, src/qt/optionsmodel.cpp
This increases the valid range percentage of automint from 10-100 to
1-100. The default value remains the same at 10%.
=> [Wallet] Increase valid range for automint percentage

src/qt/privacydialog.cpp, src/qt/privacydialog.h
Follow up on #568. Adds signal integration to change printed information on privacy tab about auto zPIV mint when its changed in the settings.
=> [Qt] Update privacy tab info about zeromint on config change

src/wallet.cpp
I stumbled upon a segmentation fault yesterday while trying to get rid of my zPIVs V1 on testnet. Turns out I did a mistake and was trying to make a spend with a value above the sum of selected coins.
This should result on a warning and stop the transaction instead of segfaulting, hence this fix.
=> [Wallet] Add a check on zPIV spend to avoid a segfault

src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet.cpp, src/wallet.h
What the title says. When hitting the reset or rescan button, zPIV balance will be updated accordingly without the need to change view and come back.
=> [Qt] Refresh zPIV balance after resetting mints or spends

src/masternodeconfig.cpp, src/masternodeconfig.h
rebase from upstream. Windows doesn't initialize CService properly
during startup before the masternode.conf file is read.
=> [Bug] Fix CMasternodeConfig::read

doc/release-notes/release-notes-3.0.4.md, doc/release-notes/release-notes-3.0.5.1.md, doc/release-notes/release-notes-3.0.5.md, doc/release-notes/release-notes-3.0.6.md, doc/release-notes/release-notes-3.1.0.1.md, doc/release-notes/release-notes-3.1.0.md
This adds historic release notes for versions 3.0.5 through 3.1.0.1 into
the `doc/release-notes/` path and also clears out the transitory
`/doc/release-notes.md` file so it can once again be used to tracking
new changes moving forward.
=> [Docs] Update historic release notes

src/Makefile.test.include, src/test/budget_tests.cpp
Prevent any future issues with calculated budget value by adding a unit test.
=> Add unit test for budget value.

src/test/budget_tests.cpp
check testnet params first, then check mainnet so as to not interfere
with subsequent unit tests that rely on mainnet params.
Also clean up include ordering.
=> [Tests] Fix chain ordering in budget tests

src/wallet.cpp
This addresses an issue where new incoming transactions aren't recorded,
and subsequently, not returned with `listtransactions` in the same
session.
fixes #578
=> [Wallet] Write new transactions to wtxOrdered properly

src/qt/privacydialog.cpp
Currently the zPIV buttons are constantly updated to enabled or disabled even if they are already in the correct state.
=> [GUI] Only enable/disable PrivacyDialog zPIV elements if needed.

src/accumulators.cpp, src/main.cpp, src/rpcblockchain.cpp, src/rpcclient.cpp, src/rpcserver.cpp, src/rpcserver.h, src/wallet.cpp, src/zpivtracker.cpp
The transition to v2 zPIV and reset of the accumulators caused blocks 1050000 - 1050010 to be accumulated twice. This was causing many v1 zPIV to not create valid witnesses. This problem is fixed by double accumulating blocks 1050000-1050010 when creating the witness.
=> Fix spending for v1 zPIV created before block 1050020. 

src/masternode.cpp, src/netbase.cpp, src/netbase.h, src/obfuscation.cpp
making use of getnameinfo() optional (default: true) and using pure byte to hex conversion for `strMessage` in mn sigs: 
https://github.com/dashpay/dash/pull/855
=> Fix bad masternode IPv6 signature

src/qt/overviewpage.cpp
Fixes a display issue introduced with https://github.com/PIVX-Project/PIVX/pull/479
This was a "display only" issue, all your coins were there all the time.
=> [GUI] Fix wrongly displayed balance on Overview tab

src/qt/multisenddialog.cpp
Multisend will display a message if it has only been enabled for masternodes and if its enabled for both (Displaying this didnt work if multisend was only enabled for masternodes)
=> Fixed Multisend dialog to show settings properly

src/wallet.cpp
When build with `--enable-debug` the linker complains about a missing `boost::gregorian` dependency which is not really needed.
This PR removes this dependency, because, as we all know, with each BOOST-dependency somewhere a Unicorn dies...
It also addresses https://github.com/PIVX-Project/PIVX/issues/601
Thanks and kudos to @FornaxA for finding the problem!
=> [Build] Remove unnecessary BOOST dependency

src/obfuscation.cpp
minor change to https://github.com/PIVX-Project/PIVX/pull/599 to have cleaner logs.
=> [Trivial] clean logs from CObfuScationSigner::VerifyMessage

src/masternode-budget.cpp
When there are 2 (or more) finalized(!) budgets (that's a valid condition) and both have the same voting count it's not deterministic which one is used to pay the monthly budgets and the network might not agree on a payment at all.
The worst possible result of this race-condition is that the network gets stuck one block before the budgets payments start, because one half of the network rejects the budgets payments of the other half.
This PR makes sorting and therefore the selection of the finalized budget deterministic and avoids this scenario.
=> [Budget] Make sorting of finalized budgets deterministic

src/main.cpp
This fixes issues that certain wallets have had with reorgs where the new blocks are rejected because the mint in the zerocoindb was not properly purged.
=> [Main] Check whether tx is in chain in ContextualCheckZerocoinMint().

src/masternode.cpp, src/netbase.cpp, src/netbase.h, src/obfuscation.cpp
This reverts the changes introduced with:
- https://github.com/PIVX-Project/PIVX/pull/599/commits/0ec1fd5577ca5f75aa7681b282283c2d1ab3c023 (https://github.com/PIVX-Project/PIVX/pull/599)
- https://github.com/PIVX-Project/PIVX/pull/606/commits/37c6e7db5834a643a13deb3c012ac68e0afe5987 (https://github.com/PIVX-Project/PIVX/pull/606)
that are causing excessive peer banning, due to the change in `strMessage` which makes signatures created prior `#599` fail validation after `#599` merge.
(included `#606` because it built on top of `#599`)
=> [Net] Revert #599 and #606

src/masternode-budget.cpp, src/masternode-payments.cpp, src/masternodeman.cpp
Many of the MN related DoS checks had their log messages output only if
the client was running in debug mode, leading to unexplained peer bans.
=> [Output] Properly log reason(s) for increasing a peer's DoS score.

src/main.cpp
Fixes #623, sister commit to a03edf6/#460
=> [Core] Missing seesaw value for block 325000

src/Makefile.am
Custom boost locations not using pkg_config can result in a header
include not being found when compiling the libzerocoin library. This
quick fix ensures that the `BOOST_CPPFLAGS` are explicitely included.
This should fix #621
=> [Build] Make sure Boost headers are included for libzerocoin

src/qt/addressbookpage.cpp, src/qt/askpassphrasedialog.cpp, src/qt/bip38tooldialog.cpp, src/qt/coincontroldialog.cpp, src/qt/intro.cpp, src/qt/multisenddialog.cpp, src/qt/multisigdialog.cpp, src/qt/obfuscationconfig.cpp, src/qt/openuridialog.cpp, src/qt/optionsdialog.cpp, src/qt/privacydialog.cpp, src/qt/receivecoinsdialog.cpp, src/qt/receiverequestdialog.cpp, src/qt/rpcconsole.cpp, src/qt/sendcoinsdialog.cpp, src/qt/signverifymessagedialog.cpp, src/qt/transactiondescdialog.cpp, src/qt/utilitydialog.cpp, src/qt/zpivcontroldialog.cpp
=> [Qt] Remove useless help button from QT dialogs (windows)

src/init.cpp, src/main.cpp, src/zpivchain.cpp
`-reindexaccumulators` and `-reindexzerocoin` can take a considerable
time to complete depending on system hardware. Lets show a progress percent
similar to `VerifyDB()` on the splashscreen.
=> [Qt] Show progress percent for zpiv reindex operations

.travis.yml, contrib/devtools/git-subtree-check.sh, contrib/devtools/lint-whitespace.sh
Break out a new job to do the basic linting that check-dock.py and
logprint-scanner.py did.
Also add new scripts to check the sanity of
any git subtrees and to check that new pull requests don't contain any
trailing whitespace.
Also, remove the outdated slack notification callback
=> [Travis] Add separate job to check doc/logprint/subtree

src/main.cpp, src/txdb.cpp, src/txdb.h, src/zpivchain.cpp
instead of using a separate write operation for each and every bit of
data that needs to be flushed to disk, utilize leveldb's batch writing
capability.
The primary area of improvement this offers is when reindexing the zerocoinDB (`-reindexzerocoin`), which went from needing multiple hours on my system to mere minutes.
Secondary improvement area is in `ConnectBlock()` when multiple zerocoin transactions are involved.
=> [Main] Write to the zerocoinDB in batches

depends/packages/qt.mk
Qt has moved the 5.7.1 downloads from the official_releases directory to it's archive.
(cherry picked from commit bitcoin/bitcoin@2fca656)
=> [Depends] Update Qt download url

src/wallet.cpp
=> #642 change COINBASE_MATURITY to Params().COINBASE_MATURITY()

src/qt/multisenddialog.cpp, src/qt/multisenddialog.h
Some much needed cleanup of the multisend dialog UI. Broken out into minimalistic commits for review-ability.
Fixes #664 when compiling against newer versions of Qt where `QStyle` is no longer inherited from other includes.
Also removes the dependency on boost in the file, as well as introduces proper translation functions for user-facing strings.
This should hold us over until the entire multisend system/ui can be redesigned.
=> [Qt] Clean up Multisend Dialog UI

src/wallet.cpp
… on the same machine; it is an edge case, but should still be fixed
related to issue #654 but a different scenario
=> [Wallet] Fix double locked coin when wallet and MN are on same machine

src/qt/forms/sendcoinsdialog.ui, src/qt/sendcoinsdialog.cpp
Minor clean up of the sendcoinsdialog for improved usability of fee control and SwiftX feature in response to the issues raised in https://github.com/PIVX-Project/PIVX/issues/672.
The smartFee slider is now on its own row for better visualization and is disabled when SwiftX is selected.
The SwiftX checkbox is put next to it, has now a tooltip, and when it's checked it:
- updates the fee label
- brings the slider to the max value before disabling it
- hides the choose button for the smart fee
- minimizes the smart fee box if already maximized
- updates the labelFeeEstimation with an explicative message.
<br>
=> [Qt] SwiftX - intuitiveness

src/qt/forms/privacydialog.ui, src/qt/privacydialog.cpp, src/qt/privacydialog.h
Minor UI change in response to issue https://github.com/PIVX-Project/PIVX/issues/676
To reduce ["information overload"](https://en.wikipedia.org/wiki/Information_overload) in the Privacy Dialog the user has now the option to minimize the zPIV denominations widget and have only the total values (own balance and total supply) printed in one row, thus making the interface much cleaner. 
The denominations list can be maximized again with a `Show Denominations` button.
<br>
The frame status (visible or hidden) is governed by a QSettings flag `fDenomsSectionMinimized` defaulted to `true` and updated in the destructor of the class.
=> [Qt] Privacy dialog: hide/show denominations

src/qt/overviewpage.cpp
Locked balances were being double counted in the total and available
values. This fixes the issue once and for all.
fixes #654 
`142bbc2` fixes the balance calculations
`0443512` improves code readability and show/hide conditions for watch-only balances
`45a1537` removes some trailing whitespace elsewhere in the file.
Keeping the commits separate to ease the review process.
=> [Qt] Fix PIV balances on overview page

src/libzerocoin/ParamGeneration.h, src/main.h
Noticed some redundant function declarations in `main.h` and `ParamGeneration.h` that were throwing compiler warnings.
=> [Trivial] Remove Redundant Declarations

src/accumulators.cpp, src/denomination_functions.cpp, src/main.cpp, src/miner.cpp, src/primitives/transaction.cpp, src/qt/clientmodel.cpp, src/qt/transactionrecord.cpp, src/rpcwallet.cpp, src/test/zerocoin_implementation_tests.cpp, src/wallet.cpp, src/zpivchain.cpp
Turning on `-Wrange-loop-analysis` shows a number of compiler warnings
with c++11 for loops creating copies when references would suffice.
This cleans up those warnings.
=> [Refactor] Use references instead of copies in for loops

src/qt/receivecoinsdialog.cpp, src/qt/receivecoinsdialog.h, src/qt/recentrequeststablemodel.cpp, src/qt/recentrequeststablemodel.h
This is a small change in direction of #678. Simply allowing to get the address from a past payment request. (new column and right-click -> copy).
Before:
After:
=> [UI] Add address to the payment request history

src/wallet.cpp
Simple fix for a simple problem. 
In the event where the combine threshold is way higher than available UTXOs, a transaction would need to exceed the maximum tx size to attain the threshold.
A check in place to avoid paying too much fees combining small amounts gets stuck under the above conditions. This small change avoids the lock.
=> [Wallet] Avoid autocombine getting stuck

src/leveldbwrapper.cpp, src/leveldbwrapper.h
Using throw() specifications in function signatures is not only
not required in C++, it is considered deprecated for [various reasons](https://stackoverflow.com/questions/1055387/throw-keyword-in-functions-signature).
It is not implemented by any of the common C++ compilers. The usage is
also inconsistent with the rest of the source code.
=> [Build] Remove throw keywords in leveldb function signatures

src/walletdb.cpp
Prevent file access collisions and possible file corruption by refusing
to overwrite the current wallet in use.
On the off chance that a user attempts to use `backupwallet` in a way that the destination is the same as the source, an error will be returned instead of an attempted backup.
=> [RPC] Don't allow backupwallet to overwrite the wallet-in-use

configure.ac, src/Makefile.am, src/compat/glibc_compat.cpp, src/init.cpp
This adds glibc 2.27 backwards compatibility to GCC 7, which is used on Ubuntu Bionic (a future gitian/TravisCI build host) to maintain the existing minimum supported ABI specs.
testability/enforcement with gitian builds will come in it's own PR later.
(Rebased from bitcoin/bitcoin#13177)
=> [Build] GCC-7 and glibc-2.27 back compat

build-aux/m4/gmp.m4, configure.ac, depends/packages/gmp.mk, depends/packages/packages.mk, src/Makefile.am, src/libzerocoin/bignum.h, src/test/zerocoin_implementation_tests.cpp
This PR adds support for a new `CBigNum` implementation and switches to it by default. This class is used in the zerocoin library and underlies all of its cryptography.
We add a new configure option which accepts 3 values `--with-zerocoin-bignum` can either be set to `auto`, `gmp`, or `openssl`. Auto being the default one and resolving to gmp.
There are 2 goal in switching from OpenSSL to gmp:
* Move away from OpenSSL which is not a simple arithmetic library but a full fledged cryptographic library which brings its own suite of faults. We are using it in various places of the code but moving away from it everywhere possible seems to be a good approach.
* Improve performances. On this front, here are my tests results:
```
gmp                          openssl
500 V2 spends …
```
=> [Depends] Add gmp bignum support for zerocoin lib

src/libzerocoin/Accumulator.cpp, src/libzerocoin/Accumulator.h
The default compiler function does just fine.
And having this function but no explicit default destructor or copy constructor
is bad practice.
=> [Zerocoin] Remove explicit copy assignement operator from Accumulator

src/rpc/blockchain.cpp
verifychain only accepts a single (optional) argument instead of two,
and we need to capture that argument properly.
=> [RPC] Fix verifychain

src/rpcwallet.cpp
Properly return an error when attempting to use a negative timeout. Also
sanitize the timeout so as to not cause a value error with libevent on
MacOS.
=> [RPC] Sanitize walletpassphrase timeout argument

src/qt/forms/receivecoinsdialog.ui, src/qt/receivecoinsdialog.cpp, src/qt/receivecoinsdialog.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet.cpp, src/wallet.h
This adds an address field to the receive tab.
IMO this, in combination with #683 and #693 should allow to close #678. I feel it correctly addresses the concern raised there, without too much changes into our UI and still following common best practices.
FYI The new address field will automatically change when the address in question receives any payment.
**Before:**
**After:**
=> [UI] Add address field in receive tab

src/rpcwallet.cpp
Even though this command is all but deprecated, it's help output and
example were incorrect and deserving of an update.
amount is the 3rd paramater, and is required. minconf is the 4th
paramater, and for all intents and purposes is a "dummy" paramater since
it is no longer considered in the functional logic.
=> [RPC] Fix movecmd's help description to include amount

src/rpcwallet.cpp
When calling `getreceivedbyaddress` with a non-wallet address, return a
proper error code/message instead of `0`
=> [RPC] Error when calling getreceivedbyaddress with non-wallet address

src/rpc/server.cpp
Return a more descriptive type error when the input paramater is not a
numeric.
This clarifies the response message a bit and allows for a faster exit
response by not needing to do subsequent mathematical or external
function checks.
NOTE: This isn't a functional change, since non-numeric input values
would previously fail anyways, returning only an "Invalid amount" error
message.
=> [RPC] Ensure that a numeric is being passed to AmmountFromValue

src/qt/bitcoingui.h, src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/zpivcontroldialog.cpp, src/qt/zpivcontroldialog.h
Numeric sorting in this dialog was broken. It was following some kind of string rules. This is a simple fix, as used in the coin selector dialog.
**Before:**
**After:**
=> [UI] Sort numbers correctly in zPIV and coin control dialogs

src/libzerocoin/bignum.h
Similar to the `CBigNum()` overloads when using GMP, there is no need to
use special pre-compiler logic for `__APPLE__`'s int64_t; just use
`long long`.
=> [zPIV] Fix bignum overloads when using OpenSSL

src/wallet.cpp
Fixes #728 
Thanks to @licobc for catching it.
=> [Staking] Ensure nCredit is correctly initialized in CreateCoinStake

src/clientversion.cpp
This changes the "dummy" `GIT_COMMIT_ID` and `GIT_COMMIT_DATE` strings used in archive packages to use live values instead of static placeholders.
Useful when compiling in an isolated/base environment with an archive produced using `make dist` from a fully connected environment.
=> [Qt] Stop using dummy strings in clientversion.cpp

src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/overviewpage.cpp, src/qt/overviewpage.h, src/qt/transactionfilterproxy.cpp, src/qt/transactionfilterproxy.h, src/qt/transactionview.cpp, src/qt/transactionview.h
Add checkbox to hide orphan stakes in 'Overview' and 'Transactions' tabs, and persist the status of the checkbox between successive runs.
This, coupled with https://github.com/PIVX-Project/PIVX/pull/677, should allow to finally close https://github.com/PIVX-Project/PIVX/issues/674
=> [GUI] Hide orphans

contrib/devtools/check-doc.py, contrib/devtools/lint-whitespace.sh, contrib/devtools/logprint-scanner.py
check-doc and logprint-scanner were still using python2 conventions.
This updates the two scripts to use pyhon3 instead and be consistent
with the rest of our python utility scripts.
Also, use a more widely accessible bash path in lint-whitespace.sh
=> [Utils] Update linters for python3

src/rpc/client.cpp, src/rpcwallet.cpp
Add a `fVerbose` boolean optional argument (*default=false*) to `listmintedzerocoins` call to have a more detailed output.
If `fVerbose` is specified as first argument, then a second optional boolean argument `fMatureOnly` (*default=false*) can be used to filter-out immature mints.
=> [RPC] include mints metadata in 'listmintedzerocoins' output

src/rpc/client.cpp, src/rpc/server.cpp, src/rpc/server.h, src/rpcwallet.cpp
Introduce the `spendzerocoinmints` RPC call to enable spending specific zerocoins, provided as lists of hex strings (serial hashes).
=> [RPC] Add 'spendzerocoinmints' RPC call

src/httprpc.cpp, src/qt/rpcconsole.cpp, src/rpc/server.cpp, src/rpc/server.h
when running the wallet with `-server` and using `walletpassphrase` over the RPC server (not the GUI console), the wallet doesn't lock again when the timeout expires, it stays unlocked indefinitely.
This is fixed in upstream Bitcoin and might allow to finally address this https://github.com/PIVX-Project/PIVX/issues/553 too.
=> [RPC] Fix RPCTimerInterface

src/activemasternode.cpp, src/chain.h, src/init.cpp, src/kernel.cpp, src/main.cpp, src/masternode-budget.cpp, src/masternode-budget.h, src/masternode-payments.cpp, src/masternode-payments.h, src/masternode.cpp, src/masternodeman.cpp, src/obfuscation.cpp, src/rpc/masternode.cpp, src/rpcwallet.cpp, src/spork.cpp, src/spork.h, src/swifttx.cpp
Since C++11 it's better to use specialized library functions for lexical casting instead of boost `lexical_cast`.
This PR:
- Replaces all occurrences of `boost::lexical_cast<std::string>` with compatible library function [std::to_string](https://en.cppreference.com/w/cpp/string/basic_string/to_string).
- Replaces `const boost::bad_lexical_cast` exception in `getmasternodescorses` (*rpc/masternode.cpp*) with [std::invalid_argument](https://en.cppreference.com/w/cpp/error/invalid_argument) (which is the exception that can be raised by `std::stoi`).
- Replaces all occurrences of `boost::lexical_cast<int>`with function [std::stoi](https://en.cppreference.com/w/cpp/string/basic_string/stol) and `boost::lexical_cast<unsigned int>` with …
=> [Refactor] Remove 'boost::lexical_cast<>'

src/init.cpp, src/main.cpp, src/net.cpp, src/net.h, src/rpc/net.cpp, src/utilstrencodings.cpp, src/utilstrencodings.h
Used primarialy (for now) in node identification for upcoming regtest
scripting.
=> [Net] Pull uacomment in from upstream

src/qt/bitcoingui.h, src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/forms/coincontroldialog.ui, src/qt/zpivcontroldialog.cpp, src/qt/zpivcontroldialog.h
As highlighted in the comments of https://github.com/PIVX-Project/PIVX/pull/738, the changes introduced with https://github.com/PIVX-Project/PIVX/pull/725 weren't enough to get rid of the hidden columns.
The proposed solution removes the hidden columns and stores as `QVariant`s the numeric value of the items (setting them with the function `QTreeWidgetItem::setData`).
The `CCoinControlWidgetItem` and `CZPivControlWidgetItem` subclasses of `QTreeWidgetItem` override the `<` operator in order to sort the interested columns by numeric value of the `QVariant` data.
=> [GUI] Sort by 'data' in zPIV and coin control dialogs

src/rpc/masternode.cpp
Add the masternode's public key (used to broadcast masternode messages) to `listmasternodes` RPC. I could not find another convenient way to get a masternode's public key (which is public information needed to validate masternode messages) from the RPC calls.
=> [RPC] Add masternode's pubkey to listmasternodes RPC

src/blocksignature.cpp, src/pubkey.h
This method is not returning the public key as hex string as the name implies.
=> [Refactor] remove CPubKey::GetHex

src/rpc/blockchain.cpp
Simple addition to the JSON output; mainly used in upcoming functional
test updates.
=> [RPC] Add mediantime to getblock/getblockheader output

src/rpcwallet.cpp
Simple consistency addition. This mimmics the output from `getinfo`.
=> [RPC] Show the configured/set txfee in getwalletinfo

src/httpserver.cpp, src/httpserver.h, src/rpc/mining.cpp, src/sync.cpp, src/sync.h, src/util.h
When adding in the `-Wthread-safety-analysis` compiler flag on my personal branch, some warnings popped up. This fixes those warnings, but also drops some big boost dependencies at the same time.
Note: the pre-check for `thread_local` support isn't included here, it will be included in a subsequent PR.
=> [Build] Fix Thread Safety Analysis Warnings

src/rpc/blockchain.cpp
This adds some extra output to the `getblockchaininfo` RPC command that shows the supermajority status of any soft-forks. Our first one is the BIP65 (CLTV) soft-fork indicated by version 5 blocks (#705).
=> [RPC] Show BIP65 soft-fork progress in getblockchaininfo

src/init.cpp, src/init.h, src/pivxd.cpp, src/qt/pivx.cpp
This moves CScheduler and threadGroup to a static declaration in init
.cpp so as to avoid a potential shutdown deadlock where both are freed
before the network message handler thread has been completely released.
=> [Main] Unify shutdown proceedure in init rather than per-app

src/qt/optionsdialog.cpp, src/qt/optionsdialog.h, src/qt/overviewpage.cpp, src/qt/transactionview.cpp, src/qt/transactionview.h
As pointed out in the comments of https://github.com/PIVX-Project/PIVX/pull/733, a more convenient way to access the option to hide orphans would be handy.
This PR builds on top of 733 adding a contextMenu checkable action, accessible directly from the transactionView (without having to navigate the options dialogs).
It retains consistency with the checkbox in the display settings.
=> [GUI] Hide orphans - contextMenu action

src/wallet.cpp
This avoids the situation where selecting too much zPIV for a spend (example: ten 1 denom to spend 3 PIV) would result in the message `Failed to find coin set amongst held coins with less than maxNumber of Spends`.
=> [Wallet] Fix zPIV spend when too much mints are selected

src/qt/rpcconsole.cpp
This adds a generic warning message to the debug console's initial
output, mentioning that the commands available should not be used
without prior understanding of what they do.
Also fixes the `clear` key combo displayed when on macOS.
=> [Qt] Add a security warning to the debug console's default output.

src/main.cpp
Zerocoin mints generated as part of a zerocoin stake are prematurely processed in the staker's wallet from `ConnectBlock()`. Connect block with the `fJustCheck` flag is called to verify the newly created block is valid. It is possible that this check could fail, or the block never gets fully connected.
This should reduce some of the reported orphans to the client interface.
=> Do not record zerocoin tx's in ConnectBlock() if it is fJustCheck

src/sync.cpp, src/sync.h
This, primarily, removes the dependency on Boost for sync.cpp, but also removes some unused code as well as utilizes c++11 standards for `nullptr`.
Commits are kept separate to ease the review process.
=> [Main] Clean up sync.cpp/h with upstream declarations

src/qt/bitcoingui.cpp
When running the client with the `-disablewallet` option, the staking
and automint icons should always be hidden. This adds a check to see if
`walletFrame` has been set before showing/updating these two icons.
=> [Qt] Don't show staking/automint status icons without a wallet

src/masternode-budget.cpp, src/masternode-budget.h
Validating a _finalized_ budget (which includes all winning budget proposals and will be paid with the next superblock) needs both the included budget proposals and the (future) budget payments sorted by hash, which they weren't.
The result was that the latest budgets weren't paid at all because the masternodes considered the finalized budget invalid.
This is fixed now.
**Note:** there are also additional fixes available already, but those are not included here because they would need a mandatory protocol update which will be done later this year.
=> [Budget] Make checks for MN-autovoting deterministic

src/Makefile.am, src/allocators.h, src/base58.cpp, src/crypter.cpp, src/crypter.h, src/db.cpp, src/qt/paymentrequestplus.cpp, src/qt/paymentrequestplus.h, src/qt/paymentserver.cpp, src/random.cpp, src/streams.h, src/support/cleanse.cpp, src/support/cleanse.h, src/util.cpp, src/utilstrencodings.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/5689 and https://github.com/bitcoin/bitcoin/pull/11196. That's part of the project of keeping up with Bitcoin Core and moving away from OpenSSL as much as possible.
=> [Refactoring] Abstract out and switch openssl cleanse

src/qt/pivx.qrc
The icon for block explorer is missing.
=> [Qt] Fix Missing Explorer Icon

src/primitives/zerocoin.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/qt/zpivcontroldialog.cpp, src/zpivtracker.cpp, src/zpivtracker.h, src/zpivwallet.cpp, src/zpivwallet.h
Changing the zPIV seed can lead to holding mints you can't spend. 
This PR aims to avoid situations where spending gets stuck because this was not taken into account.
It also shows in the zPIV control dialog if the mints can't be spent because of this.
=> [Wallet] Avoid failed zPIV spend because of changed seed

src/qt/bitcoingui.cpp, src/qt/optionsdialog.cpp, src/qt/optionsdialog.h
Opening the option dialog defaults to its last tab. This changes selects the first tab (containing zerocoin minting related options) when clicking the zerocoin autominting icon.
=> [UI] Open related options tab when clicking automint icon

depends/packages/zeromq.mk
Addresses https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6250
Signed-off-by: cevap <dev@i2pmail.org>
=> [Depends] Update zmq to 4.3.1

src/netbase.cpp, src/random.cpp, src/script/interpreter.cpp, src/serialize.h, src/test/base58_tests.cpp, src/util.cpp
With C++11 these functions are not needed anymore and gracefully
replaced. 
This is a backport of https://github.com/bitcoin/bitcoin/pull/9305.
=> [Refactor] Remove begin/end_ptr functions

doc/build-unix.md
Update the Unix build notes to be more complete, with mentioning of the
GMP and ZeroMQ dependencies, as well as OpenSSL version note.
Other stylistic updates as needed.
=> [Doc] Update build-unix.md

src/init.cpp, src/main.cpp, src/main.h
This PR mitigates the following problems:
1) Storage of invalid PoS/zPoS blocks from forked chains.
2) Blocks spam filtering.
Thanks to @random-zebra for the team work on this topic.
This work will be properly detailed on the next days of QA.
=> [NET] Invalid blocks from forks stored on disk fix + blocks DoS spam filter.

src/main.cpp, src/net.cpp, src/obfuscation.cpp
Response to #807, the stake minter thread, as well as the automint and obfuscation unlock functions rely on the presence of `pwalletMain`, which is `NULL` when the client is run with `-disablewallet`.
This PR handles that situation.
Note: the stake minter thread should probably be moved out of `net.cpp` as it really has nothing to do with P2P network inter-connectivity, but that is for a separate PR.
=> [Wallet] Fix segfault with runtime -disablewallet

src/rpc/rawtransaction.cpp
The `signrawtransaction` RPC command needed some modification to appease
the fake stake test cases, however that change introduced a minor
inconsistency in it's operation.
This PR restores the original functionality, while still providing a
means to be used for the fake stake test cases.
=> [RPC] Fixup signrawtransaction on regtest

src/qt/proposalframe.cpp
The problem seems to be related to a stack corruption issue occuring within Qt and only for windows builds. Further investigation is required but this is a suitable fix for now and there is no need to have the r-click doing the same job as the l-click in this situation.
Fix #823.
Thanks to @CryptoDev-Project for report and suggested fix.
=> [Qt] Fix a windows only crash when r-clicking a proposal

src/qt/transactiontablemodel.cpp
Feel free to ignore this PR if clock5.png is purposely not displayed in the transactions tab for some reason. Looking back through the code changes over time I see that clock5 has never been displayed properly, but yet it is still included in the newest source. My suggestion is to either use this fix to display the proper clock image for immature txs or else simply remove clock5.png from the source to prevent further confusion
=> Fix to display missing clock5.png tx image

doc/release-notes.md
In preparation for 3.2.0 release, this adds to the "Notable Changes" section of the release notes template.
marked as [WIP] for now, as there are more items that will be added.
=> [Doc] Update release notes with forthcoming 3.2.0 changes

contrib/macdeploy/custom_dsstore.py
macOS versions 10.12 and above have a problem reading the WindowBounds object in the custom `.DS_Store` when it is a byte object. This fixes the issue by changing the WindowBounds object to a string.
Fixes #857
=> [Build] [macOS] Fix macOS dmg issue (10.12+)

contrib/devtools/optimize-pngs.py
Optimization script does optimize/clean all existing pngs in projects folder, before png is merged into master, it probably should be optimized.
How to use
-----------
Run script until you get: `Checksum stable: True`
```bash
contrib/devtools/optimize-pngs.py
```
Run on current pivx
-------------------
After adding the script, I did run and on first run it returned `Checksum stable: False` which means images were not optimized:
After running it, it did optimize `src/qt/res/icons/debugwindow.png`
Log
-----
- First run
```
$ contrib/devtools/optimize-pngs.py
optimizing spinner-025.png... done
optimizing spinner-005.png... done
optimizing spinner-020.png... done
optimizing spinner-034.png... done
optimizing spinner-018.png... done
optimizing spinner-033.png... done
optimizing …
```
=> [Scripts] Add optimize pngs python script

src/main.cpp
When the shutdown process is started, it is possible that the call to
`ValidateAccumulatorCheckpoint()` in `ConnectBlock()` will fail. Instead
of returning an invalid state, which causes the block to pass through
`InvalidChainFound()`, just return a stateless error if a shutdown has
been requested.
=> [Main] Don't return an invalid state when shutting down the wallet

src/qt/zpivcontroldialog.cpp
When opening the zPIV coin selection in privacy tab, if the wallet is
locked the message for all mints is that the seed is wrong. This commit
fixes it by replacing the message and stating that the locked wallet
prevents precomputation and spending.
Fix #851
=> [QT] Fix a display bug about zPIV mints

src/chainparams.cpp
This adds two new checkpoints for mainnet:
* Block 1679090 - first block with a wrapped serial
* Block 1686229 - last block that zPIV was active
Also for testnet:
* Block 1016800 - Arbitrary recent block
=> [Net] Add new checkpoints for mainnet/testnet

src/main.cpp
When `showProgress()` is passed a `100` int value, the dialog is deleted
. If the function is passed a `100` int value a second time in the same
scope, like what happens at the end of `RecalculateZPIVSpent()` and
`RecalculateZPIVSupply()`, it results in a segfault.
This change standardizes the process by first initializing the progress
dialog with a `0` value, updating to a maximum of a `99` value inside
the loop, and finally closing with a `100` value after the loop has
completed.
Fixes #859
=> [Qt] Prevent double deletion of progress dialog

src/util.cpp
fixes warning during compilation:
```
util.cpp:100:13: warning: redundant redeclaration of ‘std::__cxx11::string boost::program_options::to_internal(const string&)’ in same scope [-Wredundant-decls]
std::string to_internal(const std::string&);
^~~~~~~~~~~
In file included from /usr/include/boost/program_options/detail/config_file.hpp:20:0,
from util.cpp:85:
/usr/include/boost/program_options/detail/convert.hpp:70:48: note: previous declaration of ‘std::__cxx11::string boost::program_options::to_internal(const string&)’
BOOST_PROGRAM_OPTIONS_DECL std::string to_internal(const std::string&);
^~~~~~~~~~~
```
=> [Cleanup] Fix redundant redeclaration of boost's to_internal

src/rpc/mining.cpp
fixes warning during compilation:
`warning: ‘template<class> class std::auto_ptr’ is deprecated`
=> [Refactor] Replace deprecated auto_ptr with unique_ptr

src/chainparams.cpp, src/chainparams.h, src/masternode-budget.cpp, src/masternode-budget.h, src/qt/governancepage.cpp, src/qt/res/css/default.css
This introduces two new colors for proposals items in the governance page. Yellow for proposals accepted by the voting system but unfunded by lack of funds and blue for unestablished (less than 24 hours old) proposals.
It also factors out a function to check if a proposal is passing, independently of it being funded or not. This is used for the colors and might be reused in the future.
=> [Qt] Add new budget colors

configure.ac, src/Makefile.am, src/libzerocoin/bignum.cpp, src/libzerocoin/bignum.h, src/libzerocoin/bignum_gmp.cpp, src/libzerocoin/bignum_openssl.cpp
=> [Refactor] Refactor bignum header file into several files

src/main.cpp, src/main.h, src/txdb.cpp
Removing completely the ``setStakeSeen`` variable since it's not used anywhere.
=> [Refactor] Remove unused setStakeSeen variable

src/qt/forms/governancepage.ui, src/qt/forms/masternodelist.ui, src/qt/forms/multisenddialog.ui, src/qt/forms/overviewpage.ui, src/qt/forms/privacydialog.ui, src/qt/forms/receivecoinsdialog.ui, src/qt/forms/sendcoinsdialog.ui
No functional change. This simply shortens the code and makes it clearer.
=> [UI] Simplify Qt margins.

src/blocksignature.cpp, src/bloom.cpp, src/coins.cpp, src/coins.h, src/kernel.cpp, src/main.cpp, src/masternode-payments.cpp, src/miner.cpp, src/primitives/block.cpp, src/primitives/transaction.cpp, src/primitives/transaction.h, src/qt/privacydialog.cpp, src/qt/transactionrecord.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/script/script.cpp, src/script/script.h, src/script/standard.cpp, src/test/zerocoin_implementation_tests.cpp, src/txmempool.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/zpiv/zpivwallet.cpp, src/zpivchain.cpp
This fixes zerocoin mints and/or spends tx identification considering the fact that a transaction can have multiple zerocoin spend inputs and multiple zerocoin mint outputs.
=> [Zerocoin] remove CTransaction::IsZerocoinSpend/IsZerocoinMint

src/Makefile.test.include, src/libzerocoin/bignum.h, src/libzerocoin/bignum_gmp.cpp, src/libzerocoin/bignum_openssl.cpp, src/test/zerocoin_bignum_tests.cpp, src/test/zerocoin_denomination_tests.cpp, src/test/zerocoin_implementation_tests.cpp
This fixes an issue where the GMP bignum PRNGs could output numbers slightly bigger than the max size set.
Instead of using native functions (such as `mpz_urandomm` or `mpz_urandomb`) which would require separate seeding, it uses OpenSSL `GetRandBytes()` (reducing modulo the limit requested) to retain consistency and leverage OpenSSL PRNGs initialization.
=>  [Zerocoin] GMP BigNum: Fix limits for random number generators

src/qt/walletframe.cpp
The walletView element should be parented to walletStack instead of the WalletFrame.
=> [UI] Fix improperly parented walletView and segmentation fault on QT 5.10

src/qt/forms/receivecoinsdialog.ui, src/qt/forms/zpivcontroldialog.ui
Resolves compiler warnings about a label's name having been already used.
```make
qt/forms/receivecoinsdialog.ui: Warning: The name 'label' (QLabel) is already in use, defaulting to 'label1'.
qt/forms/zpivcontroldialog.ui: Warning: The name 'verticalLayout' (QVBoxLayout) is already in use, defaulting to 'verticalLayout1'.
```
=> [Qt] Fixup duplicate label names

src/wallet/wallet.cpp
https://github.com/PIVX-Project/PIVX/pull/897 disables mints outputs at consensus level.
This prevents zerocoins from being included in `SelectStakeCoins` thus disabling zPIV staking in the wallet.
=> [zPIV] Disable zPIV staking

src/chainparams.cpp
The PR merely set the zerocoin public spend network enforcement block height. 
After block **1,880,000** (~ 28/06/19), users will be able to convert their v2 zPIV back to PIV freely. Using the functionality described and recently merged on #891.
=> [Consensus] Mainnet public spend enforcement height set.

src/util.h
Backport of https://github.com/bitcoin/bitcoin/pull/9963/commits/3b092bd9b6b3953d5c3052d57e4827dbd85941fd
The logging code from bitcoin is really far away from ours so I won't try to catch up here. But this basic change avoids crashing in instances where we try to log or error but the message is miscontructed with too many or not enough arguments. Like this: ``return error("str1: %s.\n", str1, str2);``
=> [Log] Handle errors during log message formatting

src/libzerocoin/CoinSpend.cpp, src/libzerocoin/CoinSpend.h, src/zpiv/zpivmodule.h
Just a minor compiler warnings cleanup.
=> [Cleanup] compiler warnings in coinSpend object.

src/Makefile.test.include, src/addrman.cpp, src/addrman.h, src/test/addrman_tests.cpp
Backport of bitcoin#6720 and bitcoin#7212
- Adds several unittests for CAddrMan and CAddrInfo.
- Makes small modifications to CAddrMan to allow deterministic and targeted tests.
- Increases the accuracy of CAddrMan tests.
- Removes non-determinism in tests by overriding the random number generator.
- Extracts testing code from addrman class to test class.
One more step for #799.
=> [Tests] Add tests for CAddrMan

src/Makefile.am
This adds extra paths that were left out and ensures that `.gcda` and `.gcno` files are properly cleaned up.
Simple way to test this is to run the following chain of commands both without and with the changeset:
```
./configure --enable-lcov
make
make clean && make distclean
find . -name "*.gcno"
```
Without this, there are leftover (non-cleaned) `.gcno` files, which could cause errors due to stale or fragmented/incomplete information when attempting to generate the coverage report (`make cov`). With this change, the `find` command shows that no such `.gcno` files remain after cleaning.
This all requires that `lcov` is available on the system, as `configure` will properly error out when using the `--enable-lcov` option if it isn't found.
=> [Build] Clean all coverage files during make clean

src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp
This PR is for issue #793
Hides zPIV options when wallet is disabled (`disablewallet`).
Main tab:
Display tab:
=> [QT] Options UI cleanup

src/main.cpp
A timing window exists where a wallet could be creating a new block from within the miner thread when a new block is received to the wallet.  This window will create a situation where TestBlockValidity() fails because the chain tip has changed between the time it created the new block and the time it tested the validity of the block.  
This situation would result in the wallet being asserted; however this is a little overkill.  rather than asserting if the tip has changed, it is better to throw the block away.
This problem was revealed during a testnet test of an altcoin, and very prevalent when multiple wallet existed with the exact same number of staking coins received in the same transaction; or when multiple wallets were staking the same coins via import private key.  The problem …
=> [Staking] Don't assert if we were beaten to the block

contrib/macdeploy/detached-sig-create.sh, contrib/macdeploy/fancy.plist
The app bundle's filename is `PIVX-Qt.app`, not `Pivx-Qt.app`.
=> [Build] Fix app name casing in mac deploy related files

contrib/gitian-descriptors/gitian-linux.yml, contrib/gitian-descriptors/gitian-osx-signer.yml, contrib/gitian-descriptors/gitian-osx.yml, contrib/gitian-descriptors/gitian-win-signer.yml, contrib/gitian-descriptors/gitian-win.yml
Bumps the gitian build versions to 3.3, which should have been done
right after 3.2 was branched off.
At the same time, update to python3 explicitly and allow for some better
error reporting.
=> [Gitian] Bump gitian build versions

src/libzerocoin/bignum_gmp.cpp
Fix a memory leak.
Before: (https://gist.github.com/Warrows/755c33593a74addcfedbe3cd5a9b8eb4)
```
==10580== LEAK SUMMARY:
==10580==    definitely lost: 8,080,863 bytes in 133,017 blocks
==10580==    indirectly lost: 0 bytes in 0 blocks
==10580==      possibly lost: 288 bytes in 1 blocks
==10580==    still reachable: 2,224 bytes in 10 blocks
==10580== suppressed: 0 bytes in 0 blocks
```
After: (https://gist.github.com/Warrows/ab3b40e7b8e56bf0570923f77715f922)
```
==10478== LEAK SUMMARY:
==10478==    definitely lost: 160 bytes in 1 blocks
==10478==    indirectly lost: 0 bytes in 0 blocks
==10478==      possibly lost: 288 bytes in 1 blocks
==10478==    still reachable: 2,224 bytes in 10 blocks
==10478==         suppressed: 0 bytes in 0 blocks
```
=> [zPIV] Free memory from ToString()

src/kernel.cpp, src/kernel.h, src/main.cpp
Two checks on the age of a transaction used to stake were removed by mistake in 3b778f5. We reintroduce them here. 
2621b7f is a bit of refactoring
105ee5f is the real change
88705a6 avoid checking blocks already in the blockchain
=> [Consensus] Time checks

src/chainparams.cpp
1. `1106100` height that zc public spends became available
2. `1112700` random recent testnet block that meets criteria
=> [Net] Add a couple new testnet checkpoints

.travis.yml, .travis/test_06_script_b.sh, test/functional/test_runner.py
Backport of https://github.com/bitcoin/bitcoin/pull/14504, https://github.com/bitcoin/bitcoin/pull/14569 and https://github.com/bitcoin/bitcoin/pull/15466.
This should help to see which test takes too long or blocks travis when it hangs because of the 50 minutes limit.
=> [Travis] Show functional tests progress

contrib/devtools/github-merge.py
Pulls in further updates to the script from upstream since #921 was
merged.
Most notably, this allows for shorter commit hashes in ACK/utACK comments/reviews
=> [Scripts] Sync github-merge.py with upstream

configure.ac
Compilation with openssl version more recent than 1.0.1 is not advised but still possible. We need to let self compilers know about that.
=> [Build] Add info about '--with-unsupported-ssl'

src/primitives/transaction.h
'==' and '!=' operators in CMutableTransaction are never used explicitly.
Them being used implicitly is probably what causes #510. There is no good reason to keep them and BTC removed them here: https://github.com/bitcoin/bitcoin/pull/13443
Should fix #510
=> [Wallet] Remove (explicitely) unused tx comparator

src/main.cpp, src/net.cpp, src/net.h, src/rpc/budget.cpp, src/rpc/misc.cpp
"monthly" instead of "monthy"
"budget" instead of "buddget"
Also included "std::" on the throw runtime_error for a smoother merge with #949
=> [Trivial] typo fixes

src/init.cpp, src/miner.cpp, src/miner.h, src/net.cpp
This moves the implementation function and thread creation to a more
appropriate file (`miner.cpp`).
Resolves #938
=> [Refactor] Move ThreadStakeMinter out of net.cpp

test/functional/test_runner.py
Fixes https://github.com/PIVX-Project/PIVX/issues/960
Rationale: the test result should be set only through `assert`s in the test and not rely on what's printed on the console. Furthermore, as shown in the issue, stderr could contain simple warnings that don't affect the test's outcome.
If stderr is not empty though, print its content.
Also re-sort tests by duration.
=> [Trivial][Tests] Do not fail test when warnings are written to stderr

src/rpc/budget.cpp
- [Refactor] Move common budget parameter checking code into a function
The code in both `preparebudget` and `submitbudget` used the same parameter checking.  This pulls that parameter checking and loading into a common routine used by both; for ease of improvements and adjustments to the parameter checking... so the risk of not adjusting them consistently in both routines is removed.
The early discussion below is based on a combined PR that addressed this, plus #950 and a PR to be named later.  The decision was made to split and focus; so the discussions can be independent of each other and refactor as needed.
=> [Refactor] Combine parameter checking of budget commands

src/masternode-payments.cpp
On the rare occasion that a small UTXO wins a stake; and that user has (by lack of understanding, or by error) configured a very small StakeSplitThreshold; they can end up in a situation where their extremely lucky stake win fails at consensus because of the way the stake split is calculated.
The logic split the block reward between the two outputs; along with the input.  However if that input is significantly small, and the block reward is significantly weighted to the masternode; then the potential for a negative (and thus very very large) output would be created in the second side of the split.  This is due to the fact that the full masternode reward is taken out of the "previous" output (`vout[i - 1]`).
This is a rare, if not relatively impossible, scenario with PIVX at it's current …
=> [Staking] Prevent potential negative out values during stake splitting

src/qt/transactionrecord.cpp, src/zpiv/zpivmodule.cpp, src/zpiv/zpivmodule.h
Essentially the crash happens when the wallet.dat file contains a zc public spend transaction (input) and the user have removed the chain data.
Specifically inside the `decomposeTransaction` in the `TransactionRecord` class the wallet tries to parse the `publicCoinSpend` looking for every output that is linked to the transaction, as there is no information about the output in disk, the wallet throws a runtime error on the startup blocking the initialization (only two ways to surpass this issue for current users: 
1) Download the snapshot. 
2) Start the wallet with another wallet.dat file and let it sync until the required output data is downloaded).
--------
Use only the coin spend serial and not try to parse + validate the whole object, there is no need to do it there, if the transaction …
=> [Wallet][zPIV] zc public spend parse crash in wallet startup.

src/chainparams.cpp, test/functional/rpc_spork.py, test/functional/test_framework/messages.py, test/functional/test_framework/util.py, test/functional/test_runner.py
This adds a first basic functional test for the spork RPC.
The spork key for RegTestNet is updated, and the relative private key is provided in the comment so anyone is able to test (prior to this, there was no public key set for RegNet so it inherited the TestNet value).
=> [Tests] Add Spork functional test and update RegTest spork key

src/rpc/budget.cpp
- [RPC] Fix potential wallet crashes in budget commands
- [RPC] Remove unnecessary conditionals in parameter checking of budget commands
**wallet segfault**
`preparebudget`, invoked before the wallet has fully started, caused a segfault and crashed.  This was due to the lack of checking for `pwalletMain` before referencing cs_wallet.  This is solved with a throw error to tell the user to try again after the wallet has started.
Furthermore; both `preparebudget` and `submitbudget` has a check for `pindexPrev` to conditionalize the assignment of nBlockMin (which references `pindexPrev->nHeight`); however later checks, `pindexPrev->nHeight` is referenced even if the pindexPrev check failed; which would have caused a crash if pindexPrev was NULL.  This would occur if `chainActive->Tip()` …
=> [RPC] Correct issues with budget commands

src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/pow.cpp
GetNextWorkRequired() was not setting the work required properly on the first Proof of Stake block.  The code section to cap the work at the bnTargetLimit wasn't called on that first block, but rather on the second Proof of Stake block.
The end result is that the first PoS block uses the difficulty from the PoW, rather than capping it at the target limit; with the second PoS block capping it at the target limit:
`uint256 bnTargetLimit = (~uint256(0) >> 24);`
Creating a difficulty problem should the final PoW difficulty be greater than bnTargetLimit.
---
This code has been tested on an altcoin; and I can provide debug output demonstrating the shift of the TargetLimit to 00000FFFF the block after the first PoS block should it be desired.
=> Modify GetNextWorkRequired to set Target Limit correctly 

src/init.cpp
This isn't used in PIVX since none of our clients are running with Bitcoin Core's old block file structure, time to kill it?
=> [Wallet] Remove Bitcoin Core 0.8 block hardlinking

src/rpc/budget.cpp, src/utilstrencodings.cpp, src/utilstrencodings.h
[RPC] Require valid URL schemes (URLs starting with "http" or "https") on preparebudget and submitbudget.
The budget proposal system did not have any checks on the URL aside of string length.  This allowed for the scheme to be left off the URL; which on some browsers, resulted in the link to fail when clicked:
```
gio: file:///home/CaveSpectre/forum.pivx.org/index.php%3Fthreads/bizdev-proposal-john-m.285: 
Error when getting information for file “/home/CaveSpectre/forum.pivx.org/index.php?
threads/bizdev-proposal-john-m.285”: No such file or directory
```
The included PR changes the `submitbudget` and `preparebudget` rpc commands to prevent inadvertent omissions of the URL scheme (http:// or https://).  
Qt changes to fixup the existing & historical budget URLs will be submitted as a …
=> [RPC] require valid URL scheme on budget commands

src/miner.cpp, src/miner.h, src/rpc/mining.cpp
- [Mining] Unnecessary mining threads now exit after PoS has begun
- [Staking] The staking thread dormancy is more efficient during PoW
- [Performance] Some unnecessary processing in the mining thread removed
- [RPC] setgenerate errors if attempted to turn on after end of PoW
- [Build] Wallet only routines conditionalized in miner.h
- [Refactoring] Log messages with bitcoin named routines changed for easier rename of routines in the future.
In order to better explain the changes in this PR, a review of the existing code would be helpful.
When fixing a PIVX forked coin's transition from PoW to PoS, it was observed that mining threads go into tight infinite loops after the switch to proof of stake.  This can be seen with a  simple `pivx-qt -testnet -gen`, and watching the debug log.
This …
=> [Staking] Modify miner and staking thread for efficiency

src/miner.cpp, src/miner.h, src/rpc/mining.cpp
This fixes the calls to `CreateNewBlockWithKey` with PoS blocks, which are not needed.
We simply call `CreateNewBlock` with an empy script for coinbase.
It should prevent the problem described in https://github.com/PIVX-Project/PIVX/pull/956#issuecomment-520166966
=> [Miner] Don't create new keys when generating PoS blocks

src/chainparams.cpp, src/chainparams.h, src/kernel.cpp, src/main.cpp, src/main.h, src/wallet/wallet.cpp
There is a bug occurring sometimes on regtest where a block is not accepted due to `CheckStakeKernelHash() : min age violation`.
This is because the min age requirement for RegTest was changed (in https://github.com/PIVX-Project/PIVX/pull/812) inside `Stake` but not in `CheckProofOfStake` (the error indicates also the  wrong function).
This fixes it and moves `nStakeMinAge` to chain params (instead of having it as rogue external variable) and sets it to `0` for RegTest (for consistency).
Also fixes the error messages in kernel.cpp.
=> [Refactor] Fix stake age checks for regtest

src/wallet/db.cpp
Straightforward change, the variable is been cleaned before the logging. Temp variable copy to be able to print it.
=> [DB] Db runtime error cleaning the variable that needs to be logged

contrib/gitian-build.py
Verifying MacOS signatures failed because the verifying script used the wrong OS as path to the binaries.
=> [Build] Fix wrong argument when verifying MacOS signatures

src/qt/pivx/mnmodel.cpp
In the event that masternode.conf contains invalid TXIDs, return early
instead of trying to further process, and thus avoiding a segfault.
=> [Qt] Guard MN tab from possible missing TXs in masternode.conf

src/qt/coincontroldialog.h, src/qt/pivx/send.cpp
At the moment, after the coin control is opened for the first time, subsequent attempts to open coin control do not give an up-to-date view of available coins.
A toggle between 'List mode' and 'Tree mode' will result in the expected update but this should not be required. This pull request will resolve this issue by calling updateView upon every opening of coin control.
**Note:** #1011 is a closed pull request for the same issue, whereby I was having difficult squashing old commits from another, yet to be merged, pull request - I had used master branch for the changes for that PR.
=> [GUI] Refresh coin control upon reopening

configure.ac, src/bip38.cpp, src/init.cpp, src/qt/forms/rpcconsole.ui, src/qt/paymentrequestplus.cpp, src/qt/paymentserver.cpp, src/qt/rpcconsole.cpp, src/qt/test/paymentservertests.cpp, src/util.cpp, src/wallet/rpcdump.cpp
Up until now we've been checking for OpenSSL version at configure time. It turns out that it's not needed anymore. We still use OpenSSL in a few places, but it's not consensus critical anymore.
So this PR removes the check at configure time and cleans up a few places where includes were done of OpenSSL unnecessarily.
=> [Build] Remove OpenSSL 1.0 check

src/masternode.cpp, src/masternode.h
The new message format was introduced with protocol 70914 (v3.1.0) and the old message was retained in order to be able to still check against it during the update.
After 4 more protocol upgrades we can safely assume that no masternode has MNANNOUNCE message signed with the old format so we can remove it from the code.
The function `GetOldStrMessage()` is removed and `GetNewStrMessage()` is renamed to `GetStrMessage()`.
=> [Consensus] Remove Old message format in CMasternodeBroadcast

src/masternode-payments.cpp, src/stakeinput.cpp, src/wallet/wallet.cpp
- [Staking] Staking inputs are now split into 2 or more outputs based on the stake split threshold
For ease of rebasing; and for cleaner testing; this PR is built on top of PR #952 and will need adjustments if PR #952 has changes.
The common function of `stakesplitthreshold` is to break a stake that has grown large into two outputs, splitting them in half.  It is assumed the size of the split is based on the users amount of coins they are staking, and they desire their staking UTXOs to be sized between their stake split threshold and 2 times that stake split threshold.
This design falters when a stake UTXO is a multiple of the stake split threshold; causing repetitive halving until all outputs reach below twice the stake split threshold.  
For example, with a stake split threshold of …
=> [Staking][Wallet] Add Multi-Split functionality to stake output splitting

build-aux/m4/bitcoin_qt.m4, depends/packages/qt.mk, src/qt/askpassphrasedialog.cpp, src/qt/askpassphrasedialog.h, src/qt/pivx.cpp, src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/dashboardwidget.h, src/qt/pivx/loadingdialog.cpp, src/qt/pivx/loadingdialog.h, src/qt/pivx/privacywidget.cpp, src/qt/pivx/prunnable.h, src/qt/pivx/pwidget.cpp, src/qt/pivx/pwidget.h, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/transactiontablemodel.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Rationale
When the splash screen finishes loading and the wallet is big enough (wallet.dat with lot of transactions), the UI gets frozen for a large period of time processing data in the main thread.
To solve it, two improvements were done:
1)  Parallelization of the transactionTableModel initial loop (for-each loop over every wallet transaction to generate the TransactionRecord list that is used in the UI).
2) stakeFilter in dashboard widget and txFilter in the privacyWidget sort speed drastically improved, done after the editRole and filter type flag set to not do it over all of the transactions and not do it twice in any of the filter flag set list invalidation.
Test environment:
- Wallet with:
- 4,400,00 tPIV (4.4kk).
- 40,150 ztPIV (40k)
-  104,000 transactions (104k). 
- Computer …
=> [Performance][Wallet][QT][Model] TransactionTableModel multi-thread initialization + tx filter sort speed improved.

CMakeLists.txt, src/crypto/common.h, src/qt/CMakeLists.txt
instead of using the ambiguous `endian.h` header include in `crypto/common.h`, specify our in-tree intermediary header. At the same time, make use of `config/pivx-config.h` and fixup the CMake builds on linux that previously used forced defines.
=> [Build] Use in-tree intermediary endian header

src/coincontrol.h, src/qt/pivx/send.cpp, src/qt/pivx/send.h
As the title says, the screen needed refresh the bottom amounts when the coinControl gets cleaned. Before only happened on the clearAll option and not when the resetCustom button was touched. Now it happen on both.
=> [UI] Send screen, total amounts refresh after custom options cleaned.

src/qt/pivx/send.cpp
straightforward change.
-----
__Before 9228678c09e7f072a050590ca08f4f5074d30a7a__:
-----
__After 9228678c09e7f072a050590ca08f4f5074d30a7a__:
=> [GUI] Update amounts when entry is removed from SendMultiRow

src/qt/pivx/forms/addnewaddressdialog.ui
The `addnewaddressdialog.ui` has a hardcoded address used to draft the UI forms, even when it's cleaned in the view object initialization, it's better to remove it.
=> [GUI][Trivial] Remove hardcoded address.

src/qt/networkstyle.cpp, src/qt/pivx.cpp, src/qt/pivx/forms/splash.ui, src/qt/pivx/pivxgui.cpp, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/pivx/splash.cpp, src/qt/pivx/splash.h
Allows for the window's title to contain `[testnet]` or `[regtest]` as
needed.
Also makes the splash screen a full window.
window with 96b4e09:
window with 4bfb2f6:
=> [Qt] Reintroduce networkstyle to title texts

build-aux/m4/bitcoin_qt.m4, configure.ac
- Remove internal checks for QtSvg and QtCharts in bitcoin_qt.m4
- Properly warn when libqrencode is missing
- Properly warn when QtSvg is missing
- Fix qtchartview.h path to properly detect QtCharts
This should also resolve #1004
=> [Build] Clean up GUI dependency checking

src/init.cpp, src/qt/pivx/qtutils.cpp, src/qt/pivx/qtutils.h, src/utilstrencodings.cpp, src/wallet/wallet.cpp
This removes a few compiler warnings:
uninitialized variables:
<code>
init.cpp:1620:47: warning: ‘nStart’ may be used uninitialized in this function [-Wmaybe-uninitialized]
</code>
<strike>
leveldb/port/port_posix.cc:60:15: warning: ‘ecx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
</strike>
<br>
signed/unsigned int comparison:
<code>
wallet/wallet.cpp:2446:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
</code>
<code>
utilstrencodings.cpp:58:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
</code>
<br>
variables defined/set but not used
<strike>
qt/privacydialog.cpp:710:13: warning: variable ‘nLockedBalance’ set but not used [-Wunused-but-set-variable]
</strike>
<code> …
=> [Cleanup] Get rid of compiler warnings

src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/dashboardwidget.h, src/qt/pivx/loadingdialog.cpp, src/qt/pivx/settings/settingswidget.cpp
PR covering an empty list pointer segfault when the wallet has no stakes on the yearly filtered data when, for some reason, the chart got visible (when it shouldn't as there are no stakes..). It happened to me when was doing a reindex and the internal wallet state is not clear/final.
Plus added a catch all in the background worker to not crash and inform to the user if there was an unexpected error running any UI background task.
=> [GUI] Dashboard chart map first segfault, background task error catching.

src/qt/pivx/privacywidget.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
Small bug with the recently added ability to spend zPIV to multiple addresses.
In `CWallet::CreateZerocoinSpendTransaction` the wallet does not create a destination address when the user does not supply it directly.
Also `convertBackZpiv` passes the generated destination as change address even when there is no change.
This PR restores the previous functionality so that the destination address is created in the wallet's `CreateZerocoinSpendTransaction` and changes `convertBackZpiv` and `PrivacyWidget::spend` so that they pass an empty list.
=> [Wallet] fix CreateZerocoinSpendTransaction with empty addressesTo

.travis.yml
Set the travis build timeout for the longest job to 21mn 40sec.
Set the build timeout for the other jobs back to 33 mn and 20 sec.
This should avoid global 50 mn timeout on the longest job and avoid
having to restart other jobs needlessly.
=> [Travis] Lower timeout for the full test suite

src/init.cpp, src/init.h, src/main.cpp, src/util.cpp, src/util.h, src/wallet/wallet.cpp, src/wallet/wallet.h
* OS memory allocation fail handler.
* OS signal handler registration method created to remove code duplication.
* AppInitBasicSetup() method created, better code organization of the wallet initialization setup step (step 1).
* Stop loading block indexes if wallet shutdown was requested.
=> [Startup][Refactor][Backport] Memory allocation fail handler + init step 1 refactored.

CMakeLists.txt, src/Makefile.am, src/Makefile.test.include, src/chainparams.cpp, src/consensus/merkle.cpp, src/consensus/merkle.h, src/init.cpp, src/main.cpp, src/miner.cpp, src/primitives/block.cpp, src/primitives/block.h, src/rpc/server.cpp, src/rpc/server.h, src/test/accounting_tests.cpp, src/test/merkle_tests.cpp, src/test/miner_tests.cpp, src/test/pmt_tests.cpp, src/wallet/db.cpp, src/wallet/db.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp, src/wallet/walletdb.h, src/zpiv/zpivwallet.cpp, test/functional/test_runner.py, test/functional/wallet_abandonconflict.py, test/functional/wallet_txn_clone.py, test/functional/wallet_txn_doublespend.py
This pull request is a happy melting pot of improvements regarding transactions handling. Most of them are backports from bitcoin. I advise reviewers to check the code of the different commits independently to understand them more easily. However, testing is probably better done all at once.
I am making a single pull request because these changes are all entangled and introducing some of them without others would probably introduce temporary bugs.
- 6c3e2ac backport of bitcoin#6550
- 5304fdf backport of bitcoin#6508
- c3eeeac simple code move from the header to the cpp file. It contains no functional change.
- 6cc4d37 backport of bitcoin#4805 
- 10be1db backport of bitcoin#7105
- 8a34c32 backport of bitcoin#7306
- 3caf123, 9e17178 and 240f5b4 are the backport for bitcoin#7312
- ad6d0b1 …
=> [Wallet] Various transaction handling improvements

src/rpc/budget.cpp, test/functional/rpc_budget.py, test/functional/test_runner.py
Adds new regression testing for the following RPC budget commands:
- `preparebudget`
- `submitbudget`
- `getbudgetinfo`
=> [Tests] Add RPC budget regression tests

src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/qt/walletmodel.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Fix a few inconsistencies with `GetDepthInMainChain` returning 0 where a value -1 was expected (for orphans) and a bug where nodes may relay coinstake transactions.
=> [Bug] Fix GetDepthInMainChain returning 0 when tx is not in mempool

.travis.yml
This shifts the cmake stage up so as to run between the lint and test stages.
Rationale here is to reduce the need to manually restart the cmake tests due to job timeouts experienced in the standard autotools/depends stage.
The cmake stage is still allowed to fail, and will simply move on to the next stage if a failure occurs.
Also adjusted a some of the autotools builds to explicitly build the GUI front end
=> [TravisCI] Run CMake tests earlier

.travis.yml
Fix a mistake from #1023 preventing the full test build to use its custom timeout.
=> [travis] Update .travis.yml

src/kernel.cpp, src/wallet/wallet.cpp, test/functional/test_runner.py, test/functional/wallet_reorg-stake.py
Additional bug introduced with the changes of #970 (and not caught in #1040 even though the culprit is the same: `GetDepthInMainChain` returning a value `0` when `-1` was expected).
After a block reorganization, the coins used as coinstake inputs in the orphan chain were still marked as spent in the wallet. Thus there were inconsistencies in the balance (either displayed in the GUI or returned by `getbalance` via CLI) and missing utxos in the wallet (either accessed through coincontrol in the GUI or returned by `listunspent` via CLI).
https://github.com/PIVX-Project/PIVX/pull/1043/commits/a0285e45285d1216ead70446d5ece3ab934b243d fixes it by marking as "spent" the inputs of not-in-mempool txes only for non-coinstakes (coinstakes don't hit the mempool so, when not in chain, their inputs …
=> [Wallet][Tests] Fix bug re-adding orphan coinstake's inputs to the wallet

CMakeLists.txt, src/Makefile.am, src/activemasternode.cpp, src/chain.h, src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/main.cpp, src/masternode-budget.cpp, src/masternode-budget.h, src/masternode-payments.cpp, src/masternode-payments.h, src/masternode.cpp, src/masternode.h, src/masternodeconfig.cpp, src/masternodeconfig.h, src/masternodeman.cpp, src/messagesigner.cpp, src/messagesigner.h, src/obfuscation-relay.cpp, src/obfuscation-relay.h, src/obfuscation.cpp, src/obfuscation.h, src/qt/proposalframe.cpp, src/rpc/budget.cpp, src/rpc/masternode.cpp, src/spork.cpp, src/spork.h, src/swifttx.cpp, src/swifttx.h
Sign the following messages based on the hash of their binary content instead of their string representation:
* masternode payment winner
* masternode ping
* budget vote
* finalized budget vote
* consensus vote
* masternode broadcast
* obfuscation relay
* spork message
=> [Consensus] New signatures for network messages

CMakeLists.txt, src/Makefile.am, src/chainparams.cpp, src/chainparams.h, src/libzerocoin/AccumulatorProofOfKnowledge.cpp, src/libzerocoin/Coin.cpp, src/libzerocoin/Coin.h, src/libzerocoin/CoinRandomnessSchnorrSignature.cpp, src/libzerocoin/CoinRandomnessSchnorrSignature.h, src/libzerocoin/CoinSpend.cpp, src/libzerocoin/CoinSpend.h, src/libzerocoin/Commitment.cpp, src/libzerocoin/ParamGeneration.cpp, src/libzerocoin/bignum.h, src/libzerocoin/bignum_gmp.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/test/zerocoin_transactions_tests.cpp, src/wallet/wallet.cpp, src/wallet/walletdb.cpp, src/zpiv/accumulatormap.cpp, src/zpiv/accumulators.cpp, src/zpiv/witness.cpp, src/zpiv/zpivmodule.cpp, src/zpiv/zpivmodule.h, test/functional/zerocoin_valid_public_spend.py
This PR proposes (as hard fork) a new PublicCoinSpend protocol suitable to be used also with zerocoins version 1. Closes https://github.com/PIVX-Project/PIVX/issues/937
Motivation and overview in the following document:
https://github.com/random-zebra/PIVX-Wiki/blob/master/Developer-Documentation/Specs/zPIV/CoinRandomnessSchnorrSignature.mediawiki
Enforcement height uses placeholder values (one million blocks after the activation of spends v3 for main net and testnet, and 100 blocks for regnet).
Changes
- replaces many instances of `CBigNum(0)`, `CBigNum(1)`, `CBigNum(2)` throughout the code with fixed constants defined in bignum.h.
- defines the `CoinRandomnessSchnorrSignature` using the algorithm described in the [wiki](https://github.com/random-zebra/PIVX-Wiki/blob/master/Developer-Docu …
=> [zPIV] PublicCoinSpend v4 - Coin Randomness Schnorr Signature

doc/Doxyfile.in
Pre-process source files by searching for comment strings containing
`TODO` or `FIXME` and replacing with the doxygen `\todo` flag.
This is an internal conversion only, and won't change the source view of
affected files.
=> [Doxygen] Generate Todo list

src/qt/forms/coincontroldialog.ui
Making this widget focusable allows for using the keyboard to navigate
and select inputs using the arrow keys and spacebar.
=> [Qt] Make CoinControlTreeWidget focusable

src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/spork.cpp, src/spork.h, src/sporkid.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, test/functional/feature_coldStaking.py
This is based on top of https://github.com/PIVX-Project/PIVX/pull/955 (only the last commit, 5a6eab590505d409481ee3f385d65b09f40bb8fd , is relevant for this PR).
It sets Cold Staking activation via SPORK instead of having it height-based.
When `SPORK_17_COLDSTAKING_ENFORCEMENT` is **not** active (default), transactions with P2CS outputs are rejected on the network. This way only cold-staking and new delegations are disabled while coin-owners can still spend their coins.
=> [Consensus] Define SPORK_17

src/qt/pivx/masternodewizarddialog.cpp
At the moment, whilst correctly labelled on the masternode.conf file and within the masternode tab, there is no label stored for the actual masternode address generated via the masternode wizard.
The labeling of these addresses with the masternode alias allows for easier identification of the coins within the coin control dialog and the transaction history. where one is easier able to identify whether rewards for any particular node are missing (signalling potential VPS issues).
=> [Wallet] Create label for addresses generated via masternode wizard

src/qt/pivx/sendconfirmdialog.cpp
With windows, the wallet was crashing without any error message or log each time I would click a tx in the overview page. That was happening consistently on one device but not others.
This fix should not lead to any performance concern. As far as I know this function is only triggered by user input in the GUI.
=> [UI] Guard a call to GetDepthInMainChain

src/wallet/wallet.cpp, src/wallet/wallet.h
Refactored and cleaned every `getBalanceXXX` method that was duplicating the same code over and over inside the wallet to a loop over txs lambda based function.
=> [Wallet][Refactor] Updating ancient getbalanceXXX methods to a lambda call.

src/wallet/wallet.cpp, src/wallet/wallet.h
Transaction IsEquivalentTo method backported + mempool duplicated check code cleanup in IsTrusted method.
IsEquivalentTo  comes from btc b2b361926215eadd6bf43ed1d7110b925fc7cae5 .
=> [Wallet] Transaction IsEquivalentTo method backported + code cleanup.

src/main.cpp
Block version 3 is enforced starting at block 1 so rules from version 2 should always be enforced. 
There is no reason to run the (kinda resource intensive) test `IsSuperMajority()`.
=> [Node] Remove a call to IsSuperMajority

src/main.cpp
First block is invalidly verified as a greater than version two block. Can be reproduced reindexing the node.
Thanks @akshaynexus for this comment 👍  .
https://github.com/PIVX-Project/PIVX/pull/1063#issuecomment-547541869
=> [Bug] Fix contextCheckBlock for the first  block that it's a v1 block.

src/chainparams.cpp, src/chainparams.h, src/main.cpp
BIP65 was enabled with block version 5. We now use block version 6 and are about to introduce version 7. It makes sense to save a bit of performance by simply checking for height activation instead of looking
for a super majority.
=> [Node] Replace IsSuperMajority with height checks

src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, test/functional/feature_coldStaking.py, test/functional/wallet_reorg-stake.py
`GetCredit` is wrongly saving the cached amount when `fUnspent` is true. 
The unspent amount is a contextual value, doesn't represent the total tx credit. Just what it's available in a period of time.
=> [Wallet] Do not cache the credit amount if fUnspent is enabled.

src/qt/transactionfilterproxy.cpp
Straightforward change, do not invalidate filter if datetime range is already set.
=> [UI] TransactionFilter, do not invalidate filter if range is already set.

src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
This option is currently not connected to any action; hide it for now.
To be re-connected in the future.
Before:
After:
=> [Qt] Hide option for 3rd party transaction URLs

src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui
Quick fix for the display unit option showing a numeric value when
saving instead of the proper text value.
Before: 
After:
=> [Qt] Show display unit option as text

src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/dashboardwidget.h, src/qt/transactionrecord.cpp, src/qt/transactionrecord.h, src/qt/transactiontablemodel.cpp, src/qt/transactiontablemodel.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h
Instead of ask twice (locking the cs_wallet) if the arriving/updated tx it's a coin stake or not, use the already parsed record and include the flag as an argument into the signal.
This removes the `isCoinStakeMine` and its subsequent `getWalletTx` method call, which locks cs_wallet, making the UI sync update process smoother, preventing any wait or thread interception between locks.
=> [GUI][Model][Performance] Dashboard, remove call to isCoinStakeMine method.

src/qt/pivx/forms/welcomecontentwidget.ui
One-liner in welcomecontentwidget.ui. Closes https://github.com/PIVX-Project/PIVX/issues/1101 .
(As a non-native speaker, I think "whomever" is correct as it refers to the object of the sentence, not the subject).
=> [Trivial][GUI] Fix typos in welcome widget

src/qt/askpassphrasedialog.cpp, src/qt/pivx/settings/settingsbackupwallet.cpp
The mode and context when calling `AskPassphraseDialog::AskPassphraseDialog` from `SettingsBackupWallet::changePassphrase` were switched.
That resulted in
A) the old passphrase was not asked when changing it to a new one
B) the action was not even completed because, during `AskPassphraseDialog::run` it failed `model->setWalletEncrypted` (`CWallet::EncryptWallet` returns false, being the wallet already encrypted).
Closes https://github.com/PIVX-Project/PIVX/issues/1100
=> [GUI] Fix bug in change wallet passphrase

src/masternode-sync.cpp, src/masternode-sync.h, src/miner.cpp
Instead of outright preventing the generation of new blocks when mnsync is incomplete, use a different logic: prevent the creation of new block when:
- mnsync is incomplete
**AND**
- _either_ the spork list is not synced (we are at the very start of mnsync) _or one_ between sporks 8,9 or 13 is active
In other words, try to stake a new block only if
- mnsync is complete
**OR**
- the spork list is synced _and all three_ sporks (8,9 and 13) are not active.
=> [Wallet] Enable miner with mnsync incomplete

src/qt/pivx/coldstakingwidget.cpp
Followup of #1014 for the Cold Staking UI widget
=> [Qt] Refresh coin control when re-opening from CS widget

src/main.cpp, src/main.h
* Not used GetInputAgeIX method removed.
* AcceptToMemoryPool HasZerocoinSpendInputs code duplication.
* Several for loops copying variable cleaned.
=> [Cleanup][Refactor]Main.cpp code cleanup.

src/wallet/wallet.cpp
Stop using the non-locked P2CS outputs as part of the auto combine flow.
=> [Wallet] Do not use p2cs outputs in the autocombine flow.

src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
- qualify as constants the arguments of CWallet's functions:
`IsLockedCoin`, `LockCoin` and `UnlockCoin`.
- Diagnose unsuitable outputs in lockunspent (backports https://github.com/bitcoin/bitcoin/pull/11087)
NOTE: the update to `wallet_basic` functional test for this particular changes will be included in a successive PR (which collects updates for the whole test suite).
=> [Wallet][RPC] Diagnose unsuitable outputs in lockunspent()

src/wallet/wallet.cpp
Straightforward update backported from https://github.com/bitcoin/bitcoin/pull/13160
NOTE: the update to wallet_basic functional test for this particular changes will be included in a successive PR (which collects updates for the whole test suite).
=> [Wallet] Unlock spent outputs

src/qt/pivx.cpp
Fixes the following warning
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.`
Tested on macOS 10.14.6
=> [UI] Fix AA_EnableHighDpiScaling warning

src/qt/pivx/qtutils.h, src/qt/pivx/settings/settingswalletrepairwidget.cpp, src/qt/pivx/settings/settingswidget.cpp, src/qt/pivx/settings/settingswidget.h
After changing a settings option that requires a wallet restart, retain
any command line argument that was passed to the current program session
and pass them to the restarted program session.
Also, address #1114 by allowing the option to postpone wallet restart on settings change.
=> [Qt] Re-work settings restart and saving flow

src/qt/transactionrecord.cpp, src/qt/transactionrecord.h, src/qt/transactiontablemodel.cpp
Remove mapWallet not needed call + stop treating coinbases differently.
Coming from bitcoin@608bbccfb97e5ecb9083ac203642524a6e556e48.
=> [Model][Backport] Remove mapWallet not needed call + stop treating coinbase differently

src/qt/pivx/res/css/style_dark.css
Auto-explainable title, 
The dashboard nav button css class, in the dark theme, is pushing down the icon when the button gets checked, this fixes it.
=> [GUI][BUG] Bad top padding on the dashboard nav icon in dark theme fix.

src/addressbook.cpp, src/addressbook.h, src/qt/addresstablemodel.cpp, src/qt/addresstablemodel.h, src/qt/pivx/addresseswidget.cpp, src/qt/pivx/addressfilterproxymodel.cpp, src/qt/pivx/addressfilterproxymodel.h, src/qt/pivx/coldstakingwidget.cpp, src/qt/walletmodel.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Essentially before there was no flow to store a remote cold staking address and the label field on the delegation screen was not storing the address properly in the address book ('send' purpose which was presenting the address in an invalid format).
This PR has implemented a fully fledged CRUD over the external cold staking addresses. Every of the four actions running on top of the contacts screen and connected to the cold staking screen contacts dropdown.
=> [Wallet][GUI][Model] Cold staking addresses contacts flow.

COPYING, contrib/devtools/copyright_header.py, src/chain.h, src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/kernel.cpp, src/kernel.h, src/libzerocoin/Accumulator.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/pow.cpp, src/timedata.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, test/functional/fake_stake/base_test.py, test/functional/fake_stake/util.py, test/functional/feature_coldStaking.py, test/functional/test_framework/messages.py, test/functional/zerocoin_valid_public_spend.py
Main changes:
- **granularity**: 15 secs, instead of 1
- **future limit**: adjustedTime + 14 secs (current timeslot) instead of 3 mins
- **past limit**: prevBlock time
- **target timespan**: 15 mins (instead of 40)
=> [PoS] Time Protocol v2

share/qt/Info.plist.in
Straightforward change, preventing any macOS dark mode theme forced change.
Coming from btc cf2f4306fe26305b24bba8833af845ada3a42ec8
=> [GUI][Backport] Explicitly disable "Dark Mode" appearance on macOS

src/chain.h, src/chainparams.cpp, src/chainparams.h, src/init.cpp, src/kernel.cpp, src/main.cpp, src/miner.cpp, src/primitives/block.cpp, src/primitives/block.h, src/stakeinput.cpp, src/zpiv/accumulators.cpp
Since the disabling of zerocoin mints, the accumulator values never change anymore.
Last updated checkpoint was at mainnet block 1686240.
Removing the accumulator checkpoints from block headers saves 256 bits per block (both on chain and on the in-memory indexes).
This PR removes the need for CBlockIndex::nAccumulatorCheckpoint (past 1686240) and enforces block version 7 via hard-fork (after `nBlockV7StartHeight` currently set at a placeholder value).
Further changes to CBlockIndex (in order to don't store empty uint256) will be addressed in a subsequent PR.
=> [Consensus] Block version 7: remove accumulators checkpoint

src/qt/pivx/mninfodialog.cpp
This PR fixes the mninfodialog code to copy the pubkey or txid correctly.
=> [UI] Copy correct data from mninfo dialog

src/qt/pivx/loadingdialog.cpp, src/qt/pivx/loadingdialog.h, src/qt/pivx/pwidget.cpp, src/qt/pivx/pwidget.h
This prevents a segfault that is happening most of the time in linux when the QThreadPool auto-delete property forces a deletion of the worker object which runnable is the parent widget that shouldn't be deleted.
Extra information: This has been running fine on the `testnet_multi_pr` branch since we launched the public segregated testnet.
=> [GUI] Prevent worker constant creation and invalid removal

src/qt/pivx/txrow.cpp
The row colors were changing invalidly when the user was scrolling the list and/or just moving along the showed rows. Essentially a bad internal state of the widget properties that needed a forced update to re paint the component using the correct css class.
Solving #1093 .
=> [Bug][GUI] Tx list row amount color changing invalidly.

src/qt/pivx/topbar.cpp, src/qt/pivx/topbar.h
The sync progressBar was not been expanded following the sync expandable button size. This PR fixes it.
Solving #1090
=> [Bug][GUI] Topbar sync progressbar not expanding fixed.

src/chainparams.cpp
`nTimeSlotLength` was set twice to `15`. Line 182 and 192 of `chainparams.cpp`.
=> [Trivial] Remove a duplicate variable definition

src/qt/pivx/topbar.cpp
Prevents negative balance results
Before:
After:
=> [Qt] Fixup topbar balance calculation

src/chainparams.cpp, src/main.cpp, src/timedata.cpp, src/timedata.h, test/functional/p2p_time_offset.py, test/functional/test_runner.py
Open for brainstorming.
Follow up to #1002 
- reject connection with a node having offset higher than 30 secs (and don't add the sample to timedata)
- repeatedly trigger the warning message when the total offset (absolute value) is above 15 seconds (and set the offset to +15/-15 instead of 0).
=> [Consensus] nTimeOffset warning for time protocol V2

src/chainparams.cpp
The changeover block height for new P2P message signatures, new time protocol and v7 blocks is still set at placeholder values (mainnet: `2967000`, testnet: `2214000`).
These need to be changed to the actual values to use.
EDIT: This PR will change only the testnet height. Mainnet will be fixed in a subsequent PR.
=> [Consensus] Define TestNet changeover block for PIVX v4.0 RC

src/qt/utilitydialog.cpp
Straight forward fix to avoid a segfault when running `pivx-qt --help`; which is supposed to simply output the help text to the console and exit.
=> [Qt] Fix segfault when running GUI client with --help or -?

src/qt/pivx/coldstakingwidget.cpp
Cold staking delegation, popup alerting user if the owner address is not from the wallet.
Preview.
=> [GUI] Cold staking, alert user if the owner address is not from the wallet

src/qt/addresstablemodel.cpp
the pointer 'var' in `AddressTablePriv::updatePurposeCachedCounted()` could be uninitialized
(e.g. in the case where purpose = COLD_STAKING). Add a default case.
=> [Bug] Fix segfault on GUI initialization for cold staker wallet

.travis.yml
Functional tests run in travis are given 1700 seconds. We are seeing more and more builds where it's not enough. So change the compile phase timeout to 800 seconds in order to have 2200 seconds for tests or cache the built binaries and restart with a full 3000 seconds for tests. Only for the full functional tests travis build.
=> [Travis] Increase functional tests reserved time

src/qt/pivx/guitransactionsutils.cpp
Not sure if this is good or it needs to be:
> Error: The wallet is unlocked for anonymization and staking only.**\n**Unlock the wallet to send the transaction.
=> [GUI][Trivial] Rewording of Error message when wallet is unlocked for staking only

src/qt/coincontroldialog.cpp, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/transactiontablemodel.cpp
Solving windows issue presented in #1076.
=> [GUI] Decreasing the tooltip padding for #1076 windows issue.

src/qt/pivx/masternodewizarddialog.cpp
In the masternodes creation wizard, IPv6 addresses are not being stored in the `masternode.conf` in the core's expected format. This solves the issue adding the needed brackets.
=> [BUG] Masternodes wizard, IPv6 addresses storage in .conf file.

src/qt/pivx/topbar.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h
If the wallet was already encrypted and it's in an unlocked state, then there is no need to re request the passphrase to "lock" it for staking only, only requirement is set the fWalletUnlockAnonymizeOnly flag to true (flag which should prevent every spending action in the wallet via GUI and RPC).
Issue presented in #1155.
=> [GUI][Model] Do not re request passphrase when the wallet is unlocked.

src/timedata.cpp
Simple update (related to #1128 and #1138).
Clear `strMiscWarning` if the median gets back within the offset limit (after being off, for example during startup when the node has very few time samples).
=> [Trivial] Remove time offset warning when it gets back within range

src/qt/pivx/masternodeswidget.cpp
IPv6 addresses use `:` rather than `.` characters in their notation,
so needed to change the way `externalip` was being copied here.
=> [Qt] properly copy IPv6 externalip MN info

src/qt/pivx/settings/forms/settingsfaqwidget.ui
discord.PIVX.com changed to discord.PIVX.org
=> [Qt] Fix for dead link to wrong PIVX website

src/qt/pivx/coldstakingwidget.cpp
It was invalidly blocking the launch of the dropdown menu for a bad check. Instead of the receive addresses (`sizeRecv()`), was checking against the stored contacts in the address book (`sizeSend()`) .
=> [GUI][Bug] Cold staking screen, fixing show receive addresses list.

src/qt/forms/askpassphrasedialog.ui
This moves the caps lock warning to the bottom line (next to "Ok" button) in the unlock dialog, to make its height fixed and avoid issues of labels partially hidden.
Fixes #1164
=> [GUI][Trivial] move caps lock warning in askpassphrase dialog

src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/forms/sendconfirmdialog.ui
This adds `Expanding` vertical size policy to tx detail dialog and its internal frame to show the full content. 
Closes #1082
=> [GUI][Trivial] Fix tx detail dialog expanding policy

src/qt/pivx/requestdialog.cpp
Default use case is to re-use the same address for multiple delegations. 
Having the amount as a required field, during the address creation, could lead to confusion.
=> [GUI][Trivial] Make amount optional in staking address gen dialog

src/qt/askpassphrasedialog.cpp, src/qt/pivx/addnewcontactdialog.cpp, src/qt/pivx/addnewcontactdialog.h, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/masternodewizarddialog.h, src/qt/pivx/requestdialog.cpp, src/qt/pivx/requestdialog.h, src/qt/pivx/settings/settingsconsolewidget.cpp, src/qt/pivx/settings/settingsconsolewidget.h, src/qt/pivx/settings/settingssignmessagewidgets.cpp, src/qt/pivx/settings/settingssignmessagewidgets.h
Follow up to #1161 .
Fixes focus in `AskPassphraseDialog` when mode is `Encrypt` (in which case the default-focused `passEdit1` is hidden). 
Also applies the same ideology in other instances:
- Receive addresses --> change label
- Receive addresses --> new payment request
- Contacts --> edit contact
- Cold Stake --> Create cold stake address
- Cold Stake --> my staking address --> change label
- Tools --> sign/verify message
- Tools --> BIP38 Tool
- Debug --> Console
- Masternode wizard
Closes #1150
=> [GUI][Trivial] Allow immediate typing in dialogs / tools widget

src/main.cpp
This adds the new spork 17 and 18 (cold staking and v4 public spends) to the fMissingSporks flag to request the sporks if them are missing as soon as possible + move the code below the old protocol validation and connected to ourself check (No need to send the message if we are going to end up disconnecting the socket).
=> [Network] Add SPORK 17 & 18 to the fMissingSporks flag + code reorg.

src/qt/askpassphrasedialog.cpp
Before the new UI it was possible to validate the wallet password by pressing the "enter"/"return" key. We return this simple flow.
=> [GUI] Validate wallet password on enter key press

src/qt/bitcoinunits.cpp, src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/pivx/forms/sendmultirow.ui, src/qt/pivx/requestdialog.cpp, src/qt/pivx/sendmultirow.cpp, src/qt/test/uritests.cpp
Have received reports from linux users experiencing problems with the amount editable box, not being able to write large numbers with decimals (even when the QDoubleValidator decimal limit was set to 8..).
Have checked it in macOS and everything is fine there, so.. the issue is pointing to an internal QT QDoubleValidator class problem that has nothing to do with our UI code in some linux distributions.
To solve it without over complicate the code, have changed the QDoubleValidator for a QRegexValidator. 
Running fine in linux now too here, more eyes are welcome.
=> [GUI] Use QRegexValidator instead of the QDoubleValidator.

src/qt/walletmodel.cpp
Currently coincontrol does not display locked coins if these are delegated outputs.
Thus, after locking a delegated utxo in the owner-wallet and closing coincontrol, said utxo "disappears" and cannot be unlocked later on (until a wallet restart).
This fixes it.
=> [GUI][Bug] Accept P2CS locked coins in coincontrol

src/chainparams.cpp
Sets enforcement at main net block **2153200**
=> [Consensus] Define MainNet changeover block for PIVX v4.0

src/qt/walletmodel.cpp
Currently in the owner wallet, when trying to send coins without selecting the inputs in coin-control, if the algo needs to select p2cs utxos (to reach the required input amount), the user is presented with "transaction creation failed" without any clue about the cause.
This happens because the `fIncludeDelegated` flag of `CreateTransaction` is kept at its default false state in the model.
This fixes it, setting the flag to `true`, thus allowing `AvailableCoins` to pick up p2cs owned utxos too.
The user is still presented the warning whenever a coldstake utxo is about to be spent.
Even though the cold-owner wallet is supposed to be offline (and not a wallet for regular spending), in the future we can modify the flow, presenting delegations locked by default and forcing the user to unlock …
=> [GUI][Wallet] Allow spending of P2CS without coincontrol selection

src/Makefile.qt.include, src/qt/CMakeLists.txt, src/qt/pivx/forms/topbar.ui, src/qt/pivx/forms/welcomecontentwidget.ui, src/qt/pivx/pfborderimage.h, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/pivx/settings/forms/settingsfaqwidget.ui, src/qt/pivx/settings/settingsdisplayoptionswidget.cpp, src/qt/pivx/settings/settingsfaqwidget.cpp, src/qt/pivx/settings/settingswidget.cpp, src/qt/pivx/topbar.cpp, src/qt/pivx/welcomecontentwidget.cpp
In some computers running OSX, gitian deployment seems to not like the `border-image` css property and the deployed binary paint it with pink stripes (this is most likely a missing plugin because local deployment and people running the deployed binaries with QT installed in their systems don't have the issue at all).
To solve this up until gitian problems gets discovered, have created a new component that scales and paints the topbar image on every window resize event (caching the last size) + added a settings option and its visual connection to enable/disable it (this is mainly because not every user has the pink stripes and cause has not been detected to make it visible only for them).
In this way, the users who are running OSX and have the issue, only need to go to settings and check …
=> [GUI] Workaround to the OSX border-image pink stripes.

src/qt/addresstablemodel.cpp, src/qt/addresstablemodel.h, src/qt/pivx/coldstakingmodel.cpp, src/qt/pivx/coldstakingmodel.h, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/coldstakingwidget.h
Currently the label in cold-staking widget states "Total **Staking**:", but then the amount is calculated summing up all the delegated utxos (staking or not).
This fixes it, considering only owned delegations and/or received delegations from whitelisted owners in the sum.
Also, refresh the total amount after a whitelist/blacklist operation (in order to achieve this, the update of the cachedAmount has been separated from the update of the delegations in the model).
=> [GUI] ColdStaking widget: fix "total staking" amount

build-aux/snap/snapcraft.yaml
Snapcraft nightly build version bump. Missed doing this in #1200
=> [Build] Bump snapcraft nightlies to 4.0.99

src/init.cpp, src/qt/pivx/welcomecontentwidget.cpp, src/qt/transactionrecord.cpp, src/wallet/wallet.cpp
Compiler warnings when building off the v4.0 tag
Several different issues:
```
init.cpp: In function ‘bool AppInit2()’:
init.cpp:1442:13: warning: unused variable ‘nStart’ [-Wunused-variable]
int64_t nStart = GetTimeMillis();
^~~~~~
```
```
wallet/wallet.cpp: In member function ‘CAmount CWallet::GetCredit(const CTransaction&, const isminefilter&, bool) const’:
wallet/wallet.cpp:5649:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < tx.vout.size(); i++) {
~~^~~~~~~~~~~~~~~~
```
```
leveldb/util/logging.cc: In function ‘bool leveldb::ConsumeDecimalNumber(leveldb::Slice*, uint64_t*)’:
leveldb/util/logging.cc:58:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
(v == kMaxUint64/10 && delta > …
```
=> Clean up 4.0 compiler warnings

src/wallet/walletdb.cpp
Large wallets suffer from long loading times as it is, this call to
`CheckTransaction()` just adds to that loading time.
Further improvements of the wallet database load process need to be investigated as large wallets still suffer from very long load times.
Also, if there is an absolute need to check the validity of a transaction contained in the wallet's on-disk file (beyond the hash check), it could be handled elsewhere.
=> [Wallet] Remove un-necessary CheckTransaction call when loading wallet.

src/init.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/rpc/mining.cpp
This comes from upstream PR 12743.
* Best block hash cached for miner thread usage (preventing one of the many many cs_main locks..).
* csBestBlock, cvBlockChange names updated to latest upstream naming convention.
=> [Backport][Performance] Cache + guard best block hash.

src/rpc/budget.cpp
`CBudgetVote` object in `mnbudgetrawvote` is initialized with default nMessVersion (`MessageVersion::MESS_VER_HASH`). Thus the signature validation fails when the user provides an external signature performed over the old message format.
=> [BUG][RPC] fix signature check (against old format) in mnbudgetrawvote

src/qt/guiutil.cpp, src/qt/pivx/addresseswidget.cpp, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/forms/addresseswidget.ui, src/qt/pivx/forms/coldstakingwidget.ui, src/qt/pivx/forms/masternodeswidget.ui, src/qt/pivx/forms/masternodewizarddialog.ui, src/qt/pivx/forms/mninfodialog.ui, src/qt/pivx/forms/privacywidget.ui, src/qt/pivx/mninfodialog.cpp, src/qt/pivx/privacywidget.cpp, src/qt/pivx/receivewidget.cpp, src/qt/pivx/requestdialog.cpp, src/qt/pivx/send.cpp, src/qt/pivx/sendchangeaddressdialog.cpp, src/qt/pivx/sendmultirow.cpp, src/qt/pivx/settings/forms/settingsfaqwidget.ui, src/qt/pivx/settings/forms/settingsmultisendwidget.ui, src/qt/pivx/settings/settingsbackupwallet.cpp, src/qt/pivx/settings/settingsbittoolwidget.cpp, src/qt/pivx/settings/settingsinformationwidget.cpp, src/qt/pivx/settings/settingsmultisenddialog.cpp, src/qt/pivx/settings/settingssignmessagewidgets.cpp, src/qt/transactiontablemodel.cpp
Only labels and text. No functional changes.
Minor edits, mostly for capitalisation consistency.
=> [GUI][Trivial] Minor edits to written content

src/kernel.cpp
This is not an error, the function should just return false. No need to spam the debug.log.
This will become a non-issue after time v2 enforcement, but better to fix it anyway.
=> [Trivial] Remove spammy log in in StakeV1

src/wallet/wallet.cpp
To explain the reason that forced me to hunt this for over a week..
In huge wallets (+100k txs wallets) the 4.0 startup time is taking +30 minutes. Which is crazy long and sounded much more as a regression over 3.4 which was taking less than 10 minutes.
Root cause:
After some time (and improvements over different areas #1217), found that the `IsEquivalentTo` method is adding an extra round of serialization + hash calculation on every transaction that is loaded into the wallet. Which gets really, time-wise, expensive in big wallets for a small benefit.
Test:
Environment:
- Wallet with 419,633 db records.
- MacOS i7, 16gb ram.
Pre-PR transactions load time:
30 minutes and i got bored and killed the process..
Post-PR transactions load time:
34.369 seconds.
For now, decided to just comment it …
=> [Wallet] IsEquivalentTo commented, removing an extra round of ser+hash calculation.

src/init.cpp, src/qt/pivx/addresseswidget.cpp, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/privacywidget.cpp, src/qt/pivx/receivewidget.cpp, src/qt/transactiontablemodel.cpp
Made several changes in order to improve the wallet startup and navigation performance in huge wallets (wallets with more than 20,000 transactions).
&nbsp;
1) Maximum amount of loaded transaction records in the GUI set to 20,000. 
* If the wallet has more, then it will not load them into the UI anymore. Hard to think that any user will be benefited from having 100k txs that he/she made in 2 years always visible when them are most likely all spent and only the latest 5k txs have utxo.. 
2) Optimized every listview load in the GUI.
* The list items are laid out in batches of a certain size, instead of all of the items loaded at once in the first run.
* Uniform row size flag enabled in every list optimizing their painting.
3) Db verification decreased to 10 blocks.
* Previously our wallet …
=> [Startup][GUI][Performance] Optimizations for huge wallets.

doc/build-unix.md
This addresses a few things in the linux build documentation:
1. Bitcoin's PPA is now unmaintained for newer versions of Ubuntu (last 
supported version was 18.10). The PIVX PPA supports all current Ubuntu 
versions for providing BDB 4.8.30 (including the upcoming Focal Fossa 20
.04 LTS version).
2. Removes the (now)stale note about OpenSSL 1.1 and the removed `--with-unsupported-ssl` configure flag.
3. Adds a note about Qt's charts library availability on older Ubuntu/Debian distro versions.
4. Adds Qt's SVG & Charts libs to Fedora build instructions
=> [Doc] Update build-unix.md file

src/qt/addresstablemodel.cpp, src/qt/pivx/receivewidget.cpp, src/qt/pivx/send.cpp, src/qt/pivx/settings/settingsbittoolwidget.cpp, src/qt/pivx/settings/settingsmultisendwidget.cpp, src/rpc/client.cpp, src/test/rpc_wallet_tests.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
This PR collects a few additions/fixes on the rpc interface to the addressbook.
- 1. First commit adds a optional string argument to `delegatoradd` to include a label (as already available from the GUI interface, and as already shown with `listdelegators` rpc).
- 2. Second commit adds a optional boolean argument (defaulted to `false`) to `listdelegators`. When `true`, the function returns the list of addresses blacklisted (i.e. removed from the whitelist, i.e. with purpose `AddressBookPurpose::DELEGABLE`).
- 3. Third commit fixes the auxiliary function `ListaddressesForPurpose` in order to use the correct Base58Type when called with purpose `COLD_STAKING_SEND` (which currently never happens anyway, but better to have it corrected).
- 4. Last commit removes all the purpose variable strings …
=> [RPC] Add optional arguments to delegatoradd and listdelegators

src/crypter.cpp
Showing the proper error message in screen and permitting the node to shutdown properly.
=> [Wallet] Graceful shutdown in the unlock corrupted wallet.

src/masternode-budget.cpp, src/masternode-budget.h, src/messagesigner.cpp, src/messagesigner.h, src/rpc/budget.cpp
Currently the log is spammed with `ERROR: CheckSignature : ERROR: Unable to find masternode vin` triggered during `CBudgetProposal::CleanAndRemove` and `CFinalizedBudget::CleanAndRemove` when the signature is not even checked.
Since the purpose, as stated in the comment, is to "*remove votes from masternodes which are not valid/existent anymore*"  there is no need to report those as errors in the logs.
Furthermore, those are the only places where we use `fSignatureCheck=false` in `CheckSignature` . This is not needed, we can check directly `mnodeman` and don't call `CheckSignature` (since the signature is **NOT** checked anyway).
This way there is no need to include the boolean argument in the function at all.
=> [Core][Trivial] Don't log missing MNs during CleanAndRemove

src/qt/transactionrecord.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Several improvements on the `updateStatus` method solving the not accepted stake type not set bug, plus performance improvements.
* The transaction record status update was not taking into account the negative depth calculation, neither if it was conflicted, for not accepted coin stakes
* GetDepth method was called in three different ways. 1) GetDepthAndMempool, 2) IsTrusted, 3) GetBlocksToMaturity. This PR unifies every call into a single call to IsTrusted(&depth, &fConflicted).
* Several calls to chainActive->Height unified into a single one in record statusUpdate.
=> [Model][Wallet][Performance] Several changes in txRecord updateStatus.

src/kernel.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/miner.h, src/qt/pivx/topbar.cpp, src/qt/pivx/topbar.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpc/misc.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
This PR cleans up the miner code and streamlines the logic used by the client (both in the RPC and in the GUI) to determine whether the wallet is staking or not. 
Currently it relies on a collection of variables (`mapHashedBlocks`, `nLastCoinStakeInterval`, `nSearchInterval`, etc...) updated in kernel.
These are here replaced with a new class `CStakerStatus`, updated in `CreateCoinStake` (thus directly in wallet), and an instance of  `CStakerStatus` is introduced as member of CWallet. 
This class keeps two variables, `timeLastStakeAttempt ` and `tipLastStakeAttempt`, containing respectively the time of last stake attempt and a pointer to the index of the block upon which last stake attempt was made.
The Staking Status is Active whenever timeLastStakeAttempt is less than
30 seconds in the …
=> [Core] Rework staking status

src/qt/pivx/coldstakingwidget.cpp
Loading of the cold staking delegations list checks to see if `isLoading`
is true, and exit's out if it is. this check is used to prevent double
loading, but on some systems `isLoading` is initialized as `true`, so
the loading of CS delegations will never occur.
This changes to initialization to be explicitly `false`.
=> [Qt] Initialize isLoading to false for CS view

src/rpc/misc.cpp, src/rpc/rawtransaction.cpp, src/wallet/rpcwallet.cpp
First step in removing the internal accounting system. All RPC command
documentation/help output now notates that account arguments are
deprecated.
Ported from https://github.com/bitcoin/bitcoin/pull/5575, with
additional edits where necessary for cold staking related commands that
also used account arguments.
=> [RPC] Notate all account stuff as deprecated

src/qt/pivx/topbar.cpp
Bug emerged for the non-presented masternodes locked balance bug fix. 
The `GetLockedCoins` is counting the delegations by default, same as `GetBalance`. Before, this was badly subtracted by the `GetBalance` minus `GetLockedCoins` and showed in the GUI, which was removing the MNs locked coins balance **and** the double counted delegations.
This PR solves it.
=> [Bug][GUI] Double counted delegated balance.

src/qt/transactiontablemodel.cpp
Fixes a comparator bug when loading the initial `walletTxes` vector.
The design intention is to load the 20k most recent transactions, but it
was loading the first 20k transactions in error, resulting in a
potentially large gap in the UI's transaction history.
=> [Qt][Bug] Load the most recent instead of the first transactions

src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/txrow.cpp, src/qt/transactionfilterproxy.cpp, src/qt/transactionrecord.cpp, src/qt/transactionrecord.h, src/qt/transactiontablemodel.cpp
Send P2CS divided in two types for a better visual treatment.
* P2CSDelegationSentOwner: Is the wallet who delegated the coins and kept the ownership.
* P2CSDelegationSent: Is the wallet who delegated the coins and transferred the coin's ownership to a remote address.
TODO: Add external address stored name (if any) in the record presentation for the `P2CSDelegationSent` txs.
=> [GUI] P2CS transaction divided in two types for visual accuracy.

src/qt/pivx/navmenuwidget.cpp, src/qt/pivx/navmenuwidget.h, src/qt/pivx/pivxgui.cpp
Two simple changes:
1) App's window opening in the smallest possible size if the screen size is lower than our base height.
2) NavMenu was not showing the dashboard button due the new scroll area in the startup, this fixes it.
=> [GUI] Quick minor GUI startup useful changes.

src/wallet/wallet.cpp
Prior to #1223 the total balance was calculated as `balance + delegatedBalance - nLockedBalance`, so the delegations (being part of each term) were counted only once.
#1223 removed `nLockedBalance` (changing the total balance calculation to `balance + delegatedBalance`) thus counting the delegation twice.
#1261 fixed the total balance calculation, removing `delegatedBalance`.
Finally, this PR fixes `nLockedBalance` (even though not part of the total balance anymore). The error is in `GetLockedCoins` which is returning the sum of locked coins **and** cold-stake delegations owned (regardless of their locking state).
=> [Wallet] Don't add P2CS automatically to GetLockedCredit

src/qt/pivx/txrow.cpp, src/qt/transactiontablemodel.cpp
Transactions spending P2CS utxos (voiding the delegations) were not displaying properly both in the staker and the owner wallet.
Although the TransactionRecord was correctly parsed as either `P2CSUnlockOwner` or `P2CSUnlockStaker`, these were never connected in the table model.
This closes #1262, fixing it.
For the moment, it is shown with the same icon as the delegation received and a negative amount in red. 
We can, alternatively, use the "sending" red icon, or (later) design a new one, specifically for this kind of record.
Examples on the staker wallet:
*--Before*
<br>
*--After*
<br>
*--After (with outgoing icon)*
=> [GUI] Connect P2CSUnlockOwner and P2CSUnlockStaker records to the model

src/chainparams.cpp
Add a new checkpoint for the first v7 block for both mainnet and testnet
=> [Core] Update checkpoints for first v7 block

src/rpc/mining.cpp
This removes the PoW loop for PoS blocks in `generate`.
Also removes un-needed variable `nHeightStart` and adds checks for shutdown requests and out-of-bound nonces.
=> [RPC] Remove extra PoW rounds in 'generate'

src/qt/transactionrecord.cpp
1) Cold stakes status was not set properly, there was no immature status set or "xxx blocks to mature" calculated, among other status fields missing.
2) GetCredit method in P2CS in wallets with both private keys is returning the real credit amount doubled because of be summing the cold staking credit and the delegated credit of the exact same utxo.
Quick fix to solve it, only request one of them, not the final solution.
=> [GUI] Transaction record cold staking fixes.

src/qt/pivx/pivxgui.cpp
Minimum window width decreased from 1200px to 1100px.
If there is a need for bigger decrement in the future, could add an option to hide the charts and/or will need to do a major change on the style sizes (fonts, components, images, etc).
=> [GUI] Min window size decreased to 1100px

src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css
When a user has lots of transactions (or other long lists) the scrollbar-handle isn't visible anymore:
The default handle-width of 4 pixel is also to small to be used on touchscreens, so both the default width and the minimum height of the handle are changed to 10 pixel now.
The result looks like this:
=> [GUI] Set width and default minimum scrollbar height

src/activemasternode.cpp, src/miner.cpp, src/qt/walletmodel.cpp, src/rpc/misc.cpp, src/rpc/rawtransaction.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
- 1st commit removes zPIV balance count in `CWallet::MintableCoins()` (as mints cannot stake anymore).
- 2nd commit removes `GetStakingBalance` calls in BitcoinMiner and `getstakingstatus` RPC (thus removing "enoughcoins", leaving only "mintablecoins" field there).
`MintableCoins()` already checks the staking balance and returns false if it is either non-positive or less than the reserve balance.
- 3rd commit removes the depth requirement check from `MintableCoins`, moving it directly in `AvailableCoins` (no need to check for age anymore, only depth).
- 4th commit introduces a performance improvement (which might be significative on wallets with many utxos). Since the only purpose of `MintableCoins` is to verify that there is *at least one* eligible utxo, there is no need to get the whole …
=> [Wallet] Refactor MintableCoins

src/qt/pivx/pivxgui.cpp
This PR (re-) implements the windowtitle-parameter which got somehow lost during the wallet redesign.
=> [GUI] Windowtitle parameter fix

src/main.cpp, src/rpc/misc.cpp, src/zpiv/accumulators.cpp, src/zpiv/accumulators.h, test/functional/mining_pos_coldStaking.py, test/functional/mining_pos_fakestake.py, test/functional/mining_pos_reorg.py, test/functional/rpc_spork.py, test/functional/test_framework/test_framework.py, test/functional/wallet_import_stakingaddress.py, test/functional/wallet_zerocoin_publicspends.py
This is based on top of #1276 and #1277 which should be reviewed before.
`generate_pos` framework function relies on the output of `getstakingstatus` RPC which was recently changed.
Since #1245, "validtime" is not returned anymore (nor it was ever really needed here).
Only things that we need in `generate_pos` are "walletunlocked" and "mintablecoins" (renamed "stakeablecoins").
"enoughcoins" is going to be removed in #1277 , and "haveconnections" is not required on regtest.
This also updates coldstaking test.
=> [Tests][Bug] Fix staking status in generate_pos()

src/activemasternode.cpp, src/chainparams.h, src/kernel.cpp, src/main.cpp, src/masternode-sync.cpp, src/masternode.cpp, src/masternodeman.cpp, src/net.cpp, src/pow.cpp, src/qt/walletmodel.cpp, src/rpc/rawtransaction.cpp, src/stakeinput.cpp, src/timedata.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/zpiv/accumulators.cpp
This removes many explicit checks `Params().NetworkID() != CBaseChainParams::REGTEST` / `Params().NetworkID() == CBaseChainParams::REGTEST` making the code more readable.
=> [Trivial][Cleanup] Add IsRegTestNet() function in chainparams

src/qt/transactiontablemodel.cpp
Fix a double `index` call locking cs_wallet and cs_main twice in every single model record index request.
=> [Model][Performance] Unnecessary double cs_wallet and cs_main lock.

src/wallet/wallet.cpp
Ref: https://github.com/PIVX-Project/PIVX/pull/1263#discussion_r366282577
`GetBlocksToMaturity` returns `0` for txes that are neither coinbases nor coinstakes, so no need to check that before.
There are actually only two places needing this quick cleanup.
Note: there are, instead, several occurrences of `if (IsCoinBase() && GetBlocksToMaturity() > 0)` (i.e. test failing for coinstakes but not coinbases). 
These need further inspection because a change there affects reported balances (e.g. in `CWalletTx::UpdateAmount` or `CWalletTx::GetUnlockedCredit`).
=> [Trivial][Cleanup] Remove extra checks before GetBlocksToMaturity

src/chainparams.cpp, src/kernel.cpp, src/kernel.h, src/miner.cpp
This removes the old StakeV1 function and does some minor optimizations in the miner code (removing redundant signature and IncrementExtraNonce calls).
This is based on top of the following three pull requests and will be rebased after their merge into master.
So, they should be reviewed before this one.
=> [Core] Remove StakeV1

src/init.cpp, test/functional/test_framework/util.py
Ref: https://github.com/PIVX-Project/PIVX/pull/1278#issuecomment-576646698
Hardcoded default `false` value, instead of having it in the config file for the test nodes.
=> [Tests] Set '-staking' disabled by default on RegTest

CMakeLists.txt, doc/release-notes.md, src/Makefile.am, src/kernel.cpp, src/kernel.h, src/main.cpp, src/qt/walletmodel.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/rpc/server.cpp, src/rpc/server.h, src/stakeinput.cpp, src/stakeinput.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/zpiv/zpos.cpp, src/zpiv/zpos.h, test/functional/test_framework/test_framework.py
This removes (now unused) code to produce old zerocoin spends and zPOS stakes.
`CZPivStake` class is replaced with a `CLegacyZPivStake` (moved in new files `zpiv/zpos.*`) used exclusively to validate the chain.
This also refactors `CStakeInput` class, removing the modifier functions (put back in kernel) and cleans up `kernel.*` files, removing old code and reorganizing them.
This PR is based on top of:
and it will be rebased after their merge. Only last **3** commits are relevant
=> [zPIV][Cleanup] Zerocoin Cleanup 2: remove CZPivStake class

src/chain.cpp, src/guiinterface.h, src/init.cpp, src/main.cpp, src/qt/clientmodel.cpp, src/qt/clientmodel.h, src/rpc/blockchain.cpp, src/rpc/server.h
Previously we were updating the chain height polling the back-end every 1000ms, acquiring every single time cs_main lock from the main thread. This commit removes this ugly, and not needed, critical section lock entirely using a signal based update.
Side note: It needs more testing and I'm planning to continue adding improvements to this area (maybe in other PR and not this one, I'm pushing this to have more eyes while I continue moving forward).
=> [ClientModel] Remove polling based chain height update entirely.

src/main.h, src/txdb.h, src/undo.h
This is PR is the second part of breaking up #1209 into individual narrow-focused PRs. Original commit was cherry-picked from @barrystyle's initial pre-squashed branch (reference branch is at https://github.com/Fuzzbawls/PIVX/commits/pr-1209)
Here `CDiskTxPos` and `CBlockUndo` are moved out of `main.h` into more appropriate files, namely `txdb.h` and `undo.h`.
=> [Refactor] Move CDiskTxPos/CBlockUndo to txdb.h/undo.h respectively

src/wallet/wallet.cpp, src/wallet/wallet.h
This introduces a little performance optimization, removing the double call to `GetDepthInMainChain` (ref: https://github.com/PIVX-Project/PIVX/pull/1281#discussion_r369861492).
Note: in a successive PR we should review the LOCKs in this area of the wallet.
=> [Wallet] Add function CMerkleTx::IsInMainChainImmature

CMakeLists.txt, src/Makefile.am, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/main.cpp, src/main.h, src/miner.cpp, src/test/script_P2SH_tests.cpp, src/test/sighash_tests.cpp, src/test/transaction_tests.cpp, src/wallet/wallet.h
This is PR is the third part of breaking up #1209 into individual narrow-focused PRs. Original commit(s) were cherry-picked from @barrystyle's initial pre-squashed branch and then re-squashed (reference branch is at https://github.com/Fuzzbawls/PIVX/commits/pr-1209)
Input commits:
https://github.com/Fuzzbawls/PIVX/commit/90950f18ea2553c0e21aebd58ecb73d1f521da59
https://github.com/Fuzzbawls/PIVX/commit/10b756628297d7ce5e73b7461af12993c5326fd4
---------------
This Moves the basic (non-zerocoin) transaction validation checks away from main.h(cpp) and into the `consensus` subdir. Code move only, no changes to functionality.
This PR conflicts minorly with #1319, and will need to be rebased once that PR is merged, but reviewing is possible now as the conflicts are mostly just matter-of-fact …
=> [Refactor] Move transaction checks out to consensus/tx_verify.cpp

src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/coldstakingwidget.h
Currently `ColdStakingWidget::onDelegateSelected` toggles visibility of `btnMyStakingAddresses` restoring its previous "state" (identified by the right icon class and updated in `ColdStakingWidget::onMyStakingAddressesClicked`).
The list of staking addresses though, remains hidden, regardless of the button state.
Closes #1296
=> [GUI] Restore address list when switching panes in CSwidget

src/rpc/mining.cpp
Small thing that was annoying my existence.
The `generate` rpc command, when the wallet is locked, is returning a "cannot generate block" error like if there were an internal block creation problem when it's not, it's just the wallet locked.
=> [Trivial][Regtest][RPC] generate call failing properly when the wallet is locked

src/net.cpp
Added a delay in the internal clock warning dialog launch to not end up creating dialogs like crazy, lagging the whole wallet.
A secondary thing that did was improve the text readability in the launched dialog.
=> [Net] Do not launch the clock warning dialog like crazy.

src/sync.h
Pretty useful functionality. Pushing it on its own separated PR to be able to use it in several open PRs.
Coming from btc@edfe943.
=> Add WITH_LOCK macro: run code while locking a mutex.

src/kernel.cpp, src/miner.cpp, src/rpc/mining.cpp
Just return the list of hashes for the blocks generated.
This affects only "live" usage of regtest wallet, as the functional tests use the utility function `generate_pos` which calls `generate(1)` and increases mocktime (or adds a `sleep`) when the node can actually stake but can't find a valid kernel at the current time.
=> [RPC][Tests] Don't throw when generate doesn't create all blocks (PoS)

src/chainparams.cpp, src/chainparams.h, src/chainparamsbase.cpp, src/chainparamsbase.h, src/test/base58_tests.cpp, src/test/test_pivx.cpp
This network is un-necessary as our unit test suite can simply be run
with MainNet's parameters, which is basically what we already do.
Minor conflict with #1328 due to that PR having already removed one of the unused methods.
=> [Cleanup] Remove stale UNITTEST network

doc/release-notes.md, src/chainparams.cpp, src/kernel.cpp, src/rpc/blockchain.cpp, test/functional/mining_pos_fakestake.py, test/functional/test_framework/messages.py, test/functional/test_framework/test_framework.py
Based on top of #1291 .
Closes #1309
=> [Tests] Use V2 stake modifiers on regtest

src/checkpoints.cpp, src/checkpoints.h, src/main.cpp, src/main.h, src/miner.cpp, test/functional/wallet_zerocoin_publicspends.py
This removes unneeded checks in AcceptToMemoryPool and cleans up main.cpp file
=> [zPIV][Cleanup] Zerocoin Cleanup 5: further main.cpp cleaning

src/main.cpp
Currently `CheckBlock` skips the masternode (or budget) payment check in coinstakes when `IsInitialBlockDownload()` returns true (essentially when the current best block time is older than nMaxTipAge seconds).
Since, in order to verify the block payee, the masternode list needs to be up to date, `IsBlockPayeeValid`also skips the checks when mnsync has not finished.
`CheckColdStakeFreeOutput` however, does not, so, when the spork list is not updated, SPORK_13 and SPORK_9 cannot be verified (in case of budget payment blocks) resulting in CheckBlock failures with
```
ERROR: CheckColdStakeFreeOutput: Wrong cold staking outputs:
```
(Unless the user doesn't manually set a lower nMaxTipAge to force IsInitialBlockDownload to true).
This fixes it.
=> [Core] CheckColdStakeFreeOutput: skip SPORK checks if mnsync incomplete

src/script/script.h, src/test/script_tests.cpp
=> [Script] Optimize and Cleanup CScript::FindAndDelete

src/main.cpp, src/main.h, src/qt/walletmodel.cpp
auto-descriptive title. 
An increased delay time between GUI polling updates when reindex/import is being executed.
=> [GUI] Do not update the GUI so often when reindex/import is being executed.

src/consensus/tx_verify.cpp, src/main.cpp, src/main.h, src/primitives/transaction.cpp, src/primitives/transaction.h, src/zpiv/zpivmodule.cpp, src/zpiv/zpivmodule.h, src/zpivchain.cpp, src/zpivchain.h
This is built on top of
This removes `CheckZerocoinMint` (mints are disabled since block 1,686,229 and we can rely on checkpoints during IBD). Also does some minor cleanup in zpivmodule/zpivchain
=> [zPIV][Cleanup] Zerocoin Cleanup 6: Remove zerocoin mint checks

src/chainparams.cpp, src/chainparams.h, src/miner.cpp, src/pow.cpp, src/rpc/mining.cpp, src/rpc/misc.cpp, src/wallet/wallet_zerocoin.cpp
The only network where fMineBlocksOnDemand is true is regtest (unittest network was removed in #1330 )
Just use IsRegTestNet function.
=> [Cleanup] Remove MineBlocksOnDemand function in chainparams

src/qt/pivx/navmenuwidget.cpp, src/qt/pivx/pivxgui.cpp
Auto-descriptive title.
if the wallet has not zPIV, the privacy widget is not presented in the screen, nor loaded into ram.
=> [GUI] Hide privacy widget when the wallet has no zPIV balance

src/qt/pivx/forms/topbar.ui, src/qt/pivx/topbar.cpp
Since there will be no **new** zerocoins anymore, there is no need to
take up UI space with zero value zerocoin balance information.
This hides the related UI labels if/when the wallet doesn't have any zerocoin
balance.
Before:
After:
=> [Qt] Hide zPIV balances when they are zero

CMakeLists.txt, src/Makefile.am, src/chainparams.cpp, src/chainparams.h, src/consensus/params.h, src/init.cpp, src/kernel.cpp, src/main.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/txmempool.cpp, src/wallet/wallet.cpp
This is PR is the forth part of breaking up #1209 into individual narrow-focused PRs. Original commit(s) were cherry-picked from @barrystyle's initial pre-squashed branch and then re-squashed (reference branch is at https://github.com/Fuzzbawls/PIVX/commits/pr-1209)
Input Commits:
https://github.com/Fuzzbawls/PIVX/commit/041c9ee39d8c1e4ae414a6eb858dbea6db7ab367
https://github.com/Fuzzbawls/PIVX/commit/5d7e61ca85f434a077e2fd7cd5c83b36c4dce322
https://github.com/Fuzzbawls/PIVX/commit/cf696e41add2f7747be6ff161b20e52e8af68445
https://github.com/Fuzzbawls/PIVX/commit/18ab8ef0c9985ffb9ce14849e5a536351fe56ae5
https://github.com/Fuzzbawls/PIVX/commit/0a8338be6e3d9926aae8c6f30b743da8376c95b1
Note: I didn't retain any transitional or "fixup" commits, so this PR is a single commit which takes the …
=> [Refactor] Introduce Consensus namespace

src/stakeinput.cpp, src/wallet/rpcwallet.cpp
RPC should accept only values between 1 and 999999 (as per `setstakesplitthreshold` help) but the input provided was only checked against the upper bound.
Setting a 0 value would result in a crash (division-by-zero) at the first stake.
Now prevent the wallet from splitting the stake if the threshold is set to zero.
Future work:
There is no reason why the split threshold should be an integer. 
Make it `CAmount` and enable decimal values for it.
Also use `JSONRPCError(RPC_INVALID_PARAMETER)` instead of runtime errors when the input is not valid.
=> [Bug] nStakeSplitThreshold: division by zero

src/amount.h, src/chain.h, src/chainparams.cpp, src/chainparams.h, src/consensus/params.h, src/consensus/tx_verify.cpp, src/kernel.cpp, src/main.cpp, src/masternode-budget.cpp, src/masternode-payments.cpp, src/miner.cpp, src/pow.cpp, src/qt/bitcoinunits.cpp, src/qt/blockexplorer.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/rpc/server.cpp, src/test/main_tests.cpp, src/txdb.cpp, src/txmempool.cpp, src/wallet/rpcdump.cpp, src/wallet/wallet.cpp
This PR builds on
Populates the `consensus` struct with all relevant consensus parameters.
Resets `nMaxMoneyOut` as chain param (with different value for TestNet).
Cleans up several unneeded fields in ChainParams.
EDIT: Current PR has been split in two. Second part is #1344
=> [Refactor] ChainParams::consensus - Part 1

CMakeLists.txt, src/Makefile.am, src/httpserver.cpp, src/init.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/obfuscation.cpp, src/sync.cpp, src/sync.h, src/util.cpp, src/util.h, src/util/threadnames.cpp, src/util/threadnames.h, src/wallet/walletdb.cpp
Part of a group of updates that will be doing from upstream to get up-to-date with latest sync.h/cpp sources.
This first PR involves:
* sync.h/cpp code refactor + reorg.
* threadnames.h/cpp file creation + connection (where "connection" means that all of the previous `RenameThread` method calls where modified to use the new `util::ThreadRename` method).
=> Inlining sync.cpp with latest upstream, first step.

doc/release-notes.md, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/pivx/settings/forms/settingswalletoptionswidget.ui, src/stakeinput.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp, src/wallet/walletdb.h
Follow-up on #1343 
- Wallet: save/use nStakeSplitThreshold as CAmount
- RPC: setstakesplitthreshold takes decimal values
- RPC: getstakesplitthreshold returns a double
- GUI: widget in settingsoptions changed to QDoubleSpinBox
- GUI: QSetting saved as double.
=> [Wallet][RPC][GUI] nStakeSplitThreshold as CAmount

doc/release-notes.md, src/qt/optionsmodel.cpp, src/wallet/wallet.h
- Lower default value of stake-split threshold
- Do not save it directly in QSettings (just in the wallet db).
Built on #1345 
Closes #1350
=> [Wallet][GUI] Set default stake-split threshold to 500

src/qt/addresstablemodel.cpp, src/qt/bantablemodel.cpp, src/qt/paymentserver.cpp, src/qt/peertablemodel.cpp, src/qt/recentrequeststablemodel.cpp, src/qt/transactiontablemodel.cpp
`qSort`, `qStableSort`, `qLowerBound`, and `qUpperBound` have been
marked as deprecated since Qt 5.2.
Also, `QSslSocket::setDefaultCaCertificates()` and `QSslSocket::systemCaCertificates()`
member functions are obsolete as of Qt 5.12
This PR replaces the former with their `std::` equivalents, and the latter
with `QSslConfiguration` equivalents.
Changes maintain backwards compatibility with Qt 5.5.1
=> [Qt] Replace deprecated Qt methods

src/consensus/zerocoin_verify.cpp, src/consensus/zerocoin_verify.h, src/init.cpp
df932b8ff85c1e668f5fea7169b0e6256b864546 introduced a bug preventing resync on mainnet due to zerocoin supply recalculation missing.
ZPIV supply recalculation shouldn't be needed in the first place, if the client is syncing from scratch and correctly filtering invalid mints.
So, instead of restoring `RecalculateZPIVMinted`/`RecalculateZPIVSpent`, this PR does 2 things:
- fixes `UpdateZPIVSupply` filtering the invalid mints/spends since the start of zerocoin (not only after `Zerocoin_Block_RecalculateAccumulators`). So, syncing from scratch doesn not trigger any recalculation at the next startup.
- inserts a call to `UpdateZPIVSupply` directly in `RecalculatePIVSupply`, to be used during init, e.g. by those clients updating from old versions (with wrong supply in the index), or when using …
=> [Chain][Bug] Fix mapZerocoinSupply recalculation

src/Makefile.am, src/Makefile.test.include, src/main.cpp, src/rpc/rawtransaction.cpp, src/sync.cpp, src/sync.h, src/test/sync_tests.cpp, src/util/macros.h
This was done on top of #1335  (Starts on 7921802). Effort to bring us up-to-date with upstream's sync.h/cpp sources.
The only task that left to be fully up-to-date with upstream, that will leave for a third PR because it touches other areas of the sources and want to keep this as small as possible, is the `CCriticalSection` removal and replacement with the `RecursiveMutex` typedef.
=> Sync Upgrades, part 2.

src/activemasternode.h, src/addrman.h, src/alert.cpp, src/alert.h, src/init.cpp, src/keystore.h, src/main.cpp, src/main.h, src/masternode-budget.cpp, src/masternode-budget.h, src/masternode-payments.cpp, src/masternode-payments.h, src/masternode.h, src/masternodeman.h, src/miner.cpp, src/net.cpp, src/net.h, src/netbase.cpp, src/rpc/mining.cpp, src/rpc/server.cpp, src/spork.h, src/sync.cpp, src/sync.h, src/test/util_tests.cpp, src/timedata.cpp, src/txmempool.h, src/util.cpp, src/wallet/db.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.h
This was done on top of #1335 and #1336 (Starting in bb575f8). Effort to bring us up up-to-date with upstream's sync.h/cpp sources.
This PR contains:
* A complete move from CCriticalSection to identical RecursiveMutex (both are AnnotatedMixin<std::recursive_mutex>). 
* Using WAIT_LOCK macro instead of WaitableLock.
=> Sync upgrade, part 3

src/qt/transactionfilterproxy.cpp
Auto-descriptive PR. 
Include missing cold stakes in the staking chart if the wallet is the cold staking owner (Didn't add the hot side because the chart is showing the wallet's received "staking rewards" and the hot wallet is not the utxo owner, just staked in behalf of the owner).
=> [GUI] Dashboard, include owner cold stakes in the chart.

src/crypter.cpp, src/init.cpp, src/zpiv/zpivwallet.cpp
With zPIV minting being disabled, there is no reason to initialize the zPIV wallet nor a default mint pool.
This simply disables that flow.
=> [Wallet] Don't initialize zpivwallet on first run

src/qt/pivx/masternodeswidget.cpp, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/mninfodialog.cpp, src/qt/pivx/mnmodel.cpp, src/qt/pivx/mnrow.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h
This PR fixes some issue with the masternode GUI interaction.
**1)**  __MasternodeWizard: lock collateral output after MN creation.__
The masternode configuration file is only read during init, and then the `COutPoint`s relative to the collateral of each entry is locked for spending. Thus, after creating a MN controller with the wizard, the collateral remains unlocked until the wallet is restarted, and therefore could be potentially spent or staked.
**2)** __Enforce required depth for mn collaterals__
The masternode collateral transaction requires at least 15 confirmations before the mn broadcast can be considered valid. Properly inform the user after creating a controller with the wizard, and when trying to start a masternode not yet confirmed.
**3)** __MasternodeWidget: unlock …
=> [GUI] MasternodeWidget-Wizard bugfixes

doc/release-notes.md, src/init.cpp, src/main.cpp, src/main.h, src/rpc/client.cpp, src/rpc/server.cpp, src/rpc/server.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
`reservebalance` is a leftover from peercoin code which was probably never used.
Currently it is also broken: the final loop in `CWallet::StakeableCoins` is useless (updating an un-used local variable `nAmountSelected` and not removing any utxo from the vector of stakeable coins).
Failing to see a valid use-case for it (not already provided by the stake-split threshold), I propose to just remove it.
This also makes the call to `GetStakingBalance` from `StakeableCoins` not needed (thus one less loop over mapWallet txes).
If this is accepted (at least conceptually) will update the release notes, and close #1366 (superseded by this one).
=> [Wallet] Remove reserve balance

src/wallet/wallet.cpp
exclude delegated balance and locked coins (if any)
=> [Wallet] Fix staking balance calculation

src/qt/pivx/receivewidget.cpp, src/qt/pivx/receivewidget.h
After editing an address label in Receive widget, the address presented (along with its QR code and label) automatically changes to another one, while the edited address is still highlited in the address list.
This could generate confusion and errors by the users.
Cause: `ReceiveWidget::refreshView()` (with no arguments) was connected to the `dataChanged(QModelIndex, QModelIndex)` signal.
Therefore, after editing the model (changing the label), the view was always restoring the first address in the addressbook (`getAddressToShow`) instead of keeping the one being modified.
Fix: This introduces an overloaded `ReceiveWidget::refreshView(QModelIndex, QModelIndex)`, taking the topleft and bottomright indexes (connected to `dataChanged`) and calling `refreshView(QString)` with the address …
=> [GUI] Don't change selected address after editing its label

src/qt/pivx/sendcustomfeedialog.cpp
Assuming it is not possible to put so low Custom Fee that transaction would not get included in blockchain, rewording to transaction speed relatedness makes more sense.
=> [Trivial] Rewording of Custom Fee dialog text

src/init.cpp, src/init.h, src/pivxd.cpp, src/qt/pivx.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/6780
Currently optionsModel(QT) parameters interaction overwrites/dominates initial and depending parameter settings. This PR would factor out init's parameter interaction and call it before AppInit2().
=> [Init] Do parameter interaction before creating the UI model

src/masternode-sync.cpp, src/qt/pivx/topbar.cpp
Straightforward change, adding the masternodes sync phase status to the topbar sync text.
=> [GUI] Topbar MNs sync phase status.

src/init.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/7257
Adds helper methods for common translatable string outputs during init, end result is that the number of strings sent to Transifex is reduced/standardized.
Based on top of #1375 
Conflicts with #1373 (this to be rebased after both #1373 and #1375 are merged)
=> [Init] Combine common error strings so translations can be shared

src/init.cpp, src/rpc/server.cpp, src/rpc/server.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, test/functional/wallet_upgrade.py
The rationality behind this work is that locked wallets, as them are encrypted, are not able to upgrade to HD wallet. The keystore and thereby keys are not available to perform any action at initialization time.
This PR solves it adding a new JSON-RPC command `upgradewallet` to be able to upgrade the wallet at runtime, requesting the wallet passphrase if it's needed.
A functional test verifying the new command was included inside the `wallet_upgrade.py` test.
=> [RPC] Upgrade to HD wallet.

src/qt/pivx/forms/sendcustomfeedialog.ui, src/qt/pivx/sendcustomfeedialog.cpp
Custom Fee is expressed in PIV/kB.
Thus can only have at max 8 decimals.
Closes #1397
=> [GUI][Bug] Fix max decimals in sendcustomfeedialog

configure.ac
- When aiming for glibc compatibility, don't use thread_local.
Ensures we're meeting the backwards compatibility target with gitian.
- Add a flag --enable-threadlocal, which, when specified, will
enable/disable thread_local regardless of the value of glibc_compat.
- MingW, Darwin, and FreeBSD have a buggy thread_local, don't use it.
=> [Build] Add flag for enabling thread_local

src/wallet/scriptpubkeyman.cpp
This fixes a bug found in the recent HD wallet implementation.
Trying to send any transaction (included delegations) on non-upgraded wallets results in a crash due to the following assertion failure in `CWallet::CreateTransaction`:
```cpp
// Reserve a new key pair from key pool
CPubKey vchPubKey;
bool ret;
ret = reservekey.GetReservedKey(vchPubKey, true);
assert(ret); // should never fail, as we just unlocked
```
**Cause**: `assert(ret)` fails here because `GetReservedKey` returns false on non-HD wallets requesting change addresses (or stake addresses) because, in this case, `CanGetAddresses` returns false: both `setInternalKeyPool` and `setStakingKeyPool` are empty.
**Fix**: on wallets with HD disabled, `CanGetAddresses`  should call `KeypoolCountExternalKeys` (which checks the size of …
=> [Wallet][Bug] Fix ScriptPubKeyMan::CanGetAddresses

src/qt/pivx/sendmultirow.cpp
In the send tab, when there is only one recipient, the address label is automatically loaded by the wallet if the user enters a known address in the recipient field.
**Problem:** If the user overwrites the recipient entry, inserting a new address, and this address is not found in the addressbook (or even simply deletes the previous inserted address), then the label does not change, and keeps displaying the one fetched earlier (the label of the __previous__ address).
This of course could lead to issues of users sending to a different recipient than intended.
**Fix:** Trivial. clear the label whenever the address is changed (before updating it if the address inserted is labeled in the addressbook).
=> [GUI] SendMultiRow: clear address label when address is changed

src/qt/clientmodel.cpp, src/qt/clientmodel.h
**Probelm**: GUI client model requires calls to `chainActive` (thus locking the main UI thread) for the following functions:
- getNumBlocks
- getLastBlockDate
- getLastBlockHash
- getVerificationProgress
**Fix**: use the `NotifyBlockTip` core signal to update a cached tip blockindex in `BlockTipChanged`, and rely on this object for the aforementioned functions.
**Note**: This should allow to complete #1047
=> [GUI][Model] Save cache BlockIndex tip in the model

src/masternode-payments.h
Small change to the `mapMasternodesLastVote`, stop using the `uint256` class as an `arith_uint256` and use directly the `COutPoint`.
=> [MN] Refactor to the `mapMasternodesLastVote` map.

src/Makefile.test.include, src/net.cpp, src/net.h, src/test/net_tests.cpp
backport of https://github.com/bitcoin/bitcoin/pull/7696/files
* CAddrDB modified so that when de-serialization code throws an exception Addrman is reset to a clean state
* CAddrDB modified to make unit tests possible
* Regression test created to ensure bug is fixed
* StartNode modifed to clear adrman if CAddrDB::Read returns an error code.
=> [Net] Fix de-serialization bug where AddrMan is corrupted after exception

doc/release-notes.md, src/rpc/misc.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, test/functional/mining_pos_coldStaking.py, test/functional/test_framework/test_framework.py
Add the number of staked/available coins during last attempt to `CStakerStatus`.
Remove the following attributes from `getstakingstatus` output
- "tiptime"
- "hashLastStakeAttempt"
- "heightLastStakeAttempt"
- "timeLastStakeAttempt"
Add the following attributes to `getstakingstatus` output:
- "lastattempt_age" (numeric, seconds since last stake attempt)
- "lastattempt_depth" (numeric, depth of the block on top of which the last stake attempt was made)
- "lastattempt_hash" (hex string, hash of the block on top of which the last stake attempt was made)
- "lastattempt_coins" (numeric, number of stakeable coins available during last stake attempt)
- "lastattempt_tries" (numeric, number of stakeable coins checked during last stake attempt)
- "stakeablecoins" (numeric, number of stakeable …
=> [RPC] Expand getstakingstatus output

src/init.cpp, src/wallet/scriptpubkeyman.cpp, test/functional/test_framework/test_framework.py, test/functional/test_runner.py, test/functional/wallet_hd.py, test/functional/wallet_keypool_topup.py, test/functional/wallet_upgrade.py
This adds a startup flag `-legacywallet`, which, on first run, enables the creation of a pre-HD wallet (when a wallet.dat is already present, the flag is just ignored). This flag is available for RegTest only.
A special option `--legacywallet` is also added to the functional test_runner.
Single tests (or the entire test suite) can now be performed over legacy wallets easily, e.g.:
```
./test_runner.py -j10 --legacywallet
./wallet_basic.py --legacywallet
```
**Note 1**: Running with pre-HD wallets, the `wallet_accounts.py` test fails. It is fixed in a successive PR.
**Note 2**: Travis currently is set to run the functional test suite only on HD wallets.
=> [Tests] Run tests on pre-HD wallets

src/qt/transactionfilterproxy.cpp
This is a (hopefully definitive) fix for a strange segfault I was consistently having on testnet with the GUI wallet (during the loading of the stake charts), with the following stacktrace
```
#0  0x00007ffff58363bb in  ()
at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff583b25d in  ()
at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff583b932 in  ()
at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff583bca9 in  ()
at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff583c50a in QSortFilterProxyModel::invalidateFilter() ()
at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00005555556aa809 in DashboardWidget::updateStakeFilter() (this=this@entry=0x5555577817d0) at qt/pivx/dashboardwidget.cpp:480
#6  0x00005555556ac736 in DashboardWidget::getAmountBy() …
```
=> [GUI] Explicit cast from quint32 to bool in filterAcceptsRow

src/rpc/masternode.cpp
`masternodecurrent` RPC is improperly returning the masternode with rank 1 instead of the next winner.
Closes #1348 
```
> getblockcount
2236241
> masternodecurrent
{
"protocol": 70918,
"txhash": "cfa69f018741e0960a436788391d9d2cec0f9aceed30e883a78818f7c073fba1",
"pubkey": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
"lastseen": 1583439177,
"activeseconds": 6690804
}
> getmasternodewinners 0
[
{
"nHeight": 2236242,
"winner": {
"address": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
"nVotes": 10
}
},
...
]
```
<https://explorer.pivx.link/block/9fe33eedf5f61a8e9f8d50b9007c25d1b0260f0c97f88265feda4c06dfa86725>
Note: `GetCurrentMasterNode` returns the masternode with lower rank and it's used as winner only when no valid block payee can be found. We should probably change its name to something more …
=> [RPC][Bug] Fix masternodecurrent: return next winner, not rank-1 mn

src/main.cpp, src/net.h
Straightforward back port. Sets a max block locator entries size.
Coming from [upstream@13907](https://github.com/bitcoin/bitcoin/pull/13907/commits).
=> [Net] Max block locator entries size.

src/qt/askpassphrasedialog.cpp
Mainly changed for `If you encrypt your wallet and lose your passphrase…`. Remaining 2 changes are to keep consistency.
**2nd thing just for the note to check: I cannot see a warning anywhere when CAPS LOCK is turned on?**
=> [GUI][Trivial] Emphasize warning better

doc/release-notes.md, src/qt/guiutil.h, src/qt/pivx/defaultdialog.cpp, src/qt/pivx/defaultdialog.h, src/qt/pivx/sendconfirmdialog.cpp, src/qt/pivx/sendconfirmdialog.h
Ref: https://github.com/PIVX-Project/PIVX/pull/1163#pullrequestreview-328980277
Completes the ability to accept/dismiss modal dialogs with the keyboard, including:
- confirmation dialogs (`DefaultDialog`)
- tx detail / tx confirmation dialogs (`TxDetailDialog`)
=> [GUI] Accept dialogs with ENTER, reject with ESC

src/wallet/scriptpubkeyman.cpp
Follow up to #1401 
Pre-HD wallets are still able to generate keys, as the comment in `ScriptPubKeyMan::CanGenerateKeys` clearly states. Fix the return value.
Based on top of 
to verify that it correctly fixes the test `wallet_accounts.py` (which was failing when run with `--legacywallet` option).
=> [Wallet][Bug] Fix ScriptPubKeyMan::CanGenerateKeys

.travis.yml, test/functional/test_runner.py
Follows the discussion in #1410 .
Defines a list of tests to be skipped by the `test_runner` when running with the `--legacywallet` flag (not directly related to the wallet / key management).
Also adds a specific Travis job, to run the functional test suite on pre-HD wallets.
Note: currently based on top of 
to make legacy tests pass.
=> [QA] Continuous Testing Environment for legacy pre-HD wallets

src/test/net_tests.cpp
from bitcoin#8070
> If addrmanUncorrupted does not have the same nKey every time it will map addrs to different bucket positions and occasionally cause a collision between two addrs, breaking the test.
=> [Tests] Remove non-determinism which is breaking net_tests

src/qt/CMakeLists.txt
#1443 removed the `denomgenerationdialog` files, but the `.cpp` file
reference wasn't also removed from the GUI's `CMakeLists.txt` file.
=> [CMake] Fix missing file error

src/qt/pivx/topbar.cpp
Based on
Offer the option to directly backup the wallet after upgrade-to-HD (and successive re-lock) is completed.
The message on the initial dialog is changed (from "Note that you will need to MAKE A NEW BACKUP.."):
If the user clicks "OK", and the wallet is locked, the unlock dialog is directly shown (as per #1387)
After the upgrade, the client directly presents this dialog:
If the user clicks "OK", then the open-file dialog is presented, so the user can select the filename for the backup file and click "Save" completing the flow.
If the user clicks "CANCEL" (or dismisses the open-file dialog later), a snackbar  popup warns the user, telling to remember to backup asap.
=> [GUI] Automatic wallet backup after upgrade to HD

src/qt/askpassphrasedialog.cpp, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css
Ref: https://github.com/PIVX-Project/PIVX/pull/1428#issuecomment-600925968
Caps-lock warning is black.
Assign text-warning css to make it clearly visible (and instantly recognizable as warning) in both themes.
=> [Trivial][GUI] Fix capsLabel color (make it text-warning)

src/wallet/wallet.cpp
If `nDepth` is equal to `nStakeMinDepth - 1` then the coin is not skipped in `AvailableCoins` and gets included in the list of stakeable utxos.
This utxo won't be able to stake though, as it will fail `ContextCheck` in `Stake()` (logging an error), thus it shouldn't have been included in the first place.
=> [Bug] Fix min depth requirement for stake inputs in AvailableCoins

src/main.cpp
Follow up to #1331 for the same bug.
**Problem:** if the finalized budgets and the masternode list are not synchronized, the output returned from `IsBudgetPaymentBlock` is unreliable.
For the moment we fix it by checking that the sum of the stake input value and block reward is at least equal to the sum of the values of non-free outputs.
A better approach, for the future, would be probably to outright prevent any call to `CheckBlock` when `IsInitialBlockDownload` is false but mnSync is not fully completed yet.
=> [Consensus] CheckColdStakeFreeOutput when mnsync not complete

src/init.cpp
`g_best_block` holds a cached best block hash.
This is updated during `ActivateBestChain` (in `UpdateTip`).
**Problem**: at startup, the object is not initialized until a new block arrives (`ActivateBestChainStep` is not called) thus `g_best_block != chainActive.Tip()->GetBlockHash()` so, if the client stakes before receiving a new block, that stake gets orphaned.
In case of segregated devnet with just one staker, it is impossible to move the chain at all.
=> [Bug] Fix g_best_block initialization in ABC

src/init.cpp, src/net.cpp, src/net.h, src/netbase.cpp
If a timeout happens while reading the proxy response, this effectively means we timed out while connecting to the remote node. This is very common for Tor, so do not print an error message to the log in that case.
Avoids a flood of
```
ERROR: Error reading proxy response
```
while running through Tor, causing users to blame the proxy.
Coming from upstream [9726](https://github.com/bitcoin/bitcoin/pull/9726)
=> netbase: Do not print an error on connection timeouts through proxy

src/blocksignature.cpp, src/chain.cpp, src/chain.h, src/chainparams.cpp, src/consensus/params.h, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/kernel.cpp, src/main.cpp, src/miner.cpp, src/primitives/block.h, src/primitives/transaction.cpp, src/primitives/transaction.h, src/rpc/blockchain.cpp, src/script/interpreter.cpp, src/script/script.cpp, src/script/script.h, src/script/script_error.cpp, src/script/script_error.h, src/stakeinput.cpp, src/stakeinput.h, src/wallet/wallet.cpp, src/wallet/wallet.h, src/zpiv/zpos.h, test/functional/mining_pos_reorg.py, test/functional/test_framework/test_framework.py
New stake modifier protocol (v3) proposed as hard fork.
Instead of using a chain of hashes, we propose to switch to a chain of *signatures*. 
So the new modifier, instead of being the hash of the previous modifier, combined with the txId of the coinstake input, becomes the hash of a signature, performed with the key of the coinstake prevout, over the previous modifier.
This makes the modifier completely unpredictable, thus offering a much better protection against grinding.
The flow is fairly simple: the staker, after finding a valid kernel, signs the modifier used, and publishes the signature (prefixed by a new opcode `OP_STAKEMODIFIER`) in the first output of the coinstake transaction. All peers then verify the signature during the proof of stake checks. The hash of this signature is …
=> [PoS] Stake Modifier V3

src/tinyformat.h, src/util.h
this backports the following pull requests from upstream bitcoin:
- bitcoin#8000 (0fa578f, 6837887)
> Now that we started using c++11, force use of variadic templates.
The autodetection may be wonky on some compilers, see discussion here and is unnecessary for us anyhow.
- bitcoin#8274 (500dfee, 2713458)
> Updates tinyformat.h to commit c42f/tinyformat@3a33bbf upstream.
- bitcoin#9417 (66ec97b)
> There are a few cases where hashes are computed inside LogPrint arguments - where they usually go unused. As LogPrint statements should never have side effects besides printing something, we can avoid the evaluation in this case.
Advantage: perhaps a small performance improvement; I haven't benchmarked.
Disadvantage: if we would have statements with side-effects, this could make this a bit harder …
=> [Util] tinyformat / LogPrint backports

src/chainparams.cpp, src/chainparams.h, src/net.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/8083
This adds the ability to filter DNS seed requests by service bit, but does not actually implement any filtering other than the default `NODE_NETWORK` (for now). Further related upstream backports will follow.
=> [Net] Add support for dnsseeds with option to filter by servicebits

src/messagesigner.cpp
Remove extra logs in `CSignedMessage::CheckSignature`.
This method is inherited by all classes extending `CSignedMessage` and its log does not give useful information to the verifier at all (it's not even clear what is the class in question). Might just be of some help when signing (`VerifyHash` is called from within `CSignedMessage::Sign` too).
All relevant logs for verifiers are already provided by the caller - e.g. 
```cpp
if (!mess.CheckSignature()) { /* log something */ }
```
=> [Trivial] Remove spammy log in CheckSignature

src/main.cpp, src/version.h, test/functional/test_framework/messages.py
Required by #1462 (if accepted).
Bumps protocol to `70919` and adds the enforcement logic.
=> [Net] Protocol update enforcement for 70919

src/qt/pivx/settings/forms/settingsbackupwallet.ui, src/qt/pivx/settings/forms/settingsexportcsv.ui, src/qt/pivx/settings/settingsbackupwallet.cpp, src/qt/pivx/settings/settingsbackupwallet.h, src/qt/pivx/settings/settingsexportcsv.cpp, src/qt/pivx/settings/settingsexportcsv.h
Export to file directly, after selecting the destination and clicking "Save", without requiring additional button presses.
Interested flows:
- backup wallet
- export txes to csv
- export addresses to csv
Closes #1417
=> [GUI] One-click export to file

src/qt/pivx/sendmultirow.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h
**Problem**: `validateStakingAddress` uses a naive validation based on the first letter, and is currently broken on regtest (as `IsTestNetwork` was updated in https://github.com/PIVX-Project/PIVX/commit/2be6f7b271d82efaab87707141ac7e7c61d90b85 to be false on RegTestNet).
**Fix**: introduce a boolean argument in `validateAddress` (which already uses a full `CBitcoinAddress` validation) to properly check staking addresses as well.
=> [GUI][Model] Fix staking address validation

src/qt/clientmodel.cpp, src/qt/clientmodel.h, src/qt/pivx/dashboardwidget.cpp
We were locking `cs_main`, calling `IsInitialBlockDownload` on every new row inserted in the transaction table model.
This PR caches the IBD state and updates it on every new block from the back-end without lock `cs_main` at all.
=> [GUI] Less GUI locks, IBD state cached.

.tx/config, contrib/devtools/update-translations.py
This restricts the fetching of translations from Transifex during the
translation process to only fetch the translations that meet a defined
minimum completion threshold percentage.
In order to allow testers/self-compilers to see partial translations in-wallet,
a runtime override flag has been added to the `update-translations.py`
script; `--ignore_completion`
Also, finally add the public configuration file for the `tx` CLI tool
Closes #1432
=> [Scripts] Only fetch translations for high-completion locals

test/functional/feature_notifications.py, test/functional/interface_rest.py, test/functional/mining_pos_coldStaking.py, test/functional/mining_pos_reorg.py, test/functional/p2p_disconnect_ban.py, test/functional/p2p_time_offset.py, test/functional/rpc_fundrawtransaction.py, test/functional/rpc_invalidateblock.py, test/functional/rpc_net.py, test/functional/rpc_rawtransaction.py, test/functional/test_framework/test_framework.py, test/functional/test_framework/util.py, test/functional/test_runner.py, test/functional/wallet_abandonconflict.py, test/functional/wallet_basic.py, test/functional/wallet_bumpfee.py, test/functional/wallet_keypool_topup.py, test/functional/wallet_listsinceblock.py
Mostly from upstream bitcoin#16898
> By default all test nodes are connected in a chain. However, instead of just a single connection between each pair of nodes, we end up with up to four connections for a "middle" node (two outbound, two inbound, from each side).
>
> This is generally redundant (tx and block relay should succeed with just a single connection) and confusing. For example, test timeouts after a call to sync_ may be racy and hard to reproduce. On top of that, the test debug.logs are hard to read because txs and block invs may be relayed on the same connection multiple times.
>
> Fix this by inlining connect_nodes_bi in the two tests that need it, and then replace it with a single connect_nodes in all other tests.
>
> Historic background:
>
> connect_nodes_bi has been …
=> [Tests][Refactor] Remove connect_nodes_bi

src/Makefile.am, src/guiinterfaceutil.h, src/init.cpp, src/init.h, src/rpc/server.cpp, src/stakeinput.h, src/test/test_pivx.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/zpiv/zpos.h
This PR does two things:
1) Move the `pwalletMain` object inside the `wallet.h` file.
2) Move the wallet's parameters initialization to an static method `ParameterInteraction` in the wallet class.
This is coming (partially) from upstream 25340b7 .
=> [Refactor] Init wallet parameters interaction

src/qt/pivx/forms/coldstakingwidget.ui
Cold staking widget: set containerSend margins to zero to keep consistency with send widget.
Closes #1444 
Before:
<br>
After:
=> [GUI][Trivial] ColdStakingWidget: fix containerSend margins

src/qt/pivx/dashboardwidget.cpp
QT charts are included by default (unless explicitely disabled or the library is not found). In which case, almost half of the dashboard space is basically "wasted".
<br>
This PR proposes to hide the charts container instead.
=> [GUI] Hide charts container when not USE_QTCHARTS

depends/packages/openssl.mk
The URL for OpenSSL 1.0.1k has changed, so update it here.
=> [Depends] Update OpenSSL download URL

src/qt/pivx/topbar.cpp
Fixing a badly bold font style set in the Tor topbar's button text.
It's not needed and it shouldn't have been coded in that way as it will not parse the tag properly.
=> [BugFix] Tor topbar button text.

src/qt/clientmodel.cpp, src/qt/clientmodel.h
Fixing cacheTip not sync with the back-end information when the node has no connection and thereby there was no tip signal broadcasted to the front-end to update the cached tip. Showing a wrong chain height instead of the correct back-end tip.
This will only happen one time. Once the tip gets updated, it will not request it anymore from the back-end and only receive signals. Not locking `cs_main` anymore.
=> [GUI] ClientModel cacheTip sync with back-end.

src/init.cpp
Implemented on top of:
Backports bitcoin#10123
> setting `-debug` can lead to very noisy debug.logs with subcomponents filling up the log file. See for example https://travis-ci.org/bitcoin/bitcoin/jobs/216767286 where there are hundreds of libevent debug logs.
This commit adds an option to exclude certain components from debug logging. The usage is:
```
pivxd -debug -debugexclude=<component1> -debugexclude=<component2> ...
```
This finally reduces spammy logs in the functional tests debug, due to libevent and leveldb (bitcoin#10124 was already included backporting the test suite).
=> [Core] Add -debugexclude option

src/torcontrol.cpp
Straightforward fix. Coming from upstream [10587](https://github.com/bitcoin/bitcoin/pull/10587)
```
Potential file descriptor leak introduced in commit 0b6f40d via PR #10408 
(submitted 2017-05-16, merged 2017-05-18).
```
=> [Net] Fix resource leak in ReadBinaryFile

src/qt/askpassphrasedialog.cpp
Adding an error notification when the encryption process throws an exception.
=> [GUI] Add missing error notification in encrypt wallet.

src/net.h
This fixes the getaddr response which is crucial for dns-seeders and wallet to find peers.On current code it only checks localhost addr being valid and if its known,while in reality we need to relay the node passed in args.
Credit to @Aviator-Coding for pointing the bug out and the fix.
=> [Net] Relay actual peers instead of localhost on getaddr

doc/release-notes.md, src/qt/pivx/addresseswidget.cpp, src/qt/pivx/addresseswidget.h, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/coldstakingwidget.h, src/qt/pivx/contactsdropdown.cpp, src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/forms/addresseswidget.ui, src/qt/pivx/forms/coldstakingwidget.ui, src/qt/pivx/forms/receivewidget.ui, src/qt/pivx/qtutils.cpp, src/qt/pivx/qtutils.h, src/qt/pivx/receivewidget.cpp, src/qt/pivx/receivewidget.h, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css
This adds GUI controls and relative logic to sort the addresses saved in the wallet and presented to the user. 
Interested views:
- Receive --> My Addresses
- Cold Staking --> My Cold Staking Addresses
- Contacts
- Send / Delegate --> recipient dropdown
Addresses can now be sorted (ascending or descending order):
- by label (default)
- by address
- by creation date.
Closes #1038 .
---
For "receive" addresses and own "cold-staking" addresses, the controls are hidden with the list, and show up when the relative button is pressed:
<br>
---
<br>
For "contacts" the controls are visible next to the title
<br>
---
<br>
For the dropdown in the "send" widget, instead, a fixed by-label ascending order is used (adding controls for customization here would be probably useless and only make the the …
=> [GUI] Customizable sorting for address books

src/rpc/masternode.cpp
`startmasternode` and `createmasternodebroadcast` error outputs are still
referencing old command `list-conf` (deprecated since version v2.3.1).
Replace with `listmasternodeconf`.
Closes #1496
=> [Trivial][RPC] Remove references to old command list-conf

src/init.cpp, src/util.cpp, src/util.h
implemented on top of
Backports bitcoin#6149
> Prevents stomping on debug logs in datadirs that are locked by other
instances and lost parameter interaction messages that can get wiped by
ShrinkDebugFile().
The log is now opened explicitly and all emitted messages are buffered
until this open occurs.  The version message and log cut have also been
moved to the earliest possible sensible location.
=> [Util] Buffer log messages and explicitly open logs

doc/release-notes.md, src/httpserver.cpp, src/httpserver.h, src/rpc/client.cpp, src/rpc/misc.cpp, src/rpc/server.cpp, src/rpc/server.h, src/util.cpp, src/util.h
Implemented on top of:
Backports bitcoin#10150
> Adds an RPC to get/set active logging categories.
First commit allows all categories except libevent to be reconfigured during runtime.
Second commit modifies InitHTTPServer() to allow leveldb logging to be reconfigured during runtime.
=> [RPC] Add logging RPC

src/wallet/wallet.h
Simple enough, last fix needed for CWallet usage in unit test.
Initializing zwalletMain to null to prevent memory access violations if it's not being set.
=> [Wallet] Initialize zwalletMain to prevent memory access violations.

src/qt/clientmodel.h, src/qt/pivx/res/css/style_dark.css, src/qt/pivx/res/css/style_light.css, src/qt/pivx/settings/forms/settingsinformationwidget.ui, src/qt/pivx/settings/settingsinformationwidget.cpp, src/qt/pivx/settings/settingsinformationwidget.h, src/qt/rpcconsole.cpp
This adds the masternode count(s) and last block hash to the new settings info panel (ported from the old RPCConsole UI Window), as well as makes the informational text select-able (good for copy/pasting information, like last block height/hash).
Also, initialize static strings directly in the `.ui` file.
=> [Qt] Add more information to settings info panel

src/qt/clientmodel.cpp
Previously, we were updating the MNs cached count in the GUI every 4 seconds and there is absolutely no need to try to lock the important `cs_main` for a number so rarely used like the masternodes count. 40 seconds looks more like a decent time to check for MNs updates.
Maybe we should discuss in the future if we really want to continue polling for this number. Could move it to a signal but still, it's a rarely used number. Thinking that it would be just fine to update it when the user request it and done.
=> [GUI] Update MNs count every 40 seconds.

doc/release-notes.md, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/pivx/send.cpp, src/qt/pivx/send.h, src/qt/pivx/sendcustomfeedialog.cpp, src/qt/pivx/sendcustomfeedialog.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp, src/wallet/walletdb.h
Don't reset user-defined fee after a spend, and persist it over wallet restart.
Closes #1398
=> [GUI] Save custom fee selected

doc/release-notes.md, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/forms/send.ui, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/send.cpp, src/qt/pivx/send.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpc/rawtransaction.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_zerocoin.cpp
__Problem:__
A few users have reported of having accidentally spent cold-stake delegations, after interacting with the GUI, in the following cases
1) Sending a transaction
2) Creating a MN controller with the masternode wizard
3) Creating another delegation
__Cause:__
Cold stakes and delegations are picked up (owner-side) by default in `AvailableCoins` (in order to get the correct balances). 
While in the RPC functions it is possible to use a boolean parameter `fIncludeDelegations` to decide whether or not to let the automatic selection algorithm include them (if needed), the GUI has no such option, thus, by default, doesn't skip them.
The user is presented with a warning before spending a cold-stake delegation, but some user doesn't pay attention, and, in any case, dismissing and …
=> [GUI] Spend cold-stake delegations

src/qt/pivx/settings/forms/settingsconsolewidget.ui, src/qt/pivx/settings/settingsconsolewidget.cpp, src/qt/pivx/settings/settingsconsolewidget.h
auto-descriptive PR.
Clear history button in the settings console.
=> [GUI] Settings console, clear history button.

src/qt/pivx/settings/settingsbittoolwidget.cpp
**Problem:** The QT wallet crashes when hitting "Import Address" on the BIP38 Tool Decrypt mode when the "Decrypted address result" is empty.
**Cause:** Without previously decrypting, `key` is empty and `key.IsValid()` is called too late.
**Fix:** Hide `pushButtonImport` until a key has been decrypted, only when a key is decrypted; the "Import Address" button will become visible. Hitting "Clear" will also hide the button again until a new decryption has been done.
**Before decrypting:**
**After decrypting:**
=> [Wallet] Fix BIP38 import crashing on empty DecKey

src/qt/pivx/loadingdialog.cpp, src/qt/pivx/pwidget.cpp
#1049 missed a few connects that were using the old SIGNAL/SLOT syntax.
This updates them to the new syntax.
=> [Qt] Convert leftover connects to Qt5 syntax

doc/release-notes.md, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/dashboardwidget.h, src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui, src/qt/pivx/settings/settingsdisplayoptionswidget.cpp, src/qt/utilitydialog.cpp
This adds a gui-only startup flag `--hidecharts` that can be used to automatically hide the chart container at startup.
Also adds  a checkbox in display option to hide/show the charts at runtime (so a wallet could even be started without charts, and then enable them later without restarting).
<br>
NOTE: this PR might be controversial, so it has been implemented independently from #1473 (which only hides the chart when they are disabled via `configure`). If both PR are conceptually accepted, this will be rebased on top of 1473.
=> [GUI] Hide charts at startup or at runtime

doc/release-notes.md, src/init.cpp, src/util.cpp, src/util.h, test/functional/feature_logging.py, test/functional/test_runner.py
Implemented on top of
Only last 4 commits are relevant to this PR.
Backports bitcoin#11781
> This patch adds an option to configure the name and/or directory of the debug log file.</br></br>
The user can specify either a relative path, in which case the path is relative to the (network specific) data directory. They can also specify an absolute path to put the log anywhere else in the file system.
Functional test included.
=> [Init] Add `-debuglogfile` option

src/qt/pivx/forms/sendchangeaddressdialog.ui
The text in the Change Address dialog is cut-off, this PR simply increases the minimum height of labelMessage to give the text enough room without clipping.
**Before:**
**After:**
=> [GUI] Fix text cut-off in sendchangeaddressdialog

src/qt/pivx/dashboardwidget.h
Trivial. No functional changes. Removes a temporary comment, leftover from #1475
=> [Trivial] Remove leftover temporary comment

src/qt/pivx/masternodeswidget.cpp, src/qt/pivx/mnmodel.cpp, src/qt/pivx/mnmodel.h
Extends the fix of #1389 (point 2) also to `startAll` (not only `startAlias`).
Additional ref: https://github.com/PIVX-Project/PIVX/issues/1226
=> [BUG] Prevent StartAll from starting mns with immature collateral

src/masternode.h
Removes un-used function  `SliceHash` (which is also buggy and overflowing,
trying to copy 64 bytes to a destination buffer having only 8 bytes).
=> [Trivial] Remove CMasternode::SliceHash

src/init.cpp
Trivial change, remove the PID file once the shutdown process is completed.
=> Shutdown: remove PID file at the very end.

src/qt/pivx/snackbar.cpp, src/qt/pivx/snackbar.h
The default 3-seconds timeout for the snackbar is not optimal in all the situations.
Sometimes the message is longer, and the user has not enough time to read it before it hides.
Other times the message is very short (e.g. "Wallet Unlocked"), and 3 seconds seem a bit much.
This PR proposes to use a variable timeout, based on the length of the message to display (50 milliseconds per character), with a minimum set at 2 seconds and a maximum at 10.
=> [GUI] Customize the timeout of the SnackBar based on its message length

src/qt/pivx/forms/welcomecontentwidget.ui
Trivial fix for last button which was cropping out part of the text "Masternode".
Linux:
Closes #1419
=> [GUI][Trivial] Fix button size in welcomecontentwidget

src/qt/pivx/coldstakingwidget.cpp
Straightforward, fixing the following bug introduced in #1477.
=> [GUI] Fix cold staking owner dropdown position.

configure.ac, src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/macdockiconhandler.h, src/qt/macdockiconhandler.mm, src/qt/pivx/pivxgui.cpp, src/qt/pivx/pivxgui.h
Updating `MacDockIconHandler` to latest upstream. Fixing #1512 .
Back ported PRs:
```
The sequence show -> raise -> activateWindow is factored out to the new function GUIUtil::bringToFront where a macOS fix is added in order to fix #13829.
Also included:
simplification of BitcoinGUI::showNormalIfMinimized
```
```
Changes in Xcode 11 Objective-C Runtime cause an error (#16387) during building on MacOS 10.15 Catalina.
This PR fixes this issue by replacing objc_msgSend() function calls with the native Objective-C syntax.
Refs:
changes in objc_msgSend function
OBJC_OLD_DISPATCH_PROTOTYPES macro
```
=> [GUI] Back port latest MacOS dock icon handler.

src/wallet/wallet.cpp, src/wallet/wallet.h
`SetMerkleBranch`'s return value is no longer being used. Remove the unnecessary code part. Coming from upstream@[9446](https://github.com/bitcoin/bitcoin/pull/9446).
And removed the `cs_main` lock from CWallet::SyncTransaction that was previously needed do the `SetMerkleBranch` assert lock held.
=> SetMerkleBranch: remove unused code, remove cs_main lock requirement

CMakeLists.txt, src/Makefile.am, src/activemasternode.cpp, src/httpserver.cpp, src/httpserver.h, src/init.cpp, src/logging.cpp, src/logging.h, src/main.cpp, src/qt/transactiondesc.cpp, src/rpc/misc.cpp, src/test/test_pivx.cpp, src/timedata.cpp, src/util.cpp, src/util.h
Implemented on top of:
This creates a new class BCLog::Logger to encapsulate all global logging configuration and state.
Adapted from
- bitcoin#13021
- bitcoin#12954
=> [Util] Refactor logging code into a global object

src/qt/pivx/loadingdialog.cpp, src/qt/pivx/loadingdialog.h, src/qt/pivx/masternodeswidget.cpp, src/qt/pivx/masternodeswidget.h, src/qt/pivx/pwidget.cpp, src/qt/pivx/pwidget.h, src/qt/pivx/topbar.cpp, src/qt/pivx/topbar.h
**Problem**: startAll fails when the wallet is locked.
**Cause**: startAll is executed as async background task, thus the lock context is lost (and the wallet is re-locked) when the execution gets to `startMN()`
**Fix**: use a global unlock context pointer (as we did with the upgrade to HD flow).
=> [BUG][GUI] Fix MasternodeWidget StartAll

src/qt/pivx/qtutils.cpp, src/qt/pivx/qtutils.h
The address type filter dropdown items and the sorting method dropdown items weren't available for localization.
Additionally, the transaction type filter dropdown items were using a call method that isn't supported by Qt's linquist utility program (which we use to generate the updated localization source file as part of `make translate`).
Finally, the file was not in compliance with our coding style guidelines, so the first commit is a reformat-only commit which can be duplicated by running the following command on `master`:
```bash
clang-format -i src/qt/pivx/qtutils.*
```
(minor blank-line changes were made afterwards in the header include section of `qtutils.h`)
=> [Qt] Fixup filter dropdown localizations

src/qt/pivx/masternodeswidget.cpp
This PR changes "Mastenode" to "Masternode", simple typo corrections in masternodeswidget.
=> [Trivial] [GUI] Fix masternodeswidget snackbar typos

src/qt/pivx.cpp
Default `-printtoconsole` to false for the GUI. 
GUI programs should not print to the console unnecessarily. For example, when launched by the
window manager, the output might end up in the X session log file, resulting in duplicate logging. On Windows, it is pointless as well because pivx-qt isn't a console application.
Coming from upstream@[13055](https://github.com/bitcoin/bitcoin/pull/13055)
=> [GUI] Don't log to console by default.

src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/send.cpp
Make contacts dropdown a little bit higher, so at least 4 addresses fit
---
---
Closes #1416
=> [Trivial][GUI] Add more room to contacts dropdown

src/qt/pivx/expandablebutton.cpp, src/qt/pivx/expandablebutton.h
Fixing compiler warning in the `expandableButton::MousePressEvent`. 
Parent and child sharing the same function name 'QWidget::mousePressEvent' with different signatures.
=> [Trivial] Fix compiler warning in mousePressEvent.

contrib/gitian-build.py
gitian's use of apt-cacher server on the host doesn't work when using
Windows 10's WSL subsystem. This adds a check to see if the ubuntu OS
version is from "Microsoft" (which indicates it is a WSL environment),
then uses the boolean result to disable the use of apt-cacher if true.
=> [Build] Disable apt-cacher for Windows WSL gitian setup

src/qt/pivx/forms/mnrow.ui
These strings are placeholders, treat them as such by not sending them
to Transifex for localization.
=> [Qt] Don't translate dummy strings in mnrow

src/primitives/transaction.cpp, src/primitives/transaction.h, src/wallet/wallet.cpp
Cleaning a wrongly coded method in the `COutPoint` primitive. Why it was receiving the transaction an as argument (without even check if it was the one corresponding one to that outpoint) it's beyond my powers..
=> BugFix: Cleanup invalid IsMasternodeReward method in OutPoint primitive.

src/net.cpp, src/net.h, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/mnmodel.cpp, src/qt/pivx/mnmodel.h, src/test/netbase_tests.cpp
First commit fixes the masternode alias: right now only letters and digits are allowed, but special characters (except spaces and hash marks) should be allowed too. It also replaces deprecated `QRegExp` with `QRegularExpression` (as per #1124) and fixes the port number to the default.
Closes #1471 
Second commit introduces validation for masternode IP addresses: they should be valid IPv4, IPv6 or .onion addresses and, if not on regtest, they should be reachable and routable. A unit test for the new `validateMasternodeIP` function is added to netbase_tests.
Also removes the validation for the port, since it's fixed to network-default.
=> [GUI] MasternodeWizard validations

src/qt/coincontroldialog.cpp, src/qt/forms/coincontroldialog.ui
The coin control dialog layout was first designed to be an internal frameless dialog but then, for the size and content, ended up being a standalone dialog using the OS predetermined frame.
This PR removes the duplicate esc button.
=> [GUI] CoinControlDialog remove duplicate esc button

doc/tor.md
v3 onion addresses are 256 bits, which is currently beyond what our P2P
protocol allows in `addr` messages. Until such time that [BIP155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki) can be
implemented, note in the tor.md doc that the `-externalip` configuration
flag should not be used with v3 onion addresses.
=> [Doc] Note that v3 onion addresses are not supported

src/qt/pivx/send.cpp, src/qt/pivx/sendchangeaddressdialog.cpp, src/qt/pivx/sendchangeaddressdialog.h
First commit fixes a bug where the `btnChangeAddress` in SendWidget was deactivated, despite a custom address still being saved (e.g. saving a valid address, and then trying to change it to an invalid one).
Second commit addresses a feature request: being able to reset only the change address (without resetting the whole coin control) directly from within the dialog.
With this PR, when a custom change address is set, the text of the "CANCEL" button in `SendChangeAddressDialog` is changed to "RESET" and, when clicked, resets the default change address to CNoDestination (which means that a new change address will be created during the send operation).
The upright "X" button retains its original function of just closing the dialog.
Closes #1526
=> [GUI][Bug] Reset custom change address

src/wallet/wallet.cpp
nFeeNeeded is an absolute value (`feePerKb * txKb`), and, as explained both in GUI labels, and in the RPC help, `-payTxFee` is a value per Kb.
`CWallet::GetMinimumFee` , instead, was improperly setting `nFeeNeeded` to just `feePerKb` when a user had a custom fee set, resulting in the creation of transactions with fee much higher than expected (most transactions are well under 1Kb in size).
Closes #881
=> [Bug][Wallet] Fix insane fees

src/qt/transactionrecord.cpp, src/qt/transactiontablemodel.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Given the strict timestamp checks enforced with POS TimeProtocol v2 (introduced with #1002: a block cannot have a timestamp earlier than previous blocks and cannot be more than 15 seconds in the future), we don't need the complex (and error-prone) logic of the current implementation of `ComputeTimeSmart`. 
We can, instead, simply rely on the blocktime, which already ensures a proper ordering for the transactions.
This also allows us to encapsulate the function in the `CWalletTx` class (renaming it to `UpdateTimeSmart`).
We can also get rid of the additional `GetComputedTxTime` (with its additional LOCK, and main chain lookup), and just use `GetTxTime`.
Finally, update the nSmartTime when a mempool transaction is added to a block.
This should, hopefully, fix #1346 (further testing needed).
=> [Bug] Simpler nTimeSmart computation

src/qt/transactionrecord.cpp
Removes an extra useless loop in `decomposeTransaction` and fixes transaction Details "Output Index", which should correspond with the vout-index (as per bitcoin#9637)
=> [GUI][Bug] Fix transaction details output-index

test/functional/test_framework/util.py, test/functional/test_runner.py, test/functional/wallet_basic.py, test/functional/wallet_zapwallettxes.py
Our current `wallet_basic.py` test takes quite some time.
Most of the preparations, though, are unnecessary, as we don't have the feature supposed to be checked (e.g. "subtract fee from amount", or fee collected by the miner or list zero value tx as available coins).
Also restore the check for the correct fee amount, previously commented, with `assert_fee_amount`.
Finally moves the `--zapwallettxes` checks to its test. This makes wallet_basic much faster (498 seconds vs 833) and wallet_zapwallettxes slower (but, at least, it can be run in parallel with the other, making the overall test_runner runtime shorter).
Note: This also fixes a bug in the previous version of the test, highlighted by #1575 (the fee was fixed at the value taken from the first tx sent).
=> [QA][Bug] Shorter wallet_basic.py functional test

src/qt/pivx/settings/settingswidget.cpp
As we hid MultiSend support for now, let's not waste memory maintaining an unused widget.
=> [GUI] Do not create new SettingsMultisendWidget

src/qt/pivx/coldstakingwidget.cpp
This action connection was incorrectly commented out when switching to
the new QT5 `connect` syntax. Fix it now by using a simple lambda.
=> [GUI][Bug] Reconnect CS owner address edit-label action

src/chainparams.cpp
Removing `warriors.dev` seeder, not answering any connection.
=> Removing dead seeder

src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h
Prioritize the action described by the button:
- if "Select All", then verify that all entries are checked, otherwise check them
- if "Unselect All", then verify that all entries are unchecked, otherwise uncheck them.
Closes #1592 
**Note**: if we had just prioritized `Qt::Unchecked` at the beginning, instead of `Qt::Checked`, without taking into account the status/text of the button, we would have solved 1592, but we'd have another bug where, using first "Select All" to check all entries, and then manually deselecting some entry, results in a successive "Unselect All" still behaving like "Select All".
=> [GUI][Bug] Fix "Select all" / "Unselect all" logic in coincontrol

src/wallet/wallet.cpp
Fixes a bug that prevented the editing of Cold Staking address labels in
the address book due to the passing of an empty purpose, which
`CWallet::ParseIntoAddress()` needs in order to determine if an address
is a cold staking type address.
=> [GUI][Bug] Fix editing of CS address labels

src/qt/pivx/send.cpp, src/qt/pivx/sendmultirow.cpp, src/qt/pivx/sendmultirow.h
The current sending flow clears and/or overwrites the user-supplied
address label multiple times, including when doing final address
validation after clicking the send button. This results in the entered
label never being used.
This stops the default clear and the overzealous replacing/setting of
the label text.
=> [GUI][Bug] Don't clear address label during send address validation

src/chainparams.cpp, src/chainparams.h, src/net.cpp
Part of #1374's goal of updating our network code
> This negates the need for CAddress here at all
=> [Net] Use SeedSpec6's rather than CAddress's for fixed seeds

src/main.cpp, src/masternode-budget.cpp, src/masternode-payments.cpp, src/masternode-sync.cpp, src/masternodeman.cpp, src/net.cpp, src/protocol.cpp, src/protocol.h, src/qt/walletmodel.cpp, src/rpc/budget.cpp, src/spork.cpp, src/swifttx.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Ported from https://github.com/bitcoin/bitcoin/pull/7181 with layer 2 messages in a followup commit, then ran both commits through `clang-format-diff.py`
> - Avoids string typos (by making the compiler check)
> - Makes it easier to grep for handling/generation of a certain message type
> - Refer directly to documentation by following the symbol in IDE
> - Move list of valid message types to protocol.cpp:
>     protocol.cpp is a more appropriate place for this, and having
>     the array there makes it easier to keep things consistent.
=> [Net] Add and document network messages in protocol.h

src/qt/askpassphrasedialog.cpp, src/qt/askpassphrasedialog.h, src/qt/forms/askpassphrasedialog.ui
This closes #1605 by adding a warning message & deactivating the "OK" button when the two passphrase fields do not match eachother.
As this warning is in the same area as the caps lock warning, the two have been merged into a single "passWarningLabel" which "stacks" warnings ontop of eachother, so both warnings can be shown independently, or both at once.
This PR ensures a user cannot proceed via the "OK" button until:
1. The new passphrase fields are not empty.
2. The new passphrase fields share identical texts.
3. (If changing password only) The **old** passphrase field is not empty.
=> [QT] Add password mismatch warnings

CMakeLists.txt, src/Makefile.am, src/Makefile.test.include, src/arith_uint256.cpp, src/arith_uint256.h, src/blob_uint256.cpp, src/blob_uint256.h, src/test/arith_uint256_tests.cpp, src/uint256.cpp, src/uint256.h, src/uint512.h
This is part of the large effort of making the uint256 file an opaque blob object and not treat every uint256 as an arith_uint256 anymore (same for the uint160 and uint512). Work coded on top of #1395, this is the second step.
As we cannot do it all at once, i opted to do the migration in steps. 
The amount of changes needed is really extensive and the risk of damage the synchronization process -and other areas as well- is high, this will need changes on the MNs, budget and zerocoin library sources which are using the uint256 object purely as a number.
This step is doing the following changes:
1) Creating blob_uint256 files (opaque blob version of the uint256 files -- this is the future uint256 files that will be refactored once all of the fields that are using it as a number in our …
=> uint256 to arith_uint256 migration (Second step).

src/activemasternode.cpp, src/addrman.cpp, src/addrman.h, src/init.cpp, src/main.cpp, src/masternodeman.cpp, src/net.cpp, src/net.h, src/protocol.cpp, src/protocol.h, src/rpc/masternode.cpp, src/test/DoS_tests.cpp, src/test/addrman_tests.cpp, src/test/net_tests.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/7749. This is next in line for #1374.
Original description:
> At this point, we do not:
> 
> * check that relayed/stored addr messages have the NODE_NETWORK bit set.
> * check that nodes selected for outbound connection have NODE_NETWORK advertized.
> * check that the nServices flag in the "version" message by a node corresponds to what we expected when deciding to connect to it.
> * store the updated nServices flag from the "version" message in addrman.
>
> Fix this.
=> [P2P] Enforce expected outbound services

src/Makefile.qt.include, src/qt/CMakeLists.txt, src/qt/pivx/addnewcontactdialog.cpp, src/qt/pivx/addnewcontactdialog.h, src/qt/pivx/defaultdialog.cpp, src/qt/pivx/defaultdialog.h, src/qt/pivx/focuseddialog.cpp, src/qt/pivx/focuseddialog.h, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/masternodewizarddialog.h, src/qt/pivx/mninfodialog.cpp, src/qt/pivx/mninfodialog.h, src/qt/pivx/receivedialog.cpp, src/qt/pivx/receivedialog.h, src/qt/pivx/requestdialog.cpp, src/qt/pivx/requestdialog.h, src/qt/pivx/sendchangeaddressdialog.cpp, src/qt/pivx/sendchangeaddressdialog.h, src/qt/pivx/sendconfirmdialog.cpp, src/qt/pivx/sendconfirmdialog.h, src/qt/pivx/sendcustomfeedialog.cpp, src/qt/pivx/sendcustomfeedialog.h
This creates a generic extension of QDialog, named `FocusedDialog`, with the property of having the focus on show and filtering key press events to call `accept()` with ENTER/RETURN and `close()` with ESC (ref: #1392).
Removes code duplication in `DefaultDialog` and `TxDetailDialog` by making them child classes of FocusedDialog.
Also add this ability to other dialogs as well:
- `AddNewContactDialog` (closes #1606)
- `MasterNodeWizardDialog`
- `MnInfoDialog`
- `ReceiveDialog`
- `RequestDialog`
- `SendChangeAddressDialog`
- `SendCustomFeeDialog`
=> [GUI][UX] Add accept/close keyboard controls to all dialogs

src/chainparams.cpp, src/chainparams.h, src/net.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/8208 based on top of #1616 (Only the last commit is important here). Part of #1374.
Original Description:
> Any flag set in nRelevantServices would propagate to all CAddress results retrieved from the DNS seed, even if that DNS seed does not support filtering.
> 
> Fix this by making the name adaptation function also update the passed in flags.
> 
> Furthermore, move that from from DNSSeedData to net. Structs in chainparams should be data only.
=> [P2P] Do not set extra flags for unfiltered DNS seed results

src/Makefile.am, src/coins.cpp, src/coins.h, src/init.cpp, src/main.cpp, src/main.h, src/memusage.h, src/test/coins_tests.cpp, src/txdb.h
This adds a basic foundation for accurate memory counting (memusage.h, with some implementation-specific assumptions, but at least the tree node and hashtable node implementations used are very generic and straightforward, so likely accurate for several systems). On the tested system at least, they are exact, ignoring memory fragmentation (tested using a single binary creating and modifying large amounts of different configurations of these data structures, and observing total resident set size afterwards). I expect this to be useful for other resource-limiting subsystems later on.
Then, this is used to implement accurate memory usage counting for CCoins objects, and efficiently computed memory usage counting for CCoinsViewCache (using cached totals, and increments/decrements on updates …
=> [Backport] Implement accurate UTXO cache size accounting

CMakeLists.txt, src/Makefile.am, src/Makefile.test.include, src/crypter.cpp, src/crypter.h, src/crypto/aes.cpp, src/crypto/aes.h, src/crypto/ctaes/COPYING, src/crypto/ctaes/README.md, src/crypto/ctaes/bench.c, src/crypto/ctaes/ctaes.c, src/crypto/ctaes/ctaes.h, src/crypto/ctaes/test.c, src/test/crypto_tests.cpp, src/wallet/test/crypto_tests.cpp
Coming from upstream [7689](https://github.com/bitcoin/bitcoin/pull/7689)
```
slow and simple AES implementation.
Performance on modern systems should be around 2-10 Mbyte/s (for short to larger messages), which is plenty for the needs of our wallet.
```
=> Replace OpenSSL AES with ctaes-based version

src/hash.cpp, src/main.cpp, src/net.cpp, src/netbase.h, src/primitives/block.cpp, src/primitives/transaction.h, src/script/script.h, src/serialize.h, src/test/serialize_tests.cpp, src/txmempool.cpp
First step in getting our serialization code up to par with upstream.
Backports bitcoin#5510 with only minor adjustments.
> Fix issue bitcoin#888.  
>
> This has been structured so that each compatibility change is one commit that touches only one file. After the initial build change, they are independent.
>
> Most extensive changes are in 'src/serialize.h: base serialization level endianness neutrality'. I had to replace READDATA and WRITEDATA with functions that take sized integer types to make use of the proper endian.h functions. I'm confident that the end result is the same, although this may require more tests.
>
> I've tested this on mipsbe32.
>
> All tests pass
> Testnet syncs correctly
> Node can successfully function on P2P mainnet
Checked that data directory can be copied …
=> [Core] Big endian support

src/allocators.h, src/crypter.cpp, src/crypter.h, src/wallet/test/crypto_tests.cpp
Built on top of #1486. Commits starting in `d058064` .
This PR back port, partially, [upstream@8753](https://github.com/bitcoin/bitcoin/pull/8753) . -- The last three commits left to back port in a future PR --
Containing the following changes:
1)  Changing CCrypter to use vectors with secure allocator instead of have to lock stack memory pages to prevent the memory from being swapped to disk.
2) Removing the unused LockObject and UnlockObject methods.
3) Adding a missing lock in the `CCryptoKeyStore::GetKeys` method.
=> CCrypter using secure allocator vector.

src/Makefile.am, src/Makefile.test.include, src/coins.h, src/hash.h, src/masternode-budget.h, src/masternode-payments.cpp, src/masternode-payments.h, src/memusage.h, src/prevector.h, src/primitives/transaction.h, src/qt/transactionrecord.h, src/script/interpreter.cpp, src/script/script.cpp, src/script/script.h, src/script/sign.cpp, src/serialize.h, src/test/miner_tests.cpp, src/test/prevector_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/script_tests.cpp, src/test/sigopcount_tests.cpp, src/wallet/walletdb.cpp
Based on:
This introduces `prevector<N, T>`, a new basic data type which is a fully API compatible drop-in replacement for `std::vector<T>` and uses it for the script, to reduce the considerable memory overhead of vectors in cases where they normally contain a small number of small elements.
Original tests in Bitcoin showed a reduction in dbcache memory usage by **23%**, and made an initial sync **13%** faster.
Backported from the following upstream's PRs, with only additional edits in the 2nd layer scripts (`masternode-payments`, `masternode-budget`) and in the unit tests (to address the differences in `insecure_rand`):
- bitcoin#6914
- bitcoin#7888
- bitcoin#8850
- bitcoin#9349
- bitcoin#9505
- bitcoin#9856
- bitcoin#10534
- bitcoin#11011
- bitcoin#14028
~~NOTE: Updates to `memusage.h` …
=> [Core] Prevector

src/coins.h
This causes CCoinsViewCache(CCoinsViewCache) to fail at compile-time rather than copy an existing cache (most likely the caller intends to sub-cache it)
It also makes ConnectBlock's fJustCheck work correctly for the genesis block, just in case it gets in there somehow.
Coming from upstream@[5580](https://github.com/bitcoin/bitcoin/pull/5580)
=> [Backport] Preemptively catch a few potential bugs

src/script/sign.cpp, src/script/sign.h
Coming from upstream@[5208](https://github.com/bitcoin/bitcoin/pull/5208)
> Build an abstraction class BaseSignatureCreator that doesn't depend on the data type being signed, and a SignatureCreator specific to CTransaction's. Instead of doing the abstraction at the hash compution level, do it at the signature creation level, which means a slight bit more code duplication, but less code changes.
> 
> Full disclosure: this is useful for sidechains-related work.
=> Abstract out CTransaction-specific signing into SignatureCreator

src/netbase.cpp, src/test/netbase_tests.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/6556
Original description:
> If I'm reading this right, I believe the intent is to keep the high order nBits and mask away the others with 1's. But before this fix it was keeping the high order (8 - nBits). I don't think there was any effect, because the only time this was used was in the case of he.net /36 IPv6 groups so nBits was 4.
=> [Net] Fix masking of irrelevant bits in address groups

src/prevector.h
Two simple additions to `prevector` class:
- name the union, to prevent compiler warnings emitted by clang (from bitcoin/bitcoin#7146) 
- use non-static data member initializers for `_size` and `_union` (from bitcoin/bitcoin#14266)
=> [Core] prevector: named union and defaults vars initialization

src/qt/pivx/guitransactionsutils.cpp, src/qt/pivx/pivxgui.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h
Triggered by #1619 
- first commit fixes a bug where the `WalletModel::message` signal was not connected to pwidget, therefore the message with `strFailReason` -fired by `prepareTransaction`:
https://github.com/PIVX-Project/PIVX/blob/f295ee4e4e089f76341a4f93058cfab3e974ccb9/src/qt/walletmodel.cpp#L526-L533
was never displayed, and the user was presented only with the generic "Transaction creation failed!" -fired by `ProcessSendCoinsReturnAndInform`:
https://github.com/PIVX-Project/PIVX/blob/f295ee4e4e089f76341a4f93058cfab3e974ccb9/src/qt/pivx/guitransactionsutils.cpp#L74-L79
- second commit addresses the fact that, with the previous commit, the user is now presented with two consecutive dialogs: "Transaction too big" and "Transaction creation failed!", and merges them into one single …
=> [GUI][Bug] Notify transaction creation failure reason

src/base58.h
auto-explainable title.
Can be tested pressing on the generate address button in the receive widget.
=> Fix Destination wrapper segfault on copy constructor

src/base58.h, src/qt/walletmodel.cpp
Not much to explain here, an invalid toString encoding.
=> [GUI] Fix invalid Destination toString encoding.

src/net.cpp, src/net.h, src/netbase.cpp, src/rpc/net.cpp
Partial backport of https://github.com/bitcoin/bitcoin/pull/8113 as part of #1374.
Original Description:
> * Maintains consistency between ThreadOpenAddedNodeConnections and getaddednodeinfo, without any DNS resolving from RPC.
> * Deals with the use case of added names whose IP mapping changes over time (switching over to the new IP only when the connection to the old one closes, though).
> * Gets rid of the fDns argument to getaddednodeinfo (turning it into a dummy)
> * Simplifies the code significantly by introducing a shared GetAddedNodeInfo in net.cpp.
> * The existing addnode logic that tries all resolved addresses for a name is pushed down into ConnectSocketByName (picking at random).
> * ~The existing addnode logic to prevent multiple connections to the same IP is pushed down into …
=> [P2P][RPC] Rework addnode behaviour

CMakeLists.txt, src/Makefile.am, src/Makefile.test.include, src/init.cpp, src/main.cpp, src/policy/fees.cpp, src/policy/fees.h, src/primitives/transaction.h, src/qt/coincontroldialog.cpp, src/qt/optionsmodel.cpp, src/qt/pivx/sendcustomfeedialog.cpp, src/test/policyestimator_tests.cpp, src/txmempool.cpp, src/txmempool.h, src/wallet/wallet.cpp, src/wallet/wallet.h, test/functional/feature_fee_estimation.py, test/functional/test_runner.py
This introduces the new fee and priority estimation code described here <https://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg06405.html>.
Instead of calculating the median fee for each possible number of blocks needed to confirm, the new code divides the possible fee rates into buckets (spaced logarithmically) and keeps track of the number of blocks needed to confirm for each transaction in each bucket.
Backports:
- bitcoin/bitcoin#5159
- bitcoin/bitcoin#6887
except for the functional test (`smartfees.py`) which is based on an older version of the framework.
Instead I've restored a more recent `feature_fee_estimation.py` (commenting out the check for `estimatesmartfee` which can be reintroduced once bitcoin/bitcoin#6134 is backported).
Additional commits exclude …
=> [Core] New fee estimation code

src/memusage.h, src/primitives/transaction.cpp, src/primitives/transaction.h, src/rpc/blockchain.cpp, src/script/script.cpp, src/script/script.h, src/txmempool.cpp, src/txmempool.h
This continues the work of #1531 adding memory accounting for the mempool.
Backports bitcoin/bitcoin#6410.
Original description:
> This implements accurate memory usage accounting for the mempool. It is only exposed through getmempoolinfo for now, but could be used for limiting the resource requirements too (bitcoin/bitcoin#6281).
=> [Core] Implement accurate memory accounting for mempool

src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/coldstakingwidget.h, src/qt/pivx/sendconfirmdialog.cpp
Three simple fixes to the cold staking widget:
1. give immediate feedback (with red outline) when the owner address is not valid (same as we have with SendMultiRow objects, e.g. the staker address in this widget). Closes #1596 
2. on send: try to unlock the wallet only when all validity checks are passing.
3. since the address shown on the confirmation dialog is the staker, change the label "Sending to" in "Delegating to".
=> [GUI] cs widget: minor usability improvements

src/qt/pivx/settings/forms/settingsfaqwidget.ui, src/qt/pivx/settings/settingsfaqwidget.cpp, src/qt/pivx/settings/settingsfaqwidget.h
=> [Cleanup][GUI] Remove zPIV faqs

src/keystore.cpp, src/keystore.h, src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_ismine.cpp, src/wallet/wallet_ismine.h, src/wallet/walletdb.cpp
Remove the backend code which was added (in #278) to support the management of multisig addresses via GUI. Since our current GUI no longer has this feature, this code is currently disconnected and, therefore, can be cleaned up.
If we ever decide to re-add a GUI tool for multisig addresses, we can re-implement it properly.
=> [Cleanup] Remove obsolete multisig code

src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/coldstakingwidget.h, src/qt/pivx/send.cpp, src/qt/pivx/send.h
payAmounts were never set in CoinControlDialog, thus `nPayAmount` was always zero.
This resulted in two bugs:
- `nDust` and `nChange` were always zero, thus their labels were never used
- the nBytes calculated were wrong if the transaction had more than one output (thus the suggested fee was also wrong).
This PR removes some unused leftover, connects payAmounts (both from send and from coldstaking widgets) and fixes the tx-size calculation, considering also the cold-staking scripts (either as inputs  and/or outputs/delegations).
Fixes point n.2 of #1609
=> [GUI][Bug] CoinControl payAmounts and nBytes calculation

src/Makefile.bench.include
Follows suit with the rest of our binary targets and prevents a
relocation error when linking on some architectures.
=> [Build] Set complete cpp/cxx flags for bench_pivx binary

src/qt/walletmodel.cpp
auto-explainable PR from the title.
=> [GUI][Model] Remove unneeded lock in checkBalanceChanged

.travis.yml
A previous bug in the TravisCI macOS images required us to force a full
homebrew update rather than rely on pre-existing package versions.
TravisCI has now updated their macOS images to fix the bug, but only for
11.x+ versions.
Further, by doing a full homebrew update, the test environment updated
to the most recent Qt 5.15 version, which we do not yet fully support (#1683 fixes this),
and was causing the build to fail.
We can go with the 11.1 image and revert to `update: false` for now,
which gives us Qt 5.14.1.
=> [Travis] Bump macOS CMake target image

src/amount.h, src/init.cpp, src/main.cpp, src/main.h, src/memusage.h, src/miner.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/test/mempool_tests.cpp, src/test/miner_tests.cpp, src/test/policyestimator_tests.cpp, src/test/test_pivx.cpp, src/test/test_pivx.h, src/txmempool.cpp, src/txmempool.h, src/wallet/wallet.cpp, test/functional/mempool_packages.py, test/functional/test_runner.py
built on top of
This PR pulls some updates from upstream in the mempool area, adding the required adjustments for legacy zerocoin txes and updating the functional test suite.
Specifically, here we:
- track mempool descendants (in-mempool transactions that depend on other mempool transactions)
- turn `mapTx` into a `boost::multi_index_container` that sorts the mempool on 3 criteria:
- transaction hash
- fee rate
- time in the mempool
- Add a max size for the mempool (throwing away the cheapest txs and bumping the min relay fee, when full)
- Implement on-the-fly mempool size limit with the flag `-maxmempool`
- Implement `-checkmempool=N` to customize the frequency of the mempool check
- Implement helper for `CTxMemPoolEntry` for the unit tests.
Backports:
- bitcoin/bitcoin#6654
- …
=> [Core] MemPool package tracking and limits

src/qt/trafficgraphwidget.cpp
Qt 5.15 no longer implicitly includes QPainterPath, so explicitly
include it here.
=> [GUI] Add missing QPainterPath include

src/main.cpp, src/main.h, src/miner.cpp, src/txmempool.cpp
Small cleanup, removing the zc invalid outputs check from the miner code. (Quickly thinking that we can remove them from everywhere in the sources actually, it's impossible for any of those to get into the current chain. Matter of review each flow properly).
=> [Miner] Remove 2017 invalid outputs check

src/qt/walletmodel.cpp, src/qt/walletmodel.h
#1549 dropped zerocoin support in the GUI, this is a follow up removing the now unused methods and signal connections from the wallet model .
=> [GUI][Model] Remove zerocoin methods.

src/main.cpp, src/main.h
Coming from bitcoin#6061
Refactor needed for an upcoming work, no functional changes.
Had to do something little bit dirty to be able to get Consensus::Params from inside the Consensus namespace (struct `Params` name clashes with global method `Params()`) and not have any functional change there.
Point of discussion for a later PR: could be moved to a function argument or check if there is another workaround to distinguish between the name clash.
=> [Core] Separate Consensus CheckTxInputs and GetSpendHeight in CheckInputs

CMakeLists.txt, doc/release-notes.md, src/Makefile.am, src/Makefile.test.include, src/chainparams.cpp, src/chainparams.h, src/consensus/params.cpp, src/consensus/params.h, src/consensus/upgrades.cpp, src/consensus/upgrades.h, src/optional.h, src/rpc/blockchain.cpp, src/test/upgrades_tests.cpp
Custom implementation for our network of [ZIP200](https://github.com/zcash/zips/blob/master/zip-0200.rst) network upgrades structure.
This PR includes only the base structure and unit test for the upgrade mechanism, no network connection to any upgrade (only a `UPGRADE_PURPLE_FENIX` placeholder was added) nor upgrade activation hash check.
This will remove ambiguity over the many places of our code that requires the exact same check to perform the post/pre upgrade validations and actions.
Instead of using:
`If (consensus.next_update_height >= height) { //post update code }`
Now we will start using:
`if (consensus.NetworkUpgradeActive(pindex->nHeight, Consensus::UPGRADE_PURPLE_FENIX)) { //post update code }`
As well as be able to differentiate features in an specific release. Which could …
=> New upgrade structure.

src/qt/addresstablemodel.cpp, src/qt/addresstablemodel.h, src/qt/pivx/qtutils.cpp
PR dividing the "Delegators" address type in table model in "Delegable" and "Delegator" as it's divided in the back end.
This will enable the different addresses type exports.
=> [GUI] Split "Delegators" address type in the table model

src/keystore.h
multisig GUI functionality was removed on a previous PR. This member and typedef is not being used anymore
=> Remove unused MultiSigScriptSet typedef and member

src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h
Only last commit is new.
This updates the flow of the toggle button SelectAll/UnselectAll in the coin control dialog (`pushButtonSelectAll`).
- use directly the checked state of the button, instead of caching it in a separate variable `fSelectAllToggled`.
- when the button is in checked ("Unselect all") state, reset it to its initial state (unchecked, with "Select all" label) if all the entries are either manually deselected, or automatically cleared after a spend)
Closes point n.3 of #1609
=> [GUI] CoinControlDialog fix SelectAll / UnselectAll

src/init.cpp, src/main.cpp, src/script/sigcache.cpp, src/script/sigcache.h
Coming from bitcoin#6918 .
> Changes the -maxsigcachesize argument from entries to megabytes
> Change the default to 40 MiB (as opposed to ~10 MiB before), corresponding to over 500000 entries on 64-bit systems.
> Store salted SHA256 hashes in the cache, rather than full entries.
> Switch implementation from std::set to boost::unordered_set (smaller and faster)
> Remove cache entries after having been validated inside a block, to keep the cache fresh.
-----
This is the first step towards an up-to-date sigcache. Next one will be to back port the CuckooCache implementation.
=> [Backport] Make sigcache faster, more efficient, larger

src/qt/pivx/pivxgui.cpp
For some mysterious reason that completely eludes me, I removed this by accident in 4863f402eb8b2ab40b0099c0ca0ea0efbd910182.
Let's put it back in.
=> [BUG][GUI] Restore message() connection for ColdStakingWidget

src/main.cpp
The starting mempool entry priority was never being set.
=> [BUG] Fix mempool entry priority

src/consensus/tx_verify.cpp, src/consensus/validation.h, src/main.cpp, src/main.h, test/functional/mining_pos_reorg.py, test/functional/wallet_zerocoin_publicspends.py
- change `CValidationState::chRejectCode` to int
- add `CValidationState::strDebugMessage` for optional information
- add `FormatStateMessage` function to convert CValidationState to a human-readable message
- introduce REJECT_INTERNAL rejection codes for ATMP and make their logging optional
- remove unnecessary direct logging in `CheckTransaction`, `AcceptToMemoryPool`, `CheckTxInputs`, `CScriptCheck::operator()`
- add detailed state information to the errors in `CheckBlock` and `ConnectBlock`
Backported from:
- bitcoin/bitcoin#5913
- bitcoin/bitcoin#6519
- bitcoin/bitcoin#7287
=> [Refactoring] CValidationState logging 

src/qt/pivx/pivxgui.cpp, src/qt/pivx/pivxgui.h, src/qt/pivx/settings/settingsinformationwidget.h, src/qt/pivx/settings/settingswidget.cpp, src/qt/pivx/settings/settingswidget.h, src/qt/pivx/topbar.cpp
Adds two features for easier navigation:
- go directly to the information panel (showing latest block num and hash) when clicking on the "sync" (double arrow) button of the top bar
- open directly the network monitor when clicking on the network button of the top bar.
Closes #1685
=> [GUI] TopBar navigation (sync/peers)

src/qt/pivx/dashboardwidget.cpp
The batch processing mode of the QListView is the cause of the list blinking on every update.
Seems that internally, QT fires up a screen region update that it's not calculated properly when the batch mode is enabled. Forcing to update the whole view even when there is no visual change for the rows that are being shown.
So, have moved the layout mode back to SinglePass, it solves the issue for now. We should check in the future if this has been solved in a newer QT version.
=> [GUI] Fix dashboard txs list blinking issue

depends/Makefile
Since our dependencies do not precisely match upstream's, we need to
have our own fallback URL to use in the event that any of the original
URLs are non-functioning.
This takes care of the issue.
I did a temporary commit that purposely sabotaged all of the dependency URLs to force the use of the fallback URL. That TravisCI build can be found at https://travis-ci.org/github/Fuzzbawls/PIVX/builds/701960081. The "failed" tests are due to the build time timeout, and are expected, but by inspecting the logs one can see that the fallback URL is used during the depends build stage.
Sample of successfully fetching from the fallback URL:
```
Fetching protobuf-2.6.1.tar.bz2 from https://blah.com/google/protobuf/releases/download/v2.6.1
% Total    % Received % Xferd  Average Speed   Time    Time …
```
=> [Depends] Update dependency fallback URL

src/main.cpp, src/main.h, src/masternode-budget.cpp, src/qt/pivx/guitransactionsutils.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpc/budget.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_zerocoin.cpp, test/functional/mining_pos_coldStaking.py
This is an alternative to #1664.
It takes the opposite approach. 
When ATMP fails in `CommitTransaction`, instead of just returning the txid (hoping that the failure is not permanent) try to directly abandon the transaction. 
Save the result of these operations in a new struct `CWallet::CommitResult`, and use it to give a detailed feedback to the user (via log lines, JSON-RPC errors and GUI dialogs).
This PR also cherry-picks 5f122633020ce5d9f78c73394cda576a8657a3ac from bitcoin/bitcoin#6898, in order to use `FormatStateMessage` outside of main.
=> [Wallet] Abandon tx in CommitTransaction if ATMP fails

src/qt/pivx/guitransactionsutils.cpp, src/qt/pivx/send.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h
If the user tries to send an amount exceeding his balance, the wallet correctly returns the error related to `AmountExceedsBalance` or `AmountWithFeeExceedsBalance`.
Although, if the wallet has enough coins, but some of them are locked, the transaction preparation will fail, without giving a specific reason.
This happens because `prepareTransaction` checks the amount to send against the total wallet's balance (without excluding locked coins if any).
We fix this introducing a `getUnlockedBalance()` function in the model, and using it in `prepareTransaction`.
Similarly, in the Send Widget, the "total remaining" shows the wallet's balance (locked + unlocked), therefore the transaction might fail if the user tries to send it all, while having locked coins.
We will use the new …
=> [BUG][GUI] check for available "unlocked" balance in prepareTransaction

contrib/devtools/logprint-scanner.py, src/chain.h, src/kernel.cpp, src/main.cpp, src/stakeinput.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/zpiv/zpos.cpp
The wallet crashes if the number of format arguments passed to `error()` or `strprintf()` does not match the number of specifiers.
The script `logprint-scanner.py` checks this only for `LogPrint()` and `LogPrintf()` lines (but not for `error()`, which indirectly uses `LogPrintf`).
This PR adds the checks to the script and fixes the few offending instances found.
=> [Tools] logprint-scanner for error() and strprintf()

src/activemasternode.cpp, src/chain.h, src/consensus/params.h, src/masternode-budget.cpp, src/masternode-payments.cpp, src/masternode.cpp, src/masternode.h, src/messagesigner.cpp, src/messagesigner.h, src/rpc/budget.cpp, src/spork.cpp, src/swifttx.cpp
This code was used during the v4.0 hard fork in order to keep signing network messages with the "old" signatures before the enforcement height. Now we can clean it up.
based on top of:
Only the last commit is new.
=> [Cleanup] Don't sign MESS_VER_STRMESS network msgs anymore

src/base58.cpp, src/base58.h, src/messagesigner.cpp, src/pivx-tx.cpp, src/qt/pivx/masternodewizarddialog.cpp, src/qt/pivx/sendconfirmdialog.cpp, src/qt/pivx/settings/settingsbittoolwidget.cpp, src/qt/pivx/settings/settingsmultisendwidget.cpp, src/qt/transactiondesc.cpp, src/rpc/masternode.cpp, src/rpc/rawtransaction.cpp, src/test/base58_tests.cpp, src/test/bloom_tests.cpp, src/test/key_tests.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.h
Mixed few things here:
1) Follow up over #1593 work. The only remaining places that are not using the destination methods are in the walletmodel and wallet objects (next PR), the rest were all already migrated.
2) CBitcoinSecret with {Encode,Decode}Secret (adapted version of upstream@32e69fa0).
3) Unused code removal (second commit).
=> Prepare for non-Base58 addresses [Step 2]

src/coincontrol.h, src/crypter.cpp, src/keystore.cpp, src/keystore.h, src/primitives/transaction.h, src/qt/coincontroldialog.cpp, src/qt/transactiondesc.cpp, src/qt/walletmodel.cpp, src/rpc/client.cpp, src/rpc/rawtransaction.cpp, src/rpc/server.cpp, src/rpc/server.h, src/script/sign.cpp, src/script/sign.h, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_ismine.cpp, src/wallet/wallet_ismine.h, test/functional/rpc_fundrawtransaction.py, test/functional/rpc_listtransactions.py, test/functional/test_framework/util.py, test/functional/test_runner.py
based on top of
This introduces a new wallet function, `CWallet::FundTransaction()` (and exposes it via RPC with `fundrawtransaction`), to fill a tx containing only vouts (or not enough vins to cover the vouts) with unspent coins from the wallet.
`fundrawtransaction` will not modify existing inputs, and will add one change output (if needed) to the outputs. It will not sign the inputs (so can include also watch-only or multi-sig inputs, if enabled).
backported from:
- bitcoin/bitcoin#6088
- bitcoin/bitcoin#17219 [`*`]
- bitcoin/bitcoin#6417
- bitcoin/bitcoin#6444
- bitcoin/bitcoin#6415
- bitcoin/bitcoin#6828 
- bitcoin/bitcoin#7296 (only bebe58b748532157958f9055e4517e280684006c)
- bitcoin/bitcoin#7506
- bitcoin/bitcoin#7518
- bitcoin/bitcoin#7967
adapting the tests for the (more recent) …
=> [Wallet][RPC] FundTransaction - fundrawtransaction

src/main.cpp, src/main.h
Three changes:
1) Clean a not used CInv in ConnectTip.
2) Move CBlock to const where was possible.
3) ~~Remove obsolete upgrade signal based on last 100 block version check.~~
=> [Cleanup] Small main.cpp cleanup 

src/wallet/wallet.cpp
Problem:
Essentially, every time that the controller started a masternode, it was looping over the entire set of transactions and outputs to get the available ones, then looping again for the specific collateral utxo of the masternode that needs to be started.
so.. if the wallet had a big number of transactions, the start all had to process an excessive amount of utxo for each masternode being started Making the start all command slow as hell.
Solution:
`GetMasternodeVinAndKeys` method rewritten to directly find the collateral utxo in the wallet's map, perform the availability validations and return the needed keys. Zero loops.
=> [Wallet] Masternodes start performance boost

src/wallet/wallet.cpp
Fixed the misspelling of hashes (previously hahes).
=> [Trivial] Spelling Error

src/qt/walletmodel.cpp
When syncing or reindexing with a pre-existing wallet, there is no need
to do any updating of the transaction table model data when the chain's
tip time is prior to the wallet's creation time.
This offers a scaling performance boost as the number of transactions
a wallet has increases. For context, here are some sync time comparisons:
Current `master`:
```
Time to sync to Nov 27 2019: ~4 hours
```
This PR:
```
Time to sync to Nov 27 2019: ~1 hour 30 minutes
```
The wallet is a testnet wallet created on Nov 27 2019, and has roughly
96k transactions since then. Sync time from wallet creation timestamp
to the current block height remain unchanged here.
Note: wallets that have **imported** a watch-only address, a private key,
or set a different HD seed will not benefit from this change as …
=> [GUI] Return early in pollBalanceChanged

src/chainparams.cpp
Add a new checkpoint for the chain-split block for mainnet, and for the first block after v4.1.1 enforcement for both mainnet and testnet.
=> [Core] Add checkpoints for PIVX v4.1.1 enforcement

src/base58.cpp, src/base58.h, src/qt/paymentserver.cpp, src/qt/pivx/settings/settingsmultisendwidget.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpc/blockchain.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_zerocoin.cpp
Finished the complete removal of the base58 address class from the sources, migrated to the destination wrapper.
Plus includes bitcoin#11117 - last commit - and bitcoin#11259 as an extra.
=> Prepare for non-Base58 addresses [Step 3]

src/coins.cpp, src/coins.h, src/main.cpp, src/main.h, src/miner.cpp, src/rpc/server.cpp, src/test/mempool_tests.cpp, src/test/miner_tests.cpp, src/test/rpc_tests.cpp, src/test/test_pivx.cpp, src/test/test_pivx.h, src/test/util_tests.cpp, src/txmempool.cpp, src/txmempool.h, src/utilstrencodings.cpp, src/utilstrencodings.h, test/functional/mempool_packages.py, test/functional/mempool_reorg.py, test/functional/rpc_fundrawtransaction.py, test/functional/rpc_rawtransaction.py, test/functional/test_framework/util.py
More back ports and adaptations over the RPC values parsing and mempool. We need to get closer in this area :) .
* bitcoin#6379
* bitcoin#6715
* bitcoin#6915
* bitcoin#7007
* bitcoin#7008
* bitcoin#12643
* bitcoin#18474
* bitcoin#18704
=> RPC & Mempool back ports.

src/base58.h, src/qt/coincontroldialog.cpp, src/qt/coincontroldialog.h, src/qt/pivx/coldstakingwidget.cpp, src/qt/pivx/send.cpp, src/qt/pivx/sendchangeaddressdialog.cpp, src/qt/pivx/sendchangeaddressdialog.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
This is an alternative to #1691 .
Instead of fixing the the issue by checking for edits to `coinControl` in the show event of the dialogs, make `coinControl` a class variable of `CoinControlDialog`, so each dialog instance has its own independent object, and there are no inconsistencies.
=> [BUG][GUI] Non-static coinControl object in CoinControlDialogs

src/main.cpp
Straightforward, coming from [btc@8007](https://github.com/bitcoin/bitcoin/pull/8007)
=> IsInitialBlockDownload: usually avoid locking

src/qt/pivx/dashboardwidget.cpp
Implements the following requirements
- Be locked to the current date (no displaying tomorrow or the day after).
- Change to the previous month when going before the 1st.
- Change to the next month when going after the last day.
Tested locally on machine on regtest.
Closes #1037
=> [UI] Improve staking chart workflow

src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_zerocoin.cpp
No functional changes. Quick zerocoin code move to cleanup the method a little bit. Code moved from ScanForWalletTransactions to wallet_zerocoin.cpp legacy file.
=> [Refactor] zerocoin code moved from wallet.cpp to wallet_zerocoin.cpp

src/masternode.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Built on top of #1719 .
Fixing/Improving a bad error notification string showed in the GUI due the `CMasternodeBroadcast::Create` calling `CWallet::GetMasternodeVinAndKeys` and returning to the GUI the same string error output that is being printed to the log (with all of the extra data, including function names, service etc..).
Can be easily tested creating a masternode, then not waiting for the 15 confirmations and trying to start the node via the menu single masternode start (click on the masternode row and then press start).
Without the last commit, will popup a bad error notification text.
=> [GUI] Better start single MN error description.

src/init.cpp, src/main.cpp, src/test/accounting_tests.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_zerocoin.cpp, src/wallet/walletdb.cpp, src/wallet/walletdb.h, src/zpiv/zpivwallet.cpp, src/zpivchain.cpp
Commits details:
1- [No functional changes] Stop using CWalletTx::WriteToDisk, and use directly CWalletDB::WriteTx.
2- Performance improvement, preventing several calls to AvailableCoins in CreateTransaction.
3- [No functional changes] Split AddToWallet in AddToWallet and LoadToWallet (these two were already divided by a boolean method argument)
=> [Wallet] AddToWallet split in AddToWallet and LoadToWallet

CMakeLists.txt, src/Makefile.am, src/legacy/validation_zerocoin_legacy.cpp, src/legacy/validation_zerocoin_legacy.h, src/main.cpp
This is a move-only PR, no functionality or code was changed.
The main idea behind this decoupling is continue cleaning main.cpp. Making new functionalities and back ports easier to implement.
Have been thinking whether this should be a new file or `zerocoin_verify.h` and ended with a new file because this flows are one step above the verify methods and are not isolated from the process that calls them. Example: `AcceptToMemoryPoolZerocoin` works only for the `AcceptToMemoryPool` method.
=> Move zerocoin validation to its own legacy file.

src/primitives/transaction.cpp, src/primitives/transaction.h
auto-descriptive title. Unused methods removed from transaction.h/cpp .
=> [Cleanup] Transaction primitive unused methods cleanup.

src/qt/optionsmodel.h, src/qt/pivx/settings/settingsdisplayoptionswidget.cpp, src/qt/pivx/settings/settingswidget.cpp
Fixes #1627 + including a small cleanup.
The selected item in the languages combobox was not being initialized with the stored value.
=> [GUI] Fix settings language combobox initialization.

src/qt/pivx/settings/settingsconsolewidget.cpp
Alternative to #1585 that leaves the wording unchanged, but adds key-combo recognition to the settingsconsolewidget the clear the history as how the initial help text describes.
Adjust the settingsconsolewidget event filter to explicitly recognize
the key combo for clearing the console.
fixes #1213 which was actually not adequately resolved in #1499
=> [GUI] Recognize key event for clearing console

.travis.yml, configure.ac, doc/dependencies.md, src/fs.h, src/init.cpp, src/qt/guiutil.cpp, src/qt/pivx.cpp, src/qt/pivx/masternodeswidget.cpp, src/qt/pivx/masternodewizarddialog.cpp, src/rpc/protocol.cpp, src/scheduler.cpp, src/test/scheduler_tests.cpp, src/torcontrol.cpp, src/util.cpp, src/utiltime.cpp
This implements a minimum required boost version bump, pursuant to #1682 
The configure script has been updated to require a detected version of at least 1.57.0, and now-redundant sub-checks have been removed. Precompiler macros that offered version or feature fallbacks have also been largely removed as they are unnecessary.
Finally, this also updates some Boost Filesystem Path codebase that was using deprecated methods, and sets the `BOOST_FILESYSTEM_NO_DEPRECATED` macro so that such methods do not get re-added to the codebase in the future.
Ready for review, but should not be merged until after the `4.2` branch-off.
=> [Build] Require minimum boost version 1.57.0

src/coins.cpp, src/coins.h, src/main.cpp, src/main.h, src/miner.cpp, src/txmempool.cpp, src/undo.h
Backport bitcoin/bitcoin#5111
Original description:
> Built on top of bitcoin/bitcoin#5100.
> coins.o doesn't need to depend on undo.h (Decouple CCoins from CTxInUndo)
> miner.o neither (Decouple miner.o from CTxUndo)
> Finally, CBlockUndo can be moved from main.h to undo.h if it is first decoupled from CDiskBlockPos.
=> [Core] Only include undo.h from main.cpp

src/qt/pivx/dashboardwidget.cpp, src/qt/pivx/dashboardwidget.h
The transaction filter settings were persisted, but never loaded when the wallet starts.
Since it would be tricky to compute the index of an item of the filter-combobox from the filter value this change does it in the other direction, it persists the index of the item and computes the filter value from it which is trivial.
=> [GUI] Load persisted transaction filter during start

src/chainparams.cpp, src/consensus/params.h, src/consensus/upgrades.cpp, src/init.cpp, src/rpc/blockchain.cpp
Few commits decoupled from the Sapling branch.
Included here:
1) Fixing an upgrade index issue (last commit).
2) Added the 'nuparams' startup arg to customize the regtest network upgrade activation height (Used in the functional tests).
=> NU custom activation height startup arg.

src/qt/transactiontablemodel.cpp
Problem: we are still signaling updates from really old transactions from the backend and, at the same time, the GUI is not loading more than 20k transactions into the transactionTableModel.
So, old transactions that are not being shown deliberately in the GUI are re appearing due the signaling update process. Increasing the cached model size again, data being shown in the GUI and erroneously popping up the new tx ballon notification.
This PR is solving it with the following changes:
Storing the first loaded transaction time and not showing signaled transactions that have time smaller than the first tx loaded time. 
Only applied if the wallet is exceeding the maximum loaded transactions limit in the GUI (20,000 transactions).
=> [GUI] Solving old, not loaded at startup, transactions notification issue.

.tx/config, src/Makefile.qt_locale.include, src/qt/locale/pivx_de.ts, src/qt/locale/pivx_en_US.ts, src/qt/locale/pivx_es.ts, src/qt/locale/pivx_es_ES.ts, src/qt/locale/pivx_fr_FR.ts, src/qt/locale/pivx_hr_HR.ts, src/qt/locale/pivx_it.ts, src/qt/locale/pivx_ko_KR.ts, src/qt/locale/pivx_nl.ts, src/qt/locale/pivx_pl.ts, src/qt/locale/pivx_ru.ts, src/qt/locale/pivx_tr.ts, src/qt/pivx_locale.qrc
For inclusion in 4.2.0
#1758 will be updated once this is merged
=> [GUI] Update translations from transifex

src/main.cpp
Built on top of #1733.
Straightforward PR, no functional changes. Purely code cleanup and refactoring around the `DisconnectBlock` function.
=> [Validation] DisconnectBlock updates.

CMakeLists.txt, src/Makefile.am, src/interface/wallet.cpp, src/interface/wallet.h, src/qt/pivx/topbar.cpp, src/qt/pivx/topbar.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h
This is motivated by the different types of balances that we currently have (and the new ones that are coming).
1) Refactor: Back ported and adapted the `WalletBalances` wrapper class.
2) Cleanup: Removed the not used balance getters from `walletModel` + some not implemented methods that we had.
3) Cleanup: Removed the zerocoin balance related fields from the GUI, we are not showing it anymore and the GUI was still calculating + caching them.
=> [Model] Wallet interface refactor + code cleanup.

src/wallet/wallet.cpp
backports bitcoin/bitcoin#7491
> If number of conflict confirms cannot be determined, this means that the block is still unknown or not yet part of the main chain, for example during a reindex. Do nothing in that case, instead of crash with an assertion.
>
> Fixes bitcoin/bitcoin#7234.
=> [Wallet] Ignore MarkConflict if block hash is not known

src/net.cpp
Value can be significantly higher if the users uses addnode.
Coming from upstream#[8944](https://github.com/bitcoin/bitcoin/pull/8944)
=> [Net] Remove bogus assert on number of oubound connections.

src/policy/policy.h
On top of #1693 (only last commit matter for this PR).
Lot of fruitful information can be found in bitcoin#6769 .
> This adds SCRIPT_VERIFY_LOW_S to STANDARD_SCRIPT_VERIFY_FLAGS which
> will make the node require the canonical 'low-s' encoding for
> ECDSA signatures when relaying or mining.
> Absent this kind of test ECDSA is not a strong signature as given
> a valid signature {r, s} both that value and {r, -s mod n} are valid.
> These two encodings have different hashes allowing third parties a
> vector to change users txids. These attacks are avoided by picking
> a particular form as canonical and rejecting the other form(s); in
> the of the LOW_S rule, the smaller of the two possible S values is
> used.
=> [Backport] Test LowS in standardness, removes nuisance malleability vector

src/blocksignature.cpp, src/blocksignature.h, src/main.cpp, src/miner.cpp, src/stakeinput.cpp, src/stakeinput.h, src/test/main_tests.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/zpiv/zpos.h, test/functional/mining_v5_upgrade.py, test/functional/rpc_blockchain.py, test/functional/test_runner.py
Moved the last remaining P2PK scripts to P2PKH (coinbase and the staking output to the current P2PKH standard).
The main argument used for the migration is that we are already using it as a standard everywhere in the sources (same as upstream) and has an increased, theorical, security due the pub key not being revealed initially (scriptsig reveals it).
=> Move coinbase & coinstake to P2PKH

src/wallet/wallet.cpp
Fixing
```
2020-08-01 09:53:49 POTENTIAL DEADLOCK DETECTED
2020-08-01 09:53:49 Previous lock order was:
2020-08-01 09:53:49  (1) cs_main wallet/wallet.cpp:1617 (in thread )
2020-08-01 09:53:49  (2) cs_wallet wallet/wallet.cpp:1617 (in thread )
2020-08-01 09:53:49 Current lock order is:
2020-08-01 09:53:49  (2) pwallet->cs_wallet wallet/walletdb.cpp:708 (in thread )
2020-08-01 09:53:49  (1) cs_main wallet/wallet.cpp:1013 (in thread )
```
(backports bitcoin/bitcoin#11126)
> `CWallet::MarkConflicted` may acquire the `cs_main` lock after `CWalletDB::LoadWallet` acquires the `cs_wallet` lock during wallet initialization. (`CWalletDB::LoadWallet` calls `ReadKeyValue` which calls `CWallet::LoadToWallet` which calls `CWallet::MarkConflicted`). 
> This is the opposite order that `cs_main` and …
=> [Wallet] Acquire cs_main lock before cs_wallet during wallet initialization

src/addrman.h, src/main.cpp, src/net.cpp, src/net.h
Running 4.2 branch with `enable-debug`.
Fixing: 
```
POTENTIAL DEADLOCK DETECTED
Previous lock order was:
pnode->cs_vRecvMsg net.cpp:1830 (TRY) (in thread )
(1) cs_main main.cpp:5275 (in thread )
(2) cs_vSend net.cpp:2465 (in thread )
Current lock order is:
(2) pnode->cs_vSend net.cpp:1846 (TRY) (in thread )
(1) cs_main main.cpp:6018 (TRY) (in thread )
```
Plus, added few more minor possible races fixes too.
Back porting:
#8862
#9225
#9535
=> [Net] cs_vSend-cs_main deadlock detection fixed.

src/chain.h, src/main.cpp, test/functional/feature_block.py
A bit of history
----
Two transactions can have the same txid if their parents are identical, since the txids of the parents are included in a transaction.
Coinbases have no parents, so it used to be possible for two of them to be identical. 
Further,  by building on duplicate coinbases, duplicate normal transactions were possible as well (http://r6.ca/blog/20120206T005236Z.html).
In order to remove the possibility of having duplicate transaction ids, Bitcoin introduced, with BIP30, the following consensus rule:
- Blocks are not allowed to contain a transaction whose identifier matches that of an earlier, not-fully-spent transaction in the same chain. [[1](https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki)]
This rule was enforced by verifying (in `ConnectBlock`) that none of …
=> [Core] Remove BIP30 check

src/qt/clientmodel.cpp, src/qt/clientmodel.h, src/qt/pivx/settings/settingsinformationwidget.cpp, src/qt/pivx/settings/settingsinformationwidget.h, src/qt/rpcconsole.cpp
The masternodes polling was starting when the clientModel object is generated, locking `cs_main` every certain amount of time without care on whether the information is being presented or not.
This PR changes it, the polling timer will only be started when the information is needed on the screen and stopped when the user leaves such screen.
=> [GUI] Start masternodes polling timer only when is needed.
