- src/wallet.cpp
Error fix for https://github.com/Darknet-Crypto/Darknet/pull/7
> Don't try to spend immature coins (it'll fail anyway...)

- src/main.cpp
- src/main.h
- src/masternode-budget.cpp
- src/masternode-payments.cpp
- src/miner.cpp
- src/pow.cpp
Re-merge of failed PR https://github.com/Darknet-Crypto/Darknet/pull/11
> Testnet integration into master-branch + probable superblock-issue-fix

- src/qt/bitcoinamountfield.cpp
- src/qt/bitcoinunits.cpp
- src/qt/bitcoinunits.h
- src/qt/coincontroldialog.cpp
- src/qt/guiutil.cpp
- src/qt/optionsmodel.cpp
- src/qt/overviewpage.cpp
Rename units from *PIVX to *PIV
> Rename units from *PIVX to *PIV

- src/chainparams.cpp
- src/masternode-budget.h
This just fixes darknetd. Further changes are required to build system for darknet-qt to compile successfully
> Fixes for C++11 compile with Clang

- build-aux/m4/ax_cxx_compile_stdcxx.m4
- configure.ac
- src/test/util_tests.cpp
Updated configure.ac, added m4 file, and fixed util_tests
> Update Build mechansim to use c++11, fix util_tests

- src/chain.h
...and some minor refactoring.
> Missing PoS hash serialization added

- src/chainparams.cpp
Add two new DNS Seeders to both mainnet and testnet
Also some minor whitespace cleanup in chainparams.cpp
> New DNS Seeders

- src/masternode-budget.cpp
- src/masternode-budget.h
This brings us in sync with Dash v0.12.0.60.
If there should still be problems it's either CBudgetManager::FillBlockPayee or CBudgetManager::GetTotalBudget which need to be fixed.
> Budget-proposal merge from Dash v0.12.0.60

- src/masternode.h
To 120 and 130 minutes respectively
> Increase MASTERNODE_EXPIRATION_SECONDS and MASTERNODE_REMOVAL_SECONDS

- src/clientversion.h
- src/init.cpp
- src/qt/locale/pivx_en.ts
- src/qt/pivxstrings.cpp
- src/timedata.cpp
Seed transifex with updated translation sources
> [Translations] `make translate`

- src/wallet.cpp
In the case that 100% of the reward is sent, currently not enough is set aside for the fee.
Change multisend to return change to the sending address.
> Add an additional fee to multisend for 100% use case

- src/masternode-payments.cpp
Merges dash [#978](https://github.com/dashpay/dash/pull/978).
Appears to fix #82.
> Merge dash issue #978

- src/qt/overviewpage.cpp
https://github.com/PIVX-Project/PIVX/issues/118
> [QT] Fix Overview Page Balances when receiving

- src/qt/forms/rpcconsole.ui
- src/qt/rpcconsole.cpp
> [UI] Show path to wallet.dat in wallet-repair tab

- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/guiutil.cpp
- src/qt/guiutil.h
- src/qt/rpcconsole.cpp
- src/qt/rpcconsole.h
> [UI] Edit masternode.conf in Qt-wallet

- src/masternode-budget.cpp
Refactor repetitive Budget logging from LogPrintf to LogPrint("mnbudget"
> [Trivial] Use LogPrint for repetitive budget logs

- src/masternode-budget.cpp
There was no log when a budget proposal gets removed from the budget list, which makes tracking down errors unnecessary difficult.
> [Budget] Add log for removed budget proposals

- src/qt/forms/sendcoinsdialog.ui
Fix for https://github.com/PIVX-Project/PIVX/issues/160
Result:
> [Qt] Sendcoinsdialog: more place for long locales

- README.md
Makes the coin specs and distribution info sections much easier to
read. Also add build status for `master` and current release version
svg badges.
> [Docs] Reformat main README.md

- src/masternodeman.cpp
- src/rpcmasternode.cpp
Refactor the masternode RPC commands to return valid JSON in most cases.
Still a work in progress, but can be tested.
> [RPC] Refactor & JSONify results from masternode command(s)

- src/qt/locale/pivx_cs.ts
- src/qt/locale/pivx_da.ts
- src/qt/locale/pivx_en.ts
- src/qt/locale/pivx_es.ts
- src/qt/locale/pivx_fi.ts
- src/qt/locale/pivx_ko_KR.ts
- src/qt/locale/pivx_nl.ts
- src/qt/locale/pivx_pl.ts
- src/qt/locale/pivx_pt.ts
- src/qt/locale/pivx_pt_BR.ts
- src/qt/locale/pivx_ru.ts
- src/qt/locale/pivx_sk.ts
> [Qt] Pull Translations from Transifex

- doc/release-notes.md
Preliminary release notes for the notable changes in the next release. Note that this is not intended to be complete, and is a running work-in-progress update to the template doc to simulate how this template doc could be updated by any PR.
Before merge, the various commits here will be rebased/squashed to keep the commit history clean.
> [WIP] [Docs] 2.3.0 release notes updates

- src/qt/masternodelist.cpp
- src/rpcmasternode.cpp
Fixed 2 possible usages of null-pointers and simplified one statement for readability.
This fixes a segmentation fault when calling `masternode list`.
> "masternode list": nullpointer reference fixed

- src/masternode-payments.cpp
- src/masternode-payments.h
- src/obfuscation.cpp
- src/obfuscation.h
- src/qt/blockexplorer.cpp
- src/qt/overviewpage.cpp
- src/rpcmasternode-budget.cpp
- src/rpcwallet.cpp
- src/swifttx.cpp
- src/wallet.cpp
- src/wallet.h
Updates money amount variables from `int64_t` to `CAmount`
Keeps the code inline with Bitcoin and Dash.
> Update money variables from int64_t to CAmount

- src/rpcmasternode-budget.cpp
- src/utilstrencodings.cpp
Backport from Zerocoin repository
> [RPC] Sanitize proposal-name and -URL parameters

- src/init.cpp
- src/wallet.cpp
- src/wallet.h
This will backup the wallet everytime a zpiv is minted. It will keep 10 backups at a time.
> Add -backupzpiv startup flag.

- src/wallet.cpp
Thanks to @Warrows https://github.com/PIVX-Project/PIVX/pull/282#discussion_r145549074
> Include both pending and mature zerocoins for automint calculations.

- contrib/gitian-build.sh
- src/bip38.cpp
- src/bip38.h
- src/init.cpp
- src/main.cpp
- src/main.h
- src/miner.cpp
- src/primitives/block.h
- src/qt/bip38tooldialog.cpp
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/privacydialog.cpp
- src/qt/privacydialog.h
- src/qt/transactionview.cpp
- src/qt/walletframe.cpp
- src/qt/walletframe.h
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
- src/qt/walletview.cpp
- src/qt/walletview.h
- src/rpcdump.cpp
- src/rpcmasternode.cpp
- src/rpcmining.cpp
- src/rpcmisc.cpp
- src/rpcwallet.cpp
- src/wallet.cpp
- src/wallet.h
Combined versions of all the PRs for v3.0.1
> 3.0.1 Backports

- src/main.cpp
- src/miner.cpp
- Add an additional check for double spending of zPiv serials within the same block.
- Add an additional check for matching zPiv serials within the stake miner.
> Additional checks for double spending of zPiv serials.

- doc/release-notes/release-notes-2.3.0.md
- doc/release-notes/release-notes-2.3.1.md
- doc/release-notes/release-notes-3.0.0.md
- doc/release-notes/release-notes-3.0.2.md
Add release notes to the archive for the following versions:
- 2.3.0
- 2.3.1
- 3.0.0
- 3.0.2
> [Docs] Add missing archived release notes

- src/qt/locale/pivx_en.ts
- src/qt/pivxstrings.cpp
Update the source translation files with `make translate`
> [Qt] Periodic make translate

- src/wallet.cpp
Currently zPIV minting will send any change to a newly generated "change address". This has caused confusion among some users, and in some cases insufficient backups of the wallet. The wallet will now find the largest contributing address and return the change from a zPIV mint to that address.
Selection of coins entering a zPIV mint tx of 1400 PIV:
After minting, the change of 66 PIV was returned to the address that contributed the most value:
> Return change to sender when minting zPIV.

- README.md
This was useful for me. I thought that someone else might need to know more about SeeSaw and therefore it would be good to include a link in the Readme.
> Readme SeeSaw reward mechanism reference.

- src/qt/bitcoingui.cpp
After all that fiddling around with CSS I feel a bit embarrassed that's it's actually trivial to force a bigger icon-size via C++ code :facepalm:
Old look: https://github.com/PIVX-Project/PIVX/pull/472
New look:
> [UI] Make toolbar icons bigger

- src/qt/forms/multisigdialog.ui
- src/qt/multisigdialog.cpp
Fixed a known bug for the dynamic list labels for multisig
Realigned the lines of code to use tabs
> [UI] Fixed Dynamic Screen Elements Issue for Multisig

- README.md
- contrib/debian/control
- contrib/debian/manpages/pivxd.1
- contrib/debian/pivx-qt.desktop
- contrib/init/pivxd.conf
- contrib/init/pivxd.openrc
- doc/masternode-budget.md
- doc/masternode_conf.md
- share/qt/Info.plist.in
- src/chainparams.cpp
- src/kernel.cpp
- src/pivx-cli.cpp
- src/pivxd-res.rc
- src/qt/forms/askpassphrasedialog.ui
- src/qt/forms/bip38tooldialog.ui
- src/qt/forms/tradingdialog.ui
- src/rpcmasternode-budget.cpp
- src/rpcserver.cpp
- src/rpcwallet.cpp
Update from Obfuscation in CLI, include automint in GUI and CLI, and fix spelling of anonymization
> [Trivial] Update unlock description in GUI and CLI

- src/init.cpp
- src/qt/optionsdialog.cpp
- src/qt/optionsdialog.h
> [Qt] Fix crash when inputting wrong port for network proxy

- src/miner.cpp
- src/util.cpp
- src/util.h
Follow up for https://github.com/PIVX-Project/PIVX/pull/523 to not have to bother @presstab with that stuff again :-)
> [core] Minor refacturing + unused variable removed

- src/qt/bitcoingui.cpp
Follow up on #566 
Adds signal integration for the icon so it changes instantly when closing the setting window after a change.
> [Qt] Connect automint icon to the UI automint setting change

- doc/release-notes.md
> [Docs] Update release notes for v3.1.0

- doc/release-notes.md
minor update to zPIV staking and added thank you to the QA's and node hosts
> [Doc] Update to zPIV staking and Thank you's

- src/masternode-budget.cpp
Unfortunately during merging the code from the private development repository to the public repository one small but important change to the available budget was missing.
This PR fixes this...
> [Budget] Fix wrong budget amount

- src/wallet.cpp
This fixes a case of wallet loop crashing I've been having. It should also cover most cases seen in #564. Not sure how it's doing performances wise.
> [Wallet] Add some LOCK to avoid crash

- contrib/devtools/logprint-scanner.py
Trivial change
also cleaned up some trailing whitespace
> [Utils] Add copyright header to logprint-scanner.py

- doc/release-notes.md
Update the `3.1` branch `doc/release-nodes.md` file for `v3.1.1`
> [Doc] Release notes for v3.1.1

- contrib/gitian-build.sh
The gitian-build.sh script was broken when I've tried to use it to compile my own wallet so I've fixed it.
> [Utils] Fix syntax error in gitian-build.sh

- src/main.cpp
- src/main.h
- src/primitives/transaction.h
This function is never used, and never will be; Nuke it from orbit.
> [Refactor] Remove GetCoinAge

- src/rpcwallet.cpp
- src/wallet.cpp
This fixes an issue where the flag could be inappropriately changed.
>  [Wallet] fix bug with fWalletUnlockAnonymizeOnly flag setting

- src/random.cpp
Backport of https://github.com/bitcoin/bitcoin/pull/5824
> [Random] WIN32 Seed Cleanup: Move nLastPerfmon behind win32 ifdef.

- contrib/devtools/symbol-check.py
- contrib/gitian-descriptors/gitian-linux.yml
- depends/packages/qt.mk
- src/compat/glibc_compat.cpp
Add [RISC-V](https://en.wikipedia.org/wiki/RISC-V) (64Bit) to gitian descriptor and build with [gitian-build.py](https://github.com/PIVX-Project/PIVX/pull/786 ) script
> [Build] Add  support for RISC-V and build it with gitian

- src/addrman.cpp
- src/addrman.h
- src/net.cpp
- src/protocol.cpp
- src/protocol.h
Simple backport of https://github.com/bitcoin/bitcoin/pull/6028
> [Net] nLastTry is only used for addrman entries

- src/addrman.cpp
Simple backport of https://github.com/bitcoin/bitcoin/pull/6530
> [Net] Improve addrman Select() performance when buckets are nearly empty

- src/init.cpp
- src/qt/forms/optionsdialog.ui
- src/qt/optionsdialog.cpp
- src/qt/optionsmodel.cpp
- src/qt/optionsmodel.h
- src/rpc/client.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- src/rpcwallet.cpp
- src/util.cpp
- src/util.h
- src/wallet.cpp
- src/wallet.h
- src/walletdb.cpp
- src/walletdb.h
Mark a specific address as an "automint address". Any balance held by the address will automatically convert to zerocoins.
> [Wallet] Add automint address

- doc/build-windows.md
add build-windows.md
from https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md
> [Doc] Update doc/build-windows.md

- src/version.h
Minor protocol version increment, with no enforcement rulings, used in
tracking upgrade deployment across the network.
> [Net] Increment Protocol Version

- src/main.cpp
In essence what this looks to solve is the rejection of valid blocks from forked chains due an invalid view of the utxo set represented on the coin cache view object.
> [NET] Valid forked blocks rejected fix.

- src/chainparams.cpp
This adds two additional checkpoints for known split points
> [Net] Add additional checkpoints

- src/chainparams.cpp
Fixes an incorrect timestamp for the last checkpoint
> [Net] Fix incorrect last checkpoint timestamp

- src/chainparams.cpp
- src/main.cpp
This backports the following PRs into the `3.2` branch:
- #880
- #884 
- #887
> [Backport] 3.2.2 backports

- src/rpc/rawtransaction.cpp
Just a couple little oversights, and a typo that was driving me crazy
> [RPC] Fix typos and oversights in listunspent

- src/zpiv/accumulators.cpp
Just an annoying missing jump line.
> [zPIV] Debug missing jump line.

- src/init.cpp
- src/main.cpp
- src/main.h
> [Backport] Max tip age to consider a node in IBD status customizable.

- src/chainparams.cpp
Removed non-running DNS for mainnet and testnet.
> [NET] Non-running dns servers removed from chainParams.

- doc/release-notes.md
Notable changes for 3.3.0
#ci-skip
> [Doc] 3.3.0 Notable Changes

- src/chain.h
- src/main.cpp
- src/txdb.cpp
- src/txdb.h
Backport from bitcoin https://github.com/bitcoin/bitcoin/pull/5367
> [Node] Do all block index writes in a batch

- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/forms/rpcconsole.ui
- src/qt/rpcconsole.cpp
Added the block hash of the latest block to the Tools -> Information tab.
And, while I was at it, added the used data-directory (similar to upstream).
> [Qt] Add blockhash + datadir to information tab

- src/chainparams.cpp
- src/main.cpp
- src/spork.cpp
- src/spork.h
- src/version.h
- test/functional/test_framework/messages.py
Built on top of #983, this adds the enforcement logic for 70917 and also
updates the spork key.
> [Net] Protocol update enforcement for 70917 and new spork keys

- doc/release-notes.md
- doc/release-notes/release-notes-3.3.0.md
Update release notes for the next release.
> [Doc] Release notes update

- src/qt/pivx/masternodeswidget.cpp
Trivial text change in MN screen.
"Master node" for "Masternode".
"No enough.." for "Not enough..".
> [Trivial][UI] MN screen, texts typo.

- src/Makefile.qt.include
- src/qt/pivx/addresseswidget.cpp
- src/qt/pivx/dashboardwidget.cpp
- src/qt/pivx/furabstractlistitemdelegate.cpp
- src/qt/pivx/masternodeswidget.cpp
- src/qt/pivx/pwidget.cpp
- src/qt/pivx/receivewidget.cpp
This aims to resolve the seemingly intermittent "missing moc" issue experienced when building on some systems.
> [Build] Fixup moc includes and generation

- src/qt/guiutil.cpp
- src/qt/guiutil.h
- src/qt/pivx/forms/sendconfirmdialog.ui
- src/qt/pivx/sendconfirmdialog.cpp
More than descriptive title, transaction detail dialog showing the transaction time seconds now.
> [GUI] Tx detail dialog, show seconds in toString date.

- src/qt/locale/pivx_en.ts
- src/qt/pivxstrings.cpp
Periodic `make translate` so we can push new strings to Transifex.
> [Qt] Update source strings

- src/init.cpp
> [Startup] Stop loading the wallet if shutdown was requested.

- src/qt/pivx/dashboardwidget.cpp
- src/qt/pivx/dashboardwidget.h
- src/qt/pivx/forms/dashboardwidget.ui
- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
Auto-explanaible title, left and right day range movement control buttons in the dashboard staking chart.
> [QT] Dashboard chart, left and right day range movement control buttons.

- src/compressor.h
- src/script/interpreter.cpp
- src/script/script.h
- src/streams.h
- src/test/coins_tests.cpp
ref: https://github.com/bitcoin/bitcoin/pull/7933
> Fix OOM when deserializing UTXO entries with invalid length

- src/crypter.h
- src/init.cpp
- src/init.h
- src/main.cpp
- src/util.cpp
- src/util.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
Back port from bitcoin#10952.
This PR is on top of #1029 because of both PRs modifying `init.cpp`. 
Check only the last commit.
> [Wallet][Startup][DB][Backport] Remove vchDefaultKey from wallet.h

- src/qt/pivx/forms/welcomecontentwidget.ui
Changes made, Mostly due to SwiftX being disabled and no privacy option yet for this release.
> [Qt] Update welcomecontentwidget.ui

- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
Hover state in the settings options buttons.
> [UI] Settings, options buttons hover css.

- src/wallet/rpcwallet.cpp
Self explanatory from the title,fixes the help text for the rpc comamnd delegatorremove.
> [Trivial] Fix help text for delegatorremove

- src/spork.cpp
Auto explainable title, guarding chainActive calls.
> [Sporks] Guard chainActive.Tip() and chainActive.Height() methods call.

- src/qt/pivx/sendcustomfeedialog.cpp
"Customize the transaction fee **at your to your liking**,"
Changed to:
"Customize the transaction fee **as per your wish**,"
> [Trivial] [GUI] Customize Fee Dialog text change

- src/masternode-sync.cpp
- src/masternode-sync.h
- src/obfuscation.cpp
Try locking cs_main when it looks for the tip, preventing possible shared resource issues.
> [Masterndoes] Masternodes sync, try locking cs_main when it looks for the tip.

- src/qt/addresstablemodel.cpp
- src/qt/addresstablemodel.h
- src/qt/pivx/receivewidget.cpp
- src/qt/pivx/send.cpp
- src/qt/pivx/topbar.cpp
Receive dialog, create address if addressbook is empty and/or inform the user and don't popup the dialog if the creation fails.
* getLastUnusedAddress, IsValid double check added just to be sure before present it in the UI.
> [Model][UI] Receive dialog, create address if addressbook is empty

- src/qt/pivx/sendconfirmdialog.cpp
Before the send transaction detail was not showing the destinations, this fixes it.
> [BUG] Fix send transaction detail destinations

- src/main.cpp
- src/version.h
- test/functional/test_framework/messages.py
Bumps protocol to `70918` and adds the enforcement logic.
> [Net] Protocol update enforcement for 70918

- src/qt/pivx/coldstakingmodel.cpp
- src/qt/pivx/coldstakingmodel.h
- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/coldstakingwidget.h
- src/qt/pivx/dashboardwidget.cpp
- src/qt/pivx/forms/coldstakingwidget.ui
- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
Cold staking screen:
* Warning label "Unconfirmed balance will not be shown" added.
* Stop updating model on every new block, only do it when the connection get lost.
> [GUI] Cold staking, Warning for unconfirmed balance + stop multiple model updates.

- src/qt/pivx/settings/forms/settingsconsolewidget.ui
- src/qt/pivx/settings/forms/settingsinformationwidget.ui
- src/qt/pivx/settings/settingsconsolewidget.cpp
- src/qt/pivx/settings/settingsinformationwidget.cpp
- src/qt/pivx/settings/settingswidget.cpp
Inform if open pivx conf and/or backups folder failed due an OS incapacity/restriction. 
Plus did some minor cleanup over the touched files.
Solving #1095.
> [GUI] Inform if open pivx.conf and/or backups folder fail.

- src/qt/pivx/masternodewizarddialog.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
Correction for regtest properly functioning in the UI.
> [GUI][Model] isTestNetwork regtest correction.

- src/qt/openuridialog.cpp
- src/qt/openuridialog.h
Re coded the URI from file read. Can be easily tested parsing a file with the following text pattern:
`pivx:%address%?amount=%number%?label=%text%?message=%text%`
About the code that was here before, really no comments.. 
This solves #1103
> [Bug] URI read from file coded properly..

- src/qt/pivx/sendchangeaddressdialog.cpp
- src/qt/pivx/sendchangeaddressdialog.h
Just a simple simple editable box focus in the custom change address dialog.
Solving #1150.
> [GUI][Trivial] Custom change address, editable box focus.

- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/coldstakingwidget.h
- src/qt/pivx/forms/coldstakingwidget.ui
- src/wallet/wallet.cpp
The total amount in the cold staking screen (delegations list section) was not being updated. This solves the issue + re organize the UI form to present it aligned to the texts in the left.
> [GUI][Bug] Cold staking screen, total amount was not being updated.

- src/qt/pivx/coldstakingwidget.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
It was not updated after the changes in Core. One more reason to never use magic numbers.
Also removes redundant calls to get the display unit.
> [GUI] Min cold staking amount in ColdStaking widget

- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/privacywidget.cpp
- src/qt/pivx/send.cpp
Improvement on #1189 
Tested working
> [GUI] Feature/Bug CoinControl Update on Open

- doc/release-notes.md
Work in progress release notes for the major changes coming in 4.0.0
> [Docs] 4.0.0 release notes

- src/qt/pivx/topbar.cpp
Auto-explainable title.
Solving the not shown locked balance.
> [GUI][Bug] Show locked balance in the available total amount.

- src/qt/pivx/forms/navmenuwidget.ui
- src/qt/pivx/navmenuwidget.cpp
- src/qt/pivx/pivxgui.cpp
Adding capability to decrease the screen size for small screens supports.
Have modified the navigation menu to be scrollable.
> [GUI] Adding capability to decrease the screen size for small screens.

- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/guitransactionsutils.cpp
- src/qt/pivx/guitransactionsutils.h
- src/qt/pivx/masternodewizarddialog.cpp
- src/qt/pivx/masternodewizarddialog.h
- src/qt/pivx/pwidget.h
- src/qt/pivx/send.cpp
Masternode creation wizard, creation fail event properly detailing the failure cause in the subsequent error dialog.
This will give more information for #1210.
> [GUI] MN creation wizard, fail event detailing the failure cause.

- src/qt/pivx/forms/masternodeswidget.ui
- src/qt/pivx/masternodeswidget.cpp
- src/qt/pivx/masternodeswidget.h
- src/qt/pivx/mnmodel.cpp
- src/qt/pivx/mnmodel.h
> [GUI] Masternodes start all and start missing flows implemented.

- src/rpc/client.cpp
- src/wallet/rpcdump.cpp
- test/functional/test_runner.py
- test/functional/wallet_import_stakingaddress.py
Still it remains to add proper support in `dumpwallet` and `importwallet`
> [RPC] Add coldstaking address support in importprivkey and importaddress

- src/qt/pivx/masternodeswidget.cpp
- src/qt/pivx/masternodeswidget.h
- src/qt/pivx/mnmodel.cpp
- src/qt/pivx/mnmodel.h
Coming from this comment https://github.com/PIVX-Project/PIVX/pull/1221#pullrequestreview-340783456 from @Mrs-X .
This was coded on top of #1221, once that gets merged the two first commits will disappear.
> [GUI] Every MN action checking tier two synced.

- src/main.cpp
Simple addition for better logging as the title says: represent `log2_work` with 16 decimals.
> [Trivial] Log log2_work value with 16 decimals

- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
- src/qt/forms/coincontroldialog.ui
CoinControlDialog, copy to clipboard action implemented in every showed label + inform snackbar notifying the user.
> [GUI] CoinControlDialog, every copy to clipboard action implemented.

- src/qt/pivx/topbar.cpp
Quick one. `setNumBlocks` is already connected.
Just need to set the text.
Preview:
> [GUI] Display latest block number in the top bar

- src/qt/pivx/forms/sendcustomfeedialog.ui
> [Trivial] fix typo "recomended" in sendcustomfee dialog

- src/libzerocoin/Coin.cpp
auto-descriptive title.
Side from this, checked @random-zebra's PRs and didn't find this cleanup. If for some reason I missed it and it's inside one of the PRs, let me know and can close this PR.
> [zPIV] Public coin, a super for-each removed.

- .travis.yml
- .travis/test_04_install.sh
- contrib/devtools/test-security-check.py
- contrib/gitian-descriptors/gitian-win.yml
- depends/README.md
- doc/build-windows.md
- doc/release-process.md
Coming from [btc@15939](https://github.com/bitcoin/bitcoin/pull/15939).
Based on #1315.
> [Build] Remove Windows 32 bit build.

- src/init.cpp
- src/main.cpp
- src/test/test_pivx.cpp
Upstream@[8392](https://github.com/bitcoin/bitcoin/pull/8392) backport.
> [Backport] Wait locking for genesis connection.

- src/qt/pivx/forms/masternodewizarddialog.ui
Replace dot with comma to keep consistency within the wallet (sending amounts, FAQ, masternode creation wizard, etc.)
> [Trivial] Minor showed amount fix

- build-aux/m4/bitcoin_qt.m4
Further cleanups to the Qt m4 file that I wanted to keep separate from #1351
> [Build] Cleanup Qt m4 file

- src/net.cpp
Minor updates to how the banlist is handled. ported from https://github.com/bitcoin/bitcoin/pull/7350
> [Net] Banlist updates

- src/qt/pivx/settings/settingsbittoolwidget.cpp
> [Trivial] Fix typo in settingsbittoolwidget.cpp

- src/Makefile.qt.include
- src/qt/CMakeLists.txt
- src/qt/addresstablemodel.cpp
- src/qt/addresstablemodel.h
- src/qt/pivx/dashboardwidget.cpp
- src/qt/pivx/qtutils.cpp
- src/qt/pivx/qtutils.h
- src/qt/pivx/settings/forms/settingsexportcsv.ui
- src/qt/pivx/settings/forms/settingswidget.ui
- src/qt/pivx/settings/settingsexportcsv.cpp
- src/qt/pivx/settings/settingsexportcsv.h
- src/qt/pivx/settings/settingswidget.cpp
- src/qt/pivx/settings/settingswidget.h
PR adding export CSV files functionality. (it's in a full screen to be able to add the export addresses (internal and remote), transactions/addresses filters, plus any other csv export functionality organized in a single location).
> [GUI] Export csv files.

- src/qt/pivx/expandablebutton.cpp
- src/qt/pivx/expandablebutton.h
- src/qt/pivx/forms/topbar.ui
- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
- src/qt/pivx/topbar.cpp
- src/qt/pivx/topbar.h
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
This was built on top of #1399. 
Essentially connecting the HD wallet upgrade to the GUI as it was defined in the release-notes in #1327.
> [GUI] Upgrade to HD wallet functionality.

- src/qt/pivx/send.cpp
- src/qt/pivx/send.h
> [GUI] SendWidget: automatically set focus on last recipient entry

- src/miner.cpp
> [Trivial] Cleaning not used pCheckpointCache.

- src/qt/pivx/settings/forms/settingswidget.ui
- src/qt/pivx/settings/settingswidget.cpp
- src/qt/pivx/settings/settingswidget.h
> [GUI] Settings widget, expand/collapse scroll area.

- src/Makefile.test.include
- src/test/accounting_tests.cpp
- src/test/test_pivx.cpp
- src/test/zerocoin_transactions_tests.cpp
- src/wallet/test/wallet_test_fixture.cpp
- src/wallet/test/wallet_test_fixture.h
- src/wallet/test/wallet_tests.cpp
Created a new testing setup for unit tests that requires the wallet. 
Removing the dependency from the ones that don't need it.
> [Test] Wallet testing setup.

- src/qt/pivx/forms/sendconfirmdialog.ui
- src/qt/pivx/sendconfirmdialog.cpp
> [GUI] Add address-label to sendconfirm-popup

- src/qt/coincontroldialog.cpp
Implemented on top of:
(only last commit is new)
**Problem**: As outlined in the description of #1391, delegated outputs are not clearly distinguishable in the coin control dialog.
**Proposed Solution**: Add a "cold staking icon" (purple snow flake) at the end of delegated utxo rows. Hovering on this icon shows a tooltip with the staker address which has received the delegation.
<br>
> [GUI] Mark delegated UTXOs in CoinControl

- src/chain.cpp
- src/chain.h
- src/chainparams.cpp
- src/consensus/params.h
- src/consensus/tx_verify.cpp
- src/consensus/tx_verify.h
- src/kernel.cpp
- src/main.cpp
- src/miner.cpp
- src/primitives/block.h
- src/primitives/transaction.cpp
- src/primitives/transaction.h
- src/rpc/blockchain.cpp
- src/script/interpreter.cpp
- src/script/script.cpp
- src/script/script.h
- src/script/script_error.cpp
- src/script/script_error.h
- src/version.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- test/functional/mining_pos_reorg.py
- test/functional/test_framework/messages.py
- test/functional/test_framework/test_framework.py
After further study and testing, we've decided not to adopt this implementation.
This PR reverts the changes introduced with #1462
> [Consensus] Revert 1462

- src/zpiv/zpos.cpp
> [BUG] Fix ambiguous call to distance in ParseAccChecksum

- src/qt/pivx/masternodeswidget.cpp
> [Trivial] Rewording of remote masternode data export notification

- src/qt/pivx/res/img/dark/ic-transaction-mint-inactive.svg
- src/qt/pivx/res/img/dark/ic-transaction-received-inactive.svg
- src/qt/pivx/res/img/dark/ic-transaction-sent-inactive.svg
- src/qt/pivx/res/img/dark/ic-transaction-staked-inactive.svg
Fixing inactive icons colors for the dark theme.
> [GUI] Dark theme, inactive icons color fix.

- src/qt/pivx/send.cpp
auto-descriptive title. #1524 .
> [GUI] Warn about change address not belonging to the wallet.

- test/functional/test_framework/test_node.py
- test/functional/test_framework/util.py
backports bitcoin#13198 and adds/moves missing flags in initialize_datadir
> [QA] Avoid printing to console during cache creation

- src/qt/coincontroldialog.cpp
> [GUI][Bug] CoinControl: mark delegated after setting checked state

- src/qt/pivx/sendcustomfeedialog.cpp
> [Bug][GUI] SendCustomFee: reset checkbox on clearAll

- src/main.cpp
- src/qt/pivx/settings/settingswidget.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/wallet/walletdb.cpp
Multisend flow is clunky and sorely out of date / in need of a full overhaul and review.
Let's disable it for now until such time that it can be either re-coded properly, or just dropped entirely.
We can thus close the following issues for now: #1560, #1561, #1563, #1567 .
> [RPC][GUI][Bug] Disable/Hide multisend

- src/qt/pivx/send.cpp
- src/qt/pivx/sendcustomfeedialog.cpp
- src/qt/pivx/sendcustomfeedialog.h
Straightforward update, as per title.
Closes #1570 
EDIT: cherrypicked a commit from @furszy , for min fee validation too.
> [GUI] SendCustomFeeDialog: prevent user from saving insane fees

- src/qt/pivx.cpp
- src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
- src/qt/pivx/welcomecontentwidget.cpp
- src/qt/pivx/welcomecontentwidget.h
Quick solution to the translations issue #1597 .
fixes #1597
> [GUI][Bug] Fix language selection invalidly stored

- doc/release-notes.md
Complete release notes for 4.1.0.
Marked `[WIP]` for now as there are still a couple un-merged PRs that need to be added
> [Doc] Finalize 4.1.0 release notes

- src/qt/pivx/topbar.cpp
auto-descriptive title. Solving #1600
> [GUI] Tor state missing translation

- doc/release-notes.md
- doc/release-notes/release-notes-4.1.0.md
Basic maintenance PR, as per title.
> [Doc] save historical release notes for 4.1.0 and reset template

- src/qt/guiutil.cpp
Built on top of #1515, only last commit counts for this.
When MacOS has no default app to open *.conf and *.log throws an error instead of try to open them with a text editor. This PR solves the issue.
Coming from btc@[16044](https://github.com/bitcoin/bitcoin/pull/16044)
> [GUI] MacOS fix open files with no default app.

- src/init.cpp
- src/net.cpp
Coming from upstream@[9002](https://github.com/bitcoin/bitcoin/pull/9002)
> [Backport] Make connect=0 disable automatic outbound connections.

- src/amount.cpp
- src/amount.h
- src/init.cpp
- src/qt/askpassphrasedialog.cpp
- src/qt/bitcoinunits.cpp
- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/dashboardwidget.cpp
- src/qt/pivx/masternodeswidget.cpp
- src/qt/pivx/requestdialog.cpp
- src/qt/pivx/send.cpp
- src/qt/transactiontablemodel.cpp
- src/qt/walletmodel.cpp
- src/rpc/budget.cpp
- test/functional/feature_help.py
> [Refactor] Define constant string variable for currency unit

- src/main.cpp
Coming from upstream@[12561](https://github.com/bitcoin/bitcoin/pull/12561)
> [Backport] Shut down if trying to connect a corrupted block

- src/masternodeman.cpp
- src/protocol.cpp
- src/protocol.h
> [Bug] removed "dseg" message support re-introduced.

- src/qt/pivx/masternodewizarddialog.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
If the wallet already has an unlocked 10k PIV utxo, use that in the masternode creation wizard, instead of making a new transaction (which requires to pay an additional fee and wait for the needed confirmations).
> [GUI] Reuse collateral UTXOs in MnWizard

- src/chain.cpp
- src/chain.h
- src/chainparams.cpp
- src/consensus/params.cpp
- src/consensus/params.h
- src/consensus/upgrades.cpp
- src/consensus/zerocoin_verify.cpp
- src/init.cpp
- src/kernel.cpp
- src/legacy/stakemodifier.cpp
- src/main.cpp
- src/masternode-budget.cpp
- src/masternode-payments.cpp
- src/miner.cpp
- src/pow.cpp
- src/rpc/blockchain.cpp
- src/rpc/mining.cpp
- src/stakeinput.cpp
- src/test/budget_tests.cpp
- src/test/upgrades_tests.cpp
- src/txdb.cpp
- src/wallet/rpcdump.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/zpiv/zpos.cpp
- src/zpivchain.cpp
- src/zpivchain.h
Refactor the past height-based network upgrades with the new interface provided by #1665
> [Refactor] Network upgrades management cleanup

- src/base58.cpp
- src/base58.h
- src/main.cpp
- src/test/bip32_tests.cpp
Coming from:
* bitcoin#6468 .
* bitcoin#7656 .
* bitcoin#7922
* bitcoin#8736 .
* bitcoin#10961 .
> [Backport] Base58 performance improvements

- doc/release-notes.md
Document the changes introduced in:
- #1549: Nuke zPIV from the GUI
- #1586: Minimum value for stake split threshold
- #1633: Bitcoin 0.12-0.14 serialization improvements
- #1645: Implement accurate memory accounting for mempool
- #1647: MemPool package tracking and limits
- #1650: Benchmarking Framework
- #1688: TopBar navigation (sync/peers)
> [Doc] Add/Update some release notes for 4.2

- src/qt/pivx/forms/sendcustomfeedialog.ui
> [GUI][Trivial] Change Custom fee amount when Recommended fee is selected

- src/Makefile.am
- src/Makefile.test.include
- src/cuckoocache.h
- src/init.cpp
- src/script/sigcache.cpp
- src/script/sigcache.h
- src/test/cuckoocache_tests.cpp
- src/test/test_pivx.cpp
Built on top of #1668.
Part of the back port series to get us closer to upstream's sigcache current state.
The main ones are:
* bitcoin#8895
* bitcoin#9480
* bitcoin#9393
> Better sigcache implementation (CuckooCache)

- src/wallet/wallet.cpp
Check for explicit wallet conflicts when `fFromLoadWallet` (from bitcoin/bitcoin@9ac63d6d3056600c1b784da0e6b98f679fa98b6e, wrongly backported in #970).
> [Wallet][BUG] fix detection of wallet conflicts in CWallet::AddToWallet

- src/qt/locale/pivx_en.ts
- src/qt/pivx/topbar.cpp
- src/qt/pivxstrings.cpp
Update source strings for export to Transifex prior to 4.2 branch off.
Also fixed a single case of trailing whitespace in `topbar.cpp`
> [GUI] Periodic make translate

- src/qt/pivx/settings/settingsconsolewidget.cpp
Fixes #1712 .
Moved the object to read only.
> [GUI] Settings console message moved to read only.

- src/miner.cpp
Small cleanup of an unused variable.
The miner code needs a good structural refactoring.
> [Miner] Unused reserveKey cleanup

- doc/release-notes.md
Minor re-arrangement of sections, added PR changelog and authors, and
noted that this is a recommended update.
> [Doc] 4.2.0 Release Notes

- src/primitives/block.cpp
- src/primitives/block.h
- src/wallet/wallet.h
- src/wallet/wallet_zerocoin.cpp
Cleaned zerocoin methods that are not used anymore in the wallet and in the block primitive.
> [Wallet] Simple unused methods cleanup.

- src/support/cleanse.h
- src/wallet/db.h
Straightforward back port PR, coming from #10308.
> [wallet] Securely erase potentially sensitive keys/values

- src/compat/glibc_compat.cpp
add missing function declaration
> [Build] Fix glibc compat

- depends/packages/openssl.mk
- src/addrman.h
- src/chain.h
- src/coins.cpp
- src/coins.h
- src/main.cpp
- src/main.h
- src/masternode-budget.cpp
- src/masternode-payments.cpp
- src/masternode.cpp
- src/masternode.h
- src/masternodeman.cpp
- src/miner.cpp
- src/net.cpp
- src/net.h
- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/test/DoS_tests.cpp
- src/txmempool.cpp
- src/undo.h
- src/wallet/wallet.cpp
- test/functional/feature_block.py
Backports the following PRs to the `4.2` branch:
#1746
#1735
#1767
#1769
#1781
#1780
#1775
#1783
#1750
#1785
#1796
#1776
#1791
> [Backport] 4.2.1 backports

- src/wallet/wallet.cpp
Improvement over the coinstake transaction creation flow, it will speed up the process a lot.
Removing a for loop redundancy (it was looping over the available outputs twice), removing a simply bad usage of unique_ptr, guarding `chainActive` access, removing unused zPoS code and few smaller warnings fixes.
> [Wallet] Speedup coinstake creation removing redundancies.

- .tx/config
- contrib/gitian-descriptors/gitian-linux.yml
- contrib/gitian-descriptors/gitian-osx.yml
- contrib/gitian-descriptors/gitian-win.yml
- src/qt/locale/pivx_en.ts
- src/qt/pivxstrings.cpp
Sets the appropriate gitian descriptor version, does a `make translate`, and sets the appropriate slug in the transifex config file.
Final version bump to `configure.ac` and the `Snapcraft.yaml` file to be done once this and #1841 are merged.
> [Build] Prepare for 4.3.0 release

- src/qt/locale/pivx_de.ts
- src/qt/locale/pivx_en.ts
- src/qt/locale/pivx_en_US.ts
- src/qt/locale/pivx_es.ts
- src/qt/locale/pivx_es_ES.ts
- src/qt/locale/pivx_fr_FR.ts
- src/qt/locale/pivx_hr_HR.ts
- src/qt/locale/pivx_it.ts
- src/qt/locale/pivx_ko_KR.ts
- src/qt/locale/pivx_nl.ts
- src/qt/locale/pivx_pl.ts
- src/qt/locale/pivx_ru.ts
- src/qt/locale/pivx_tr.ts
- src/qt/locale/pivx_zh_CN.ts
- src/qt/pivxstrings.cpp
Updates translations from transifex for the 4.3.0 release
> [GUI] Update translations for 4.3.0

- doc/release-notes.md
Finalized release notes for 4.3.0
> [Doc] 4.3.0 Release Notes

- src/main.cpp
- src/main.h
- src/rpc/blockchain.cpp
Small PR, fixed some compiler warnings that have been seen recurrently.
> [Misc] Fixing recurrent compiler warnings 

- src/wallet/wallet.cpp
Fixing `CWallet::GetMasternodeVinAndKeys` accessing `mapWallet` without locking `cs_wallet`.
Decoupled from #1829 .
> [wallet] GetMasternodeVinAndKeys wasn't locking cs_wallet to obtain the collateral.

- src/Makefile.test.include
- src/test/CMakeLists.txt
- src/test/script_P2CS_tests.cpp
Essentially proving #1830 bug and #1888 subsequent fix.
> [Test] unit test checking cold staking script key extraction.

- src/qt/pivx/settings/settingsconsolewidget.cpp
- src/qt/rpcconsole.cpp
Adds autocompletion for the 'help' command.
from https://github.com/bitcoin/bitcoin/pull/9500
> [GUI] Autocomplete 'help' PRC commands in UI Consoles

- src/test/mempool_tests.cpp
- src/txmempool.cpp
- src/txmempool.h
Straightforward back port https://github.com/bitcoin/bitcoin/pull/7539
> [Mempool] Add tags to mempool's mapTx indices

- src/rpc/rawtransaction.cpp
#1336 Introduced a "lock-not-held" assertion in `sendrawtransaction` RPC as per upstream.
But, while in Bitcoin `sendrawtransaction` calls `BroadcastTransaction`, which then locks `cs_main` before `AcceptToMemoryPool`, we call directly ATMP without any lock.
This fixes it.
> [BUG][RPC] Add missing lock in sendrawtransaction

- src/dbwrapper.cpp
- src/dbwrapper.h
- src/guiinterfaceutil.h
- src/init.cpp
- src/net_processing.cpp
- src/pivx-tx.cpp
- src/streams.h
- src/test/dbwrapper_tests.cpp
- src/txdb.cpp
- src/txdb.h
- src/wallet/db.cpp
- src/wallet/db.h
- src/wallet/test/wallet_tests.cpp
- src/wallet/wallet.cpp
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
Upgrading the wallet, wallet db and db wrapper areas with several back ports and updates adaptations.
List of PRs:
* #5933
* #7537
* #8191
* #8564
* #8574
* #8629
* #9353
Note:
Low priority PR, can be reviewing after merge Sapling and tier two PRs. 
I made it because we are pretty far from upstream in the db area and want to introduce some new functionality in the future that requires a more up-to-date db layer.
> [Wallet][DB] Back ports up to the CWallet/CWalletDB/CDB refactor.

- src/qt/pivx/settings/forms/settingsfaqwidget.ui
> [GUI] FAQ "Exit" moved to "Close FAQ"

- src/sapling/sapling_txdb.cpp
Trivial one.
Log the number of changed sapling nullifiers/anchors when batch-writing in the coins view database.
> [Trivial] Log changed count for sapling nullifiers and anchors

- .github/workflows/build-and-test.yml
- contrib/devtools/lint-whitespace.sh
Instead of opening multiple pull requests to fixup the remaining issues with the GA workflow, i've condensed them here as follows:
1. GA doesn't update apt mirrors internally during initialization, so force
this behavior ourselves to prevent intermittent apt package install
issues
2. #1990 was an incorrect fix, but it didn't result in a CI job error
3. don't use `ubuntu-latest` identifier as that is subject to change.
> [Build] Fix a few GA issues

- test/functional/sapling_supply.py
- test/functional/test_runner.py
Add basic test for the shielded pool value update, as suggested in https://github.com/PIVX-Project/PIVX/pull/1982#pullrequestreview-537029426
> [Tests] Add sapling_supply functional test

- src/qt/pivx/send.cpp
With the introduction of the dynamic fee calculation for shielded transaction (#1979), the "shield all transparent balance" flow got broken due the different fee requirements.
In other words, as we are shielding all the available transparent balance, the dynamic fee requirement needs to be known before hand to be subtracted from the total amount that is going to be shielded (otherwise the wallet has no other utxo to add to the transaction to cover the fee).
So.. this PR fixes it calculating and subtracting the fee from the recipient total amount before create the transaction.
> [BugFix] [GUI] Shield all transparent balance fee calculation.

- src/Makefile.qt.include
- src/qt/CMakeLists.txt
- src/qt/pivx.qrc
- src/qt/pivx/coldstakingwidget.cpp
- src/qt/pivx/forms/sendconfirmdialog.ui
- src/qt/pivx/forms/sendmemodialog.ui
- src/qt/pivx/forms/sendmultirow.ui
- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
- src/qt/pivx/res/img/ic-chevron-right-liliac.svg
- src/qt/pivx/send.cpp
- src/qt/pivx/send.h
- src/qt/pivx/sendconfirmdialog.cpp
- src/qt/pivx/sendmemodialog.cpp
- src/qt/pivx/sendmemodialog.h
- src/qt/pivx/sendmultirow.cpp
- src/qt/pivx/sendmultirow.h
- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/walletmodel.cpp
- src/sapling/saplingscriptpubkeyman.cpp
- src/sapling/saplingscriptpubkeyman.h
Essentially implemented the visual capabilities to make use of the encrypted memo field of the new privacy protocol in the GUI. 
This means transaction record loaded with the memo, send screen memo connection for single shielded outputs and memo visualizations in the transaction confirmation dialog and transaction detail dialog (this second one used to visualize incoming transactions memos).
> [GUI] Encrypted memo feature implemented

- src/sapling/saplingscriptpubkeyman.cpp
- src/sapling/saplingscriptpubkeyman.h
Fix some class function not marked `const`.
Also add a brief description for the class (removing another todo left there).
> [Trivial] constant functions in SaplingScriptPubKeyMan

- src/qt/pivx/send.cpp
Bug found by @jakimanboy (https://github.com/PIVX-Project/PIVX/pull/1999#issuecomment-736984982)
In the send widget, we are presenting a warning if a `t->t` tx includes any memo.
But this is not the correct logic, as it doesn't cover all possible mis-placements:
- a `t->s` tx could still have the memo set on a transparent recipient. The warning is not triggered though, if the transaction has at least one shielded recipient (thus it's a shielded tx).
- a `s->t` tx should not be able to include any memo, yet no warning is triggered.
Memos are encrypted in the ciphertext of the **output** description, so the only thing that matters here are the outputs.
We should check the presence of the memo, for each output, against the recipient address of __that particular__ output.
> [BUG][GUI] Encrypted memo with transparent recipient address

- src/spork.cpp
Discard known stale protocol enforcement spork data during startup.
Quick workaround for clients that have not yet seen the new spork 15 broadcast since they last ran.
This evaluates the signing time of spork 15 (used to disconnect peers in the version handshake) and
discards the data of known-stale information. This will prevent the need for such clients to manually
delete the `sporks` folder in their datadir.
> [Net] Prevent un-necessary disconnections in version handshake

- src/qt/pivx/receivewidget.cpp
- src/qt/pivx/send.cpp
- src/qt/transactionrecord.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
Visual notification, do not try to create shielded addresses or process shielded spends if v5 upgrade hasn't been enforced yet.
> [GUI] Guard shielded flows pre-v5 enforcement

- src/addrman.h
Straightforward cherry-pick from bitcoin/bitcoin#11585
> [P2P] Add missing lock in CAddrMan::Clear()

- COPYING
Add `The Zcash developers` to the `COPYING` file.
> [Trivial] Add Zcash copyright statement

- test/functional/mining_pos_reorg.py
- no need to check "spendable" utxos (as we are not dealing with watch-only).
- no need to catch `bad-txns-inputs-spent` exception with `sendrawtransaction` (as we are not dealing with zPIVs anymore)
- double check that the double-spend is not on chain/mempool with `getrawtransaction`
> [Tests] minor fixes for mining_pos_reorg.py

- README.md
Another step towards better documentation, the main repo's readme hasn't being updated in a while, this PR updates it to the current project state.
Have added only the bare minimum project information, for the rest, the reader is pointed to PIVX.org (future task would be to continue adding more documents, explaining how each part of the system work and link them here as well instead of depend on the website information).
> [Doc] Main readme re-written, updated to the current project state.

- doc/release-notes.md
Initial cycle over the v5 release notes. 
Added information about the new introduced core features, block and transaction primitives changes, SHIELD GUI and wallet capabilities, tier two network improvements and the thread synchronization overhaul.
-- Pending proofreading --
> [Doc] v5 Release Notes

- src/qt/pivx/receivewidget.cpp
> [GUI] Receive screen, fix missing "Add label" text.

- src/budget/budgetmanager.cpp
- src/budget/budgetmanager.h
- src/budget/finalizedbudget.h
- src/chainparams.cpp
- src/masternode-payments.cpp
- src/masternode-payments.h
- src/test/budget_tests.cpp
- src/version.h
Also bump active protocol and add checkpoint.
> [Consensus] Fix superblock block value

- src/budget/budgetdb.cpp
- src/budget/budgetmanager.cpp
- src/budget/budgetmanager.h
- src/budget/finalizedbudget.h
- src/chainparams.cpp
- src/init.cpp
- src/masternode-payments.cpp
- src/masternode-payments.h
- src/masternode.cpp
- src/masternodeman.cpp
- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/protocol.cpp
- src/protocol.h
- src/qt/pivx/receivewidget.cpp
- src/spork.cpp
- src/test/budget_tests.cpp
- src/version.h
backport the following PRs to the `5.0` branch:
#2128
#2133
#2130
#2134
#2129
#2136
#2137
> [Backport] 5.0.1 backports

- src/rpc/budget.cpp
Refactored and cleaned the `mnbudgetvote` RPC command code up to the point of not having code duplication there.
> [RPC] mnbudgetvote generalized, duplicated code cleaned.

- src/primitives/transaction.h
- src/rpc/blockchain.cpp
- src/script/interpreter.cpp
- src/script/script.h
- src/test/dbwrapper_tests.cpp
- src/txdb.cpp
- src/wallet/walletdb.cpp
Straightforward cleanup, from bitcoin/bitcoin#10760
> [Refactoring] Avoid dereference-of-casted-pointer

- test/functional/interface_zmq.py
- test/functional/test_runner.py
Fixing and enabling zmq functional test.
> [Tests] Fix and enable zmq functional test in the test suite

- src/qt/pivx/forms/dashboardwidget.ui
> [GUI][Trivial] Minor content change for more precise description

- src/qt/addressbookpage.h
- src/qt/addresstablemodel.cpp
- src/qt/addresstablemodel.h
- src/qt/coincontroldialog.h
- src/qt/notificator.cpp
- src/qt/pivx.cpp
- src/qt/pivx/coldstakingmodel.h
- src/qt/pivx/coldstakingwidget.h
- src/qt/pivx/dashboardwidget.h
- src/qt/pivx/receivewidget.h
- src/qt/pivx/requestdialog.h
- src/qt/pivx/sendmultirow.h
- src/qt/pivx/settings/settingswidget.h
- src/qt/pivx/txviewholder.h
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
- src/qt/transactiontablemodel.h
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
Trivial. Add default initialization for the members of some GUI class.
> [GUI][Trivial] Default initialization for scalar and pointer fields

- src/Makefile.test.include
- src/test/CMakeLists.txt
- src/test/script_standard_tests.cpp
Coming straight from upstream, unit tests covering standard scripts.
> [Test] script standard tests back ported

- src/wallet/db.cpp
Fixes linking problem as seen on GA CMake-macOS  [here](https://github.com/PIVX-Project/PIVX/runs/2032160204).
From bitcoin/bitcoin#8626
> [Wallet] Berkeley DB v6 compatibility fix

- src/blockassembler.cpp
- src/primitives/block.h
- src/wallet/test/wallet_shielded_balances_tests.cpp
Bump block version in preparation for PIVX 5.1.0 release.
> [Protocol] Block version 9

- src/qt/locale/pivx_en.ts
- src/qt/pivxstrings.cpp
Updates the source strings prior to branch-off
> [GUI] Pre-5.1 make translate

- src/core_io.h
- src/core_read.cpp
- src/pivx-tx.cpp
- src/primitives/transaction.h
- src/rest.cpp
- src/rpc/rawtransaction.cpp
- src/script/interpreter.cpp
- src/script/script.cpp
- src/script/script.h
- src/test/script_tests.cpp
- src/utiltime.cpp
- test/functional/test_framework/script.py
- test/util/data/bitcoin-util-test.json
Simple refactoring + backport bitcoin#9743
> [Core] Fix several potential issues found by sanitizers

- test/functional/mempool_packages.py
Solving the intermittent failures in mempool_packages test that happen way too often.
Coming straight from #7368.
PD: thanks to my good zebra for finding the cause
> [Test] Eliminate race condition in mempool_packages test

- src/qt/pivx/sendcustomfeedialog.cpp
Implementing the comment https://github.com/PIVX-Project/PIVX/pull/2215#discussion_r598132747
> [GUI] if the custom fee is disabled, use minimum required fee

- src/qt/pivx/pivxgui.cpp
Straightforward, ported #12838 solution for Windows users.
> [GUI] Show the window when double clicking the taskbar icon

- src/addrdb.cpp
- src/addrdb.h
- src/budget/budgetdb.cpp
- src/masternode-payments.cpp
- src/masternodeman.cpp
- src/netaddress.h
- src/protocol.h
- src/script/keyorigin.h
- src/serialize.h
- src/test/net_tests.cpp
- src/test/serialize_tests.cpp
- src/test/streams_tests.cpp
- src/util.cpp
- src/util.h
- src/validation.cpp
Digging down the peers and ban databases commits path in upstream found some good stuff, back ported the following PRs:
* #9216.
* #10248.
* #12740.
* #13039.
* #16212.
> Addrdb code deduplication + Native support for FLATDATA + Add file syncing logging and error handling

- src/netaddress.cpp
- src/netaddress.h
Trivial. Ref: https://github.com/PIVX-Project/PIVX/pull/2304#discussion_r616384386
> [Trivial] fix indenting and code styling in netaddress.h/.cpp

- .tx/config
- src/qt/locale/pivx_de.ts
- src/qt/locale/pivx_en.ts
- src/qt/locale/pivx_en_US.ts
- src/qt/locale/pivx_es.ts
- src/qt/locale/pivx_es_ES.ts
- src/qt/locale/pivx_fr_FR.ts
- src/qt/locale/pivx_hr_HR.ts
- src/qt/locale/pivx_it.ts
- src/qt/locale/pivx_ko_KR.ts
- src/qt/locale/pivx_nl.ts
- src/qt/locale/pivx_pl.ts
- src/qt/locale/pivx_ru.ts
- src/qt/locale/pivx_tr.ts
- src/qt/locale/pivx_zh_CN.ts
- src/qt/pivxstrings.cpp
Pull translations from transifex for the 5.1.0 release
> [GUI] Update translations for 5.1.0

- doc/release-notes.md
Finalized release notes for v5.1.0
> [Doc] v5.1.0 Release Notes

- src/test/dbwrapper_tests.cpp
> [BUG][Tests] Properly set temporary datadir for dbwrapper_basic_data

- src/wallet/wallet.cpp
> [Backport] wallet fix segfault for P2CS inputs in CreateTransaction

- doc/release-notes.md
Finalized release notes for v5.2.0.
> [Doc] v5.2.0 Release Notes

- src/script/interpreter.cpp
- src/script/script.cpp
- src/script/script.h
- src/test/script_P2CS_tests.cpp
- src/validation.cpp
Remove contextual global flag guarding v5.2 enforcement
> [Refactor][Cleanup] remove g_newP2CSRules flag

- src/qt/pivx/mninfodialog.cpp
- src/qt/pivx/mninfodialog.h
Stop shadowing local variables
Make variables const where appropriate
Truncate net address for Tor v3 addresses
> [Refactor][GUI] Clean up mninfodialog

- contrib/gitian-descriptors/gitian-linux.yml
- contrib/gitian-descriptors/gitian-osx.yml
- contrib/gitian-descriptors/gitian-win.yml
Set the version in the gitian descriptors to match the branch version, this was missed for the rc1 tag
> [Gitian] Set version to 5.3

- src/chainparams.cpp
Add two checkpoints for main net in chainparams.
> [Consensus] Add checkpoints before v5.3.1 release

- doc/release-notes/release-notes-5.3.1.md
Auto-descriptive title, release notes for the coming v5.3.1.
> [Doc] v5.3.1 Release Notes

- src/validation.cpp
- test/functional/mining_pos_fakestake.py
> [Backport] 5.3.2 backports

- src/Makefile.qt_locale.include
- src/qt/locale/pivx_en.ts
- src/qt/locale/pivx_ko_KR.ts
- src/qt/pivx_locale.qrc
Straight forward scripted update of the translations from transifex based on the `5.3` branch.
The Korean language got back up over the 80% threshold, and many more strings have been translated for the Polish language since 5.3.2.1
> [GUI] Update translations from transifex for v5.3.3

- src/init.cpp
- src/init.h
- src/qt/pivx.cpp
Cleaning code redundancies from the "restart with args" process.
> [GUI] Clean restart process

- src/budget/finalizedbudget.cpp
- src/budget/finalizedbudget.h
- test/functional/tiertwo_governance_sync_basic.py
same as it's done on the proposals side.
> [Tiertwo] Clean inactive MNs from the fin count.

- src/qt/pivx/res/css/style_dark.css
- src/qt/pivx/res/css/style_light.css
Previously, the governance nav button was not showing the same
background color as the rest of the nav buttons. This fixes it to be
the same as the others.
Also slightly increase the size of the icon.
> [GUI] Fix governance nav button hover css

- src/wallet/rpcwallet.cpp
Currently called twice in `listunspent` rpc for each utxo (three times for P2SH).
Coming from bitcoin#7825
> [Refactor] Prevent multiple calls to ExtractDestination

- doc/release-notes/release-notes-5.4.0.md
Final release notes for the coming v5.4.0 release.
Note: #2678 is still pending.
> [Doc] v5.4.0 release notes

- doc/release-notes/release-notes-5.4.0.md
Add the 5.4.0 historical release notes to master branch.
-- Merge only when the release gets tagged --
> [Doc] Add v5.4.0 historical release notes

- src/qt/clientmodel.cpp
- src/qt/pivx/governancemodel.cpp
- src/qt/pivx/governancewidget.cpp
Followup to #2717 which was incorrectly marking proposals as Over Budget
instead of Not Passing
> [GUI] Fix Passing Not Funded logic

- test/functional/mining_pos_coldStaking.py
Adds RPC test coverage for the following RPC Commands:
- liststakingaddresses
- listdelegators
- delegatorremove
> [Tests] Add further RPC test coverage for cold staking

- src/httpserver.cpp
Lately, we have been spending a lot of time messing with our test cases. We are hitting random errors at various points and it is causing us to waste time constantly fixing and re-running tests in order to be 'ready for review'. After discussion with the other developers, I went and looked into the code and found some tiny improvements that can assist us in not dealing with these cases anymore.
Threads are still considered active, even if the code is finished executing before being joined, and we do not want to try to join them if the code is not finished executing. So we are now checking if the threads can be closed and we are doing a little bit better cleanup of 0 > nullptr. Lastly, we want to make sure any queue is empty before closing.
To test: 
The best route is to fork this branch …
> [Core][Tests] Cleanup HTTPServer start and stop

- src/bls/bls_batchverifier.h
- src/llmq/quorums_signing.cpp
- src/llmq/quorums_signing_shares.cpp
- src/test/bls_tests.cpp
The first commit updates `bls_batchverifier.h` to the most recent upstream version
The second commit adds unit tests  for the batchverifier
> [BLS] [TEST] Update bls batchverifier

- src/qt/pivx/addresseswidget.cpp
- src/qt/pivx/send.cpp
- src/qt/pivx/sendchangeaddressdialog.cpp
- src/qt/walletmodel.cpp
This PR fixes some uninitialized booleans. This fixes the issue of not being able to send to addresses in the qt version of PIVX
> Fix unititialized booleans

- src/rpc/blockchain.cpp
Codespell complained of this typo
> [Trivial] Fix typo reccomended->recommended

- build-aux/m4/ax_boost_base.m4
- build-aux/m4/ax_boost_chrono.m4
- build-aux/m4/ax_boost_filesystem.m4
- build-aux/m4/ax_boost_system.m4
- build-aux/m4/ax_boost_thread.m4
- build-aux/m4/ax_boost_unit_test_framework.m4
- build-aux/m4/ax_check_compile_flag.m4
- build-aux/m4/ax_check_link_flag.m4
- build-aux/m4/ax_check_preproc_flag.m4
- build-aux/m4/ax_cxx_compile_stdcxx.m4
- build-aux/m4/ax_gcc_func_attribute.m4
- build-aux/m4/ax_pthread.m4
This is the first part in what will be a series of updates to our autotools build system. these commits are simply updating macro scripts from their upstream published versions. the only manual change that i've made is to ensure there is a new line at the bottom of each file.
> [Build] Update m4 macros from upstream

- .gitignore
Add new filters for various files that we don't want tracked in the git tree.
> [Build] Update .gitignore
